### ISSUE TITLE
[Feature Request] Card View

### ISSUE THREAD

**Issue by slideup-benni** [nextcloud/tasks#100]
It would be awesome, when we could add a card view beside the list view.
As the content of the card we could use the list of the sub-tasks or the a excerpt of the task description or after https://github.com/nextcloud/tasks/issues/91 the fist attached image / link

I like the layout of google keep, maybe we could adopt it:
![spectacle hf5133](https://user-images.githubusercontent.com/12446028/29740346-ce63923c-8a54-11e7-8c48-f58bda8aa2c7.png)

**Comment by sunjam** [comment]
A big part of this puzzle might be resolved once [Deck finishes their PR for CalDAV support](https://github.com/nextcloud/deck/issues/15)

**Comment by raimund-schluessler** [comment]
We won't implement a card view in the Tasks app, since this would basically mean to clone the Deck app. Instead, Deck will implement support for CalDAV sources so you can work on the same tasks in both apps.
