### ISSUE TITLE
Tasks missing when HTTP2 enabled

### ISSUE THREAD

**Issue by kain** [nextcloud/tasks#1000]
### Steps to reproduce
1. Open tasks in browser
2. Start creating task lists with tasks
3. Create 300 or more total tasks

### Expected behaviour
All 300 tasks should load

### Actual behaviour
Random number of tasks is loading. Every page refresh load different number of tasks. Some task lists missing completely. Some task lists missing some tasks in it.

### Server configuration

**Operating system**: Linux 4.15.0-76-generic #86~16.04.1-Ubuntu SMP Mon Jan 20 11:02:50 UTC 2020 x86_64

**Web server:** Apache/2.4.7 (apache2handler)

**Database:** mysql 5.6.39

**PHP version:** 7.2.15
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, json, mbstring, session, standard, posix, Reflection, Phar, shmop, SimpleXML, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, mysqlnd, apache2handler, curl, enchant, gd, gmp, imap, interbase, intl, imagick, ldap, mcrypt, mailparse, memcached, mysqli, odbc, PDO, PDO_Firebird, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_dblib, pdo_sqlite, pgsql, pspell, recode, redis, snmp, ssh2, sqlite3, tidy, xmlrpc, xsl, phalcon, yaml, geoip, raphf, propro, memcache, ionCube Loader, Zend OPcache

**Nextcloud version:** 18.0.4 - 18.0.4.2

**Tasks version:** tasks: 0.12.2

**Updated from an older Nextcloud or fresh install:** Update from 16 to 17 to 18

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - deck: 0.8.2
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - groupfolders: 6.0.6
  - issuetemplate: 0.6.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.3.4
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.12.2
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap

```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "itgenius.ru"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "overwrite.cli.url": "https:\/\/itgenius.ru\/nextcloud",
        "htaccess.RewriteBase": "\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 75

**Operating system:** Ubuntu 18.04.4 LTS x64

**CalDAV-clients:** Web browser

#### Web server error log
```
No errors appears
```

#### Nextcloud log (data/nextcloud.log)
```
No log items when issue appears
```

#### Browser log
Console log
[example.com-1588327616256.log](https://github.com/nextcloud/tasks/files/4564694/example.com-1588327616256.log)

Network log
[example.com.har.txt](https://github.com/nextcloud/tasks/files/4564708/example.com.har.txt)

**Comment by raimund-schluessler** [comment]
This is clearly a setup issue of your server, especially since you already figured out it is bypassed when you disable HTTP2. Tasks has nothing to do with the network protocol directly. We just send HTTP requests to the server and rely on them being properly answered.

Since this is a configuration issue of your server, please post this question in the forum: https://help.nextcloud.com

**Comment by kain** [comment]
This is relatively big shared hosting, so unfortunately, I can't update it. I chatted in first place with hosting techsupport, and they assured me that server setup is OK.
I see some issues with HTTP/2 protocol in NC server part (https://github.com/nextcloud/server/issues/16138), but guys direct me to Tasks for bug reporting (https://github.com/nextcloud/server/issues/16138#issuecomment-622326848).

@raimund-schluessler can you, please, check if 300 or more tasks work OK on your setup?

I exported my 300 test empty tasks (they can be imported via Calendar - Settings & Import)
[testcal300.ics.zip](https://github.com/nextcloud/tasks/files/4564959/testcal300.ics.zip)

**Comment by raimund-schluessler** [comment]
> @raimund-schluessler can you, please, check if 300 or more tasks work OK on your setup?
> 
> I exported my 300 test empty tasks (they can be imported via Calendar - Settings & Import)
> [testcal300.ics.zip](https://github.com/nextcloud/tasks/files/4564959/testcal300.ics.zip)

Did you try to import this ics file on your server? For me this fails with Calendar 2.0.3, might be a Calendar bug as well.

**Comment by raimund-schluessler** [comment]
But I can tell you, that the app / config reproducible loads 443 completed tasks just fine.

**Comment by kain** [comment]
Thank you for support! Then I will configure test server on home computer with Ubuntu 18.04 and apache and test. Will post result here for future reference.

**Comment by raimund-schluessler** [comment]
What happens with the requests to the server? Do they succeed and return the correct number of tasks? If not, then it is a server and likely a config issue and we cannot do anything in the Tasks app.

**Comment by kain** [comment]
Some tasks load OK (207 HTTP code), some won't load (503 HTTP code). Which is which is random every page refresh.
![Screenshot_nc_tasks](https://user-images.githubusercontent.com/445250/80825554-505af300-8be9-11ea-8cbd-b45fbd93e2ab.png)

**Comment by raimund-schluessler** [comment]
Well, if they randomly fail, especially with `HTTP 503 (Service Unavailable)`, then it's definitely a server or config issue. These requests are handled by the CalDAV server which is part of Nextcloud server, so nothing we can do here, sorry. You should have a look at the server log, maybe it gives you a hint, why the requests fail. Also the Apache2 log might help here.

**Comment by kain** [comment]
Thanks @raimund-schluessler! I will try on local server, if issue are gone, then will change webhosting.
