### ISSUE TITLE
Sidebar Collapse Button overlaps input box on smaller displays/windows

### ISSUE THREAD

**Issue by Nickno95** [nextcloud/tasks#1011]
![image](https://user-images.githubusercontent.com/11400284/81316501-443fbd00-9051-11ea-9523-a2788df3eaa3.png)

### Expected behaviour
When window size is small enough for the sidebar to collapse, the hamburger menu button to uncollapse shouldn't overlap with the 'add task' input box

### Actual behaviour
The hamburger menu button overlaps with the 'add task' input box.

This occurs in both Firefox and Chrome, looks like it has to do with the button's 'position: fixed' styling.

**Comment by raimund-schluessler** [comment]
This has been fixed with https://github.com/nextcloud/tasks/pull/965. We now always show the hamburger menu so one can hide the sidebar on desktop as well.

![tasks_vue](https://user-images.githubusercontent.com/2496460/80715922-5670a700-8af7-11ea-99bc-839a6f568925.gif)
