### ISSUE TITLE
[Feature Request] Simple color change

### ISSUE THREAD

**Issue by javisomoza** [nextcloud/tasks#1012]
Hi

Sorry in case im doing something wrong; im not developer and im not used to using github and sending issues or a feature request.

This is a simple feature in which i have had to change only 2-3 lines of code:
![image](https://user-images.githubusercontent.com/49761255/81430710-2ad96680-9160-11ea-8ccb-f93da3e78e61.png)

I think that maintaining the list color in the tasks groups its a small change but enhances the look&feel considerably. 

Thanks for the app! Its great!

**Comment by raimund-schluessler** [comment]
@javisomoza Welcome to Nextcloud 🙂 

I think it is a nice idea to show the calendar color in the task list. But showing it for every task creates to much visual noise for my taste and reduces the discoverability of the task which is currently opened in the right sidebar.

How about we show the calendar color next to the calendar name. This would also be consistent with how we show the calendar color in the app-navigation, right details sidebar and week view.
![Screenshot_2020-05-08 Tasks - Nextcloud](https://user-images.githubusercontent.com/2496460/81439860-5dd72680-916f-11ea-820e-824e59fff5c9.png)

PR is #1013.

**Comment by javisomoza** [comment]
Thanks for your response, Raimund, and glad you are interested in the request.

Ill try to do my best explaining because i can do English grammatical mistakes jaja.
I like the idea of showing the color on each task to receive more info just the moment you look the task list and it also would allow (when showing "All" tasks together) to show all tasks mixed if you prefer (giving that option) and reduce opacity to reduce the noise. Anyway, each person works in his own way and has its preferences, even more when talking about colors and I completely understand what you say related to the visual noise.

Let me another small suggestion: the left border color in blue when hovering in a task could be the same as the calendar instead of blue?

Anyway, what you said about showing the calendar color next to the calendar name would be great.

Thanks!

**Comment by raimund-schluessler** [comment]
> and it also would allow (when showing "All" tasks together) to show all tasks mixed if you prefer (giving that option)

Hm, I don't see a benefit of mixing all tasks in such a view. In the current "All" view you also see every task, but they are additionally sorted by calendar, which makes a lot of sense, I think.

> Let me another small suggestion: the left border color in blue when hovering in a task could be the same as the calendar instead of blue?

I would be ok to do that. But I think we will get rid of the left border sooner or later, since it is already not used anymore in most of the current apps (e.g. in the left sidebar). Is this correct @jancborchardt?

@nextcloud/designers What do you think about showing the border in the calendar color?

**Comment by jancborchardt** [comment]
I’d say you both make good proposals:
- @raimund-schluessler, adding the colored circle left of the calendar name is good and makes it more consistent
- @javisomoza your proposal to show the color closer to the tasks is good. Indeed we are phasing out that left border, so what we could do is what we do for the navigation hover effect: Use a 10% version of the primary color (in this case the calendar color as it’s more relevant) on hover of an entry.

What do you think?

**Comment by javisomoza** [comment]
Yeah, it would be good :)

**Comment by raimund-schluessler** [comment]
>   * @javisomoza your proposal to show the color closer to the tasks is good. Indeed we are phasing out that left border, so what we could do is what we do for the navigation hover effect: Use a 10% version of the primary color (in this case the calendar color as it’s more relevant) on hover of an entry as the full row background color, or if that’s too much just for the area around the checkbox on the left.

Hm, I think both variants don't look ideal to be honest:

![Screenshot_2020-05-09 Tasks - Nextcloud](https://user-images.githubusercontent.com/2496460/81481837-1ca84a80-9233-11ea-9c10-a9d1f3f8f102.png)

![Screenshot_2020-05-09 Tasks - Nextcloud(1)](https://user-images.githubusercontent.com/2496460/81481908-b1ab4380-9233-11ea-998e-0b87a3cfcd81.png)

Out of the two, I would prefer the first one coloring the full task.

Also, I don't know how to implement it to change the background-color on hover with javascript (especially with transparency).
