### ISSUE TITLE
Feature request: Hide selected calendars from Tasks list

### ISSUE THREAD

**Issue by janvonde** [nextcloud/tasks#1032]
Hi,

thanks for the great app! I am using it now since a long time on a daily basis. On my setup I have different calendars for different types of things like "Private", "Work", "Birthdays" and one is called "ToDo". The last one is the only one where I store tasks. 

When I am in the Tasks app, I see all my calendars on the left hand side, but I only need the "ToDo" calendar. It would be an awesome feature (from my perspective) if I could hide other calendars there.

Keep up your great work!

Jan :-)

**Comment by olyrius** [comment]
I agree, this would be a nice feature.

**Comment by rkaraba** [comment]
There is workaround. 
You can edit your calendar in database and it will not show in tasks.
Calendars are stored in table oc_calendars. There is column components'.
Usually calendars have VEVENT VTODO there. Delete VTODO from there. And Calendar will not show in Tasks.
If you uses Calendar 2 you can chose if you want to create calendar with or without tasks.

**Comment by szaimen** [comment]
Another way is exporting the calendar, as .ics file, deleting it, editing the exported ics file and delete all vevent vtodo and import it again jn the calendar app. Then it shouldn't be shown in the tasks app, as well.

**Comment by ilippert** [comment]
I guess the feature request implementation would manage to edit a calendar's format (remove VTODO) via the nextcloud UI, rather than asking the end user to fiddle with the database.

Personally, I typically follow @szaimen's work around.

**Comment by raimund-schluessler** [comment]
As said multiple times in similar threads, changing the calendar components after creation is forbidden by the RFC 5545 iCal specification. Hence, this will never be implemented in the UI.

The proper solution to hide task lists are folders in my opinion. Then you can sort all lists you don't want to see into the respective folder and only see this folder then, see https://github.com/nextcloud/tasks/issues/84

**Comment by szaimen** [comment]
But what do you see here as creation timestamp?
If you import an ics file, it is in nextcloud created at this time, so why not remove unnecessary VTODO if importing a normal calendar (or if importing a tasks calendar VEVENTs) before creating those inside the database?
Though, I can understand that there shouldn't be a possibility to delete any entry after it was imported and created in nextcloud.

**Comment by raimund-schluessler** [comment]
> But what do you see here as creation timestamp?

Exporting the calendar as ICS, deleting it, editing the ICS file and recreating the calendar by importing the file again is fine.
Only if the calendar already exists, you are not supposed to edit the components in the database anymore. While it might lead to the desired result, you might get unexpected behaviour when syncing (e.g. since a client might expect to be able to store events as well, which is not possible anymore after deleting the VEVENT component).

**Comment by AlexandreBonneau** [comment]
> If you import an ics file, it is in nextcloud created at this time, so why not remove unnecessary VTODO if importing a normal calendar (or if importing a tasks calendar VEVENTs) before creating those inside the database?

Please no, VTODO are a part of the ics specification, and even if fullcalendar does not yet display those ([they should](https://github.com/fullcalendar/fullcalendar/issues/3528)), Nextcloud correctly keep those.
Hence, complete PIM app like [korganizer](https://userbase.kde.org/KOrganizer) can still use NC to synchronize events **and** tasks between devices.

So please, do not remove `VTODO` when importing ics files ; if they are in the file, keep those. There are their for a reason.
If you don't want those, just remove them beforehand with `sed`!
