### ISSUE TITLE
Some ideas how to improve the mobile view

### ISSUE THREAD

**Issue by szaimen** [nextcloud/tasks#1034]
I am now running v0.13.0 and I really love the design of the tasks app but I have some suggestions especially for the mobile view.

### These are all areas that I would change:
![image](https://user-images.githubusercontent.com/42591237/81840271-09ee8800-9549-11ea-91f9-baef31d060a8.png)
1. The placeolder on the left in the input-field isn't the same like on top and bottom of the text; the text is cut off on the right side
2. the fiter button has not an equal space on the left and right
3. I would move the red circle of the list a bit to the right to align with the checkboxes (is too close to the edge in the moment)
4. I would completely remove the lines that separate the checkboxes from the tasks-title.
5. the tasks title are often cut-off even if there is still a lot of space left to show more of the tasks title and instead shows 3 dots.

Currently | Proposed
------------ | -------------
![image](https://user-images.githubusercontent.com/42591237/81839111-65b81180-9547-11ea-899e-778b39cb5830.png) | ![image](https://user-images.githubusercontent.com/42591237/81840033-ae23ff00-9548-11ea-8270-47c7376277e3.png) 

**I know, the 5. point isn't solved yet but this is dificult to edit ;)**

**Comment by raimund-schluessler** [comment]
Thanks for the detailed feedback, I basically agree with all your points.
Re 4. I actually liked the lines separating task body and checkbox, but given, that there are no lines e.g. in the files app, it's consistent to remove them.

Point 5 might be difficult to solve. I remember I noticed that already, but didn't find a good / quick solution.

**Comment by szaimen** [comment]
> Thanks for the detailed feedback, I basically agree with all your points.

You are welcome!

> Re 4. I actually liked the lines separating task body and checkbox, but given, that there are no lines e.g. in the files app, it's consistent to remove them.

I didn't thought this way but makes sense, yes 👍

> Point 5 might be difficult to solve. I remember I noticed that already, but didn't find a good / quick solution.

I could be wrong but there seems to be already some calculation in place that calculates the distance that is left to the nextcloud icon on the right, since the cut-offs seems to have kind of the same width. So maybe it is enough to change that calculation to reduce that width?

**Comment by szaimen** [comment]
Since we are already at it:
6. To make it consistent with the files app, I think the outer frames should get removed:
## Currently 
![image](https://user-images.githubusercontent.com/42591237/81853791-36140400-955d-11ea-93ac-76ac9e2da98f.png) 
## Proposed
![image](https://user-images.githubusercontent.com/42591237/81853722-1aa8f900-955d-11ea-8356-50e5c6f6a274.png)

**Comment by raimund-schluessler** [comment]
>   1. To make it consistent with the files app, I think the outer frames of the tasks list should get removed:

You are right, this would be consistent. But somehow I don't really like it. It looks to densely packed to me. In the mobile view we anyway already don't have a padding around the task list, since space is limited. But on desktop with enough space, I like to have a little padding around the lists.

What do @nextcloud/designers think about this?

**Comment by raimund-schluessler** [comment]
7. The time is cropped although enough space is available
![Screenshot_2020-05-14 Aufgaben - Nextcloud](https://user-images.githubusercontent.com/2496460/81908107-15819380-95c9-11ea-9e08-f52e3353c349.png)
