### ISSUE TITLE
Please add a spacer between tasks and subtasks 

### ISSUE THREAD

**Issue by elfersar** [nextcloud/tasks#1045]
<img width="736" alt="Bildschirmfoto 2020-05-17 um 11 14 09" src="https://user-images.githubusercontent.com/65486519/82140556-bcffff80-982f-11ea-8e0a-550a577fab09.png">

- Problem: When you have a bunch of Tasks it is gonna be very messy and sometimes you have problems to find what you want.

- Possible solution: Please add a spacer between the last subtask and the new following task. 

**Expectation**
Hopefully with the spacers it's gonna be more cleaner and its possible to navigate faster through tasks. Yes it's is only for the user experience but for my part it would be a lot easier to use the app.

**Comment by raimund-schluessler** [comment]
To me, this looks a bit weird and I don't think we will add it:
<img width="697" alt="Screenshot_2020-05-17 Tasks - Nextcloud" src="https://user-images.githubusercontent.com/2496460/82141661-a9f12d80-9837-11ea-999e-2cdce9983f37.png">


However, you can achieve what you want with the Custom CSS app. After enabling it, just insert this CSS snippet in the CSS input under the admin theming section
```css
.app-tasks .task-list .subtasks-container ol li:last-child {
	margin-bottom: 10px;
}
```

**Comment by elfersar** [comment]
Thats what I am looking for. 
For me I will add the spacer before every new Main Task. Not between subtasks. 
Thanks a lot!
