### ISSUE TITLE
[Feature Request]: Add Tasks functionality to the NextCloud IOS App

### ISSUE THREAD

**Issue by Mito173** [nextcloud/tasks#1048]
The Tasks App works great in the web browser - but this does not help much on mobile devices - and this is where we normally use shared task lists. I miss an integration concept, at least since Apple dropped CalDAV support for the reminders app in IOS 13... 
I was searching several hours now for an easy to use and affordable app which would allow me to sync my NextCloud tasks ...none :-( 
How about integrating the task functionality in the meanwhile really great IOS NextCloud App? This way you would not depend on the mood of Apple (at least for the IOS side)

Kind regards,
Michael

**Comment by raimund-schluessler** [comment]
Nextcloud uses CalDAV to sync tasks as you correctly mentioned. Apple still supports CalDAV both for Events (Calendar) and Todos (Tasks) on iOS. The dropped support for CalDAV just affects the iCloud sync and is not related to the Nextcloud server. I use it with out problems on iOS 13.4. and 13.5. So you can use any Todo app which supports CalDAV (2Do, Fantastical, Calendar360 and the built-in Apple Todo app work fine).

Hence, it doesn't make sense to create just another Todo app for iOS.

**Comment by Mito173** [comment]
You are right... my mistake :-( 
It stopped working last week and I was mislead by some articles on the web, so I did not search in my configuration any longer. 
Sorry about that - I will see if I can delete my comment on the tasks developers page...
