### ISSUE TITLE
[Feature Request] Add a completion date-time to tasks when checked

### ISSUE THREAD

**Issue by SLYtiger16** [nextcloud/tasks#1069]
I would like to see a completion date-time added to each task for when it was checked as complete. I can think of a few use cases such as reviewing work for the day, time lining myself or others, and historical milestone tracking. 
Something such as: `"Marked complete: 06/03/2020 14:54:00"` written on each completed task.

**Comment by raimund-schluessler** [comment]
We show the completed date in the right sidebar as a tooltip when hovering over the `i` at the bottom center.

<img width="245" alt="CompletedDate" src="https://user-images.githubusercontent.com/2496460/83726864-75a5ab80-a644-11ea-997c-3dfb33afe12f.png">


Where else would you propose to show it?

**Comment by SLYtiger16** [comment]
Honestly, I didn't know that "i" was there. So that is cool, but it still requires multiple clicks to see it and I can find usefulness in seeing the date-time in the main view like this doctored photo 
![image](https://user-images.githubusercontent.com/36513817/83755755-a3362900-a633-11ea-86fc-496d74724a86.png)

**Comment by raimund-schluessler** [comment]
I agree, for completed tasks we could show the completed date at the position and instead of the due date.

**Comment by raimund-schluessler** [comment]
See https://github.com/nextcloud/tasks/pull/1078
