### ISSUE TITLE
[Feature Request] Add URL field to task detail

### ISSUE THREAD

**Issue by rodrigoaguilera** [nextcloud/tasks#1079]
### Steps to reproduce
1. Create a task on the openTasks android app with the URL field filled
2. Sync with davx5
3. Display that task in nextcloud

### Expected behaviour
The URL field is displayed on nextcloud

### Actual behaviour
No URL field

### Server configuration

**Operating system**: debian 10

**Web server**: nginx

**Database**: mariadb

**PHP version**: 7.3

**Nextcloud version:** 18.0.6

**Tasks version:** 0.13.1

**Updated from an older Nextcloud or fresh install:** Fresh

### Client configuration
**Browser:** firefox 77

**Operating system:** debian 10

**CalDAV-clients:** opentasks

**Comment by tbm** [comment]
Location has been requested in issue #7.  Maybe you can change the title of this ticket to "Add URL field to task detail".

I guess this related to this section of the  standard:

```
3.8.4.6.  Uniform Resource Locator
```
