### ISSUE TITLE
i18n: Should strings between square brackets being translated?

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/tasks#1085]
https://github.com/nextcloud/tasks/blob/07e12bad0f0283d27d981eb3d585a1aa693b798a/src/components/TaskBody.vue#L248

Should we translate the strings? If no they are placeholders and being replaced?

**Comment by raimund-schluessler** [comment]
These are strings for moment.js. moment.js uses brackets to escape strings: https://momentjs.com/docs/#/displaying/format/. So yes, strings in square brackets need to be translated, the `LT` is a token for moment.js and will be replaced with a time. 

I guess we should put a note how to translate it similar to here: https://github.com/nextcloud/tasks/blob/07e12bad0f0283d27d981eb3d585a1aa693b798a/src/components/TheDetails.vue#L477

**Comment by rakekniven** [comment]
Unfortunately that doesn't help because the vue files are getting "compressed" and we loose your comments. See 

![2020-06-16_15h28_57](https://user-images.githubusercontent.com/2069590/84780822-57499380-afe6-11ea-8bd5-ba6d8f6577a1.png)

**Comment by rakekniven** [comment]
For PHP files it works.

https://github.com/CollaboraOnline/richdocumentscode/blob/master/lib/Settings/Section.php#L62

![2020-06-16_15h42_32](https://user-images.githubusercontent.com/2069590/84782309-2702f480-afe8-11ea-97a4-47b6e7e58a93.png)

**Comment by raimund-schluessler** [comment]
> Unfortunately that doesn't help because the vue files are getting "compressed" and we loose your comments.

Any other ideas? I don't see anything we can do besides putting a comment there.
