### ISSUE TITLE
Documentation for 2Do

### ISSUE THREAD

**Issue by ischiros** [nextcloud/tasks#1113]
Hello,

I'm desperately trying to sync Tasks with 2Do app, which is mentioned as compatible in the readme file.
But I can't find any explanation about the parameters which should be used.
Did I miss something ?
If yes, could there be a link to some documentation in the readme file and/or the projet page on nextcloud site ?
If no, can someone provide some help ?

Here are the fields in 2Do for the "personalized CalDAV" syncing :
- username
- password
- https://cal.server.com:8443 (that's the name of the field)
- principal path (optional)
- server port
- use SSL (yes/no)

Thanks.

**Comment by raimund-schluessler** [comment]
The synchronization is handled by the DAV app which is part of the server. The documentation for this can be found here https://docs.nextcloud.com/server/latest/user_manual/pim/sync_ios.html

The server address depends on if you want to sync with iOS or others, you can copy it in the settings of the Calendar app:
iOS: https://<owncloud>/remote.php/dav
Others: https://<owncloud>/remote.php/dav/principals/users/<username>/

If you need more support, please ask this question in the forum.

**Comment by ischiros** [comment]
Hello,

Thank you for answering so fast.
https://owncloud/remote.php/dav/principals/users/username/ half-worked (aka it says that connexion is ok, but no task is synced).

I'd love to ask this in a forum, but what forum ?
[The readme file](https://github.com/nextcloud/tasks/blob/master/README.md) and [the App page](https://apps.nextcloud.com/apps/tasks) don't indicate any link to forum. Which is why I had no other solution than asking my question here.

Also, there was also an enhancement suggestion in my issue : even after a lot of time searching the web, I couldn't find any answer to my question. It seems to me that syncing Tasks with a device is an impossible mission for whoever is not a Nextcloud expert.
That's why I suggested to add in the readme some informations and/or links to some tutorial or forum, to help users.

**Comment by raimund-schluessler** [comment]
The Tasks app does not handle the synchronization, this is done by the Nextcloud server. You can also sync tasks with your device via CalDAV without the Tasks app being installed. Hence, the place for documenting how to sync is Nextcloud server, and there it is documented under the links I provided above. No need to duplicate that here.

The forum is the general Nextcloud forum, see https://help.nextcloud.com/c/apps/tasks specifically for questions about Tasks. We could probably add a section similar to how Calendar does this: https://github.com/nextcloud/calendar#satellite-support
