### ISSUE TITLE
Issue during build process

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/tasks#114]
I followed the readme installing nodejs and npm, still there’s this error:
```
jan@Rechenknecht:~/nextcloud/apps/tasks$ make
make yarn
make[1]: Entering directory '/home/jan/nextcloud/apps/tasks'
cd js &&  run build
/bin/sh: 1: run: not found
Makefile:94: recipe for target 'yarn' failed
make[1]: *** [yarn] Error 127
make[1]: Leaving directory '/home/jan/nextcloud/apps/tasks'
Makefile:89: recipe for target 'build' failed
make: *** [build] Error 2
```
Guess I’m missing something again ;) should be in the readme.

**Comment by raimund-schluessler** [comment]
I updated the build environment just yesterday with https://github.com/nextcloud/tasks/pull/105 and forgot to update the readme.

Just like the Calendar app, we use Yarn now instead of NPM, so please install Yarn as well. I will update the readme accordingly.

**Comment by jancborchardt** [comment]
Yeah, I tried installing yarn according to this: https://yarnpkg.com/lang/en/docs/install/

But the error remains. :\

**Comment by raimund-schluessler** [comment]
This is weird. It runs normal for me and @skjnldsv. Does the calendar make file run normally? It is basically the same as this one here.

**Comment by raimund-schluessler** [comment]
@jancborchardt Any news on this?

**Comment by raimund-schluessler** [comment]
@jancborchardt Could you check whether https://github.com/nextcloud/tasks/pull/120 works for you? You need to install npm version 5.

**Comment by skjnldsv** [comment]
I get this issue as well on fresh install :)

**Comment by raimund-schluessler** [comment]
Please try again with current master or stable12. We moved to NPM5.

**Comment by raimund-schluessler** [comment]
Any news, are there still problems? Otherwise I will close the issue in the next days.
