### ISSUE TITLE
Adjust app to NC 20 and unified search

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/tasks#1171]
With the unified search on NC 20, the old search box is not available anymore. We have to realize filtering differently now.

Also at the moment you get a warning that
```
[Vue warn]: Error in mounted hook: "Error: searchBox not available"

(found in <Root>) vue.runtime.esm.js:619
```
but since this warning is issued in https://github.com/nextcloud/server/blob/master/core/search/js/search.js#L62 and you get it in every app using the old search I guess this is a server issue? @skjnldsv

**Comment by skjnldsv** [comment]
This is fixed already with https://github.com/nextcloud/server/pull/22099
We now warn the deprecation :)

**Comment by raimund-schluessler** [comment]
Needs clarification from server as how to proceed with content filtering: https://github.com/nextcloud/server/issues/22092#issuecomment-673328326
