### ISSUE TITLE
[Feature Request] Changing the order of Task Lists

### ISSUE THREAD

**Issue by t3pfaffe** [nextcloud/tasks#1183]
Can the ability to custom order the task lists be implemented? As far as I can tell this is not currently possible. I would like to be able to have my more vital/more generic task lists be at the top rather than the current alphabetical order it is currently in.

**Comment by raimund-schluessler** [comment]
This has been implemented with https://github.com/nextcloud/tasks/pull/1155 and will come with the next Version.

**Comment by t3pfaffe** [comment]
My apologies for in spam then. Should have checked. Thanks!
