### ISSUE TITLE
[Feature request] Make the task details pane wider

### ISSUE THREAD

**Issue by chepec** [nextcloud/tasks#1185]
I'd like to suggest widening the tasks details pane.

Why? When I open a task, I focus on filling out the details of that task, and at that time I don't care (that much) about  about the contents of the central pane (list of tasks) or the left pane (list of calendars/task lists). I'm mainly concerned about desktop use here.

On my 1200px wide monitor (monitor in portrait mode), with the tasks details pane open, it looks like this:
![Tasks - Nextcloud_037](https://user-images.githubusercontent.com/979546/89910748-264d9f80-dbe0-11ea-838f-8e0bc6f75335.jpg)

But even on on a wider monitor (1920px), the tasks details pane is still using too little width, considering it is the user's focal point (in fact, now the central pane uses almost two times the width of the details pane):
![Selection_042](https://user-images.githubusercontent.com/979546/89910846-3f565080-dbe0-11ea-8d14-784741dbd3fa.jpg)

I suggest making the task details pane as wide as the central pane (for all desktop use). I think that would make working on a specific task, particularly when editing the text box (which supports Markdown, that's fantastic!) much more comfortable.
Also, at the same time, perhaps you would consider decreasing the width of the left-most pane. I think it's unnecessarily wide.

Screenshots taken when using Nextcloud server 18.0.7 with Tasks 0.13.3.

**Comment by raimund-schluessler** [comment]
The rework of the sidebar is tracked in #664 and #1030. The width follows global Nextcloud standards and we won't overwrite them specifically for Tasks. We can discuss in the nextcloud-vue repository whether we want to adjust the width or maybe even allow to dynamically adjust the width by dragging the border.

For now you can adjust the width with the Custom CSS app.

**Comment by chepec** [comment]
I understand. Thanks for taking the time to reply.
I really appreciate the pointer to the Custom CSS app, I was not aware of it before now.

For anyone else who might read this, I managed to make the right sidebar wider and the left sidebar thinner in the Tasks app by adding the following lines to the Custom CSS box in Nextcloud settings -> Theming after installing the Custom CSS app (logged in as the admin user, it took effect immediately for all users). Very cool!

```
#app-sidebar {
   min-width: 400px; // increased from the default 300px
   max-width: 600px; // did not really have any effect in my tests, but increased from default 500px for good measure
}
#app-navigation-vue {
   width: 220px; // default 300px
}
```
