### ISSUE TITLE
[Feature request] Integration with Deck

### ISSUE THREAD

**Issue by iGadget** [nextcloud/tasks#1211]
Currently Deck and Tasks are two completely(?) separate apps with somewhat overlapping functionality.
It would be really helpful if the two had some level of integration to prevent duplicate work and to complement each other's missing functionality.
Just being able to link Deck projects / cards to specific tasks easily and vice-versa would already help a lot.

**Nextcloud version:** (see Nextcloud admin page)
9.0.2

**Tasks version:** (see Nextcloud apps page)
0.13.3

**Comment by iGadget** [comment]
Apparently, the Deck team is already working on this - see https://github.com/nextcloud/deck/pull/1545 and https://github.com/nextcloud/deck/issues/15. What I'm not sure of however, if this also means that projects in Deck will also be (easiliy) accessible from / integrated into Tasks. If so, I guess this feature request can be closed.

**Comment by juliushaertl** [comment]
Yes, that will be the case once deck exposes them though CalDAV.

**Comment by raimund-schluessler** [comment]
I think we can close this issue. Tasks will stay a CalDAV client and will be able to edit Deck cards once the implementation in Deck is finished.

**Comment by HieronymusCH** [comment]
My apologies for writing to this closed issue.

Question: Wasn't there an option in the settings on the Tasks page for show/hide tasks from Deck?

**Comment by raimund-schluessler** [comment]
> Question: Wasn't there an option in the settings on the Tasks page for show/hide tasks from Deck?

No, there is no setting. Cards/tasks from Deck are always shown. In case you want to not expose them, please open an issue in Deck to toggle the behaviour.

**Comment by raimund-schluessler** [comment]
> Question: Wasn't there an option in the settings on the Tasks page for show/hide tasks from Deck?

I just saw there is already a setting for this in Deck. Please toggle it there.
