### ISSUE TITLE
[Bug] Visual glitch in actions context menu

### ISSUE THREAD

**Issue by thomas-mc-work** [nextcloud/tasks#1225]
![hard to delete](https://user-images.githubusercontent.com/6542498/92929350-add93900-f440-11ea-9f99-dd08ae706125.png)

# Steps to reproduce
1. Create two tasks
2. Mark one of them complete
3. Open the actions menu of the other one

### Expected behaviour
The menu should be on top of the layer

### Actual behaviour
It's below the completed task.

### Client configuration
**Browser:** Firefox 80.0.1

**Operating system:** Xubuntu 20.04.1

**Comment by raimund-schluessler** [comment]
Issue is fixed with latest master on Nextcloud 20.

![Screenshot_2020-09-13 Aufgaben - Nextcloud](https://user-images.githubusercontent.com/2496460/93027468-4de3bd80-f60d-11ea-8a3e-be50f6a3559e.png)

**Comment by thomas-mc-work** [comment]
"Latest master" means milestone `0.14`? What about renaming it to `1.0`?

**Comment by raimund-schluessler** [comment]
> 
> 
> "Latest master" means milestone `0.14`? What about renaming it to `1.0`?

Latest master means it will be available with the next release, which will be 0.14.0 for now. There might be a 0.13.4 with some adjustments for Nextcloud 20, which would then include the fix as well.

Tasks will eventually reach version 1.0 once we have repeating tasks and reminders 😉
