### ISSUE TITLE
Sync via DavDroid broken

### ISSUE THREAD

**Issue by theScrabi** [nextcloud/tasks#125]
Every time I try to delete, or create anything on my OpenTasks using DavDroid, no change gets synchronized with my nextcloud installation. Also thunderbird takes forever to synchronize a change, and when I change something on the webfrontend, the first change gets commited the rest not.

**Comment by raimund-schluessler** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the task app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues
