### ISSUE TITLE
UI does not work after update to V.20 (Docker)

### ISSUE THREAD

**Issue by lExplLicit** [nextcloud/tasks#1257]
UI Does not show up properly aftter upgrade to V.20 (Docker)

Error:
![image](https://user-images.githubusercontent.com/54572942/95174704-b829f100-07ba-11eb-824d-29043c887284.png)

Chrome console:
![image](https://user-images.githubusercontent.com/54572942/95174806-e0b1eb00-07ba-11eb-993c-2e451170ec85.png)

Nextcloud Log:
![image](https://user-images.githubusercontent.com/54572942/95174547-83b63500-07ba-11eb-8990-e29b18889442.png)

**Comment by raimund-schluessler** [comment]
Duplicate of #1251.
