### ISSUE TITLE
Start and due icons are not idiomatic

### ISSUE THREAD

**Issue by bergentroll** [nextcloud/tasks#1259]
As for me the start and the due icons in detailed view should be swapped. 
![image](https://user-images.githubusercontent.com/14995027/95416395-14704a80-094c-11eb-8674-ebc68e26b5f5.png)

The icon with an arrow on left side likely shows that we are entering an event. The icon with an arrow on right side likely shows that we are leaving the event.

Related: #864.

**Comment by raimund-schluessler** [comment]
They are "correct" as they are. The start icon indicates the task starts at the beginning of the arrow and goes on. The end icon indicates the task is ongoing and ends at the end of the arrow. This is also the most common interpretation you find when searching for start and end icons.

**Comment by raimund-schluessler** [comment]
If you don't like it like that, you can overwrite it with the custom css app.
