### ISSUE TITLE
Tasks History Comment

### ISSUE THREAD

**Issue by marcusitpro** [nextcloud/tasks#127]
In version tasks 0.93, I used the feedback history. From what 've seen, you've removed this option. Do you have how to put the comment history option in version 0.95?

Admin Example, below the main comment.
![tasks](https://user-images.githubusercontent.com/33964093/33219471-7c872368-d129-11e7-89bc-060ab85a4f2c.png)

**Comment by raimund-schluessler** [comment]
The option to comment on tasks has not been implemented after the move to the Nextcloud CalDAV server with version 0.9 which was released 1,5 years ago. So I don't really understand how you use this feature with version 0.93.

Anyway, the issue for implementing the comments feature again is in https://github.com/nextcloud/tasks/issues/109.

**Comment by marcusitpro** [comment]
I expressed myself in the wrong way. I used Owncloud and migrated to NextCloud. And there I used it, version 0.93. Anyway, thank you very much for the collaboration.

**Comment by raimund-schluessler** [comment]
Still a bit weird, since it was removed with 0.9.0, see release notes: https://github.com/owncloud/tasks/releases/tag/v0.9.0
