### ISSUE TITLE
Can't edit list names

### ISSUE THREAD

**Issue by dohlin** [nextcloud/tasks#1276]
### Steps to reproduce
1. Install Tasks app
2. Create List
3. Attempt to edit via the overflow menu > Edit

### Expected behaviour
Should be able to edit the task list name

### Actual behaviour
Nothing, it's as if you didn't click anything.  Have tried alternate browser (Chrome & FF), uninstalling & reinstalling tasks app, running 'php occ maintenance:repair', checking browser console for errors (don't see any), etc.  Same behavior for NC 19 as for NC 20

## Server configuration detail

**Operating system:** Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 8.0.21

**PHP version:** 

7.4.7
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, exif, msgpack, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, Phar, memcached, Zend OPcache

**Nextcloud version:** 20.0.0 - 20.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 19

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - apporder: 0.11.0
 - bruteforcesettings: 2.0.1
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.0
 - drawio: 0.9.7
 - federatedfilesharing: 1.10.1
 - federation: 1.10.1
 - files: 1.15.0
 - files_external: 1.11.1
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - impersonate: 1.7.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - nextcloud_announcements: 1.9.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - onlyoffice: 6.0.2
 - password_policy: 1.10.1
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - tasks: 0.13.4
 - text: 3.1.0
 - twofactor_backupcodes: 1.9.0
 - twofactor_totp: 5.0.0
 - unsplash: 1.1.6
 - updatenotification: 1.10.0
 - user_status: 1.0.0
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - activity
 - admin_audit
 - calendar
 - encryption
 - firstrunwizard
 - photos
 - recommendations
 - theming
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        [redacted]
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.0.9",
    "overwrite.cli.url": "redacted",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "filesystem_check_changes": 1,
    "maintenance": false,
    "trashbin_retention_obligation": "auto, 7",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "beta",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "theme": "",
    "loglevel": 2,
    "app_install_overwrite": [
        "dropit",
        "unsplash",
        "drawio"
    ],
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** SMB

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** No

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36

**Operating system:** Ubuntu 20.04

## Logs

<details><summary>Web server error log</summary>

```
n/a - same issue persists accessing server directly by internal IP address
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

index.js:46 No OC found
t.getLanguage @ index.js:46
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
5globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
2globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
session-heartbeat.js:97 session heartbeat polling started
7globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
2/ocs/v2.php/apps/user_status/api/v1/statuses/[redacted]:1 Failed to load resource: the server responded with a status of 404 ()
</details>

**Comment by raimund-schluessler** [comment]
Thanks for the report, I can reproduce the issue. Will have a look.

**Comment by dohlin** [comment]
It's always awesome news to find out it's not just me!  Many thanks!

**Comment by raimund-schluessler** [comment]
With the update to nextcloud-vue@2.6.0 the popover menu is attached to the body and not to the parent element anymore. Hence, the `vue-click-outside` handler https://github.com/nextcloud/tasks/blob/master/src/components/AppNavigation/ListItemCalendar.vue#L25 immediately closes the editing input after clicking the edit button. Should be possible to solve with https://github.com/nextcloud/nextcloud-vue/pull/983.

**Comment by Leprazoriy** [comment]
Hi guys! Is there a workaround for this issue before a new version is released? Otherwise, my boss will kick my ass on Monday =)

**Comment by raimund-schluessler** [comment]
> Hi guys! Is there a workaround for this issue before a new version is released? Otherwise, my boss will kick my ass on Monday =)

You can use any other CalDAV client to rename the list. In case the list you want to rename supports events, you can also rename it with the Calendar app.

I will release a new version on Tuesday, maybe your boss can practice some patience until then 😉

**Comment by Leprazoriy** [comment]
Yes, I changed the Name and Color of the task list in the Calendar application, but the problem is that if you do this in the Calendar application, then the Name and Color of the task list changes only for the current user, and not for all users with whom you have shared this Task list ... It is important for me that the changes are applied to all users at once!

**Comment by raimund-schluessler** [comment]
> Yes, I changed the Name and Color of the task list in the Calendar application, but the problem is that if you do this in the Calendar application, then the Name and Color of the task list changes only for the current user, and not for all users with whom you have shared this Task list ... It is important for me that the changes are applied to all users at once!

This won't work with the Tasks app either.

Users can rename lists shared with them without changing the name for everyone, but only for themselves. This also means you cannot change the list name for everyone after it is shared already, as it might overwrite individual changes of the users. You might achieve what you want by unsharing and reshaping the renamed list, but I don't know for sure.

**Comment by Leprazoriy** [comment]
Yes, unshare task list, change the name and color, and reshare task list. I'm waiting for the new version of the application! Thanks!

**Comment by Leprazoriy** [comment]
Update! Completed testing! If the user has not changed the name and color of the Tasks list in their profile, then the global name and color for the task list, which was set by the user who created the task list, works. And if the user who created this list of tasks changes the Name and color, then changes occur for everyone, there is even no need to close and open public access! It's comfortable! So when the "Edit" button in the Tasks application works, I'll get what I need! Thank you for attention...

**Comment by raimund-schluessler** [comment]
Published a new release to the appstore.

**Comment by Leprazoriy** [comment]
Great thanks!
