### ISSUE TITLE
"Deleting the calendar in {countdown}"

### ISSUE THREAD

**Issue by HammyHavoc** [nextcloud/tasks#1279]
### Steps to reproduce
1. Delete a list on Tasks
2. Mouse over the 'revert'/'undo icon

### Expected behaviour
Correct language used

### Actual behaviour
![image](https://user-images.githubusercontent.com/503951/95882729-f2266480-0d71-11eb-9b3d-4204ea561aa4.png)
Mentions a 'calendar', this is really confusing for users as they think they're deleting a calendar rather than a list, and ultimately panic, and undo the deletion.

**Comment by raimund-schluessler** [comment]
Well, a task list is a calendar, so this is not confusing but exactly what it means.

But judging from your screenshot, you mean a list from Deck, right? In that case we could indeed name it like this exlicitly, although I don't know whether we can determine if it a list from Deck or really a calendar.
