### ISSUE TITLE
Too easy to delete a task by mistake

### ISSUE THREAD

**Issue by kommserv** [nextcloud/tasks#1328]
### Steps to reproduce
1. Open a new task
2. Add some text to the text area
3. Press Tab once, then press Spacebar
4. Voilá, the task is immediately deleted and all work on it is lost!

### Expected behaviour
The task should not be deleted due to pressing something as ubiqituous as the spacebar key. 
(I think pressing Tab is hardwired for many developers, sometimes you don't even think about it ;)

### Actual behaviour
This has happened several times over the last few months for me. I've been telling myself that complaining about this is rather frivolous, but now I don't think it is. It is way too easy to write some text in a task, then click Tab (because it seems to be the simplest way to see the rendered Markdown), then move the mouse pointer to some other window (say, the browser) and scroll along some webpage for a while (on my Ubuntu desktop, simply scrolling the mousewheel, without clicking, does not move the keyboard focus to that same window).

Do you notice how dangerous this situation is? 
It is not obvious, but if my analysis is correct, because the user pressed Tab once, the focus is now on the next element after the text box in the task sidebar, which is the *delete* button! (In this case, the user only pressed Tab with the intention to render the Markdown in the textbox).
Any distracted press of the spacebar key after that (assuming the focused window has not changed), and the task just vanishes. The user may not even understand what happened, when they later switch their focus back to the Nextcloud Tasks window.

I think the easiest fix for this UI problem is to move the delete button somewhere else. That has already been suggested (for different reasons) by others, e.g. in #651 and https://github.com/nextcloud/tasks/issues/521#issuecomment-528805157.

### Server configuration

**Operating system**: Ubuntu 18.04 server

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** 19.0.4

**Tasks version:** 0.13.5

This behaviour was the same for older Tasks versions (since the latest UI remake).

### Client configuration
**Browser:** Chrome 86.0.4240

**Operating system:** Ubuntu 18.04

**Comment by raimund-schluessler** [comment]
This never happened to me, but I can imagine it occuring. We currently rework the right sidebar in #1030. This includes moving the delete button into a dropdown menu similar to how it's done in the Calendar app. This should solve this issue.

**Comment by kommserv** [comment]
Fantastic! Turns out you guys were already on top of it. Go Nextcloud :-)
