### ISSUE TITLE
Moving subtasks between lists also moves the main task

### ISSUE THREAD

**Issue by AlarithUhde** [nextcloud/tasks#1329]
### Steps to reproduce
1. Create a task with a subtask in List A
2. Drag and drop the subtask to List B

### Expected behaviour
The main task should remain in List A while the subtask should be moved to list B and become a separate task there.

### Actual behaviour
The main task including the subtask is moved to list B. If other subtasks exist, they are also moved.

### Server configuration

**Operating system**: CentOS (7 I think)

**Web server:**

**Database:** MariaDB 10.3

**PHP version:** 7.4.11

**Nextcloud version:** 19.0.4

**Tasks version:** 0.13.5

**Updated from an older Nextcloud or fresh install:** updated

### Client configuration
**Browser:** Firefox 78.4.0

**CalDAV-clients:** Thunderbird 78.4.0

**Comment by raimund-schluessler** [comment]
I cannot reproduce this behaviour. Moving a subtask only moves the subtask (plus potential subsubtasks), but not the main task. Can you give a bit more detail how to reproduce this, please?

**Comment by AlarithUhde** [comment]
Just to make sure our wording is the same: With "List" I mean the calendars on the left hand side and on the bottom of the page there is a +-button labeled with "add list" ("Liste hinzufügen" in German).

Otherwise it's just as I described:
E.g. I have two lists, "today" and "later".
1. In "today" I add the task "clean the room". Then I add a subtask "get a broom".
2. When I try to move "get a broom" to the list "later", then the whole task "clean the room" will be moved to "later".

Would any log data help that I can provide? I have nextcloud installed on a shared host with no admin access to the server.

**Comment by raimund-schluessler** [comment]
Ok, I see what you mean and can reproduce it now. When you drag the subtask onto the list in the left sidebar, also the parent task is moved.

I moved the subtask between lists by dragging it from one list to the other in the main content section when having selected the "All" or "Current" collection. In that case it works fine.

**Comment by AlarithUhde** [comment]
Yes, I dragged it to the list on the left. I also tried the "all" and "current" collections and it works there for me as well.
