### ISSUE TITLE
Nextcloud 13 support

### ISSUE THREAD

**Issue by joekerna** [nextcloud/tasks#134]
### Steps to reproduce
1. Update to Nextcloud 13 Beta

### Expected behaviour
Tasks app should be available

### Actual behaviour
Tasks app is not available for Nextcloud 13

**Comment by joekerna** [comment]
I just saw it was already fixed in #130 It is just not included in Nextcloud 13 Beta 1 yet.

Thank you!

**Comment by raimund-schluessler** [comment]
Well, we still need to release it to the appstore.

**Comment by joekerna** [comment]
You're right.. Do you need me to test anything?

**Comment by raimund-schluessler** [comment]
It has been tested already, but testing current master with NC13 for sure wouldn't hurt ;)

**Comment by acidwars** [comment]
So when will you release it to the appstore? :)

**Comment by pss34** [comment]
As I can see, it is not here for now.
