### ISSUE TITLE
[Feature Request] No start date = No "Current" entry

### ISSUE THREAD

**Issue by Torenga** [nextcloud/tasks#1342]
Right now Tasks work on the philosophy that every single task is active except the ones that can't start yet (which is indicated by the start date.

I suggest changing it so that tasks without a start date doesn't show up in the "Current" view, indicating that such tasks are planned but aren't active and haven't gotten a confirmed start date yet.

Right now there's practically no difference between "All" and "Current" for me with approx. 95% of my tasks not having a start date, wasting a good view concept.

Thank you for your consideration.

**Comment by raimund-schluessler** [comment]
I tend to agree. What do @nextcloud/designers think about that?

**Comment by MaggiWuerze** [comment]
That would be really great, as I try to use Tasks as a general ToDo List and not only things that are immediate. Having only the ones that are actually near in current would definitely improve the experience

**Comment by duesseldorferjung** [comment]
+1 
So my practice is to sit down adding tasks like a backlog. 
After that I want to drag and drop them to example current week, to start working on it.

**Comment by duesseldorferjung** [comment]
I just observed adding a task in the ALL list does not add a startdate only if you add it in current or week.
So I guess this topic can be close. Is there some sort of documentation of how those features work??

**Comment by raimund-schluessler** [comment]
> I suggest changing it so that tasks without a start date doesn't show up in the "Current" view, indicating that such tasks are planned but aren't active and haven't gotten a confirmed start date yet.

Now that I think about it, not showing tasks without a start date (so showing only tasks with a start or due date that has passed) is exactly what the `Today` collection is doing. Hence, changing `Current` collection like this, doesn't make sense. One could debate the usefulness of the `Current` collection, but with it you can hide all Tasks starting in the future only. And in case this is of no use to you, you can hide the `Current` collection.

I'll close this a won't fix. Please speak-up if I got something wront.
