### ISSUE TITLE
[Feature Request] Show notes when hovering / mouse over the note icon without the need to open the task

### ISSUE THREAD

**Issue by klawdhfzasjhaa** [nextcloud/tasks#1351]
### Steps to reproduce
1. Open tasks app in web browser
2. Point the mouse over the note icon
3. Wait for the note to show up

### Expected behaviour
The concent of the note field should be displayed in a tool tip like "window"

### Actual behaviour
Nothing happens.

### Server configuration

**Operating system**: Raspbian (Linux 5.4.72-v7)

**Web server:** nginx/1.14.2 (fpm-fcgi)

**Database:** MariaDB (mysql 10.3.25)

**PHP version:** 7.3.19-1~deb10u1

**Nextcloud version:** 19.0.4 - 19.0.4.2

**Tasks version:** 0.13.6

**Updated from an older Nextcloud or fresh install:** old install

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:** Enabled:
 - accessibility: 1.5.0
 - admin_audit: 1.9.0
 - admin_notifications: 1.0.2
 - apporder: 0.11.0
 - calendar: 2.0.4
 - caniupdate: 0.2.0
 - cloud_federation_api: 1.2.0
 - comments: 1.9.0
 - contacts: 3.4.1
 - contactsinteraction: 1.0.0
 - cookbook: 0.7.6
 - dav: 1.15.0
 - deck: 1.2.0
 - federatedfilesharing: 1.9.0
 - files: 1.14.0
 - files_automatedtagging: 1.9.0
 - files_external: 1.10.0
 - files_mindmap: 0.0.23
 - files_pdfviewer: 1.8.0
 - files_retention: 1.8.2
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_videoplayer: 1.8.0
 - firstrunwizard: 2.8.0
 - gpxedit: 0.0.13
 - gpxpod: 4.2.2
 - issuetemplate: 0.7.0
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - mindmaps: 0.1.0
 - nextcloud_announcements: 1.8.0
 - notes: 3.6.4
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - occweb: 0.0.7
 - password_policy: 1.9.1
 - photos: 1.1.0
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - recommendations: 0.7.0
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - systemtags: 1.9.0
 - tasks: 0.13.6
 - text: 3.0.1
 - theming: 1.10.0
 - theming_customcss: 1.6.0
 - twofactor_backupcodes: 1.8.0
 - twofactor_u2f: 6.0.0
 - updatenotification: 1.9.0
 - viewer: 1.3.0
 - workflow_ocr: 1.19.1
 - workflow_pdf_converter: 1.4.0
 - workflow_script: 1.4.0
 - workflowengine: 2.1.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/nextcloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** FF 82

**Operating system:** Manjaro

**CalDAV-clients:** not important

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by raimund-schluessler** [comment]
I don't really think that this would be helpful. Tooltips are quite limited in size, so we could only show the first few lines. And for editing, you still need the sidebar.

With https://github.com/nextcloud/tasks/pull/1703 it will be possible to open a note directly by clicking on the icon. So instead of hovering over the icon, you just need to click and directly see the note.

**Comment by klawdhfzasjhaa** [comment]
Thanks for your answer!

"limited in size" is not an issue, as the use case is: scanning through the list of tasks and hovering over the Notes icon to get an idea of what it is about. The first 3-4 lines are enough for this purpose, no editing required. Problem with direct opening (in the sidebar or popup?) distracts the described workflow massively.

@TheNomad11: What do you think?

I will have a look though, once 0.14.1 is published.

**Comment by TheNomad11** [comment]
> @TheNomad11: What do you think?

I totally agree with you!

(OT: There are many other things that could be improved with the notes. For example, what to do with all the notes after the task is completed but contain useful information? Will have to create a new issue or discussion thread one day....)

**Comment by klawdhfzasjhaa** [comment]
I've now tested #1703, but my request stays valid. Also because the notes sidebar takes up too much space. To only get a glimpse of the notes for several tasks after one another the hovering feature would be much nicer.

Have a nice week!
