### ISSUE TITLE
Sort by due date - add sections & sort on same due date/time

### ISSUE THREAD

**Issue by th23x** [nextcloud/tasks#1369]
Hi together,

I would like to suggest an improvement for displaying / structuring the tasks list - especially when sorted by due date:

1) It would help greatly to get a quick overview, when the individual tasks would be grouped into few key sections - based on due date "Past", "Today", "Next 7 days", "Later", and "No date"

2) For tasks with the same due date/time, I would suggest to order them by importance (from high to low)

Thanks for considering this in some future update :-)

**Comment by raimund-schluessler** [comment]
>   1. It would help greatly to get a quick overview, when the individual tasks would be grouped into few key sections - based on due date "Past", "Today", "Next 7 days", "Later", and "No date"

I would say this is basically what the smart lists on the left are for, no?

>   2. For tasks with the same due date/time, I would suggest to order them by importance (from high to low)

Fine with me. Can be easily done by adding `sortByPriority` here:
https://github.com/nextcloud/tasks/blob/master/src/store/storeHelper.js#L227

**Comment by th23x** [comment]
> > 1. It would help greatly to get a quick overview, when the individual tasks would be grouped into few key sections - based on due date "Past", "Today", "Next 7 days", "Later", and "No date"
> 
> I would say this is basically what the smart lists on the left are for, no?

Okay, but with these I always only see then the selection eg all tasks for "Today". My idea would be still to have the full overview, but have this structured by secions in the list. If unclear, I can try to put a mockup together...

**Comment by ModusB** [comment]
> > 2. For tasks with the same due date/time, I would suggest to order them by importance (from high to low)
> 
> Fine with me. Can be easily done by adding `sortByPriority` here: https://github.com/nextcloud/tasks/blob/master/src/store/storeHelper.js#L227

Can I pay for this update? @raimund-schluessler

**Comment by raimund-schluessler** [comment]
> > > 2. For tasks with the same due date/time, I would suggest to order them by importance (from high to low)
> > 
> > 
> > Fine with me. Can be easily done by adding `sortByPriority` here: https://github.com/nextcloud/tasks/blob/master/src/store/storeHelper.js#L227
> 
> Can I pay for this update? @raimund-schluessler

No need to pay for this, it's a minor change that will come with the next release. See #2210.
