### ISSUE TITLE
Bug - Deadline - Bug - Horaire d'échéance

### ISSUE THREAD

**Issue by KPB-69** [nextcloud/tasks#1380]
Hello, 
I have a bug regarding the deadline, the task deadlines are all one hour ahead of what I planned.
How can I fix this bug?

Regards,

--

Bonjour, 
J'ai un bug concernant la date limite, les dates limites des tâches ont toutes une heure d'avance sur ce que j'ai planifiée.
Comment puis-je corriger ce bug?

Cordialement,

PHP - 7.4
NextCloud - 20.0.4
Tasks - 0.13.6

**Comment by raimund-schluessler** [comment]
This is probably a timezone issue. Task doesn't support timezones yet, see #1233

**Comment by raimund-schluessler** [comment]
Let's track this further in #1233.
