### ISSUE TITLE
Tasks app not loading/shown correctly

### ISSUE THREAD

**Issue by Kombustor** [nextcloud/tasks#1383]
### Screenshot

![](https://i.imgur.com/6nPeMQI.png)

### Steps to reproduce
1. Open task page

### Expected behaviour
The tasks should be loaded and shown correctly

### Actual behaviour
No tasks are shown and the UI is buggy

## Server configuration detail

**Operating system:** Linux 4.14.138-rancher

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 10.5.8

**PHP version:** 

7.4.13
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 20.0.4 - 20.0.4.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** Docker

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.13.4
 - apporder: 0.11.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.2
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.2
 - contactsinteraction: 1.1.0
 - dav: 1.16.2
 - duplicatefinder: 0.0.4
 - external: 3.7.1
 - federatedfilesharing: 1.10.2
 - federation: 1.10.1
 - files: 1.15.0
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.1
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - issuetemplate: 0.7.0
 - lookup_server_connector: 1.8.0
 - nextcloud_announcements: 1.9.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - photos: 1.2.1
 - previewgenerator: 3.1.0
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - richdocuments: 3.7.11
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - spreed: 10.0.4
 - tasks: 0.13.6
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - twofactor_totp: 5.0.0
 - unsplash: 1.1.7
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - accessibility
 - admin_audit
 - dashboard
 - encryption
 - files_external
 - files_external_dropbox
 - files_mindmap
 - firstrunwizard
 - logreader
 - onlyoffice
 - password_policy
 - polls
 - serverinfo
 - support
 - survey_client
 - systemtags
 - text
 - user_ldap
 - user_saml
 - whiteboard

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.redacted.com"
    ],
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.redacted.com",
    "overwriteprotocol": "https",
    "overwritehost": "cloud.redacted.com",
    "htaccess.RewriteBase": "\/",
    "dbtype": "mysql",
    "version": "20.0.4.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "3306",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": "3",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "updater.release.channel": "stable",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "twofactor_enforced": "false",
    "twofactor_enforced_groups": [],
    "twofactor_enforced_excluded_groups": [],
    "data-fingerprint": "----------",
    "has_rebuilt_cache": true,
    "mail_sendmailmode": "smtp",
    "preview_max_x": 512,
    "preview_max_y": 512,
    "preview_max_scale_factor": 1,
    "encryption.key_storage_migrated": false
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
None
```
</details>

<details><summary>Nextcloud log</summary>

```
None
```
</details>

Browser log

**The resource from “https://cloud.redacted.com/apps/files/” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).tasks**

**Comment by raimund-schluessler** [comment]
This is very likely a caching issue with your configuration. Please refresh all caches (server and browser). If that does not help, try reinstalling the Tasks app.

**Comment by Kombustor** [comment]
I cleared all cached, reinstalled the app and even completely re-initialized all containers (`docker-compose down && docker-compose up -d`) with no luck.

But I noticed something. After the last step, the error in the browser changed to:
`GET https://cloud.redacted.com/custom_apps/tasks/css/tasks.css?v=98d620c4-19
[HTTP/2 404 Not Found 26ms]`
because the .htaccess wasn't generated yet.

I can't reproduce it, but then I got a MIME type mismatch error on a tasks css file.

After generating the .htaccess with `occ maintenance:update:htaccess` again the previous error re-appeared:
`The resource from “https://cloud.redacted.com/apps/files/” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).       tasks`

I'm posting this issue in this repository as all other apps and NC itself work fine for me, but it seems not to be a caching issue.

**Comment by raimund-schluessler** [comment]
Is the CSS file correctly available in the appdata folder?

**Comment by Kombustor** [comment]
> Is the CSS file correctly available in the appdata folder?

Yes, my assumption is that the 404 error was created due to the .htaccess not being generated, but the app assumed the files are available at `/custom_apps/tasks/...` instead of `/index.php/custom_apps/tasks/...`

**Comment by raimund-schluessler** [comment]
The Tasks app uses the same mechanism to load the style as probably all other Nextcloud apps (see https://github.com/nextcloud/tasks/blob/master/templates/main.php#L4). It is a solution provided by Nextcloud server, so it is not clear to me, why this should fail here, but works for other apps.

**Comment by Kombustor** [comment]
> The Tasks app uses the same mechanism to load the style as probably all other Nextcloud apps (see https://github.com/nextcloud/tasks/blob/master/templates/main.php#L4 and compare it to e.g. Calendar https://github.com/nextcloud/calendar/blob/master/templates/main.php#L23). It is a solution provided by Nextcloud server, so it is not clear to me, why this should fail here, but work for other apps.

I doesn't make sense for me either, but I re-checked and the tasks app is the only one with this issue I can find.

**Comment by raimund-schluessler** [comment]
@Kombustor Could you resolve the issue?

**Comment by raimund-schluessler** [comment]
@Kombustor Ping.

**Comment by Kombustor** [comment]
Sorry, was absent the last days. The issue still persists, I don't know how to solve it.

**Comment by raimund-schluessler** [comment]
@skjnldsv @georgehrke Do you have an idea here?

**Comment by raimund-schluessler** [comment]
@Kombustor Could you please check if this is still the case with 0.14.0?

**Comment by Kombustor** [comment]
The issue disappeared after updating to Nextcloud 20.0.11 & Tasks 0.14.0 :+1:
