### ISSUE TITLE
(Feature request) Show upcoming tasks in Dashboard 'Upcoming Events' pane.

### ISSUE THREAD

**Issue by Ruthalas** [nextcloud/tasks#1396]
It would be really cool if upcoming tasks were visible in the Dashboard 'Upcoming Events' pane, the same way upcoming Deck cards are.

I know there's another issue for making a dedicated Tasks widget for the Dashboard (issue 1243), but this seems like a different functionality, and possibly a simple one(?).

Thanks for the app!

**Comment by Mela** [comment]
Yes, please. A own "tasks" pane also would be very welcome.

**Comment by jakobroehrl** [comment]
duplicate of https://github.com/nextcloud/tasks/issues/1243

**Comment by raimund-schluessler** [comment]
Let's track this is #1243. If you want the Calendar app widget to show tasks as well, please report this in the Calendar repository (although I think having a dedicated Tasks widget is the better solution).
