### ISSUE TITLE
prompt to delete a task or provide undo delete

### ISSUE THREAD

**Issue by teneighty-yvr** [nextcloud/tasks#1408]
### Steps to reproduce
1. Create task
2. Click delete task (unintentionally).

### Expected behaviour
Prompt to delete the task if not reversible, or provide either a trash where deleted tasks can be restored from, or undo delete feature. If any of these features are implemented, they are difficult to find in the UI.

### Actual behaviour
Task is deleted immediately and permanently.

### Server configuration

**Operating system**: 
Debian 10

**Web server:**
NginX

**Database:**
Postgresql

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
19.0.6

**Tasks version:** (see Nextcloud apps page)
0.13.6

**Updated from an older Nextcloud or fresh install:**

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/nextcloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by raimund-schluessler** [comment]
@nextcloud/designers What do you think? As far as I know, we don't ask for confirmation anywhere.

**Comment by tcitworld** [comment]
I like the time-based confirmation to delete calendars we've got on the calendar app.

Also see https://github.com/nextcloud/server/issues/1662 for long-term.

**Comment by teneighty-yvr** [comment]
I didn't think to use the keyword "trashbin", still, I don't know how I missed nextcloud/server#1662 in my search.

That discussion seems very focused on calendars and events, but tasks app issue #29 is the same idea and it's still open. Duplicate. Sorry.

**Comment by raimund-schluessler** [comment]
Let's keep this open. I think it's worth implementing.

Because now that you reported this, I realized we have an inconsistency in the app about how we delete tasks:
- If you delete a task in the list view (by clicking the three-dots menu -> delete), we have a time-based confirmation with the possibility to cancel deletion within 7 seconds.
- If you delete a task in the details view (right sidebar), it gets deleted immediately, without any confirmation. We should have a time-based warning in the sidebar as well.

The trashbin really is the prefered long-term solution, but requires server changes. So we can try to reduce data loss with changes on the client side. And a time-based approach also doesn't interfere to much, in case you want to delete multiple tasks.

**Comment by teneighty-yvr** [comment]
Ok. In that case, sounds like a good plan. Thank you @raimund-schluessler!
