### ISSUE TITLE
[Feature Request] Expose List order in WebDAV

### ISSUE THREAD

**Issue by marbetschar** [nextcloud/tasks#1415]
Although this does not seem to be documented in the standard, quite a lot of clients do support this. Therefore it would be handy to have the [custom list order](https://github.com/nextcloud/tasks/pull/1155) exposed via the WebDAV property `calendar-order` (this seems to be already done with `calendar-color`).

For more context see:

- https://github.com/python-caldav/caldav/blob/529073d9d907e18200ed0b51ca0c920174ad5242/caldav/lib/namespace.py#L9-L18
- https://github.com/python-caldav/caldav/blob/master/docs/source/index.rst#misbehaving-server-implementations

**Comment by raimund-schluessler** [comment]
This property is exposed by Nextcloud server via CalDAV already as `calendar-order` .

If you need something more/else, please report this in the server repository. The Tasks app is just a CalDAV client itself, and does not handle the CalDAV server implemention (which is done by Nextcloud server).

**Comment by marbetschar** [comment]
@raimund-schluessler twow, hat was quick! Thanks, good to know - somehow missed that.
