### ISSUE TITLE
[Feature request] Sort tasks by tag name

### ISSUE THREAD

**Issue by rubenmantecon** [nextcloud/tasks#1427]

**Comment by raimund-schluessler** [comment]
I don't think we will implement this. We already have 9 sorting options and I am a bit reluctant to add even another one. Also, I don't think this will work well in case of multiple tags on a task.

@nextcloud/designers For feedback.

**Comment by hoshi411** [comment]
This would have been the most important sorting feature considering there is currently no way to filter by tags , making tags completely useless.

What is the point of adding a tag to a a task if I cannot then filter by tags in any sort of way at all?

**Comment by Bugsbane** [comment]
> This would have been the most important sorting feature considering there is currently no way to filter by tags

This seems like a good argument to implement filtering by tag, rather than sort by tag which, as pointed out, is not likely to work with random multiple tags on different tasks.

**Comment by raimund-schluessler** [comment]
> I expected the tags on the tasks to work like a button so that I could push it and it would show me all tasks with that tag, but I tried and absolutely nothing happened.  

Well... that's what I would expect too.

But... this is open-source, non-commercial software. Let me explain this: no one considering this feature important was motivated to contribute, and no one motivated to contribute considered this feature important (enough over other tasks to keep the app running).

But here is the silver lining: this is your chance to break this cycle and be the one to contribute code for this feature motivated.

I know it sucks that features one desires are not implemented, but keep in mind, you get the app for free, which also means, you are free to use something else.
