### ISSUE TITLE
cannot collapse Task, if there is a sub-sub-task

### ISSUE THREAD

**Issue by aseedorf** [nextcloud/tasks#143]
First create a Task (1) and under that a subtask (1.1)
collapsing the main-task (1) works

in this subtask(1.1) create a sub-sub-task (1.1.1)
collapsing the main task does not work

deleting the sub-sub-task (1.1.1) solves the collapsing problem

**Comment by raimund-schluessler** [comment]
Sorry, I cannot reproduce this.
Could it be, that you have the sub- or sub-sub-task open in the sidebar? If a subtask is open, it overwrites the collapse setting of the parent task, so that the subtask is visible.

**Comment by aseedorf** [comment]
You are right
It was a combination of an open sub-task in the sidebar and a "hanging" browser.
Firefox (58.0.1) did not correctly recognized a click on another task (e.g. task 2)
a reload fixed it
