### ISSUE TITLE
0.9.6 is broken

### ISSUE THREAD

**Issue by yan12125** [nextcloud/tasks#144]
### Steps to reproduce
1. Download https://github.com/nextcloud/tasks/releases/download/v0.9.6/tasks.tar.gz
2. Decompress it to the nextcloud/apps folder
3. Try to access the app from the browser

### Expected behaviour
Works fine as usual

### Actual behaviour
![default](https://user-images.githubusercontent.com/1937689/35973084-141eaad6-0d0f-11e8-95c8-51755b8e4847.png)

### Server configuration

**Operating system**: Arch Linux x86_64

**Web server:** Apache 2

**Database:** SQLite

**PHP version:** 7.2.2

**Nextcloud version:** (see Nextcloud admin page)
13.0

**Tasks version:** (see Nextcloud apps page)
0.9.6

**Updated from an older Nextcloud or fresh install:**
Updated from an older Nextcloud

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - calendar: 1.6.0
  - contacts: 2.0.1
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - comments
  - encryption
  - federation
  - files_external
  - gallery
  - systemtags
  - user_external
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "chyen.csie.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/127.0.0.1\/nextcloud",
        "dbtype": "sqlite3",
        "version": "13.0.0.14",
        "logtimezone": "UTC",
        "installed": true,
        "appstoreenabled": false,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpport": "587",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox Nightly 60.0a1 (2018-02-07)

**Operating system:**
Arch Linux

**CalDAV-clients:**
N/A

#### Web server error log
```
(Not sure what does this mean)
```

#### Nextcloud log (data/nextcloud.log)
```
Nothing special. Just quite a few updater logs
```

#### Browser log
```
Seems nothing special. All requests returns 200 OK
```

**Comment by raimund-schluessler** [comment]
My guess is that the access rights are wrong since you manually downloaded it. Please try do automatically install it from the appstore and check if the issue persists.

**Comment by yan12125** [comment]
Thanks for the hint. Installing from the official app store works fine. Sorry for bothering!
