### ISSUE TITLE
App broken on Nextcloud 12.0.x

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/tasks#145]
### Steps to reproduce
1. Update app to 0.9.6

### Expected behaviour
Good display

### Actual behaviour
Display is broken. Browser and server logs don't seem to contain any relevant info, it's just the CSS/JS that's broken.

![selection_175](https://user-images.githubusercontent.com/2197836/36029601-24cda8ce-0da4-11e8-8a80-552dc4bed1e5.png)

P.S : Integrity check failure isn't related to this app.

### Server configuration
**Operating system**: Debian

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page)12.0.2 (same with 12.0.3)

**Tasks version:** (see Nextcloud apps page) 0.9.6

### Client configuration
**Browser:** Firefox Nightly, Chromium stable

**Operating system:** Debian unstable

**Comment by raimund-schluessler** [comment]
How did you update or install it? I have used and tested it with 12.0.5 and it looks just fine.

**Comment by tcitworld** [comment]
Through the web updater. It happened on two different instances, so I guess it wasn't an error while updating. Uninstalling and reinstalling didn't fix it.
Unfortunately I won't be able to test the app with these instances on 12.0.5 since I'll upgrade them directly to 13, but I'll try to set up a 12.0.3 instance to have a look.

**Comment by raimund-schluessler** [comment]
This is weird. It looks as if neither CSS nor JS are loaded at all.

**Comment by raimund-schluessler** [comment]
Could you check the access rights for the tasks app folder?

**Comment by tcitworld** [comment]
They seem to be all right.

However, the call to the task app `style.css` returns an empty file, so I guess that's the issue.

**Comment by tcitworld** [comment]
In 12.0.3, we don't have those SCSS related PRs : https://github.com/nextcloud/server/pull/7688, https://github.com/nextcloud/server/pull/6661, https://github.com/nextcloud/server/pull/7257

**Comment by raimund-schluessler** [comment]
> In 12.0.3, we don't have those SCSS related PRs : nextcloud/server#7688, nextcloud/server#6661, nextcloud/server#7257

Hm, can we mitigate this within the app? Or does this mean, we cannot use SCSS in < 12.0.5 at all? Maybe @skjnldsv as well.

**Comment by raimund-schluessler** [comment]
Also, could we set 12.0.5 as minimal version?

**Comment by skjnldsv** [comment]
@raimund-schluessler Nop, scss is active on stable12.

**Comment by khoebling** [comment]
@skjnldsv my apps directory is under the nextcloud web directory and i have the same issues

**Comment by skjnldsv** [comment]
Any errors in the nextcloud log?

**Comment by khoebling** [comment]
After manual upgrading from 12.0.0 to 12.0.5 the issues disappeared

**Comment by raimund-schluessler** [comment]
IE is a different problem and not supported. On IE there are more problems than just the styling.

Seems like NC12.0.5 is necessary to get rid of SCSS problems.

**Comment by raimund-schluessler** [comment]
IE is a different problem and not supported. On IE there are more problems than just the styling.

Seems like NC12.0.5 is necessary to get rid of SCSS problems.

**Comment by skjnldsv** [comment]
@raimund-schluessler I'd like to know why though :p

**Comment by raimund-schluessler** [comment]
> @raimund-schluessler I'd like to know why though :p

Yes, that would be good. But I think this is more of a server issue, than an issue of this app.

**Comment by skjnldsv** [comment]
We need a server log to be sure, but I think too!

**Comment by tcitworld** [comment]
Unfortunately I didn't see anything relevant inside it.

**Comment by skjnldsv** [comment]
@tcitworld did you tried clearing your appdata cache?

**Comment by tcitworld** [comment]
Yeah, deleting `appdata_*/css/tasks/*` didn't change anything.

**Comment by skjnldsv** [comment]
Strange. We need to find out what is the issue here.

**Comment by raimund-schluessler** [comment]
I vaguely remember that I might have experienced something similar, but I don't know anymore exactly how I solved it. Could you try to create the empty folder `appdata_*/css/tasks/` with the correct access rights (the same as the other folders in in `css`, please?

**Comment by tcitworld** [comment]
It already had fine access rights. However, it seems the folder isn't repopulated since I deleted files inside it.

**Comment by skjnldsv** [comment]
I will try with a 12.0.5 installation when I have the time! :)

**Comment by tcitworld** [comment]
As @khoebling said it seems to work with 12.0.5, just not with 12.0.3 and 12.0.2.

**Comment by raimund-schluessler** [comment]
With 12.0.5 everything worked for me when I tested it.

**Comment by skjnldsv** [comment]
@raimund-schluessler yes, up-to-date versions should be considered as the current supported ones. We need to move forward, we can't patch downward. 👍

**Comment by tcitworld** [comment]
I have no issues with versions not supported being ignored, but it would be better if the app was marked as incompatible with these versions ;)

**Comment by skjnldsv** [comment]
@tcitworld but 12.0.5 is supported right? :)

**Comment by tcitworld** [comment]
Yeah, but we could set min-version="12.0.5" instead of `min-version="12"` ;)

**Comment by skjnldsv** [comment]
Does the appinfo parser supports it? :p

**Comment by khoebling** [comment]
I just went through the logs again, but there were no errors before updating to 12.0.5

**Comment by raimund-schluessler** [comment]
> Does the appinfo parser supports it? :p

If the parser supports that, we will change it accordingly.

**Comment by tcitworld** [comment]
I think I found the issue : `Undefined variable $color-border: line: 242`

**Comment by raimund-schluessler** [comment]
> I think I found the issue : Undefined variable $color-border: line: 242

Does it work when you add it?

**Comment by tcitworld** [comment]
I tried, unfortunately deleting the files inside appdata_*/css/tasks/* and force refreshing or running cron doesn't seem to recreate them. Anyway to clear the SCSS cache properly ?

**Comment by skjnldsv** [comment]
@tcitworld see rullzer's app for this purpose https://github.com/rullzer/appdatacleaner
Then it's with the occ command line

**Comment by tcitworld** [comment]
Yup, fixes it. 👍

**Comment by raimund-schluessler** [comment]
Ok, then I will add this variable to https://github.com/nextcloud/tasks/blob/master/css/src/nc12.scss

**Comment by raimund-schluessler** [comment]
Fix is in https://github.com/nextcloud/tasks/pull/147

**Comment by raimund-schluessler** [comment]
Problem should be fixed now. Would you consider this worth a new release?

**Comment by tcitworld** [comment]
Well, no one else reported the issue here or on https://help.nextcloud.com so I guess it's fine to wait next release.

**Comment by danopz** [comment]
Just updated tasks (0.9.6) on my NC12 (<12.0.5) and got the same issue.

**Comment by alexgleason** [comment]
I'm using Nextcloud 12.0.3 and installed tasks 0.9.6 from the admin UI. I also experienced this issue. I will try updating to Nextcloud 13 later.

**Comment by alexgleason** [comment]
Ohh, I get it, the fix isn't in the latest release. Yes, if you made a new release that would be helpful! Thank you.

**Comment by tcitworld** [comment]
Upgrading to 12.0.5 or the latest is far easier ;)

**Comment by alexgleason** [comment]
I've upgraded to 12.0.5 but still having the issue. I chose not to go with 3.0 because I'm using mailinabox which doesn't support it yet.

**Comment by alexgleason** [comment]
I'm also happy manually editing the .scss file to make this change, but I'm not sure how to use the above-linked appdatacleaner :confused:

**Comment by tcitworld** [comment]
@raimund-schluessler Sad to report it's again broken with 0.97 and NC 13.0.5.
