### ISSUE TITLE
[Feature Request] Show all Tasks with that category, when clicking on a category pill

### ISSUE THREAD

**Issue by MaggiWuerze** [nextcloud/tasks#1453]
It would be great if i could see a list of all Tasks that share the same category when clicking on it in the interface.
![image](https://user-images.githubusercontent.com/9729962/111449754-fb946e00-870f-11eb-9f8a-d5593719a2fe.png)

Maybe there could also be a list of used categories below the lists

**Comment by raimund-schluessler** [comment]
Implemented by #2427.
