### ISSUE TITLE
 [Feature Request] Dynamic Lists based on category

### ISSUE THREAD

**Issue by MaggiWuerze** [nextcloud/tasks#1458]
When trying to structure the different Tasks, it would be nice if you could have them show up in dynamic lists based on a tag.

You could for example have ToDo Lists like Next, Scheduled or something like that and within them have Tasks tagged with "Garden". 

A "Garden" list that collects the Tasks with the same tag would be really useful. That way you wouldn't have to use the search every time you want to find all similar Tasks.

**Comment by SamuXzX** [comment]
It could be useful to tag this feature request in the main the main thread where they were discussing it: #89

**Comment by raimund-schluessler** [comment]
There is now the option to filter by tags. Creating a permanent smart list from a filter might come as an enhancement and is tracked in #220.
