### ISSUE TITLE
[Feature request] Sort by Category

### ISSUE THREAD

**Issue by Coderdude112** [nextcloud/tasks#1466]
Hello,

This isn't available right now but I think sorting by the category such as what tick tick (They call them tags) allows would be very helpful, especially for bigger todo lists like school or work where individual todo lists wouldn't be helpful.

**Comment by arrowd** [comment]
Another idea pretty close to this one - make it possible to list all tasks with a given tag. Maybe in form of special collection, or something.

**Comment by SamuXzX** [comment]
I too think that the tag system should be enhanced. There's an old thread where they were discussing the various improvements needed: #89

**Comment by MaximeMaW** [comment]
We also have inquiries from users about this feature!

**Comment by raimund-schluessler** [comment]
> We also have inquiries from users about this feature!

I would propose to pay someone to implement it then.

**Comment by MaximeMaW** [comment]
Hi @raimund-schluessler, this is definitely an option, would you be able to direct me towards someone who would be willing to discuss that?

**Comment by macpac59** [comment]
I would like to see that feature as well. The list could then contain multiple instances of a task if more than one tag has been assigned but that could be helpful for some workflows.

**Comment by hoshi411** [comment]
How was this only being considered two years ago since it is basic operation of any gtd / task app in existence since the beginning of time.  What was the point of having a tags function without the ability to filter by those tags ?
