### ISSUE TITLE
[Feature request] picture attachments

### ISSUE THREAD

**Issue by tylnesh** [nextcloud/tasks#1470]
iOS reminders app support adding picture (and other) attachments to the reminders. Would be nice to have this feature in the Nextcloud Tasks as well.

**Comment by raimund-schluessler** [comment]
As far as I know, iOS reminders does not support attachments for CalDAV lists (at least, I couldn't find this option on my device). So I doubt that supporting attachments in Tasks would benefit iOS reminders (other clients might do).

Anyway, attachments are tracked in #91 already.
