### ISSUE TITLE
[Feature Request] Change order of lists

### ISSUE THREAD

**Issue by RandolfEbelt** [nextcloud/tasks#15]
1. It would be nice to be able to change the order of lists manually in the overview list
2. Currently, it is not possible to create a list and drag an existing item to this new empty list

**Comment by Braintelligence** [comment]
Also it would be awesome if you could create nested lists. 👍

**Comment by korelstar** [comment]
Instead of nested lists, you may use subtasks.

**Comment by Braintelligence** [comment]
I'm thinking of something like a list CLIENTS with other lists Client A, Client B, Client C and so on. If I create a task in the list Client A, then I will see the task in Client A and CLIENTS. If I create a task in Client B as well I can see it in Client B and CLIENTS but not in Client A.

**Comment by korelstar** [comment]
I understand. But I think it would be better, to create a new issue for your feature-request, @Braintelligence

**Comment by joel-porquet** [comment]
There is currently a way of reordering task lists, but manually (eg using phpmyadmin).

Task lists are actually stored as calendars in the database, in table "oc_calendars". For each row of the table (ie each task list), there already exists a field called "calendarorder" (added in version 1.6.0 according to the changelog). By default, this field is 0 for all lists, which means that the nextcloud server returns the list of tasks by creation order (ie according to their creation ID). But if you change the field manually, it is correctly reflected. Note that the number is treated in ascending order: a list with calendarorder=0 will appear before a a list with calendarorder>0.

For example, if I have two tasks lists:
- "listA" created first
- and "listB" created second
By default, the tasks app displayed them in the creation order: listA, listB

Now if I manually change the field calendarorder to '1' for listA, then the tasks app displays them in the new order: listB, listA.

It'd be great if the tasks app could give a way to manage the calendarorder field :)

**Comment by raimund-schluessler** [comment]
Calendar has implemented this recently: https://github.com/nextcloud/calendar/pull/2244

**Comment by raimund-schluessler** [comment]
Implemented with https://github.com/nextcloud/tasks/pull/1155.
