### ISSUE TITLE
popover menu below main view

### ISSUE THREAD

**Issue by mcnesium** [nextcloud/tasks#1507]
In Firefox 87, Nextcloud v21.0.1 Tasks v0.13.6 the popover menu in the sidebar on the left is covered partially by the main view:

<img src="https://user-images.githubusercontent.com/476060/115115852-f177c080-9f96-11eb-96c8-2f58c72b5f57.png" width="50%" height="50%"/>

**Comment by raimund-schluessler** [comment]
This works for me in latest master now.
