### ISSUE TITLE
Icons lost after update

### ISSUE THREAD

**Issue by johannsele** [nextcloud/tasks#153]
### Steps to reproduce
1. updating nc from 12.0.4. to 13.0.1 and also updating all apps

### Expected behaviour
all icons should be visable like before

### Actual behaviour
most icons don't appear propperly or even don't show up at all.

### Server configuration
**Web server:** nginx

**Database:** sqlite

**PHP version:** latest

**Tasks version:** 0.9.6

Does anyone have the same issue?

I appreciate any hint and/or help.
Best regards

**Comment by raimund-schluessler** [comment]
Please try to clear the cache of your browser and reload the page.

**Comment by johannsele** [comment]
I did so, but i didn't help.

**Comment by johannsele** [comment]
Just to show whats wrong.

![icon - tasks](https://user-images.githubusercontent.com/33330230/37713405-2396c4ee-2d17-11e8-9e07-af5c7f1a731f.png)

**Comment by raimund-schluessler** [comment]
This looks as if the old sprite file from the Tasks version you used before is used. Maybe the server caches it somewhere? You could try to disable and delete the app and reinstall it.

You could also check if the same thing happens with an other device to check if it is cached on the server or client side.

**Comment by johannsele** [comment]
Different device worked. There seems to be stuck something on my computer. Thank you.
