### ISSUE TITLE
Tasks and Deck cards should be "the same"

### ISSUE THREAD

**Issue by dtcg** [nextcloud/tasks#1544]
Nextcloud Deck integration seems read-only and... pretty useless:

* All Deck lists are automatically mixed in a single Task list: unusable.
* Tasks in a "Deck task list" are undraggable, untickable, uneditable: what is the point?
* Tasks from a "normal" task list can't be dragged into a "deck" task list.

It seems to me that Tasks and cards in Deck don't share the same underlying structure.  
Any chance of actually merging the two technologies?  Rather than offering a pretty broken workaround?
(I don't mean to sound rude, sorry. Only surprised at the current implementation)

**Comment by raimund-schluessler** [comment]
As you said, Deck lists are currently read-only. So obviously, no editing, no dragging. The corresponding issue is https://github.com/nextcloud/deck/issues/2399.

Whether or not having all Deck lists in a single Task list is a good decision can be up to debate. Please also discuss this in the Deck repository. Tasks simply shows what is offered via CalDAV and has no influence on how Deck serves its data over CalDAV. If you don't like having a "broken workaround" shown, you can turn it off in the Deck app settings..
