### ISSUE TITLE
[Feature Request] Sharing Task List

### ISSUE THREAD

**Issue by Rebexter** [nextcloud/tasks#156]
Hi,

Could you add sharing a task list, the same way one can share a folder in nextcloud?
This would be a great step towards working together with other people on a task.

Thanks :)

**Comment by GoetheG** [comment]
@Rebexter: Yes, this would be the most important thing to do. Then we could have everything at one spot :).

@developer: Thank you very much for doing this jop. I like you tasks app very much and hope it will evolve in the future,

**Comment by sunjam** [comment]
[Perhaps the NextNote app, which has Rich Text support, could help provide this functionality,](https://github.com/brantje/nextnote/issues/89#issuecomment-380684750)

**Comment by GoetheG** [comment]
@sunjam Any idea when NextNote will be part of the Nextcloud App Store?

**Comment by GoetheG** [comment]
Thank you for your work, @sunjam.

**Comment by JumpLink** [comment]
Any update by adding sharing support?

**Comment by raimund-schluessler** [comment]
Duplicate of #14
