### ISSUE TITLE
l10n: No native language translation

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/tasks#1561]
### Steps to reproduce

1. Select a task list.
2. Select "Load all completed tasks".

There is an untranslated text string `[Completed] L`. The translation in l10n is for Polish.

![obraz](https://user-images.githubusercontent.com/47037905/117122881-a501f280-ad96-11eb-99d0-10f8953bcf0b.png)

https://github.com/nextcloud/tasks/blob/b1b0c31fdc64cbcf09f35a3a6794e15b0947937f/src/views/AppSidebar.vue#L315-L322

### Server configuration

**Nextcloud version:** 21.0.0

**Tasks version:** 0.13.6

**Comment by raimund-schluessler** [comment]
Translations are handled via Transifex. The string in question is quite new, so it probably wasn't translated there, or not pulled to the repository yet. E.g. for German it is translated correctly, so it should work in principle.

**Comment by Valdnet** [comment]
@raimund-schluessler I know it's new and that's why I added it manually to the l10n files on my server but still no translation. Only later did I notice that it was not adapted to the l10n 😉.

**Comment by raimund-schluessler** [comment]
> 
> 
> @raimund-schluessler I know it's new and that's why I added it manually to the l10n files on my server but still no translation. Only later did I notice that it was not adapted to the l10n 😉.

What do you mean by `not adapted to the l10n`? Do you think we need to adjust something here?

**Comment by Valdnet** [comment]
I mean, it wasn't adapted to l10n translations before. It looked like this: `nextWeek: "[Completed] L"`.

**Comment by raimund-schluessler** [comment]
> 
> 
> I mean, it wasn't adapted to l10n translations before. It looked like this: `nextWeek: "[Completed] L"`.

Hm? I am confused. When was this ever the case? The strings were always wrapped inside the `$t()` function.

https://github.com/nextcloud/tasks/blob/master/src/views/AppSidebar.vue#L317-L322

**Comment by Valdnet** [comment]
It is in version v0.13.6.

**Comment by raimund-schluessler** [comment]
These string didn't even exist in v0.13.6. They were only added when we moved to the AppSidebar component in #1030, and there they were wrapped properly: https://github.com/nextcloud/tasks/pull/1030/files#diff-58161df558fc7d5cb4d78e5fcd93fe30aa6a8392f8931ba73ce7a58b3cd462afR317-R322

Anyway, is there anything to do here? I think all is fine now, right?

**Comment by Valdnet** [comment]
Yes. When a new version is released, it will be possible to say with certainty 😉.
