### ISSUE TITLE
calendar not visible in chromium

### ISSUE THREAD

**Issue by benkibbey** [nextcloud/tasks#157]
### Steps to reproduce
1. Load the Calendar app in Nextcloud

### Expected behaviour
Should be able to see the calendar.

### Actual behaviour
Between the < previous and > next  month selector is: {{ | dt datepickerFilter:selectedView }}
The Day Week Month and Today buttons are available but don't do anything.

**Operating system**:
Debian testing

**Web server:**
lighttpd 1.4.49

**Database:**
postgresql 10.3

**PHP version:**
7.2

**Nextcloud version:**
git stable-13

### Client configuration
**Browser:**
Chromium 65.0.3325.146

Firefox 58 *does* work correctly.

**Operating system:**
Debian GNU/Linux (testing)

**Comment by raimund-schluessler** [comment]
This is the repo for Tasks, pleas report your issue in https://github.com/nextcloud/calendar.
