### ISSUE TITLE
use text-box-outline instead of NoteText?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/tasks#1577]
Hi @raimund-schluessler, 
I think the text-box-outline (might be called differently) icon does fit better for notes than the NoteText icon. What do you think? 
I've created a fast mockup:
| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/117643022-410d6e80-b188-11eb-9163-3f028cb6d572.png) | ![image](https://user-images.githubusercontent.com/42591237/117643280-86ca3700-b188-11eb-8a57-f1951e365c0e.png) |

(of course this should then also be changed in the list view)

**Comment by raimund-schluessler** [comment]
I don't have a preference her tbh. I just took the icon which resembled the previous one best. Maybe @nextcloud/designers have a recommendation or guideline here

**Comment by szaimen** [comment]
For me the NoteText icon looks like a text file or attachment and is quite confusing for me since it is a simple text/description and not a file, hence I find the texto-box-outline icon better which looks more like text/desccirption/notes to me.
