### ISSUE TITLE
[Feature Request] Optional Checklist-handling from OpenTask-App

### ISSUE THREAD

**Issue by newhinton** [nextcloud/tasks#159]
The OpenTask-App implemented an easy way to handle checklists, which does not rely on Subtasks. I think it would be a great idea to support those kinds of list as an option.

I have provided a screenshot which shows my idea.
![Image of Idea](https://s2.imagebanana.com/file/180409/NIWr2qII.png)

I would like to implement this by myself, but i am not sure where to start.

**Comment by raimund-schluessler** [comment]
Supporting markdown in description field is already in #76 as @danopz pointed out.

However, you also want to show subtasks from the description field as real subtasks in the main view. Although this might be possible by parsing the description field, I don't think this is a good idea. This fake subtasks will behave different than normal subtasks, since they cannot have a due- or start-date, priority, own subtasks or any other additional information.

This will most likely lead to confusion for the user, since they cannot do anything else than checking, unchecking or renaming the subtask. I think this would be perceived as a bug of the app, in case the user is not aware it is a fake subtask.

Hence, I in my opinion, rendering the fake subtask nicely in the description field of the parent task is the best solution.

**Comment by newhinton** [comment]
This is the current state and represents a way to deal with this

![Image of State](https://s2.imagebanana.com/file/180411/9khveuIt.png)

**Comment by raimund-schluessler** [comment]
This could be one solution. But as a first iteration I would go with parsing markdown in the notes field only. We can then enhance this to showing fake subtasks in the main view as well.

I would not introduce further settings.

**Comment by newhinton** [comment]
I understand that markdown-parsing would (or at least could) solve this issue, but sadly i dont have time nor the ability to implement such feature. I want to contribute and as far it concerns me, this "simple" extension of the subtasks is already big enough to acomplish  at this time, so i would like to concentrate my time to the main view, because that is a goal which i can achieve and may improve this app.

If that clashes with your long term planing, please say so, i will not try to push a feature that is not yet due.

**Comment by pixelipo** [comment]
Hi @newhinton - thanks for joining the team! I'm looking forward to your contributions, however, I have to agree with @raimund-schluessler - I think the best place for these "fake subtasks" is the description area.

One important element that should be implemented as part of this (or #76 ) is that marking elements as checked also automatically updates percentage done for a task...

By the way, implementing markdown shouldn't really be a very big task - it's mostly just a matter of choosing an existing parser node package and making sure it plays along nicely with the rest of the code.

If you don't have time for it, maybe I will be able to find some time during May to get it done.

**Comment by newhinton** [comment]
@pixelipo You are right, it could be confusing, for users who stumble across this "duplicate" task-element. However, i also think that users who do know why there are a second set of tasks would appreciate the ability to see those tasks in the main list. It makes managing them easier. 

One possible solution to this dilemma would be to disable it in the default, and enable it via the usersetting for this app. Then this would only show up if a user opts-in. 


The percentage done is a feature i planned implementing after my first prototype works, which means basic editing and managingfunctions.

**Comment by raimund-schluessler** [comment]
I would not add further options here and always show them if the markdown string " - [ ] Subtask" is found in the description field. If a user puts a markdown checkbox there, I think it is reasonable to interpret it as a subtask and show it accordingly. Maybe a headline like "Subtasks from the description field" (feel free to make this shorter/more precise) over the "fake subtasks" would be enough to clearly indicate that these tasks come from the description field.

I don't think that updating the percentage done is really a blocking issue for showing the subtasks.

**Comment by danopz** [comment]
Even as OpenTasks user I think I don't really like this new feature. Those checkboxes are part of the description, they are no subtasks, so should they be displayed next to the description field. Also OpenTasks is not showing them as subtasks in their overview, just in the details view.

**Comment by raimund-schluessler** [comment]
Since we support markdown in the description field and render the checkboxes now, I am going to close this issue. Feel free to comment if you don't agree.
