### ISSUE TITLE
Tasks app disappeared after upgrade from OwnCloud to NextCloud

### ISSUE THREAD

**Issue by agilob** [nextcloud/tasks#16]
### Steps to reproduce
1. Upgrade from ownCloud 8.x or 9.x (I don't remember which one) to NextCloud 9 then to 10
2. Tasks app was installed before, files in /app/ still exist, but there is no app named Tasks to enable/disable, there is no UI for tasks in top left side menu.
3. Tasks are still handled correctly by DavDroid
4. I tried reinstalling Tasks by removing /app/tasks/ cloning from git and providing correct permissions, still app is not visible in webui (not on disabled/enabled lists)

### Expected behaviour
I would totally expect to have UI for Tasks in web-ui

### Server configuration
**Operating system**: Debian

**Web server:** nginx

**Database:** mysql

**PHP version:** `PHP 5.6.27-0+deb8u1 (cli) (built: Oct 15 2016 15:53:28) `

**ownCloud version:** (see ownCloud admin page) Latest production

**Tasks version:** (see ownCloud apps page)

**Updated from an older ownCloud or fresh install:**

**Signing status (ownCloud 9.0 and above):**

**List of activated apps:** Calendar, PDF viewer, LibreOffice editor, Contacts, Gallery, Activity

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'datadirectory' => 'owncloud/data',
  'overwrite.cli.url' => ',
  'dbtype' => 'mysql',
  'version' => '8.2.3.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'theme' => '',
  'maintenance' => false,
  'ldapIgnoreNamingRules' => false,
  'appstore.experimental.enabled' => true,
  'loglevel' => 2,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'trashbin_retention_obligation' => 'auto',
);

```

**Are you using encryption:** no

**Comment by eppfel** [comment]
> Tasks are still handled correctly by DavDroid

Tasks is just a Frontend for the CalDav implementation in Nextcloud/ownCloud, so even if the Tasks app is disabled you can access your tasks over CalDav in DavDroid etc.

> (not on disabled/enabled lists)

Have you tried using the occ command or is it just missing in the web UI:

```
sudo -u www-data php occ app:list
```

If it is disable try:

```
sudo -u www-data php occ app:enable tasks
```

Any errors in the logs?

**Comment by agilob** [comment]
Ok I run:

```
$sudo -u nginx php occ app:list
Enabled:
  - activity: 2.2.1
  - calendar: 1.4.1
  - contacts: 1.4.0.0
  - documents: 0.12.1
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - gallery: 14.5.0
  - provisioning_api: 0.4.1
Disabled:
  - encryption
  - external
  - files_encryption
  - files_external
  - files_locking
  - files_trashbin
  - files_versions
  - files_videoviewer
  - firstrunwizard
  - galleryplus
  - gpxpod-oc
  - libreonline
  - mobilecomp
  - news
  - notifications
  - tasks
  - templateeditor
  - updater
  - user_external
  - user_ldap
  - user_webdavauth
```
then:
```
$sudo -u nginx php occ app:enable tasks
tasks enabled
```

Then I tried to login with a browser, after login update was triggered (?) I get message to contact administrator and check server logs. Server log doesn't contain anything useful for me:
```
{"reqId":"ZHRK5oaomq0gz\/k6HIVZ","remoteAddr":"92.19.43.205","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/home\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/home\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2016-05-29T19:15:45+00:00"}
{"reqId":"1ekkZm++G1xbW3T3jwx2","remoteAddr":"92.19.43.205","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/home\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/home\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2016-05-29T19:17:00+00:00"}
{"reqId":"syx4AXty0WN4USrL2J3p","remoteAddr":"92.19.43.205","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/home\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/home\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2016-05-29T19:17:46+00:00"}
{"reqId":"++rDVKtwx3e07DZTyLzO","remoteAddr":"92.19.43.205","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/home\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/home\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2016-05-29T19:18:52+00:00"}
{"reqId":"M8te2v9Pmiej+JueI9VU","remoteAddr":"92.19.43.205","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/home\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/home\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2016-05-29T22:31:26+00:00"}
{"reqId":"i8+yqZ13FSWK0vWYvO9u","remoteAddr":"195.122.150.130","app":"core","message":"Archives of type text\/html are not supported","level":3,"time":"2016-05-30T18:05:14+00:00"}
{"reqId":"wbeN2LycpOLKrmm\/hg2w","remoteAddr":"195.122.150.130","app":"PHP","message":"Call to undefined method OC\\Server::getShareManager() at \/home\/owncloud\/apps\/gpxpod\/appinfo\/application.php#50","level":3,"time":"2016-05-30T18:05:59+00:00"}
{"reqId":"DB3cHqi\/D53Te73\/8U35","remoteAddr":"195.122.150.130","app":"PHP","message":"Call to undefined method OC\\Server::getShareManager() at \/home\/owncloud\/apps\/gpxpod\/appinfo\/application.php#50","level":3,"time":"2016-05-30T18:06:24+00:00"}
{"reqId":"1mcxuIGblXsD\/4wSYAul","remoteAddr":"195.122.150.130","app":"PHP","message":"Call to undefined method OC\\Server::getShareManager() at \/home\/owncloud\/apps\/gpxpod\/appinfo\/application.php#50","level":3,"time":"2016-05-30T18:07:01+00:00"}
{"reqId":"xGxFeqiLcKfZJprxfb\/V","remoteAddr":"","app":"core","message":"starting upgrade from 8.2.3.2 to 8.2.3.2","level":0,"time":"2016-12-02T13:13:48+00:00","method":"--","url":"--"}
```

When I try to login again, there is nothing appended to the log file. Just it and info about internal server error.

Running it second time, shows that tasks was not enabled:

**Comment by agilob** [comment]
Uff, fixed database problem by reinstalling NC and downloading Tasks app.

**Comment by eppfel** [comment]
Do you have update logs, might be interesting, if there was a migration bug. Did this fix everything for you?

**Comment by agilob** [comment]
Looks like I haven't lost any data, or at least I can't find any now, so it looks good. Tasks app after re-install was upgrading as before, but this time it didn't fail and list of tasks is available from web-UI.

All logs I have since that time is useless, it doesn't even mention upgrades (too high log level?)

>{"reqId":"9dB27ZyVwSbHEk5SwqBO","remoteAddr":"81.144.171.73","app":"admin_audit","message":"Login attempt: \"agilob\"","level":1,"time":"2016-12-02T12:52:04+00:00","method":"PROPFIND","url":"\/remote.php\/dav\/addressbooks\/users\/agilob\/contacts\/","user":"--"}
{"reqId":"9dB27ZyVwSbHEk5SwqBO","remoteAddr":"81.144.171.73","app":"admin_audit","message":"Login successful: \"agilob\"","level":1,"time":"2016-12-02T12:52:04+00:00","method":"PROPFIND","url":"\/remote.php\/dav\/addressbooks\/users\/agilob\/contacts\/","user":"agilob"}
{"reqId":"Tw66A\/sBR0TQPaLZfyEE","remoteAddr":"83.22.54.117","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT `fileid`, `storage`, `path`, `parent`, `name`, `mimetype`, `mimepart`, `size`, `mtime`,\\n\\t\\t\\t\\t\\t   `storage_mtime`, `encrypted`, `etag`, `permissions`, `checksum`\\n\\t\\t\\t\\tFROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?' with params [\\\"23\\\", \\\"d41d8cd98f00b204e9800998ecf8427e\\\"]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'checksum' in 'field list'\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/home\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `fileid`...', Array)\\n#2 \\\/home\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(184): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `fileid`...', Array, Array, NULL)\\n#3 \\\/home\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/cache.php(128): OC\\\\DB\\\\Connection->executeQuery('SELECT `fileid`...', Array)\\n#4 \\\/home\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/homecache.php(75): OC\\\\Files\\\\Cache\\\\Cache->get('')\\n#5 \\\/home\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1262): OC\\\\Files\\\\Cache\\\\HomeCache->get('')\\n#6 \\\/home\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1315): OC\\\\Files\\\\View->getCacheEntry(Object(OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption), '', '\\\/k')\\n#7 \\\/home\\\/owncloud\\\/lib\\\/private\\\/files\\\/node\\\/root.php(179): OC\\\\Files\\\\View->getFileInfo('\\\/k')\\n#8 \\\/home\\\/owncloud\\\/lib\\\/private\\\/files\\\/node\\\/root.php(341): OC\\\\Files\\\\Node\\\\Root->get('\\\/k')\\n#9 \\\/home\\\/owncloud\\\/lib\\\/private\\\/server.php(742): OC\\\\Files\\\\Node\\\\Root->getUserFolder('k')\\n#10 \\\/home\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/serverfactory.php(126): OC\\\\Server->getUserFolder()\\n#11 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ServerFactory->OCA\\\\DAV\\\\Connector\\\\Sabre\\\\{closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/home\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#13 \\\/home\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#14 \\\/home\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#15 \\\/home\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#16 \\\/home\\\/owncloud\\\/remote.php(138): require_once('\\\/home\\\/owncloud\\\/...')\\n#17 {main}\",\"File\":\"\\\/home\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":71,\"User\":\"k\"}","level":4,"time":"2016-12-02T13:15:03+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"k"}
{"reqId":"ZREBxiwxmAwcphtVvqTg","remoteAddr":"83.22.54.117","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT `fileid`, `storage`, `path`, `parent`, `name`, `mimetype`, `mimepart`, `size`, `mtime`,\\n\\t\\t\\t\\t\\t   `storage_mtime`, `encrypted`, `etag`, `permissions`, `checksum`\\n\\t\\t\\t\\tFROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?' with params [\\\"23\\\", \\\"d41d8cd98f00b204e9800998ecf8427e\\\"]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'checksum' in 'field list'\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/home\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `fileid`...', Array)\\n#2 \\\/home\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(184): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `fileid`...', Array, Array, NULL)\\n#3 \\\/home\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/cache.php(128): OC\\\\DB\\\\Connection->executeQuery('SELECT `fileid`...', Array)\\n#4 \\\/home\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/homecache.php(75): OC\\\\Files\\\\Cache\\\\Cache->get('')\\n#5 \\\/home\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1262): OC\\\\Files\\\\Cache\\\\HomeCache->get('')\\n#6 \\\/home\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1315): OC\\\\Files\\\\View->getCacheEntry(Object(OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption), '', '\\\/k')\\n#7 \\\/home\\\/owncloud\\\/lib\\\/private\\\/files\\\/node\\\/root.php(179): OC\\\\Files\\\\View->getFileInfo('\\\/k')\\n#8 \\\/home\\\/owncloud\\\/lib\\\/private\\\/files\\\/node\\\/root.php(341): OC\\\\Files\\\\Node\\\\Root->get('\\\/k')\\n#9 \\\/home\\\/owncloud\\\/lib\\\/private\\\/server.php(742): OC\\\\Files\\\\Node\\\\Root->getUserFolder('k')\\n#10 \\\/home\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/serverfactory.php(126): OC\\\\Server->getUserFolder()\\n#11 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ServerFactory->OCA\\\\DAV\\\\Connector\\\\Sabre\\\\{closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/home\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#13 \\\/home\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#14 \\\/home\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#15 \\\/home\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#16 \\\/home\\\/owncloud\\\/remote.php(138): require_once('\\\/home\\\/owncloud\\\/...')\\n#17 {main}\",\"File\":\"\\\/home\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":71,\"User\":\"k\"}","level":4,"time":"2016-12-02T13:15:06+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"k"}

My issue is closed, thanks.

**Comment by eppfel** [comment]
OK, happy to help! 👍
