### ISSUE TITLE
Deleting Calendar

### ISSUE THREAD

**Issue by mtzfamly** [nextcloud/tasks#162]
### Steps to reproduce
1. Delete Task Owner
2.
3.

### Expected behaviour
Deletes only the Task owner's List
### Actual behaviour
Deleted Task owners names off list AND Calendar

**Comment by raimund-schluessler** [comment]
Could you ellaborate a bit on this, please? I think I don't understand your problem.

**Comment by raimund-schluessler** [comment]
Closing since there was no feedback. Feel free to reopen in case.
