### ISSUE TITLE
Enable Support for Nextcloud 22

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/tasks#1648]
Thanks

**Comment by raimund-schluessler** [comment]
What exactly do you mean? The app already supports NC22:
https://github.com/nextcloud/tasks/blob/master/appinfo/info.xml#L23

**Comment by jakobroehrl** [comment]
I use the latest tasks version:
![image](https://user-images.githubusercontent.com/24530680/123242262-2138cc80-d4e2-11eb-92b9-ec44d17773b7.png)

**Comment by raimund-schluessler** [comment]
Ah, yes, that's because it's not released to the appstore yet. Anyway closing, since it will be fixed with the next release.

**Comment by dvzrv** [comment]
@raimund-schluessler The currently available application is [only available for up to (and including) nextcloud 21](https://github.com/nextcloud/tasks/blob/d5205a59e71e6cfe09db5ceb2463b70209df6c1c/appinfo/info.xml#L23).

Would it be possible for your to update and release the app? it is currently blocking the update to nextcloud 22 on Arch Linux.
Thanks! :)

**Comment by raimund-schluessler** [comment]
Please see https://github.com/nextcloud/tasks/issues/1676
