### ISSUE TITLE
Increase the `Load all completed tasks` button and add an icon?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/tasks#1667]
`Load all completed tasks` should have a minimal clickable size of 44px like other components and an icon, too.

See https://github.com/nextcloud/tasks/issues/1665 for further details.

**Comment by utack** [comment]
Could this be why I only see it in Chromium and not Firefox any more after the new update?

**Comment by raimund-schluessler** [comment]
> 
> 
> Could this be why I only see it in Chromium and not Firefox any more after the new update?

We didn't change anythin in this regard yet. I will have a look.
