### ISSUE TITLE
Nextcloud 22 compatibility

### ISSUE THREAD

**Issue by waja** [nextcloud/tasks#1676]
Hi,

Nextcloud 22 was released today. Would be great if there can be released a compatible app.

Many thanks for your good work, Jan.

**Comment by raimund-schluessler** [comment]
Latest master is already compatible with NC22, and Tasks v0.13.6. should also work without problems (although not specifically marked as compatible). Official compatibility will come with v0.14.0, see https://github.com/nextcloud/tasks/milestone/8 for what's left to do before the release.

I will leave this issue open until v0.14.0 is released, so we don't get further duplicates.

**Comment by waja** [comment]
@raimund-schluessler thanks for declaring.

**Comment by robwolff3** [comment]
I just tried to "Enable untested app" and the tasks app does not run it seems to me. The icon doesn't show in the top app bar and when you navigate to /apps/tasks/ it redirects back to dashboard. Is there another way to get to the tasks app up in the mean time until the v0.14.0 release? Ive become very dependent on it, love the app otherwise, thank you so much!

**Comment by TomBraider42** [comment]
I see other issues in fresh installed NC 22. Tasks is enabled and activated but doesn't work (no actions possible) and looks ...
![tasks](https://user-images.githubusercontent.com/5128016/124884004-2b72c480-dfd2-11eb-988b-a0a47b0b8dbf.png)

**Comment by raimund-schluessler** [comment]
I will pack a pre-release of the app with the status of current master and upload it here for you to test this evening.

**Comment by raimund-schluessler** [comment]
> 
> 
> I see other issues in fresh installed NC 22. Tasks is enabled and activated but doesn't work (no actions possible) and looks ...
> ![tasks](https://user-images.githubusercontent.com/5128016/124884004-2b72c480-dfd2-11eb-988b-a0a47b0b8dbf.png)

You don't have a writable task list. The list you show comes from the Deck app and is read-only. Create a new task list on the left.

**Comment by raimund-schluessler** [comment]
Here is the alpha release of v0.14.0. Trashbin and Talk integration are missing, but it should work just fine on NC22.
[tasks.tar.gz](https://github.com/nextcloud/tasks/files/6786619/tasks.tar.gz)

**Comment by Sp1l** [comment]
> 
> 
> Latest master is already compatible with NC22, and Tasks v0.13.6. should also work without problems (although not specifically marked as compatible). Official compatibility will come with v0.14.0, see https://github.com/nextcloud/tasks/milestone/8 for what's left to do before the release.
> 
> I will leave this issue open until v0.14.0 is released, so we don't get further duplicates.

Would appreciate this reflected in v0.13.7...

**Comment by raimund-schluessler** [comment]
> 
> 
> > Latest master is already compatible with NC22, and Tasks v0.13.6. should also work without problems (although not specifically marked as compatible). Official compatibility will come with v0.14.0, see https://github.com/nextcloud/tasks/milestone/8 for what's left to do before the release.
> > I will leave this issue open until v0.14.0 is released, so we don't get further duplicates.
> 
> Would appreciate this reflected in v0.13.7...

No, this won't happen. v0.14.0 will come when it's ready, until then you can use 0.14.0-alpha.1: [tasks.tar.gz](https://github.com/nextcloud/tasks/files/6786619/tasks.tar.gz) Maintaining stable branches to release patch updates for older versions is to much work for me alone.

**Comment by Sp1l** [comment]
> No, this won't happen. v0.14.0 will come when it's ready, until then you can use 0.14.0-alpha.1: [tasks.tar.gz](https://github.com/nextcloud/tasks/files/6786619/tasks.tar.gz) Maintaining stable branches to release patch updates for older versions is to much work for me alone.

As a maintainer of the FreeBSD Nextcloud ports, I have an interest in making sure I can update all apps ports with the major upgrade so users don't get caught out with non-functional (if only disabled) apps.

I do appreciate that these upgrades aren't trivial! Many thanks for maintaining this app!

**Comment by carhe** [comment]
Hi there, 

First of all thank you very much for your great job with Nextcloud and Nextcloud Tasks.

Some days ago I received the update to Nextcloud 22 (I use the docker image). Since then I have trouble with moving tasks between lists. In some cases it works, but in other (increasing number of) cases it fails with an unspecific error message ("Es ist ein Fehler aufgetreten.").

I tried to monitor it and find out when it fails. My impression is that movement fails when a task is shifted from some list A to some list B and then back to A (A -> B works, B -> A fails). Is it possible that there is an issue with IDs or so?

I tried it first with Tasks v0.13.6 and afterwards with the v0.14.0-alpha-1 version provided above. It does not seem that 0.14.0 changes anything in this regard.

**Comment by raimund-schluessler** [comment]
> As a maintainer of the FreeBSD Nextcloud ports, I have an interest in making sure I can update all apps ports with the major upgrade so users don't get caught out with non-functional (if only disabled) apps.

I know it's unfortunate and I am also not happy with being delayed, but it is what it is, sorry.

Would it help you if I put v0.14.0-alpha.1 to the appstore? This should at least simplify the installation of the alpha version.

**Comment by raimund-schluessler** [comment]
> Some days ago I received the update to Nextcloud 22 (I use the docker image). Since then I have trouble with moving tasks between lists. In some cases it works, but in other (increasing number of) cases it fails with an unspecific error message ("Es ist ein Fehler aufgetreten.").
> 
> I tried to monitor it and find out when it fails. My impression is that movement fails when a task is shifted from some list A to some list B and then back to A (A -> B works, B -> A fails). Is it possible that there is an issue with IDs or so?

Could you please create an issue for this problem including server and browser logs, please? I never noticed this problem so far and there were also no changes in Tasks that I would relate to such an issue (especially since it occurs with v0.13.6 as well).

**Comment by carhe** [comment]
> > Some days ago I received the update to Nextcloud 22 (I use the docker image). Since then I have trouble with moving tasks between lists. In some cases it works, but in other (increasing number of) cases it fails with an unspecific error message ("Es ist ein Fehler aufgetreten.").
> > I tried to monitor it and find out when it fails. My impression is that movement fails when a task is shifted from some list A to some list B and then back to A (A -> B works, B -> A fails). Is it possible that there is an issue with IDs or so?
> 
> Could you please create an issue for this problem including server and browser logs, please? I never noticed this problem so far and there were also no changes in Tasks that I would relate to such an issue (especially since it occurs with v0.13.6 as well).

I added an issue: https://github.com/nextcloud/tasks/issues/1685

**Comment by john-2000** [comment]
> > As a maintainer of the FreeBSD Nextcloud ports, I have an interest in making sure I can update all apps ports with the major upgrade so users don't get caught out with non-functional (if only disabled) apps.
> 
> I know it's unfortunate and I am also not happy with being delayed, but it is what it is, sorry.
> 
> Would it help you if I put v0.14.0-alpha.1 to the appstore? This should at least simplify the installation of the alpha version.

yes if you could the 0.14.-0-alpha.1 in the appstore that would work (for me at least), however would not want you to be flooded with issues and comments due to its alpha state

**Comment by dvzrv** [comment]
> Would it help you if I put v0.14.0-alpha.1 to the appstore? This should at least simplify the installation of the alpha version.

This (assuming it comes with a tag and a build in this repository) would allow Arch Linux to ship that build and eventually update nextcloud to >= 22.0.0.
It would be much appreciated, unless you think https://github.com/nextcloud/tasks/milestone/8 is close to completion anyhow, in which case I'd rather wait for you to craft a stable release :)

(sorry for necro-bumping that other ticket, I didn't see this one)

**Comment by raimund-schluessler** [comment]
> It would be much appreciated, unless you think https://github.com/nextcloud/tasks/milestone/8 is close to completion anyhow, in which case I'd rather wait for you to craft a stable release :)

I will release 0.14.0 later today. It will also contain the trash bin implementation. This will allow to update to NC22, although some fixes and updated translations will only come with 0.14.1.

Just out of curiosity (since I don't use Arch): Does Arch actually ship the Tasks app or is the app still installed from the Nextcloud appstore (and you just wait to ship Nextcloud 22 until the Tasks app is ready)?

**Comment by raimund-schluessler** [comment]
Tasks v0.14.0 is in the appstore now.

**Comment by dvzrv** [comment]
> Does Arch actually ship the Tasks app or is the app still installed from the Nextcloud appstore (and you just wait to ship Nextcloud 22 until the Tasks app is ready)?

We ship the tasks app: https://archlinux.org/packages/community/any/nextcloud-app-tasks/

However, users are still able to install whichever app they want to from the app store as well (we offer a writable location for nextcloud to store apps in).
