### ISSUE TITLE
[Feature Request] Share a Task with a Circle -- Circles App Integration

### ISSUE THREAD

**Issue by sunjam** [nextcloud/tasks#169]
[See this PR from the Calendar app on sharing an event within a Circle.](https://github.com/nextcloud/calendar/pull/602)

Circles app integration would be very useful!  [Here is a link to the API documentation](https://github.com/nextcloud/circles/wiki)

[_Circles - Create groups with other users on a Nextcloud instance and share with them_](https://github.com/nextcloud/circles)

Slightly different but issue #14, #72 and #156 on sharing tasks / lists relate to this request.

**Comment by GoetheG** [comment]
Xes @sunjam. This is a feature I think we all need. Basically I think that this app should have all the functions CalDav allows to use like adding users, set a time for the stand and the end of a task.

**Comment by GoetheG** [comment]
Anything new here?

**Comment by morgannunan** [comment]
I installed Tasks and Circles, and I don't see any way to share a task with a circle. I see that you can share a whole calendar, but not an individual task.

**Comment by sunjam** [comment]
@morgannunan let's discuss further on help.nextcloud.com and link back here.  Can you please create a post and then link it here.  Thanks.
