### ISSUE TITLE
Allow to delete all items in the trash bin at once

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/tasks#1692]

**Comment by Aeredren** [comment]
I coded it in frontend by iterating over the list of items, as suggested in the similar issue for calendar https://github.com/nextcloud/calendar/issues/3171

I still have to fix the button placement before any PR.

**Comment by raimund-schluessler** [comment]
> 
> 
> I coded it in frontend by iterating over the list of items, as suggested in the similar issue for calendar [nextcloud/calendar#3171](https://github.com/nextcloud/calendar/issues/3171)
> 
> I still have to fix the button placement before any PR.

Great, thanks a lot! Feel free to send a (draft) PR already.
