### ISSUE TITLE
Allow to open the notes of a task directly

### ISSUE THREAD

**Issue by szaimen** [nextcloud/tasks#1698]
Hi there, 
first of all, thanks for the great 0.14.0 release!

## The problem
Sometimes I want to see the notes of a task. 
Since the 0.14.0 release, it needs two clicks to show the notes. 
Would be great if there was a way to open the notes of a task directly.

## Possible solution
Use the notes icon in the list view to open the notes section in the sidebar directly.
![image](https://user-images.githubusercontent.com/42591237/126068459-c726f7c5-dfe0-49bb-857a-8916c9c9974c.png)

Thanks for considering!

**Comment by raimund-schluessler** [comment]
Makes sense.

**Comment by szaimen** [comment]
🎉
