### ISSUE TITLE
Show task title in appsidebar title tooltip

### ISSUE THREAD

**Issue by szaimen** [nextcloud/tasks#1699]
Hi there,

I am not sure if this is new in the 0.14.0 release but I am unable to see the whole title of a task in the sidebar. Would be great if there was a way to see the whole title of a task in the sidebar by default since the title is already cut in the list view and there is currently no place to see the whole title without editing it.

Thanks for considering!

![image](https://user-images.githubusercontent.com/42591237/126068711-83e4ba9e-1b5a-48c0-a3ac-24d4a6dc6fe0.png)

**Comment by raimund-schluessler** [comment]
This is a limitation of the app-sidebar component from nextcloud/vue. There is an issue to change it to two lines https://github.com/nextcloud/nextcloud-vue/pull/1788

**Comment by raimund-schluessler** [comment]
We could set the titleTooltip prop for the appsidebar to show the title in a tooltip already.
