### ISSUE TITLE
Due date for Nextcloud Task not synchonized to aCalendar via OpenTasks app on Android

### ISSUE THREAD

**Issue by armaccloud** [nextcloud/tasks#170]
When using aCalendar + required supporting apps to make it work with nextcloud, the due date is not synchonized to aCalendar for tasks that have been created using nextcloud tasks. The way around (task created within aCalendar) does synchronize the due date towards Nextcloud Tasks.

### Steps to reproduce
On Android
1. Install the OpenTasks app (https://f-droid.org/packages/org.dmfs.tasks/)
2. install Davdroid (https://f-droid.org/packages/at.bitfire.davdroid/)
3. Install the aCalendar + Calendar & Tasks app (https://play.google.com/store/apps/details?id=org.withouthat.acalendarplus)
4. Open the Nextcloud Tasks
5. Create a task with a due date (all date)
6. Synchronize on Android

### Expected behaviour
The tasks is synchronized, including the due date

### Actual behaviour
The task is synchronized, but the due date on the task is not

## Server configuration detail

**Operating system:** Linux 3.10.0-714.10.2.lve1.4.75.el7.x86_64 #1 SMP Fri Nov 3 04:25:16 EDT 2017 x86_64

**Webserver:** Apache (litespeed)

**Database:** mysql 10.1.33

**PHP version:** 7.1.16
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, litespeed, bcmath, bz2, calendar, ctype, curl, dba, dom, enchant, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, exif, mcrypt, mysqlnd, odbc, PDO, pgsql, Phar, posix, pspell, shmop, SimpleXML, snmp, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, wddx, xmlreader, xmlrpc, redis, Zend OPcache

**Nextcloud version:** 13.0.2 - 13.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Integrity checker has been disabled. Integrity cannot be verified.
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - apporder: 0.4.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.1
 - contacts: 2.1.3
 - dav: 1.4.6
 - deck: 0.3.1
 - encryption: 2.0.0
 - federatedfilesharing: 1.3.1
 - files: 1.8.0
 - files_markdown: 2.0.4
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - ownbackup: 17.5.0
 - passman: 2.1.4
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - tasks: 0.9.6
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - twofactor_totp: 1.4.1
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - comments
 - federation
 - files_external
 - firstrunwizard
 - systemtags
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "arnomuhren.hostiso.host"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/arnomuhren.hostiso.host",
    "dbtype": "mysql",
    "version": "13.0.2.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "integrity.check.disabled": true,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "updater.release.channel": "stable",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes

## Client configuration

**Browser:** Firefox Quantum 59.0.2 (64-bit)

**Operating system:** 
PC: ElementaryOS 0.4.1 Loki
Smartphone: LineageOS 14.1-20171228-NIGHTLY-klte - Android 7.1.2

**Comment by raimund-schluessler** [comment]
Thanks for the report. Is the due date visible/saved in the Nextcloud Tasks app after a reload of the app?

**Comment by armaccloud** [comment]
Hi @raimund-schluessler 
Indeed these seem related. The due date is gone after I refresh the app.
When re-setting the due date, opening the files app, reopening the tasks app; the due date is present.
That task now also synchronizes to my phone.
