### ISSUE TITLE
Can't create a task of a talk message

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/tasks#1707]
![image](https://user-images.githubusercontent.com/24530680/126779588-b15ac759-25c0-4a0a-8f1d-e018d99868ae.png)

There is no calendar to select. 
Tested in 2 different servers, NC 21, and NC22. 
But on both servers calendars are useable in the task app itself.

**Comment by raimund-schluessler** [comment]
I can also see that. It's probably a regression after implementing the trash bin, where I changed the name of the action for getting the calendars.

This line
https://github.com/nextcloud/tasks/blob/18de6fbbdc6fa500c06d020a428ab964e8bc8714/src/components/TaskCreateDialog.vue#L154

will need to be changed to
```js
await this.$store.dispatch('getCalendarsAndTrashBin')
```
I guess.
