### ISSUE TITLE
title of the task becomes overwritten

### ISSUE THREAD

**Issue by cocoonie** [nextcloud/tasks#1714]
### Steps to reproduce
1. Click on a task
2. Click on the title of the task in the right field
3. The title becomes editable
4. Click on the next task in the list

### Expected behaviour
The title of the newly clicked task is displayed in the right field

### Actual behaviour
The title of the previous task will be copied to the current one (overwrites the current one). This cannot be undone and causes confusion as two different tasks with the same title are now displayed.

## Server configuration detail

**Operating system:** Linux 4.15.0-38-generic #41~16.04.1-Ubuntu SMP Wed Oct 10 20:16:04 UTC 2018 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.7.33

**PHP version:** 

7.3.25-1+ubuntu16.04.1+deb.sury.org+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, apcu, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, geoip, gettext, gmp, gnupg, iconv, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, pdo_sqlite, apc, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 20.0.11 - 20.0.11.1

**Updated from an older Nextcloud/ownCloud or fresh install:** done by hoster ocloud.de

**Where did you install Nextcloud from:** done by hoster ocloud.de

<details><summary>Signing status</summary>

Integrity checker has been disabled. Integrity cannot be verified.
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.4
 - admin_audit: 1.10.0
 - apporder: 0.13.0
 - audioplayer: 3.1.0
 - calendar: 2.3.1
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 4.0.0
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.2
 - deck: 1.2.8
 - external: 3.7.3
 - federatedfilesharing: 1.10.2
 - federation: 1.10.1
 - files: 1.15.0
 - files_markdown: 2.3.4
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.2
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - forms: 2.2.4
 - impersonate: 1.7.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - onlyoffice: 6.4.2
 - password_policy: 1.10.1
 - photos: 1.2.3
 - polls: 2.0.6
 - provisioning_api: 1.10.0
 - rainloop: 7.1.2
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - side_menu: 1.25.2
 - spreed: 10.0.9
 - systemtags: 1.10.0
 - tasks: 0.14.0
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - encryption
 - files_external
 - firstrunwizard
 - nextcloud_announcements
 - privacy
 - support
 - survey_client
 - updatenotification
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***.ocloud.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/***.ocloud.de",
    "dbtype": "mysql",
    "version": "20.0.11.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "enable_previews": "true",
    "loglevel": 0,
    "maintenance": false,
    "appstore.experimental.enabled": true,
    "integrity.check.disabled": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "versions_retention_obligation": "10,30",
    "trashbin_retention_obligation": "10,30",
    "updater.release.channel": "stable",
    "simpleSignUpLink.shown": false,
    "activity_expire_days": "30",
    "upgrade.disable-web": true,
    "forcessl": true,
    "htaccess.RewriteBase": "\/"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:**

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0

**Operating system:** Ubuntu 20.04.2 LTS

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by raimund-schluessler** [comment]
Thanks for the report. I can reproduce the issue.
