### ISSUE TITLE
set checkbox to priority color

### ISSUE THREAD

**Issue by jeyca** [nextcloud/tasks#172]
Instead of setting an extra star with the priority color on the right side of the task list, I suggest to mark the checkbox in the corresponding color and make the star superfluous. 

current:
![screenshot_2018-05-30_15-00-08](https://user-images.githubusercontent.com/37297730/40721783-d1dda0d8-641a-11e8-966d-a57a4abf6aad.png)

suggested:
![screenshot_2018-05-30_15-09-23](https://user-images.githubusercontent.com/37297730/40722030-808640f4-641b-11e8-84ac-91c891dcee71.png)

This is handled in this way in the [F-droid app tasks](https://f-droid.org/en/packages/org.tasks/) and is very pleasant there.

**Comment by raimund-schluessler** [comment]
To be honest, I don't like this idea very much, because it is limiting functionality. The star is not only an indicator, but also a button to set or unset the priority when clicked. When you merge this into the checkbox, there is no possibility to set the priority anymore.
