### ISSUE TITLE
Export / report option

### ISSUE THREAD

**Issue by geiger108** [nextcloud/tasks#1727]
Hi there,

thank you for the great extension. Suggestion: How about an export option? I would love to have an option for exporting lists or maybe even create reports.

Best regards!

**Comment by raimund-schluessler** [comment]
You can export/download a whole task list (in the app-navigation on the left) or only a single task (in the task details pane on the right) as ICS files.

For exporting as formatted lists, please see https://github.com/nextcloud/tasks/issues/163.
