### ISSUE TITLE
_Created date_ in #UI | #Feature #request

### ISSUE THREAD

**Issue by petesimonic** [nextcloud/tasks#1746]
### Expected behaviour
If it's UX issue, and not a tech limitation, please consider returning this information. Was really useful!

### Actual behaviour
New UI doesn't show _created date_ as in previous versions.

**Comment by raimund-schluessler** [comment]
There are no technical limitations, we can show it. The easiest option would be to show it as a tooltip when hovering the subtitle showing the created/last-modified date in the AppSidebar.

**Comment by raimund-schluessler** [comment]
I accidentally pushed to master, so there won't be any PR, but here is how it now looks with a2ba14634dbe3fa4c95387b6c561a9746644a9dd:

<img width="338" alt="subtitletooltip" src="https://user-images.githubusercontent.com/2496460/130499780-c384d998-fb72-4c7a-abd0-72de21e137b7.png">
