### ISSUE TITLE
Create new list on mobile site

### ISSUE THREAD

**Issue by qoheniac** [nextcloud/tasks#175]
I have the most recent Nextcloud and Task versions. When I use my phone trying to create a new list I open up the sidebar in the Tasks app and touch the new list field. This makes my keyboard pop up and the sidebar disappear, leaving me unable to create a new list. I am using Fennec from F-Droid (Firefox 60.0.2) on Fairphone Open 18.04.1 (Android 6.0.1).

**Comment by raimund-schluessler** [comment]
Should be closed with #190.
