### ISSUE TITLE
Reoccuring tasks are being duplicated when synced with CalDav clients

### ISSUE THREAD

**Issue by meichthys** [nextcloud/tasks#1750]
I [reported this on the Nextcloud community forum](https://help.nextcloud.com/t/tasks-duplicating-when-syncing-reoccurring-task-from-outlook-to-nextcloud-using-caldavsynchronizer/122414), but realized it should probably be reported here.

Nextcloud version _(eg, 20.0.5)_: `22.1.0`
Operating system and version _(eg, Ubuntu 20.04)_: `Ubuntu 20.04`
Apache or nginx version _(eg, Apache 2.4.25)_:  `Apache`
PHP version _(eg, 7.4)_: `7.4`

I'm seeing tasks being duplicated when trying to sync reoccurring tasks to a Nextcloud task list using CaldavSynchronizer (Outlook) or TBSync (Thunderbird).

Steps to replicate it:
1. Install latest nextcloud with latest Tasks app
2. Create a task list and share it with another user
3. Sync tasks to Outlook using CaldavSynchronizer or Thunerbird using TBSync
4. Create a reoccurring task in Outlook/Thunderbird.
![image](https://user-images.githubusercontent.com/10717998/130511785-c0d98086-0eb1-487b-a3b6-581442970f94.png)
5. Mark the task as completed in Nextcloud
![image](https://user-images.githubusercontent.com/10717998/130511803-2ec4a18b-b558-44c2-93bc-56c381be2969.png)
6. The completed task is duplicated in Outlook/Thunderbird and on Nextcloud after each sync.
    - Outlook: the task is re-created in outlook for tomorrow, but no associated task exists in Nextcloud
    - Thunderbird: the task is not re-created in Thunderbird (no new task for tomorrow exist on client or on server)
![image](https://user-images.githubusercontent.com/10717998/130511830-faff7868-130c-498e-bf03-1fb2c6f945bc.png)
![image](https://user-images.githubusercontent.com/10717998/130511853-0845b01e-dbc1-4748-9d7b-1d48728e4cfe.png)

Nextcloud Logs:
![image](https://user-images.githubusercontent.com/10717998/130511874-44af4947-6579-415e-bbbe-85f2e9149bbf.png)

A little more information:
- If i delete all completed tasks on Nextcloud, then all the tasks in Outlook are deleted (including the uncompleted task that was re-scheduled for tomorrow).
![image](https://user-images.githubusercontent.com/10717998/130511934-2a4e9d2b-366d-4fe0-935a-f5826ceb997b.png)
![image](https://user-images.githubusercontent.com/10717998/130511960-519792a7-ba06-401a-98e2-5a83b3fbbafc.png)

- I am aware of the 'map reoccurring tasks' option in CalDavSynchronizer, but it doesn't seem to matter if it is selected or not.
![image](https://user-images.githubusercontent.com/10717998/130511991-9ad45e43-71ea-47c2-974e-36bcc558d047.png)

- As strange as it may sound, i've also seen situations where the re-created task is created to be a weekly reoccurring task instead of a daily task like it was originally created to be.

**Comment by meichthys** [comment]
I've updated the initial issue description above to indicate that the issue is seen regardless of which client I use to sync (CalDavSynchronizer or TBSync).

**Comment by raimund-schluessler** [comment]
Thanks for the extensive report. The thing is that the Tasks app does not support repeating tasks at all (see #34) and I don't know what happens when you complete a repeating task with the Tasks app.

Anyway, would it be possible that you provide the ICS files of the tasks after every step, i.e. after creating the task in Outlook, syncing it, completing it in the Tasks app etc.

And you mention that you shared the list with a different user. Is this important? I would guess it also happens for not shared lists.

**Comment by meichthys** [comment]
@raimund-schluessler Thanks for following up 👍

> And you mention that you shared the list with a different user. Is this important? I would guess it also happens for not shared lists.

This is not important, but does exacerbate the issue since there are more clients syncing with the same list, so the duplicates get out of hand very quickly!

Here's the ics files after each step (renamed as txt since github doesn't allow attaching ics files directly):

I create the daily task in Thunderbird and export ics:
[After Initial Tunderbird Creation.txt](https://github.com/nextcloud/tasks/files/7039382/After.Initial.Tunderbird.Creation.txt)
I then mark the task as completed in Nextcloud and then manually Sync Thunderbird:
[After Marked as Completed in Nextcloud.txt](https://github.com/nextcloud/tasks/files/7039388/After.Marked.as.Completed.in.Nextcloud.txt)
I then manually sync Thunderbird (Again) a few seconds later:
[After Manually Syncing Thunderbird (Again).txt](https://github.com/nextcloud/tasks/files/7039390/After.Manually.Syncing.Thunderbird.Again.txt)

Note: All ics files were exported from Thunderbird.

**Comment by meichthys** [comment]
I'm not sure if this helps, but it might add more data points. Here's another scenario which i thought was strange:

[After daily task Created in Outlook - synced to nextcloud - synced back to Thunderbird.txt](https://github.com/nextcloud/tasks/files/7039502/After.Created.in.Outlook.-.synced.to.nextcloud.-.synced.to.Thunderbird.txt)
[After marked as completed in Thunderbird.txt](https://github.com/nextcloud/tasks/files/7039504/After.marked.as.completed.in.Thunderbird.txt)
After this, the task shows as completed in Thunderbird:
![image](https://user-images.githubusercontent.com/10717998/130625387-06c9719b-5a8e-41f8-bf23-6e422b1fa5f1.png)
but nothing changes in Nextcloud:
![image](https://user-images.githubusercontent.com/10717998/130625445-f90b9cd7-0c34-4674-9524-b5852db27cf8.png)
or in Outlook:
![image](https://user-images.githubusercontent.com/10717998/130625476-05466da6-d334-4378-81b4-d7e478d1b15d.png)

Again, all ics exports are from Thunderbird.

**Comment by meichthys** [comment]
Potentially related to #316

**Comment by meichthys** [comment]
Another data point: If I create a daily reoccurring task in MacOS Reminders, wait until it syncs to Nextcloud, then mark it as completed in Nextcloud, then wait until MacOS Reminders syncs again, I see the task as completed in MacOS Reminders and in Nextcloud, but the task is not re-created. However, if I mark the task as completed in MacOS Reminders, the task is re-created.

I'm not sure if this helps, but I figured I'd add it here in case it does 👍

**Comment by meichthys** [comment]
I'm closing this for now as i believe the issue is due to the way Outlook re-creates tasks. 
I've tested with TBSync + Thunderbird and do not see this issue unless I'm also syncing with Outlook.


@raimund-schluessler You had said:
> I don't know what happens when you complete a repeating task with the Tasks app.

After some testing, I can report that when completing a re-occuring task via the Nextcloud web interface, the task and all of it's re-occurrences in the client are completed (This is probably the best case until the much anticipated #34 is completed).

This is not the case with outlook + caldavsynchronizer which causes tasks to be duplicated as described in the Caldavsynchronizer issue here: https://github.com/aluxnimm/outlookcaldavsynchronizer/issues/327#issuecomment-938077999
