### ISSUE TITLE
Cleanup hacks

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/tasks#1776]
Remove (https://github.com/nextcloud/nextcloud-vue/pull/2229)
https://github.com/nextcloud/tasks/blob/b07b6c343cd22a8b967b2af4e5dbcfae3f338fc0/src/main.js#L100-L105
and (https://github.com/nextcloud/nextcloud-vue/pull/2211)
https://github.com/nextcloud/tasks/blob/b07b6c343cd22a8b967b2af4e5dbcfae3f338fc0/src/views/AppNavigation.vue#L459-L461
once the next nextcloud/vue version is released and merged here.

**Comment by szaimen** [comment]
4.1.1 is released 🚀
