### ISSUE TITLE
Calendars not Detected

### ISSUE THREAD

**Issue by Ethaseo** [nextcloud/tasks#1788]
I could not find an FAQ or Manual Section about this issue and the search didnt seem to give any good results so im sorry if this has been here before or the way it is because of technical limitations:

I installed Tasks after the Calendar App. When i create a Task List a Calendar for it appears but existing Calendars dont have a Task List showing up. Is there any way to add the Task list for existing Calendars? Also it would be nice to find this information more easily. Will it cause any problems if i create a tasklist with the name of an existing calendar? I dont want to break anything :)

**Comment by raimund-schluessler** [comment]
Task lists created from the Tasks app don't show up as calendars. This is to prevent data loss (some users didn't realize they are the same thing, deleted a task list and lost all their calendar events as well).

The Calendar app allows to chose to create calendars/lists supporting both events and tasks (optional).

Changing what a calendar supports after it's creation is forbidden by the CalDAV specification. So you will either have to recreate them or just create a second one with the same name.

A documentation about this would be good indeed. Mind sending a PR 😉?

**Comment by Ethaseo** [comment]
It was new to me as well but i can try. I only used Github for issues so far, do i need to clone the repo before making a pull request? What would be the right place to do so? The readme file of this repo or the NC Documentation?
