### ISSUE TITLE
After selecting a tag for a task the dropdown doesn't go away

### ISSUE THREAD

**Issue by jpschewe** [nextcloud/tasks#1796]
When I click on tags in the task details pane I get a list of the tags. I can click on the tags to select them. However once I do this I can't see the other details of the task (priority, etc.). Clicking over to notes and then back to details leaves me at the same view where I see the tags, but no other details.

**Comment by raimund-schluessler** [comment]
Hm, it's weird. For me, it most often closes correctly after selecting a tag, but sometimes it does not. Not sure what happens here. As a workaround, you can click inside the tag field and press `Esc` this reliably closes it every time for me.

**Comment by jpschewe** [comment]
Clicking inside the tag field just unselects the tag or selects another tag. Esc has no effect. The only way to get the panel back is to close it with the X and then select another task. I'm using Firefox on Linux.

**Comment by raimund-schluessler** [comment]
> 
> 
> Clicking inside the tag field just unselects the tag or selects another tag. Esc has no effect. The only way to get the panel back is to close it with the X and then select another task. I'm using Firefox on Linux.

I mean the input field (where you can type for filtering the available tags), not the list with the tags. If the cursor is in the input field, the dropdown closes normally. As soon as the the input field loses the focus, the dropdown won't close anymore.

**Comment by jpschewe** [comment]
Thank you, that works.

**Comment by raimund-schluessler** [comment]
> Thank you, that works.

Great.

Let's keep the issue open. The dropdown should close no matter what.

**Comment by raimund-schluessler** [comment]
Fixed with #2193.
