### ISSUE TITLE
Task creation modal styling broken

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/tasks#1798]
When creating a task from the Dashboard or Talk, the styling is currently off:
![Screenshot 2021-09-27 at 13-51-24 Dashboard - Nextcloud](https://user-images.githubusercontent.com/2496460/134902714-3f3fa6f1-3d19-4f39-bdec-b88dea08dad6.png)

**Comment by szaimen** [comment]
Which vue version did you use? The modal size shouldn't have changed in the 4.x releases...

**Comment by raimund-schluessler** [comment]
> Which vue version did you use? The modal sizes shouldn't have changed in the 4.x.x releases...

This was nextcloud/vue@master. I npm linked it.

**Comment by szaimen** [comment]
Yep. Vue master has changed modal sizes and will be released as 5.0.0 because of that.

**Comment by szaimen** [comment]
You could maybe have a look if the `small` size works here.

**Comment by raimund-schluessler** [comment]
I will close this for now, since nextcloud/vue@5.0.0 is not released yet.

**Comment by szaimen** [comment]
With vue 5.1.0 the small modal size should probably have a good size for this.
