### ISSUE TITLE
Invalid priority value

### ISSUE THREAD

**Issue by treiher** [nextcloud/tasks#180]
### Steps to reproduce
1. Click on existing task with priority > 0
2. Click on priority in task details
3. Click right behind current priority number and enter a new value
4. Click on check mark or somewhere else

### Expected behaviour
The priority should be changed to the new value. If the new value was 1, the corresponding VTODO should contain `PRIORITY:1`.

### Actual behaviour
The priority is changed to the new value and correctly shown in the tasks app. If the new value was 1, the corresponding VTODO contains `PRIORITY:-1`. This leads to synchronization errors with other applications (e.g., DAVdroid), as the `PRIORITY` property should only be set to values in the range 0 to 9 (like specified in RFC 5545).

### Server configuration

**Nextcloud version:** 12.0.7

**Tasks version:** 0.9.6

### Client configuration

**Browser:** Chromium 67.0.3396.87

**Comment by raimund-schluessler** [comment]
The Tasks app currently shows values from 1 to 4 as low, 5 as medium and 5 to 9 as high, but writes them as 9 to 6 for low, 5 as medium and 4 to 1 as high to the database as specified in RFC 5545.

When I enter 1, the app writes 9 to the database. I can't reproduce a `PRIORITY:-1`. Could you specify how you did that?

Also, with #194 the priority values will be shown as RFC 5545 specifies it with 1 as high etc.

**Comment by treiher** [comment]
I still observe the behavior in the current version 0.9.7. The important point to trigger the bug is to click right behind an existing non-zero priority number and enter a new value. If I select the priority number before entering a new value or use the slider, the result looks fine.

Here is a more detailed example:

1. Create a new task with a priority level 9
2. Download the task list (using the menu on the left side)
    The downloaded ICS contains the task with `PRIORITY:1`.
3. Select the task
    The details of the task are shown on the right side.
4. Click on `priority 9: high`
    An input field containing 9, a slider and some icons appear.
5. Click in the input field right behind 9 and type 8
    The 9 is replaced by 8.
6. Click on the green checkmark icon
    The input field and slider disappear. `priority 8: high` is shown.
7. Download the task list
    The downloaded ICS contains `PRIORITY:-8` for the task.

**Comment by raimund-schluessler** [comment]
@treiher Thanks for the detailed explanation, I can reproduce it now. I will have a look.
