### ISSUE TITLE
[Feature Request] Sort TaskList list in left sidebar

### ISSUE THREAD

**Issue by eggithub** [nextcloud/tasks#181]
It is possible to sort tasks within a tasklist.

However, it is not possible to sort you TaskList list in he left sidebar, say alphabetically. With 20+ tasklists this list becomes quite cluttered.  

Keep up the good work, just lovin it!

Cheers!

**Comment by raimund-schluessler** [comment]
With #194 the calendars/lists in the sidebar are ordere alphabetically. I hope this helps a bit until we implement manual sorting.

**Comment by raimund-schluessler** [comment]
Actually, duplicate of #15.
