### ISSUE TITLE
Error while updating tasks with different uid and uri

### ISSUE THREAD

**Issue by l0ga** [nextcloud/tasks#1818]
### Steps to reproduce
First:
1. Login to NC Tasks GUI, create a task
2. Connect a Caldav client, create a task
3. Download these tasks and compare their uids with filenames (and URLs / URIs)

Second:
1. Try to update these tasks via different clients

### Expected behaviour
Tasks update without errors, URLs and filenames are aligned with their uid

### Actual behaviour

First:
When I create a task via external clients, everything works fine (clients can update it, its name is aligned with its uid)

When I create a task with NC Task GUI its URL look like: /apps/tasks/#/calendars/testcal/tasks/15340142-5713-4847-907D-7539A05E0EA0.ics

However, uid in downloaded 15340142-5713-4847-907D-7539A05E0EA0.ics is different:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Nextcloud Tasks v0.14.2
BEGIN:VTODO
UID:b6de9389-98c0-483c-a842-8c2908a239ef
CREATED:20211004T162554
LAST-MODIFIED:20211004T162554
DTSTAMP:20211004T162554
SUMMARY:next2105
END:VTODO
END:VCALENDAR

```

Not an error per se but I think it can be related to the second part of the issue. When I try to update NC-created tasks with at least "caldav" python library  I constantly get an error. I thought it can be somehow related to UID (2do doesn't use dashes in uid, for example) but tasks created in other clients with similar uids update without problems.

At first it looks very much like a library issue (I already reported it). Still I get this error only while trying to update NC-created tasks. As I understand the library is trying to update this task using its uri (15340142-5713-4847-907D-7539A05E0EA0.ics) which is not its uid. Also tasks created manually and/or via other clients update without errors or code corrections.

In my database all tasks created NOT by NC have similar uri and uid, while all tasks created by NC don't. Is it by design? My initial guess is that not all clients can handle this difference.

The error:
```
Traceback (most recent call last):
  File "C:\Users\usernamehere\AppData\Local\Programs\Python\Python37\lib\site-packages\caldav\objects.py", line 1464, in save
    self._create(self.data, self.id, path)
  File "C:\Users\usernamehere\AppData\Local\Programs\Python\Python37\lib\site-packages\caldav\objects.py", line 1374, in _create
    raise error.PutError(errmsg(r))
caldav.lib.error.PutError: 400 Bad Request

b'<?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>Sabre\\DAV\\Exception\\BadRequest</s:exception>\n  <s:message>Calendar object with uid already exists in this calendar collection.</s:message>\n</d:error>\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "M:\Downloads\force_update_task.py", line 34, in <module>
    c.save_todo(todo.data)
  File "C:\Users\usernamehere\AppData\Local\Programs\Python\Python37\lib\site-packages\caldav\objects.py", line 598, in save_todo
    return Todo(self.client, data=ical, parent=self).save(no_overwrite=no_overwrite, no_create=no_create, obj_type='todo')
  File "C:\Users\usernamehere\AppData\Local\Programs\Python\Python37\lib\site-packages\caldav\objects.py", line 1466, in save
    self._create(self.vobject_instance.serialize(), self.id, path)
  File "C:\Users\usernamehere\AppData\Local\Programs\Python\Python37\lib\site-packages\caldav\objects.py", line 1374, in _create
    raise error.PutError(errmsg(r))
caldav.lib.error.PutError: 400 Bad Request

b'<?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>Sabre\\DAV\\Exception\\BadRequest</s:exception>\n  <s:message>Calendar object with uid already exists in this calendar collection.</s:message>\n</d:error>\n'
```

### Server configuration

It's a docker image from https://hub.docker.com/r/linuxserver/nextcloud

**Operating system**: Linux 4.4.59+ #25556 SMP PREEMPT Sat Aug 28 02:17:26 CST 2021 x86_64

**Web server:** nginx/1.18.0 (fpm-fcgi)

**Database:** mysql 10.4.18

**PHP version:** 7.4.19

**Nextcloud version:** 21.0.5 - 21.0.5.1

**Tasks version:** 0.14.2

**Updated from an older Nextcloud or fresh install:** it's been updated since 19.0.3, maybe earlier

**Signing status:** (I didn't get any useful information about it from system report)

```
<details><summary>Signing status</summary>
Array ( )
</details>
```

**List of activated apps:**

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - audioplayer: 3.2.2
 - breezedark: 21.0.11
 - bruteforcesettings: 2.2.0
 - calendar: 2.3.4
 - camerarawpreviews: 0.7.12
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - dav: 1.17.1
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - firstrunwizard: 2.10.0
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - maps: 0.1.9
 - metadata: 0.14.0
 - nextcloud_announcements: 1.10.0
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - password_policy: 1.11.0
 - photos: 1.3.0
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - recommendations: 1.0.0
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - support: 1.4.0
 - survey_client: 1.9.0
 - systemtags: 1.11.0
 - tasks: 0.14.2
 - text: 3.2.0
 - theming: 1.12.0
 - theming_customcss: 1.9.0
 - twofactor_backupcodes: 1.10.0
 - twofactor_totp: 6.1.0
 - updatenotification: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.5.0
 - weather_status: 1.1.0
 - workflowengine: 2.3.1
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_ldap
```

**Nextcloud configuration:**

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
       "***REMOVED SENSITIVE VALUE***",,
        "***REMOVED SENSITIVE VALUE***",
    ],
    "dbtype": "mysql",
    "version": "21.0.5.1",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",,
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "twofactor_enforced": "true",
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": [],
    "simpleSignUpLink.shown": false,
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "updater.release.channel": "stable",
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\Movie",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown"
    ],
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 92.0.1

**Operating system:** Android

**CalDAV-clients:** 2Do, NC Tasks GUI, "caldav" python library

**Comment by raimund-schluessler** [comment]
The UID of a VOBJECT (VEVENT, VTODO, i.e. an event or a task) is required to be globally unique to securely identify the object. However, the respective RFC 5545 does not specify anything regarding the relation of the URI and the UID (see https://datatracker.ietf.org/doc/html/rfc5545#section-3.8.4.7). So it is perfectly valid for the last part of the URI to be different than the UID. Hence, every client should be able to handle this properly, otherwise it is a bug, I would say. We could of course change this behaviour (respective code is here https://github.com/nextcloud/cdav-library/blob/master/src/models/calendar.js#L137) but I don't see any reason to do so.

Looking at the error message
```
<s:exception>Sabre\\DAV\\Exception\\BadRequest</s:exception>\n  <s:message>Calendar object with uid already exists in this calendar collection.</s:message>
```
it seems your client tries to create or move an object into a calendar that already contains an object with the same UID. This will of course fail, because the UID has to be unique. I don't know how the library you use works, but it could indeed be, that it tries to create a task instead of updating it, because the URI is not the UID.

However, I could consider this a bug of the library. Could you link the issue you created in the library repo here, please?

**Comment by raimund-schluessler** [comment]
Found it https://github.com/python-caldav/caldav/issues/153
