### ISSUE TITLE
Tasks: New categories are not saved to backend/shared between instances

### ISSUE THREAD

**Issue by hcderaad** [nextcloud/tasks#182]
Steps to reproduce

    Add a new task and assign a newly created category in one client session (browser)
    Open another session (private mode/other workstation) try to assign the category created in 1 to a task
    The instance from 2 will add the category as New.

Expected behaviour

Task categories that are added through one user session should be shared between sessions.
Actual behaviour

See 3.
Server configuration

Operating system: openSUSE Tumbleweed

Web server: Apache

Database: MariaDB

PHP version: 7.2

Nextcloud version: 13.0.4

Updated from an older Nextcloud/ownCloud or fresh install: Since 11ish.

Where did you install Nextcloud from: openSUSE build service RPMs

List of activated apps:
N.A. this only concerns Tasks.

Nextcloud configuration:
N.A. this only concerns Tasks.

Are you using external storage, if yes which one: No

Are you using encryption: No, full disk encryption on volume level.

Are you using an external user-backend, if yes which one: No
LDAP configuration (delete this part if not used)

N.A.
Client configuration

Browser: Firefox / Chrome

Operating system: Windows / Linux.
Logs
Web server error log

No usable log info found regarding unstorable categories.
Nextcloud log (data/nextcloud.log)

No usable log info found regarding unstorable categories.
Browser log

The developer tools show the event being updated in the PUT request with the label and ("Nieuwe categorie" = Dutch) and the new category. The newly added category is not reusable.

This issue was previously (incorrectly) registered under NC Server as: https://github.com/nextcloud/server/issues/10365

**Comment by mpodshivalin** [comment]
I also have the same problem. Actually, I think it is not necessarily connected with sessions. I can reproduce this problem as follows:
* Open Tasks app
* Assign a category to the task
* Assign the same category to another task (it works)
* Reload page
* Try to assign the same category to another task (category will be marked as new and you have to type the name of the category again)

I've tried a clean installation of Nextcloud as well as Nextcloud hosting demo and I was able to reproduce this problem

**Comment by raimund-schluessler** [comment]
This is not implemented at the moment. Categories are not queried from the server, so the app is only aware of categories created after a page reload. This is basically covered in https://github.com/nextcloud/tasks/issues/89 already, so I close this here. Thanks for reporting anyway.

**Comment by hcderaad** [comment]
@raimund-schluessler Thanks for your response. I don't think this is the same issue. The current task manager supports categories, however those categories are obviously not saved to the tasks in the database in such a way that other instances can reuse them. Your statement that they are only usable after a payload does not seem the case for me. The are not reusable at all.

Implementing Nextcloud wide labelling would be even better. Yet I would already be happy if the current simple categories would work as expected. But perhaps I am overlooking or misunderstanding your comment here?

**Comment by raimund-schluessler** [comment]
> Your statement that they are only usable after a payload does not seem the case for me. The are not reusable at all.

The app is not aware of a list of categories available on the server, it does not load them from the server. You only see categories in this list, which were created in the current session, after you open the Tasks app. This local list is gone after you reload the page. Loading the categories list from the server is just not implemented yet, but it will be, when #89 is implemented.

**Comment by hcderaad** [comment]
@raimund-schluessler Ah ok, then I don't see what the use of offering this functionality is at all at this point in time. If I understand correctly from your message, they are basically throwaway labels that after even a page reload will be ditched. Perhaps it would be advisable to disable this completely to prevent (more) confusion until #89 is implemented? Or perhaps I am misunderstanding your comment.

**Comment by raimund-schluessler** [comment]
Well, they are visible on the task where you added them to. So I think this is a helpfull already. But I agree, functionality is very limited at the moment.
