### ISSUE TITLE
[Feature Request] Sort Task by lates activity / due dates

### ISSUE THREAD

**Issue by kaktux** [nextcloud/tasks#183]
Hi there,

i couldn't find a request like that - so as i just started using tasks for project managment status overviews this would be a great feature:
Add the option to sort tasks by activity. I can see on the activity tab of nextcloud when i last added something to a task (subtask, note etc) - but it would be great if the tasks could be sorted by last activity.
So e.g. in addition to a due date that i can basically see the workflow/state (like: i ordered something, i got a offer, i accepted the offer, i paid, the product gets shipped, it arrives etc.) by sorting that way.
This way you can keep track of a projects activity even for tasks that have no due date. 

I don't know if i've overseen so far - but so far i couldn't find if the "created or last changed date/time" is shown somewhere in the tasks - like it is shown with the activities.

Anyway: already a great tool. Thx for all the work and effort.

**Comment by raimund-schluessler** [comment]
As of #194 you can sort the tasks by the last-modified date. I hope, this is what you were looking for. Otherwise please reopen.
