### ISSUE TITLE
[Feature Request] Dashboard Widget should process start dates

### ISSUE THREAD

**Issue by HumanNr4584093104** [nextcloud/tasks#1834]
### Steps to reproduce
1. Create multiple tasks
2. Set priority and start date on all
3. Do not set due date on any

### Expected behaviour
Tasks are sorted by due date -> start date -> priority-> alphabetically, and thus the tasks that starts tomorrow is higher on the list than the tasks that starts next month.

### Actual behaviour
According to #1641, tasks are sorted by due date -> priority -> alphabetically, and tasks are sorted by priority.

### Server configuration

**Nextcloud version:** 21.0.4

**Tasks version:**  0.14.2

**Comment by raimund-schluessler** [comment]
The tasks in the dashboard are sorted by start date, it's only that they are sorted by priority before. So your prioritization overrules the start date. The complete order is
pinned -> completed date -> due date -> priority -> start date -> alphabetically, see here:
https://github.com/nextcloud/tasks/blob/af17fcaa17bd39736b270ed476127c9c98be770d/src/store/storeHelper.js#L264

The decision what is more important (start date, priority, any other parameter) is quite personal, I guess. So there won't be an order to satisfy everyone.

**Comment by HumanNr4584093104** [comment]
Is there any way for me as an server admin to change the sort order, perhaps like one can manually edit config.php?

**Comment by raimund-schluessler** [comment]
> Is there any way for me as an server admin to change the sort order, perhaps like one can manually edit config.php?

Unfortunately there is no configuration for this. You could of course adjust the source code of the app and compile it yourself, but you would need to to this for every release.
