### ISSUE TITLE
Compatibility with Nextcloud 14

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/tasks#184]
Any chance you can try to look into that @raimund-schluessler  ?

**Comment by raimund-schluessler** [comment]
Will do. Are there any known issues besides that max-version is 13 at the moment?

**Comment by nickvergessen** [comment]
I guess https://github.com/nextcloud/server/pull/9982 could have broken the whole layout

**Comment by raimund-schluessler** [comment]
See #185.
