### ISSUE TITLE
[Feature Request] Hide tasks with a future start date

### ISSUE THREAD

**Issue by Dopeelf** [nextcloud/tasks#1843]
### Steps to reproduce
1. Create a task with a start date in the future

### Current behaviour
The task with a start date in the future is listed together with actionable tasks.

### Wanted behaviour
The alternative to hide tasks that have a start date in the future.

**Comment by raimund-schluessler** [comment]
The `Current` collection does exactly that. Tasks with a start date in the future don't show up there. If this collection is not visible for you, you can enable it in the settings (left bottom).
