### ISSUE TITLE
Can't indent tasks on MacOS native tasks app

### ISSUE THREAD

**Issue by MrDaves24** [nextcloud/tasks#1853]
The app is called Reminders... My bad !

For Apple, indent means creating group and subgroup of tasks
I use the native app of MacOS called "Reminders" and I sync my tasks from Nextcloud through the WebCAL and the sync of my calendars.  
I have tasks that are grouped, multiple level. They're displayed "flat" on the app, no group, no indent.
I thought it was because the app doesn't support this option but I right-clicked by mistake and saw a greyed out option "indent task".  
I tried with the iCloud group of tasks and on this part, I can group tasks !

It would be awesome if I can the same with my tasks from Nextcloud :). 

But, I wonder if it's an issue of the way to sync and present tasks from Nextcloud, or maybe it's just Apple that disable this option for external sources...

### Steps to reproduce
1. Have a mac
2. Sync your tasks in preferences
3. Have indented tasks in Nextcloud
4. OR try to indent on the Task app of the Mac

### Expected behaviour
Tasks should group together

### Actual behaviour
- Indent option is greyed out
- Indented tasks on server are shown flat

**List of activated apps:**
- tasks: 0.14.2
- calendar: 2.3.4

**Nextcloud configuration:**
- version: 22.2.0.2

**Are you using encryption:** yes

### Client configuration
**Operating system:**
MacOS 10.15.7

**CalDAV-clients:**
Native MacOS account management
Syncing tasks through the WebCAL

I didn't add much details about server and client as I think it isn't usefull. But if needed, I'll add them !

**Comment by raimund-schluessler** [comment]
As far as I know, this is a limitation of the Reminders app that does not allow nested tasks on external CalDAV synced servers. I think there is nothing we can do about this.
