### ISSUE TITLE
[Feature Request] Support markdown in title

### ISSUE THREAD

**Issue by maxlStone** [nextcloud/tasks#1856]
e.g. having markdown support in the title would allow to add a hyperlink to the title name (looks clean).

**Comment by raimund-schluessler** [comment]
Links in the title are already linkified and clickable. Having more markdown support (e.g. formatting like italic or bold, images or tables) would not be useful or feasible, I think. Hence, real markdown support for the title has no benefit in my opinion.

Here is how a link in the title looks like:
![Screenshot 2021-11-26 at 09-25-52 Aufgaben - Nextcloud](https://user-images.githubusercontent.com/2496460/143550297-32b93499-51ad-4ade-a35d-254322baf6f0.png)

**Comment by maxlStone** [comment]
Oh okay.

I also thought about inline code, but maybe the use cases are to specific and hence not that useful as you said.

**Comment by raimund-schluessler** [comment]
> I also thought about inline code

For this I would propose to use the Notes panel. There, markdown is supported and code formatting also works:
![Screenshot 2021-11-26 at 09-47-12 Aufgaben - Nextcloud](https://user-images.githubusercontent.com/2496460/143552988-f7570960-af2c-4384-a319-2e8b615be455.png)

**Comment by maxlStone** [comment]
okay thanks
