### ISSUE TITLE
[Feature Request] Add visual hint for task lists that are shared with other users

### ISSUE THREAD

**Issue by nkakouros** [nextcloud/tasks#1862]
### Steps to reproduce
1. Add a task list
2. Share it with another user

### Expected behaviour
These should be some visual hint that the list is shared. If a user has shared a task list with you, there is indeed such a visual hint, but the opposite does not happen.

### Actual behaviour
The list shows exactly like the ones that are not shared.

### Server configuration

**Nextcloud version:** 22.2.3

**Tasks version:** 0.14.2

**Comment by raimund-schluessler** [comment]
Well there is a visual hint if the list is selected/opened. Do you want to see it for every list also without having it open?

**Comment by nkakouros** [comment]
Exactly! This would be on par with the calendar app.

**Comment by raimund-schluessler** [comment]
I guess that makes sense. Fix is in #1877.
