### ISSUE TITLE
Dependabot for dependency management

### ISSUE THREAD

**Issue by rullzer** [nextcloud/tasks#187]
Would you like me to enable dependabot for this repo as well?

**Comment by raimund-schluessler** [comment]
Yes, why not. Although I am afraid the Angular dependencies are quite outdated and upgrading them would require a bit of work, which might not be worth it facing the move to Vue 🙈

**Comment by rullzer** [comment]
@raimund-schluessler if you first want to migrate to Vue then I can also just enable it once that has been done. That way you don't get spammed by dependabot now and have to invest a lot of time into getting it working.

Just ping me when you want me to enable it. It is 3 clicks or so for me ;)

**Comment by rullzer** [comment]
Done :)
