### ISSUE TITLE
Feature Request: Be able to set a board as default

### ISSUE THREAD

**Issue by Emporea** [nextcloud/tasks#1878]
It is not possible to set a board of [nextcloud/deck](https://github.com/nextcloud/deck) as the default boards for tasks. This might be useful.

Edit:
This would only make sense if you are able to add tasks to deck boards. #1879

Also it would be nice to disable certain calendars / deck boards so that they dont show up at the "all" section. But this might be on Decks or Tasks side. I dont know. I dont know if its on Decks or Tasks side [nextcloud/deck:#3477](https://github.com/nextcloud/deck/issues/3477)

**Comment by raimund-schluessler** [comment]
Once https://github.com/nextcloud/deck/issues/2399 is implemented, Deck boards will become selectable as default lists in the Tasks app. They currently just don't show up, because they are not writable.
So nothing to fix in the Tasks app.

**Comment by raimund-schluessler** [comment]
As for the disabling calendars for smart collections this is covered in https://github.com/nextcloud/tasks/issues/1133.
