### ISSUE TITLE
Feature Request: Be able to add new Tasks ( full tasks functionality ) inside Deck Lists.

### ISSUE THREAD

**Issue by Emporea** [nextcloud/tasks#1879]
This is not yet possible and "artificially" blocks intuitive deck <-> tasks interactions.

**Comment by raimund-schluessler** [comment]
Well, this is not "artificially" blocked, it is simply not yet implemented in the Deck app. The corresponding issue is https://github.com/nextcloud/deck/issues/2399. From the Tasks app there is nothing we can do.
