### ISSUE TITLE
Release version for NC14

### ISSUE THREAD

**Issue by rullzer** [nextcloud/tasks#188]
Would be great if you could put a version for 14 in the appstore.

**Comment by raimund-schluessler** [comment]
Will do that.

**Comment by Sp1l** [comment]
Just updated my install to 14.0.0RC2 and found out that tasks isn't 14 compatible.

Anything I can do to help? Test?

**Comment by raimund-schluessler** [comment]
Sorry, I just have to release it to the appstore. Will try to do that this evening.

**Comment by StygianBlues** [comment]
Thank you Mr. Schlüßler.
