### ISSUE TITLE
[Feature request] possibility to modify the tasks texts

### ISSUE THREAD

**Issue by lowig** [nextcloud/tasks#1890]
Hi, I'm @lowig
I use Nexcloud via Ecloud (/e/OS) and I wonder why i can't modify the text of a task once being created.
Would it be possible to implement this feature ?

**Comment by raimund-schluessler** [comment]
What is the "text" for you? The title/summary, the note/description? Both can be modified with the Tasks app. Maybe share screenshot of what is not working.

**Comment by lowig** [comment]
the tittle of the task
