### ISSUE TITLE
[Feature Request] Add multiple tasks at once (bulk / batch)

### ISSUE THREAD

**Issue by CodeAlDente** [nextcloud/tasks#1894]
I'd like to add multiple tasks in one step like in Google Tasks. So if I have multiple lines (one line = one task) in my clipboard and just paste it in the field it should offer me to add them all in a row.
Maybe even with the detection of intended lines to automatically handle sub tasks?

Example with multiple tasks
```
Buy milk
Walk the dog
Clean living room
```

Example with sub tasks
```
Go to supermarket
  buy milk
  buy cheese
Invite friends to party
Call Bob
```

**Comment by Redsandro** [comment]
I just tried out Tasks and this was my first annoyance with the current implementation. I'm surprised you don't have more responses or thumbs up.

At least you can keep typing when pressing enter, that helps. But it would be great if you can copy/paste lists from text files or emails. That includes removing the bullet point, e.g.: `-` or `*`.
