### ISSUE TITLE
Nextcloud 11 Beta 1 Issue

### ISSUE THREAD

**Issue by zacharyrohrbach** [nextcloud/tasks#19]
### Steps to reproduce
1. cd /var/www/cloud.rohrbach.tech/public_html/apps/
2. git clone https://github.com/owncloud/tasks/
3. had to comment out below to get it to work
```
 13     <dependencies>
 14         <owncloud min-version="9.1" max-version="9.2"/>
 15     </dependencies>
```
4. enabled app as min

### Expected behaviour
The app to work.

### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/13573113/20842397/74bd0b24-b885-11e6-9725-020c5aff4bfd.png)

### Server configuration
**Operating system**: Debian 8.6

**Web server:** nginx 1.6.2

**Database:** MySQL

**PHP version:** 5.6.27

**ownCloud version:** Nextcloud 11 Beta 1

**Tasks version:** 0.9.3

**Updated from an older ownCloud or fresh install:** Fresh install of Nextcloud 11 Beta 1

**Comment by nickvergessen** [comment]
@raimund-schluessler @korelstar this was fixed I think.
Can you please create a new release and publish it on the nextcloud app store?

**Comment by raimund-schluessler** [comment]
I will do when I am back from Holiday next weekend.

**Comment by macmeck** [comment]
@zacharyrohrbach, you should clone from https://github.com/nextcloud/tasks/ instead of https://github.com/owncloud/tasks/ Should be fixed there. The link in README.md still points to the owncloud repository. I fell into this trap, too.
PR #18 will update the information but it has not been merged into the master branch yet.

**Comment by raimund-schluessler** [comment]
The latest master of the app is compatible with Nextcloud 11. Issue for publishing to appstore is https://github.com/nextcloud/tasks/issues/25
