### ISSUE TITLE
[Question] Sync with Gitlab To-dos

### ISSUE THREAD

**Issue by ebanDev** [nextcloud/tasks#1919]
Hey ! 
I'd like to sync Gitlab Todos with Nextcloud Tasks, do you guys know any way to achieve that ?
Thanks ! :D

**Comment by raimund-schluessler** [comment]
Sorry, I don't know a way to do this.
Nextcloud Tasks is a CalDAV client, so if Gitlab would expose its Todos as CalDAV, Tasks could use it. There is an issue for this on Gitlab: https://gitlab.com/gitlab-org/gitlab/-/issues/14390

**Comment by ebanDev** [comment]
Thanks for your answer ! 😊
