### ISSUE TITLE
Task could be send to any user

### ISSUE THREAD

**Issue by SadBoen** [nextcloud/tasks#1930]
I hope this plugin choud:
1. Add a task and sent to any one I want.
2. copy, or built a new task according to an old one.
3. Templete, or sub-task could builded automaticlly, 1 day later,two days later, like H.Ebbinghaus memory schedule.

**Comment by raimund-schluessler** [comment]
1. You can already share tasks with other users
2. is in #174
3. is in #34.

**Comment by SadBoen** [comment]
It's 2022 now, both the two target will be reach or not?
