### ISSUE TITLE
en_SG locale broken

### ISSUE THREAD

**Issue by angelsl** [nextcloud/tasks#1938]
### Steps to reproduce

1. Set locale to English (Singapore)
2. Observe incorrect date formats

### Expected behaviour

Dates should be formatted in day/month/year, etc

### Actual behaviour

Dates are formatted in moment.js 'en' locale (month/day/year).

The fix is to bump moment.js to 2.25 or later. It seems that nextcloud-moment already bumped to 2.29.1, but no new version of that has been released yet. (Please move this issue there if it is more appropriate there. This actually affects the Calendar app as well, and probably anything else that uses Moment 2.24 based on the version specified in nextcloud-moment 1.1.1's package.json.)

The reason is that in nextcloud-moment:

https://github.com/nextcloud/nextcloud-moment/blob/d1d20cb00b53079fcdf735adece7c15d230fe72f/lib/index.ts#L7-L12

`moment.locale` is called with the argument `en_SG`. Moment tries to find the locale, normalising the name to `en-sg`:

https://github.com/moment/moment/blob/e96809208c9d1b1bbe22d605e76985770024de42/src/lib/locale/locales.js#L26-L63

Due to a bug in Moment 2.24 and fixed in 2.25 and onwards in this PR https://github.com/moment/moment/pull/5025, the locale file was wrongly named `en-SG` in Moment, causing the lookup to fail. Moment thus falls back to the plain `en` locale.

---

I'm providing my server configuration below, but I think it is largely irrelevant. I've already diagnosed the bug above.

<details><summary>Server and client configuration</summary>

## Server configuration detail

**Operating system:** Linux 5.16.7-1-ec2 #1 SMP PREEMPT Tue, 08 Feb 2022 02:26:28 +0000 x86_64

**Webserver:** nginx/1.20.2 (fpm-fcgi)

**Database:** pgsql PostgreSQL 13.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 11.1.0, 64-bit

**PHP version:** 

8.1.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, session, PDO, standard, posix, readline, Reflection, Phar, SimpleXML, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, bcmath, curl, gd, gmp, iconv, intl, pdo_pgsql, pgsql, zip, apcu, imagick, Zend OPcache

**Nextcloud version:** 23.0.2 - 23.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Arch Linux repositories

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.9.0
 - bruteforcesettings: 2.3.0
 - calendar: 3.0.6
 - circles: 23.0.1
 - cloud_federation_api: 1.6.0
 - dav: 1.21.0
 - federatedfilesharing: 1.13.0
 - files: 1.18.0
 - files_rightclick: 1.2.0
 - issuetemplate: 0.7.0
 - logreader: 2.8.0
 - lookup_server_connector: 1.11.0
 - oauth2: 1.11.0
 - provisioning_api: 1.13.0
 - settings: 1.5.0
 - tasks: 0.14.2
 - theming: 1.14.0
 - twofactor_backupcodes: 1.12.0
 - user_status: 1.3.1
 - viewer: 1.7.0
 - workflowengine: 2.5.0
Disabled:
 - activity
 - admin_audit
 - comments
 - contactsinteraction
 - dashboard
 - encryption
 - federation
 - files_external
 - files_pdfviewer
 - files_sharing
 - files_trashbin
 - files_versions
 - files_videoplayer
 - firstrunwizard
 - nextcloud_announcements
 - notifications
 - password_policy
 - photos
 - privacy
 - recommendations
 - serverinfo
 - sharebymail
 - support
 - survey_client
 - systemtags
 - text
 - updatenotification
 - user_ldap
 - weather_status

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
    "apps_paths": [
        {
            "path": "\/usr\/share\/webapps\/nextcloud\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/lib\/nextcloud\/apps",
            "url": "\/wapps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "dbtype": "pgsql",
    "version": "23.0.2.1",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "defaultapp": "tasks",
    "installed": true,
    "theme": "",
    "loglevel": 2,
    "maintenance": false,
    "default_locale": "en_SG",
    "default_phone_region": "SG",
    "app_install_overwrite": [
        "issuetemplate"
    ]
}
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0

**Operating system:** Arch Linux

</details>

**Comment by angelsl** [comment]
If anyone else is running into this issue and is bothered by it (unlikely I presume...) a quickfix is to replace en-SG with en-sg in apps/tasks/js/*.js:

```
sed -i 's/en-SG/en-sg/g' *.js
```

**Comment by raimund-schluessler** [comment]
Hm, we need a new release of nextcloud-moment. The last one was 2 years ago. I created https://github.com/nextcloud/nextcloud-moment/issues/497 to trigger a new nextcloud/moment release.
