### ISSUE TITLE
Where is task data located?

### ISSUE THREAD

**Issue by nameOfUser0236** [nextcloud/tasks#1953]
I have encountered an internal server error, and not being able to fix it, I am moving to a new installation.
However, I need to migrate my data, and can't locate my tasks either in my files or in the server database.
Some help would be appreciated.

**Comment by raimund-schluessler** [comment]
Tasks are stored in the database in a table called `calendarobjects`. But you will probably have to copy all tables starting with `calendar` and the user names also need to match. And maybe more. So restoring your data will be a tricky thing to do.
