### ISSUE TITLE
Use workflow organization templates

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/tasks#1967]
Tasks should use the workflow templates from https://github.com/nextcloud/.github for `lint`, `node-test` and `phpunit`.

- [x] `lint`
- [ ] `node-test`
- [ ] `phpunit`

**Comment by raimund-schluessler** [comment]
@skjnldsv Am I missing something or is there no template for running javascript tests via `npm run test` (and upload coverage to codecov)? Similar to https://github.com/nextcloud/tasks/blob/master/.github/workflows/node-test.yml.

**Comment by skjnldsv** [comment]
Currently, there is none. Feel free to add one :)

**Comment by raimund-schluessler** [comment]
> Currently, there is none. Feel free to add one :)

I created an issue for now, https://github.com/nextcloud/.github/issues/128. Might look into it later.
