### ISSUE TITLE
Unable to create task list without latin alphanumeric characters in the name

### ISSUE THREAD

**Issue by the-vindicar** [nextcloud/tasks#198]
### Steps to reproduce
1. Click "Add task list..."
2. Enter a string that contains no A-Z 0-9 characters (for example, a cyrillic-only string).
If your string contains Latin letters or digits, app behaves as expected.
3. Click "Save" 

### Expected behaviour
New task list is created with specified name.

### Actual behaviour
No new task list appears, refreshing the page reveals that it hasn't been created.
I suspect that unique ID for the task list object is generated by stripping the name of non-ASCII characters. For aforementioned names it results in an empty ID, which is either rejected, or is treated as non-unique.
In the log, there is an error mentioning "resource already exists".

### Server configuration

**Operating system**:
Ubuntu Server 14.04.5 LTS
**Web server:**
lighttpd/1.4.33 (ssl)
**Database:**
mysqld 5.5.61-0ubuntu0.14.04.1
**PHP version:**
PHP 5.6.37-1+ubuntu14.04.1+deb.sury.org+1
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 13.0.5
**Tasks version:** (see Nextcloud apps page)
Tasks 0.9.7
**Updated from an older Nextcloud or fresh install:**
updated
**Signing status:**
```
No errors have been found.
```

**List of activated apps:**
```
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - gallery: 18.0.0
  - issuetemplate: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - metadata: 0.7.0
  - news: 12.0.4
  - nextcloud_announcements: 1.2.0
  - notes: 2.4.1
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - tasks: 0.9.7
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "session_lifetime": 2592000,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.5.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "logfile": "\/var\/log\/owncloud-access.log",
        "loglevel": 2,
        "log_authfailip": true,
        "maintenance": false,
        "theme": "",
        "trashbin_retention_obligation": "auto",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true
    }
}

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 62. Adblocker is installed, but disabled for the owncloud instance. Disabling it entirely has no effect.
**Operating system:**
WIndows 10 x64
**CalDAV-clients:**
none
#### Web server error log
```
2018-09-10 04:40:53: (server.c.1242) logfiles cycled UID = 0 PID = 31842
2018-09-10 18:48:12: (connections.c.305) SSL: 1 error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
2018-09-11 10:28:48: (connections.c.305) SSL: 1 error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
2018-09-11 14:26:24: (connections.c.305) SSL: 1 error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
2018-09-11 17:01:35: (connections.c.305) SSL: 1 error:140943E8:SSL routines:SSL3_READ_BYTES:reason(1000)
2018-09-11 17:51:36: (connections.c.305) SSL: 1 error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
2018-09-11 23:50:40: (server.c.1558) server stopped by UID = 0 PID = 21263
2018-09-11 23:58:53: (log.c.166) server started
```
The testing for this issue has been done at 2018-09-12, so as you can see, no related errors are in the server log.

#### Nextcloud log (data/nextcloud.log)
This message appears every time, immediately after I reproduce the bug.
```
Fatal | webdav | Sabre\DAV\Exception\MethodNotAllowed: The resource you tried to create already exists

/var/www/vindicar.name/owncloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php - line 303:  Sabre\DAV\Server->createCollection('calendars/vindi...', Object(Sabre\DAV\MkCol))
[internal function] Sabre\CalDAV\Plugin->httpMkCalendar(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/vindicar.name/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:  call_user_func_array(Array, Array)
/var/www/vindicar.name/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:  Sabre\Event\EventEmitter->emit('method MKCALEND...', Array)
/var/www/vindicar.name/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:  Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/vindicar.name/owncloud/apps/dav/lib/Server.php - line 287:  Sabre\DAV\Server->exec()
/var/www/vindicar.name/owncloud/apps/dav/appinfo/v2/remote.php - line 35:  OCA\DAV\Server->exec()
/var/www/vindicar.name/owncloud/remote.php - line 164:  require_once('/var/www/vindic...')
{main}
```

**Comment by raimund-schluessler** [comment]
Might be the same problem as https://github.com/nextcloud/tasks/issues/148.
Could you check if you can create a calendar with such a name in the Calendar app, please. If you can, than it is the same problem, will be solved with the app rewrite in Vue.js, see #194.

**Comment by the-vindicar** [comment]
@raimund-schluessler Actually, I'm able to create such a Calendar. 
However, the problem does indeed look identical to #148. 
As such, I believe there is no need to reopen this issue.
