### ISSUE TITLE
VTODO due date cannot be saved (due to timezone/locale issues?)

### ISSUE THREAD

**Issue by Nightfirecat** [nextcloud/tasks#1987]
### Steps to reproduce

(note, I am doing these steps from the America/Los_Angeles timezone and have configured my local computer, `Groupware`, and server to use the same timezone)

1. Create a task with a start date in some CalDAV/CardDAV-synced source, ex. Thunderbird with "Provider for CalDAV & CardDAV" and "TbSync".
2. Access the task from Nextcloud and try to set a due date within 7 hours of the start time and save it

### Expected behaviour
Updating the due date should work without issue.

### Actual behaviour
Updating task fails, UI displays a "Could not update the task." message

### Server configuration

**Operating system**: `Linux 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64`

**Web server:** `Apache/2.4.53 (Debian) (apache2handler)`

**Database:** `mysql 10.5.15`

**PHP version:** `8.0.18`
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, pdo_sqlite, session, posix, Reflection, standard, SimpleXML, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** `23.0.4`

**Tasks version:** `0.14.4`

**Updated from an older Nextcloud or fresh install:** Fresh install ([via `docker-compose`](https://github.com/nextcloud/docker))

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - bruteforcesettings: 2.4.0
  - calendar: 3.2.2
  - circles: 23.1.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.1.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - files: 1.18.0
  - files_markdown: 2.3.6
  - files_pdfviewer: 2.4.0
  - files_readmemd: 1.2.2
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - forms: 2.5.0
  - issuetemplate: 0.7.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - maps: 0.1.10
  - metadata: 0.16.0
  - nextcloud_announcements: 1.12.0
  - notes: 4.3.1
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - polls: 3.6.1
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - richdocuments: 5.0.4
  - richdocumentscode: 21.11.402
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - tasks: 0.14.4
  - text: 3.4.1
  - theming: 1.14.0
  - twofactor_admin: 3.2.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.3.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - encryption
  - federation: 1.13.0
  - files_external
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.nightfirec.at"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.4.1",
        "overwrite.cli.url": "http:\/\/cloud.nightfirec.at",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpport": "465",
        "mail_smtpauthtype": "LOGIN",
        "default_phone_region": "US",
        "loglevel": 2,
        "app_install_overwrite": [
            "issuetemplate"
        ]
    }
}
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 99.0.1 (64-bit)

**Operating system:** Debian 11 (bullseye)

**CalDAV-clients:** Thunderbird 68.3.1 (64-bit) [flatpak release] w/ Provider for CalDAV & CardDAV 1.12 and TbSync 2.12

#### Web server error log
None (`/var/log/apache2/error.log` is a symlink to `/dev/stderr`)

#### Nextcloud log (data/nextcloud.log)
[nextcloud.log](https://github.com/nextcloud/tasks/files/8636299/nextcloud.log)

#### Browser log
[console log](https://github.com/nextcloud/tasks/files/8636306/console-export-2022-5-5_22-0-43.txt)
[network log (added .txt extension for upload)](https://github.com/nextcloud/tasks/files/8636308/cloud.nightfirec.at_Archive.22-05-05.22-00-59.har.txt)

**Comment by raimund-schluessler** [comment]
Yes, this look like a timezone issue. Timezone support is not yet implemented in Tasks.
