### ISSUE TITLE
Give access to task list to persons or groups / share with persons & groups

### ISSUE THREAD

**Issue by blu-IT** [nextcloud/tasks#199]
Hi,

is there a way to share and restrict individual task list/tasks with people/groups that have a nextcloud account or even people who don't have a nextcloud account?
I see that I can download a calendar path for caldav integration for task lists, but this gives only access for me to my list with my credentials. If I want to to share, I would have to give others my login credentials. This is not a solution for me.

Thanks!

Regards

**Database:**
mysql
**PHP version:**
5.6.34
**Nextcloud version:** (see Nextcloud admin page)
13.0.6
**Tasks version:** (see Nextcloud apps page)
0.9.7

**Comment by raimund-schluessler** [comment]
Please see https://github.com/nextcloud/tasks/issues/14. It is currently not possible from within the Tasks app. But you can share a task list from the Calendar app.

Sharing from the Tasks app might be implemented after #194 is done.
