### ISSUE TITLE
Keeping text cursor focus in "new entry" field

### ISSUE THREAD

**Issue by Braintelligence** [nextcloud/tasks#20]
I know keyboard shortcuts already have their own issue, but maybe it would be possible to keep the "new entry" field focused when entering new tasks until then.

This way you can enter new tasks one after another without always clicking into the text field first.

**Comment by korelstar** [comment]
I think this is already the case (at least in the `master` branch): if you type something in the new-entry field an press enter, then the focus is lost temporarily, the sidebar with the new task opens and then the new-entry field receives the focus again and you can type the next new task.

Which version do you use? If you are in doubt, please test with the current state from the git repository.

**Comment by Braintelligence** [comment]
I did a `git clone https://github.com/nextcloud/tasks/`. It says my version is 0.9.3 in the Apps overview.

**Comment by korelstar** [comment]
I've tested this again and found out that the (re-)focus works on Firefox but it doesn't work on Chromium/Chrome. So it's a valid issue. But since I don't know if it works by accident in Firefox, I can't estimate whether this should be classified as bug or as feature-request. :wink:

**Comment by Braintelligence** [comment]
I didn't test it with Firefox yet but I am using Chrome indeed. Well I think it should be implemented either way because this can drastically speed up the task-input 👍 .

**Comment by jaduff** [comment]
Ordering behaviour when sub-lists are involved would need to be thought out. If the last thing entered was a sub-item of an existing list, should the next item added be appended below it, or be added as a new item at the bottom of the parent list?

**Comment by Braintelligence** [comment]
You should copy the behaviour of todoist.
There you can use Tab and Shift-Tab for moving around the nesting.

**Comment by raimund-schluessler** [comment]
Fixed in #194.
