### ISSUE TITLE
Not working yet with NextCloud 14?

### ISSUE THREAD

**Issue by sebtombs** [nextcloud/tasks#200]
### Steps to reproduce
1. Upgrade to NextCloud 14
2. Upgrade script says that Tasks will be disabled
3. After upgrade, Tasks will not re-enable

### Expected behaviour
Tasks should enable

### Actual behaviour
Tasks will not enable (presumably because Tasks is telling NextCloud it is not compatible with version 14)

This may be expected at present, given NextCloud 14 has only just been released.

**Comment by raimund-schluessler** [comment]
There is a compatible version in the appstore, it should automatically update. If not, please manually update to version https://github.com/nextcloud/tasks/releases/tag/v0.9.7

**Comment by sebtombs** [comment]
Thanks Raimund. The automatic upgrade to 0.9.7 had worked (I should have mentioned that in the steps to reproduce, sorry) but what I hadn't done was logged out and back in. This seems to have triggered activation of the enable button.
