### ISSUE TITLE
No notification/reminder when synced with Android app

### ISSUE THREAD

**Issue by GambaJo** [nextcloud/tasks#2006]
### Steps to reproduce
1. Create a task in the web app with an expiration date and time
2. Go to your Android app and sync your tasks
3. Look in the Adroid app in this task if there is a reminder set

### Expected behaviour
When I create a task with an expiration date and time in the web app the task should have set a reminder, when I sync it with my Adroid app.

### Actual behaviour
The task don't have a reminder set.

### Server configuration

**Operating system**: Ubuntu Linux 20.04.4

**Web server:** 

**Database:** mysql 8.0.28

**PHP version:** 8.0.16

**Nextcloud version:** 23.0.3

**Tasks version:** (see Nextcloud apps page) 0.14.4

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
``` No errors have been found.

**Comment by raimund-schluessler** [comment]
Tasks does not support setting reminders, see https://github.com/nextcloud/tasks/issues/154. What you do is setting a due date, but that's not a reminder. You can set a reminder with your Android device, though.
