### ISSUE TITLE
Data storage location & modification

### ISSUE THREAD

**Issue by Jaishankar872** [nextcloud/tasks#2012]
I am  using this task app with nextcloud. My question here is, In which location path data will be store(file location)??
 Also is there any way is change that saving location??

Thanks in advance!!!!!!!!!!

**Comment by raimund-schluessler** [comment]
The task data is not stored in a file, but in the database. Changing the location is hence not possible.

**Comment by Jaishankar872** [comment]
Is there any to take backup of this data??

**Comment by raimund-schluessler** [comment]
If you want a full backup, you need to backup your database and config files. If you are fine with a partial backup of the tasks from a certain list only, you can just download/export the tasks from the context menu of the list in question in the left sidebar as a ICS file.

Please ask further questions in the forum at help.nextcloud.com
