### ISSUE TITLE
Syncronizing with macOS 12 Monterey

### ISSUE THREAD

**Issue by balonchiks** [nextcloud/tasks#2021]
First of all I would like to apologize if this is not a correct place to ask. I know CalDAV issues should be posted in nextcloud repo, but connecting a CalDAV calendar works fine with macos, it's only the tasks/reminders that are not syncing.

I am using the following details when i add a CalDAV account:

**server**: myserver.com (has a valid let'sencrypt ssl certificate). also tried myserver.com:443 - same result
**login**: my nextcloud login
**password**: my nextcloud password (also tried generated password but with no luck)
**port**: 443
**use SSL**: yes
**server path**: /remote.php/dav/principals/users/MYUSERNAME
**kerberos V5 auth**: no/yes - no difference

Worth mentioning that exactly this setup perfectly works on iOS with the reminders app but not on macOS. I have also browsed forums and google as much as i can but could not find any working solution... Does anyone managed to make tasks work with macos maybe?

### Steps to reproduce
1. Add CalDAV account in Settings -> Internet accounts
2. Fill in all the details in Advanced mode
3. Tasks do not showup in Reminders.app

### Expected behaviour
Tasks are expected to show up in Apple reminders.app

### Actual behaviour
Tasks do now showup in reminder.app

### Server configuration

**Operating system**: macOS 12.4

**Nextcloud version:** (see Nextcloud admin page) 24.0.1

**Tasks version:** (see Nextcloud apps page) 0.14.4

**Updated from an older Nextcloud or fresh install:** updated from previous version

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by raimund-schluessler** [comment]
I don't own a Mac, so I cannot really tell how to setup reminders. But if calendar entries are synced, tasks should be as well. They use the same interface/account after all. So I suspect the issue on the configuration or capability side of your Mac and not on the side of Nextcloud.

Furthermore, the Tasks app has no role in syncing with your Mac, that's entirely handled by Nextcloud server. If you need further advise how to configure your device, please ask for support in the forum https://help.nextcloud.com/
