### ISSUE TITLE
[ask for consideration/review] Relation beetwen deck and tasks

### ISSUE THREAD

**Issue by orglube** [nextcloud/tasks#2022]
### Steps to reproduce

I use Deck to manage projects and also tasks which is very usefull for the day to day activity management.

However the relation between deck and tasks seems to me confusing and quite useless as it is currently implemented. Let me explain :

1. each stack in deck currently appears in tasks as a “read only” list that can't be removed nor hidden in tasks : this overloads the task dashboard and is moreover quite useless from a management point of view since there is no way to modify deck cards from tasks. Even worse : DAVX fails to synchonize those deck lists on smartphone which produces useless notifications.

2. on the other hand, It would be really usefull to be able to create todolists within deck cards in the same way that they are created in tasks. I tried to create tick boxes in my deck cards or to link existing tasks within cards, but I didn’t manage to do it. I thought that a very easy way to implement this would be to have te possibility to link task lists to cards in the "details" panel : what do you think ? Is there any chance to see this implemented ?

**Comment by raimund-schluessler** [comment]
The underlying issue is that Decks CalDAV implementation does not allow write access, see https://github.com/nextcloud/deck/issues/2399. Unless this is implemented, there is nothing we can do here.

If seeing the Deck entries in Tasks or DAVX disturbs you, you can disable their exposition in Deck via Settings -> "Show boards in calendar/tasks"

**Comment by orglube** [comment]
Thank you Raimund for your response that fixes to me the topic number one, I disabled exposition.

Do you think I could keep opened this wish :

- would it be to possible to link task lists within cards in the "details" panel (in the same way than it's possible to link another card, a talk or a file) ?

**Comment by raimund-schluessler** [comment]
> Do you think I could keep opened this wish :
> 
>    * would it be to possible to link task lists within cards in the "details" panel (in the same way than it's possible to link another card, a talk or a file) ?

That's a question for the Deck developers, since it is a feature to be implemented in Deck (if I understood correctly what you want). Please open an issue in the [Deck repo](https://github.com/nextcloud/deck).

**Comment by orglube** [comment]
Dear Raimond, thank you. I did so, they say that I should contact the tasks repo developper :-)

Here is the response from Niedermann :

> You will need to ask the tasks app for supporting thr "Nextcloud Projects" feature which allowd linking entities
> to other entities in their corresponding repository - please search there for existing issues regarding this topic,
> I guess this has already been asked :)

May be that is a relatively XL issue to implement this, or not in your plans to consider it ?

**Comment by orglube** [comment]
Ok, I see that has been already requested : #534
