### ISSUE TITLE
[Feature Request] Collapse/Expand Subtasks for a better Overview

### ISSUE THREAD

**Issue by paskalito** [nextcloud/tasks#2028]
### Problem
I happen to have e quiet hudge Task List, to not use track i have grouped them into diffrent type of tasks.
Now i can more or less seperate Tasks Visually from one another, but at least when the sublists get so long i have to scroll it is really hard to tell the level they are in.
![grafik](https://user-images.githubusercontent.com/8012793/173541089-138cc62e-efbf-4e1e-97a2-cec837b488a3.png)

### Proposal
Implement Compact/Hide and Expand for Subtask, in a classic expand manner:
![grafik](https://user-images.githubusercontent.com/8012793/173542389-ee5b063e-851d-4758-84d0-ed912ed82512.png)

**Comment by paskalito** [comment]
1. Oh, i just found that Menu:
![grafik](https://user-images.githubusercontent.com/8012793/173544938-6b71ed16-4fd4-4bfe-979d-4cd7f0755bce.png)

2. I think it is Confusing, that you can expand a list on click, but not collapse again if you click one more time.

3. Also i do not Understand the Visual Cues:
![grafik](https://user-images.githubusercontent.com/8012793/173545910-0f0c95a3-dc94-4e13-ad28-dfcf681fd837.png)
Here all of them have "the Icon" but only the one with tha "hand" on it is actually expandable - with all the others nothing happens.

4. The "traditional method" also let´s you decide in the moment, to have two lists expanded and another collapsed, so you can for exapmle drag subsubolders from one list into subsubfolders from another one..

**Comment by raimund-schluessler** [comment]
>    2. I think it is Confusing, that you can expand a list on click, but not collapse again if you click one more time.

The task expands when it's open in the sidebar, no matter the setting. Closing the sidebar on clicking the task again does not seem intuitive to me.

>    3. Also i do not Understand the Visual Cues:
>        ![grafik](https://user-images.githubusercontent.com/8012793/173545910-0f0c95a3-dc94-4e13-ad28-dfcf681fd837.png)
>        Here all of them have "the Icon" but only the one with tha "hand" on it is actually expandable - with all the others nothing happens.

These other tasks have completed subtasks that you have hidden. Click on `Show closed subtasks` on the parent task to show them.

>    4. The "traditional method" also let´s you decide in the moment, to have two lists expanded and another collapsed, so you can for exapmle drag subsubolders from one list into subsubfolders from another one..

That's well possible by simply showing the subtasks by clicking `Show subtasks` for every parent task for which you want the subtasks to be visible.

**Comment by stellarpower** [comment]
I hadn't realised this was a feature either.

Personally I would prefer the traditional triangular arrow to appear on the left, next to the completed check-box, which points downwards when a task is expanded, and to the right when it is collapsed (just as in the Nautilus screenshot above).

I think this is the standard metaphor users are accustomed to, but can appreciate there may be arguments against this.
