### ISSUE TITLE
How to add Calendars in Tasks?

### ISSUE THREAD

**Issue by corincorvus** [nextcloud/tasks#2031]
Hi,

i have some Calenders like Family, they are in Tasks visible.
Some Calenders are not visible in Tasks. Now i want to add some Tasks on a non visible Calender.

How i can add Calenders in Tasks?
![grafik](https://user-images.githubusercontent.com/21257329/176610848-2442b17c-ecbe-4f37-a76f-8e4260a32773.png)
![grafik](https://user-images.githubusercontent.com/21257329/176610921-e951adcb-5d52-4181-ac1b-8f54d8c36bc5.png)

In the Settings are no Option to import Calenders in Tasks.
I wont delete and import again the calenders :/

Thanks

**Comment by raimund-schluessler** [comment]
Calendars not visible in the Tasks app were created without the support for storing tasks. Since there is no standard conform way of changing this for existing calendars, your only way is to recreate them. You can use the Calendar app for this and select "events and tasks" when creating.
