### ISSUE TITLE
Checklist daily bound possible?

### ISSUE THREAD

**Issue by Elvis2000NC** [nextcloud/tasks#2032]
I am looking for an app for Nextcloud that allows the following: I have checklists that are day bound. I would like this app to show the checklist for Monday on every Monday and the tasks can be set to “done” by a check mark if possible. The next Monday, the checklist should then appear blank again, so that it can be worked through again. Is it possible with tasks?

**Comment by raimund-schluessler** [comment]
This is called repeating tasks, and is not yet implemented here. Please see #34.
