### ISSUE TITLE
NC14.0.1 & tasks 0.9.7: "App is not compliant"

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/tasks#204]
`occ app:check-code tasks`

```
Invalid appinfo.xml file found: Element 'licence': This element is not expected. Expected is one of ( description, version ).

Invalid language file found: l10n/af.json: Control character error, possibly incorrectly encoded
App is not compliant
```

**Comment by raimund-schluessler** [comment]
Thanks for the hint, I will have a look. But I am not sure, what I can do against the invalid language file, because this one is autogenerated by transifex. Maybe @MorrisJobke has an idea?

**Comment by MorrisJobke** [comment]
Weird - `activity` also uses this one. cc @nickvergessen

**Comment by nickvergessen** [comment]
the af translation contained a control character by accident.
I removed it on transifex and triggered a sync.
See the box in line 20:

![bildschirmfoto von 2018-10-16 09-37-34](https://user-images.githubusercontent.com/213943/46999911-49fc4780-d127-11e8-8080-b8a4671b5a80.png)

**Comment by MorrisJobke** [comment]
> Weird - `activity` also uses this one. cc @nickvergessen

I meant the "licence" element, but it is somehow invalid or is just the XSD outdated?

**Comment by nickvergessen** [comment]
The php parser does somehow not allow arbitrary order of the siblings.
So I fixed the order in https://github.com/nextcloud/tasks/pull/207

Only thing removed is the ocs tag.
