### ISSUE TITLE
task cant be shares

### ISSUE THREAD

**Issue by icf20** [nextcloud/tasks#205]
### Steps to reproduce
1. create 2 users
2. install tasks app
3. create a task category add few tasks

### Expected behaviour

there should be a way to share tasks 

### Actual behaviour

tasks cant be shared 

**Nextcloud version:** 13 

**Tasks version:** 	0.9.6

**Updated from an older Nextcloud or fresh install:** fresh

**List of activated apps:**

tasks

**Comment by peterthomashorn** [comment]
This might be a duplicate of #14 unless you request the feature of sharing individual tasks instead of whole lists.

**Comment by icf20** [comment]
@peterthomashorn hello, yes you are corest
