### ISSUE TITLE
[Feature Request] Show submit button on the right of new Task input field

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [nextcloud/tasks#2075]
![2022_08_15_20_27_17_Window](https://user-images.githubusercontent.com/46269721/184743047-5cd62641-2c1b-4256-8d63-90a6ff4cf4dc.png)

I think clicking that icon should do the same as pressing the enter key. I thought my instance was broken for quite a while until I realized it actually expects the user to press the enter key.

I'm logging this as a bug because if this isn't a broken button, I don't know why it was put there in the first place

**Comment by raimund-schluessler** [comment]
This for sure is not a bug. It simply visualizes what this input field is supposed to do: add a Task. Besides, why should a submit/create button be on the left and provide no feedback when hovered, unlike every other button in the app? And if you ever used the Google search engine, you might be used to it: The magnifying glass icon on the left just does nothing and is not a button.
![Screenshot 2022-08-16 at 21-55-09 Google](https://user-images.githubusercontent.com/2496460/184973071-995c60be-24a3-49d9-81be-7e140806b388.png)

But I agree, that we could show a submit button on the right of the input field, similar to how it's done in the new TextField component of nextcloud/vue:
![Screenshot 2022-08-16 at 21-59-00 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/184973545-1fd97006-15ea-4fbf-a748-edadd8a68b8b.png)

**Comment by girugamoz** [comment]
My two cents: Google tries to avoid confusion like OP's: They show the magnifying glass icon as slightly darker than the input's font color, the same color as the input field's borders. This makes it more clear that the icon is not interactive. Maybe the same could be done here, too.
