### ISSUE TITLE
Autosave doesn't differentiate between its own changes and external ones

### ISSUE THREAD

**Issue by nawordar** [nextcloud/tasks#2078]
### Steps to reproduce

Many things trigger this problem, but the most reliable way I found is this one:

1. Add a new tag to a task. Let's call it "test"
2. After adding it, remove it right away

### Expected behaviour

The tag is removed successfully.

### Actual behaviour

A yellow warning signs shows up with a message "Could not update the task because it was changed on the server. Please click to refresh it, local changes will be discarded."

### Server configuration

I have my instance running through a Docker image: docker.io/nextcloud:24-apache

**Operating system**: Arch Linux

**Web server:** Apache

**Database:** PostgreSQL (docker.io/postgres:14-alpine)

**PHP version:** 8.0.22

**Nextcloud version:** 24.0.4

**Tasks version:** 0.14.4

**Updated from an older Nextcloud or fresh install:** I was updating both Nextcloud and Tasks

**Signing status:** ?

**Comment by raimund-schluessler** [comment]
This is very likely a configuration issue, either on the server side or in your browser. The Etag of the request is probably changed somewhere on the way and then the Tasks app has no chance of figuring out if it might overwrite a change that happened on the server or not. See https://github.com/nextcloud/tasks/issues/2077 for example where a browser plugin stripped of the correct Etag.

Also, if the Task was indeed changed on the server (which is not clear from your description), then showing a conflict warning is the only way we can currently handle this.

**Comment by nawordar** [comment]
> This is very likely a configuration issue, either on the server side or in your browser. The Etag of the request is probably changed somewhere on the way and then the Tasks app has no chance of figuring out if it might overwrite a change that happened on the server or not. See #2077 for example where a browser plugin stripped of the correct Etag.
> 
> Also, if the task was indeed changed on the server (which is not clear from your description), then showing a conflict warning is the only way we can currently handle this.

This was exactly my problem (clearing ETags in ClearURLs add-on). Sorry for not filling in the whole template, I was convinced that this is a problem with Tasks itself. Will do the next time.
