### ISSUE TITLE
Allow modification of a task from Desk app directly form task app

### ISSUE THREAD

**Issue by Iwios** [nextcloud/tasks#2097]
Hello,

It's possible to add a function to allow modification of a task from a Desk?

May be it's difficult, because a task has to state: Current or Finished and Desk allow multi states.
But in default, If the task was finished, the desk may be tagged with a standard Finished?

**Comment by raimund-schluessler** [comment]
I suppose you mean the Deck app?
The underlying issue is that Deck boards are only readable, but not writable when exposed via CalDAV. As soon as the Deck app implements https://github.com/nextcloud/deck/issues/2399 it will automatically work to edit Deck entries from the Tasks app.
