### ISSUE TITLE
main tasks page doesn't scroll

### ISSUE THREAD

**Issue by tbasilici** [nextcloud/tasks#2118]
### Steps to reproduce
1. open the tasks main page
2. load a task list longer than the browser viewport
3. try to scroll down

### Expected behaviour
The page should scroll in order to show the older tasks

### Actual behaviour
The page does not scroll

### Server configuration

**Operating system**: linux debian 11

**Web server:** nginx 1.18.0 

**Database:** 10.5.15

**PHP version:** 8.0.23

**Nextcloud version:** 25.0.0 RC 1

**Tasks version:** 0.14.4

**Updated from an older Nextcloud or fresh install:** updated

**Signing status:** No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.17.0
  - bookmarks: 11.0.3
  - bruteforcesettings: 2.5.0
  - calendar: 4.0.0-alpha.1
  - circles: 25.0.0-alpha.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.0-alpha.3
  - contactsinteraction: 1.6.0
  - dav: 1.24.0
  - deck: 1.8.0-beta.2
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.0
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - files_videoplayer: 1.14.0
  - files_zip: 1.1.2
  - groupfolders: 13.0.0-beta.1
  - impersonate: 1.11.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.0.0-rc.1
  - metadata: 0.16.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.5.1
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - phonetrack: 0.7.0
  - photos: 1.7.1
  - polls: 4.0.0-beta1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.0
  - richdocuments: 7.0.0-beta.2
  - riotchat: 0.13.8
  - sendent: 1.3.0
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - systemtags: 1.15.0
  - tasks: 0.14.4
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.0.13",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0
        },
        "maintenance": false,
        "loglevel": 0,
        "updater.release.channel": "beta",
        "theme": "",
        "app.mail.verify-tls-peer": false,
        "app_install_overwrite": [
            "mindmap_app",
            "documentserver_community",
            "riotchat",
            "groupfolders",
            "impersonate",
            "metadata",
            "onlyoffice",
            "ownpad",
            "polls",
            "rainloop",
            "ransomware_protection",
            "sendent",
            "talk_simple_poll",
            "bruteforcesettings",
            "spreed",
            "weather",
            "bookmarks",
            "tasks",
            "richdocuments",
            "phonetrack"
        ],
        "default_phone_region": "+39"
    }
}

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** firefox 105 and chrome 106.0.5249.61

**Operating system:** Ubuntu Kinetic Kudu , linux mint and windows 11

**CalDAV-clients:** n/a

#### Web server error log

empty

#### Nextcloud log (data/nextcloud.log)

{"reqId":"7k0ipXme8Hs2lPqzRmTq","level":0,"time":"2022-09-27T09:33:34+00:00","remoteAddr":"***REMOVED SENSITIVE VALUE***","user":"***REMOVED SENSITIVE VALUE***","app":"metadata","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/user_status?format=json","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Linux) mirall/3.6.0-20220906.073332.ccc9f8930-1.0~jammy1 (Nextcloud, linuxmint-5.15.0-48-generic ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"25.0.0.13","data":{"app":"metadata"}}

#### Browser log

The resource from “***REMOVED SENSITIVE VALUE***/apps/tasks/css/tasks.css?v=8f71fc8e-19” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

**Comment by raimund-schluessler** [comment]
Fixed with https://github.com/nextcloud/tasks/pull/2114. Tasks needs a new release to run properly on NC 25.
