### ISSUE TITLE
"Load all completed tasks" button clipped

### ISSUE THREAD

**Issue by BrandonMFong** [nextcloud/tasks#2140]
### Steps to reproduce
1. Open nextcloud
2. go onto the tasks app

### Expected behaviour
The "Load all completed tasks" button looks like it should be rounded at its corners

### Actual behaviour
The buttons seems to be clipped

### Server configuration

**Operating system**:  Linux 5.10.0-16-amd64 x86_64

**Web server:** Nginx 1.18.0

**Database:**  10.5.15-MariaDB-0+deb11u1 Debian 11

**PHP version:** 7.4.30

**Nextcloud version:** (see Nextcloud admin page) 24.0.2

**Tasks version:** (see Nextcloud apps page) 0.14.5

**Updated from an older Nextcloud or fresh install:** fresh install

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - bookmarks: 11.0.4
  - breezedark: 24.0.2
  - bruteforcesettings: 2.4.0
  - calendar: 3.5.1
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.2
  - dashboard: 7.4.0
  - dav: 1.22.0
  - external: 4.0.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - files_zip: 1.1.2
  - firstrunwizard: 2.13.0
  - integration_reddit: 1.0.5
  - integration_twitter: 1.0.3
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - onlyoffice: 7.5.6
  - password_policy: 1.14.0
  - passwords: 2022.10.10
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - tasks: 0.14.5
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_totp: 6.4.1
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - contactsinteraction: 1.5.0
  - deck: 1.7.1
  - encryption
  - spreed: 14.0.5
  - user_ldap

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "brandonmfong.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.2.1",
        "overwrite.cli.url": "https:\/\/brandonmfong.com\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "maintenance": false
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, smb

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/nextcloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** Firefox 106.0.1

**Operating system:** Macos 12.6

**CalDAV-clients:** Apple Calendar, Apple Reminders

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. asyncToGenerator.js:6:4
No OC found index.js:46:4
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
JQMIGRATE: Migrate is installed, version 3.4.0 jquery-migrate.min.js:2:698
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
Loading theming data for notification bell styling App.vue:150
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
Registering notifications container as a menu App.vue:160
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Notifications permissions granted App.vue:395
Polling interval updated to 30000 App.vue:355
Started background fetcher as session_keepalive is enabled App.vue:217
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
Proxying an event bus of version 2.1.1 with 3.0.2 index.js:19:12
Proxying an event bus of version 2.1.1 with 3.0.2 index.esm.js:11:12
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:6
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
session heartbeat polling started session-heartbeat.js:103:9
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 204 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 16 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 80 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 28 globals.js:62:15
Got notification data App.vue:318
Polling interval updated to 30000 App.vue:355
[DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, app: "unified-search", … }
ConsoleLogger.js:29:8
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 140 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 6 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 14 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 13 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 375 globals.js:62:15

**Comment by raimund-schluessler** [comment]
Could you show a screenshot of the clipped button, please? It looks fine on my Nextcloud 24 instance.

**Comment by BrandonMFong** [comment]
@raimund-schluessler, of course! 
![image](https://user-images.githubusercontent.com/55638760/199287626-2d34346c-0ee0-445b-8f66-26821b91241b.png)

**Comment by raimund-schluessler** [comment]
Your Nextcloud looks quite different to the default style. Could you please try to disable the `breezedark` theme and check if that fixes the issue?

**Comment by BrandonMFong** [comment]
Yes, that does fix the issue:
![image](https://user-images.githubusercontent.com/55638760/199289154-a0e3e109-2f2b-4ad9-bf3c-f829ca399d5d.png)

How the button looks is not a big deal to me but just figured I'd let y'all know.

**Comment by raimund-schluessler** [comment]
If breezedark is the issue, than the theme needs to be adjusted. There isn't much we can do here, sorry.
