### ISSUE TITLE
Images are missing (reverse proxy)

### ISSUE THREAD

**Issue by sNiXx** [nextcloud/tasks#215]
### Steps to reproduce
1. Nextcloud is running from within docker container (image: "wonderfall/nextcloud"), a reverse proxy is used to make it reachable via "myserver.com/nextcloud"
2. Install the tasks app and icons sprites.svg are missing, while other images seem to be loaded properly. It seems the app is ignoring the setting for 'overwritewebroot', as the link reads "https://myserver.com/apps2/tasks/img/sprites.svg" instead of "https://myserver.com/nextcloud/apps2/tasks/img/sprites.svg", where they actually are stored.

### Expected behaviour
After installing, the images (e.g. for "week", "change sort order" or "add subtask") should be shown

### Actual behaviour
Some images seem to be missing

## Server configuration detail

**Operating system:** Linux 4.17.0-0.bpo.3-amd64 #1 SMP Debian 4.17.17-1~bpo9+1 (2018-08-27) x86_64
**Webserver:** nginx/1.15.5 (fpm-fcgi)
**Database:** sqlite3 3.20.1
**PHP version:** 7.2.10
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, gd, hash, iconv, json, mbstring, SPL, PDO, pdo_sqlite, bz2, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, Phar, exif, ftp, gmp, imap, intl, ldap, mysqli, pcntl, pdo_mysql, pdo_pgsql, pgsql, zip, redis, smbclient, libsmbclient, Zend OPcache
**Nextcloud version:** 14.0.3 - 14.0.3.0
<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - dav: 1.6.0
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - metadata: 0.7.0
 - nextcloud_announcements: 1.3.0
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - password_policy: 1.4.0
 - provisioning_api: 1.4.0
 - ransomware_protection: 1.2.0
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - tasks: 0.9.7
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - workflowengine: 1.4.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "apps_paths": [
        {
            "path": "\/nextcloud\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/apps2",
            "url": "\/apps2",
            "writable": true
        }
    ],
    "memcache.local": "\\OC\\Memcache\\APCu",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "logdateformat": "Y-m-d H:i:s",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***/nextcloud",
    "overwritewebroot": "\/nextcloud",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***:8888"
    ],
    "dbtype": "sqlite3",
    "version": "14.0.3.0",
    "installed": true,
    "maintenance": false,
    "loglevel": 2,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
**Operating system:** Windows 10

## Screenshot
![missingimages](https://user-images.githubusercontent.com/3066873/48061538-96cfbd00-e1bf-11e8-9112-f2aa1cdd7b0f.png)

**Comment by raimund-schluessler** [comment]
Is it working for other apps, e.g. Contacts or Calendar?

**Comment by sNiXx** [comment]
I partially solved it by changing from a subfolder (myserver.com/nextcloud) to a subdomain (nextcloud.myserver.com) structure. However, icons for all "smart collections" (e.g. Today", "Week"), "Add List" and possibly others are still not shown.

I checked the error console and I get two CSP errors related to tasks (using the default values in /nextcloud/lib/private/legacy/response.php)
```
The page's settings blocked the loading of a resource at inline ("script-src")
The page's settings blocked the loading of a resource at eval ("script-src").
```
and one warning related to tasks
```
Source map error: request failed with status 404
Resource URL: https://nextcloud.myserver.com/js/tasks/merged.js?v=dda68890-0
Source Map URL: app.min.js.map
```
I quickly enabled Contacts and Calendar, but it seems there aren't any icons missing. I checked their html and there was no sprite class in either.

**Comment by raimund-schluessler** [comment]
> I partially solved it by changing from a subfolder (myserver.com/nextcloud) to a subdomain (nextcloud.myserver.com) structure. However, icons for all "smart collections" (e.g. Today", "Week"), "Add List" and possibly others are still not shown.

I also run a server with subdomain structure and there the app works fine.

> I checked the error console and I get two CSP errors related to tasks (using the default values in /nextcloud/lib/private/legacy/response.php)

This is most likely not related.

> and one warning related to tasks
> ```
> Source map error: request failed with status 404
> Resource URL: https://nextcloud.myserver.com/js/tasks/merged.js?v=dda68890-0
> Source Map URL: app.min.js.map
> ```

This one most likely not either (but is fixed in master now).

> I quickly enabled Contacts and Calendar, but it seems there aren't any icons missing. I checked their html and there was no sprite class in either.

They don't use a sprites file, but they also load images from their `img` folder. And the sprite is just an image as well.

Is there an error message that the image is not loaded somewhere? What is the path under which it is requested?

**Comment by sNiXx** [comment]
There is no error regarding any image. I'm not sure how I could answer your question "What is the path under which it is requested?" - could you tell me where to look? 

The only other error I found was this:
```
downloadable font: rejected by sanitizer (font-family: "Nunito" style:normal weight:700 stretch:100 src index:2) source: https://nextcloud.myserver.com/core/fonts/Nunito-Bold.woff2
```

**Comment by raimund-schluessler** [comment]
Has anything changed with v0.10.1?

**Comment by sNiXx** [comment]
Thanks for the follow-up!
I can't really answer your question, because I changed the way my reverse proxy hanldes requests. Instead of a subpath (https://myserver.com/nextcloud/) I now use a subdomain (https://nextcloud.myserver.com/) and it seems to work flawlessly. The app seemed to somehow incorrectly handle subpaths (see step two in my opening post).

**Comment by raimund-schluessler** [comment]
I still don't know why the Tasks app would work incorrectly, while the other apps function without a problem. There are no special adjustments known to me that would need to be applied in order to make a subpath setup work with an app. Everything should be handled by the server.

Anyway, since you can't debug this anymore with the subdomain setup, I am going to close this issue. Anyone experiencing the same problem, feel free to comment.
