### ISSUE TITLE
Delete the sample Tasks is not possible!

### ISSUE THREAD

**Issue by PromoTime24** [nextcloud/tasks#2155]
Hello,
it is on this time not possible that we can delete the sample tasks. (We have add a screenshot!)

We have try it on 3 Installation.

<img width="1219" alt="Bildschirm­foto 2022-11-12 um 08 07 50" src="https://user-images.githubusercontent.com/109661560/201462278-61a7232f-366d-43cf-86dc-e6c018d97865.png">

Can you Help us or fix the issue..

Best regards
Thomas

**Comment by raimund-schluessler** [comment]
These are entries from the Deck app. They are read-only. You can
- delete them in the Deck app
- disable showing them in the Tasks app in the Deck app
- disable the Deck app

Tasks cannot do anything here.

**Comment by wakest** [comment]
@raimund-schluessler this should still be fixed, this makes no sense as a default. I was trying to delete these for ages and only figured it out by finding this old issue.

**Comment by raimund-schluessler** [comment]
> @raimund-schluessler this should still be fixed, this makes no sense as a default. I was trying to delete these for ages and only figured it out by finding this old issue. 

As I said, the Tasks app is not responsible for this, nor can we fix it here. If you want it changed, please open an issue in the Deck app repository.
