### ISSUE TITLE
Subtasks disappear when adding sub-subtask when subtask hide option is enabled

### ISSUE THREAD

**Issue by maxlStone** [nextcloud/tasks#2188]
### Steps to reproduce
1. Create a task
2. Choose hide subtasks
3. Create subtasks
4. Try to add subtask to one of the subtasks

### Expected behaviour
Subtasks should stay visible while working inside the subtask area of a task

### Actual behaviour
All subtasks of the main task get hidden and the entry for the new sub-subtask also disappears.

### Server configuration

**Operating system**: Debian GNU/Linux 10

**Web server**: apache2

**Database**: mysql

**PHP version**: 7.3.31

**Nextcloud version:** 25.0.3

**Tasks version:** 0.14.5

**Updated from an older Nextcloud or fresh install:** updated from older versions

```
No errors have been found.
```

**List of activated apps:**

```
  - accessibility: 1.9.0
  - activity: 2.15.0
  - breezedark: 23.2.2
  - bruteforcesettings: 2.4.0
  - circles: 23.1.2
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - duplicatefinder: 0.0.15
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_downloadactivity: 1.15.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - geoblocker: 0.5.7
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - maps: 0.2.0
  - nextcloud_announcements: 1.12.0
  - nextcloudpi: 0.0.1
  - notes: 4.3.1
  - notify_push: 0.5.2
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - suspicious_login: 4.1.0
  - systemtags: 1.13.0
  - tasks: 0.14.5
  - text: 3.4.1
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.3.0
  - unsplash: 2.0.1
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
```

**Nextcloud configuration:**

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "***REMOVED SENSITIVE VALUE***"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.6.1",
        "overwrite.cli.url": "An unhandled exception has been thrown:\nRedisException: read error on connection in \/var\/www\/nextcloud\/lib\/private\/Memcache\/Redis.php:66\nStack trace:\n#0 \/var\/www\/nextcloud\/lib\/private\/Memcache\/Redis.php(66): Redis->get('8e5358d2d6cd7b6...')\n#1 \/var\/www\/nextcloud\/lib\/autoloader.php(153): OC\\Memcache\\Redis->get('OCA\\\\ServerInfo\\\\...')\n#2 [internal function]: OC\\Autoloader->load('OCA\\\\ServerInfo\\\\...')\n#3 [internal function]: spl_autoload_call('OCA\\\\ServerInfo\\\\...')\n#4 \/var\/www\/nextcloud\/lib\/private\/ServerContainer.php(106): class_exists('OCA\\\\ServerInfo\\\\...')\n#5 \/var\/www\/nextcloud\/lib\/private\/ServerContainer.php(176): OC\\ServerContainer->getAppContainer('serverinfo', 'ServerInfo')\n#6 \/var\/www\/nextcloud\/lib\/private\/ServerContainer.php(143): OC\\ServerContainer->getAppContainerForService('OCA\\\\ServerInfo\\\\...')\n#7 \/var\/www\/nextcloud\/lib\/private\/Console\/Application.php(217): OC\\ServerContainer->query('OCA\\\\ServerInfo\\\\...')\n#8 \/var\/www\/nextcloud\/lib\/private\/Console\/Application.php(128): OC\\Console\\Application->loadCommandsFromInfoXml(Array)\n#9 \/var\/www\/nextcloud\/console.php(99): OC\\Console\\Application->loadCommands(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 \/var\/www\/nextcloud\/occ(11): require_once('\/var\/www\/nextcl...')\n#11 {main}:\/\/nextcloudpi\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "tempdirectory": "\/media\/NCPiMainData\/ncdata\/tmp",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "overwriteprotocol": "https",
        "maintenance": false,
        "logfile": "\/media\/NCPiMainData\/ncdata\/nextcloud.log",
        "loglevel": "2",
        "log_type": "file",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "theme": "",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "data-fingerprint": "14a018fd88132e1f7770b7f81ee979a4"
    }
}

```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 107.0.1

**Operating system:** elementary OS 6.1 Jólnir (Ubuntu 20.04.5 LTS)

**Comment by raimund-schluessler** [comment]
I cannot follow the behavior you described. If you add a task, it is automatically opened in the right sidebar. Tasks that are open in the sidebar stay visible in the task list, as well as all of their ancestor and sibling tasks. So, a Task you just added never disappears in the task list, no matter if 'Hide subtasks'  is enabled for the parent task.

What change in behavior do you really expect here?

**Comment by maxlStone** [comment]
If you click into the field to create a new sub-subtask (*1) the currently selected task is unselected and therefore the subtasks are hidden and also the entry field.- task (hidden subtasks)  - subtask1    - <new subtask entry field> (*1)Maybe this helps to understand my observation. ---- On Fr, 03 Feb 2023 11:47:22 +0100  ***@***.***  wrote ----
I cannot follow the behavior you described. If you add a task, it is automatically opened in the right sidebar. Tasks that are open in the sidebar stay visible in the task list, as well as all of their ancestor and sibling tasks. So, a Task you just added never disappears in the task list, no matter if 'Hide subtasks'  is enabled for the parent task.
What change in behavior do you really expect here?

**Comment by raimund-schluessler** [comment]
Ok, I see. If you click into the input field, the sidebar closes and the tasks get hidden. This is worth being fixed. For now, you could just not click into the input field, as it's autofocused.

**Comment by maxlStone** [comment]
Exactly :)Yeah that was also the way I did it in the past but somehow the focus now gets lost after seeing the cursor blink one time an then I have to click. ---- On Fr, 03 Feb 2023 12:45:10 +0100  ***@***.***  wrote ----
Ok, I see. If you click into the input field, the sidebar closes and the tasks get hidden. This is worth being fixed. For now, you could just not click into the input field, as it's autofocused.

**Comment by raimund-schluessler** [comment]
With the changes in #2226 I cannot reproduce the issue anymore.
