### ISSUE TITLE
Random task selection

### ISSUE THREAD

**Issue by sebastienaubry** [nextcloud/tasks#2198]
Hi,
I would very much like a feature to select a random task, either from the current task list, or from the current view (e.g. All tasks). It could also be interesting to add the option to display task numbers (currently the number of tasks is displayed next to the list name).
Thanks

**Comment by raimund-schluessler** [comment]
What do you want to do with the selected task?

**Comment by sebastienaubry** [comment]
I would like to select a random task from a long list and display it, to avoid the hassle to choose what to do next. 
Another idea would be a "random" sort order.

**Comment by raimund-schluessler** [comment]
Ok, I think now I understand. You want the software to decide randomly for you which task to do. To be honest, I think this is to much of a niche feature to put effort into implementing and maintain this. I propose you mimic the feature by wiggling your mouse and clicking with the eyes closed 😉

**Comment by sebastienaubry** [comment]
Hello,
On the contrary, I think there could be more generally many uses of this random item selection. A random sort order may be the easiest way to implement it.
