### ISSUE TITLE
Markdown format glitch

### ISSUE THREAD

**Issue by max65482** [nextcloud/tasks#2205]
### Steps to reproduce
1. Create a new task
2. Add a note with markdown syntax ("- [ ] Subtask")
3. Re-enter the note preview

### Expected behaviour
Markdown elements are vertically aligned with the text.

### Actual behaviour
The text is rendered below the markdown element.

![Tasks_bug](https://user-images.githubusercontent.com/56191773/221128663-3113b2d8-f491-43d0-8158-4ded41cf6c7d.png)

### Server configuration

**Operating system**:
Debian 11

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
8.1.16

**Nextcloud version:** (see Nextcloud admin page)
- 25.0.3
- 26.0.0 beta 5

**Tasks version:** (see Nextcloud apps page)
0.14.5

**Updated from an older Nextcloud or fresh install:**
fresh install

**Signing status:**
No errors have been found.

### Client configuration
**Browser:**
- Chrome Version 110.0.5481.105
- Firefox 110.0

**Comment by raimund-schluessler** [comment]
@max65482 See #2206.
