### ISSUE TITLE
Transfer Lists from one instance to other instance.

### ISSUE THREAD

**Issue by XHyperDEVX** [nextcloud/tasks#2207]
Hello.

I'm in the process of moving my Nextcloud to another server and I'm facing the problem that I can't transfer my list in the tasks app.

Is this possible? If so how?

I have a list with over 1k items, so it is not possible to transfer everything by hand.

**Comment by raimund-schluessler** [comment]
The Tasks app is only a CalDAV client and does not provide the backend in which your task (and calendar) data is stored. This is part of Nextcloud server. Please ask this question how to move your Nextcloud instance in the forum at https://help.nextcloud.com/

As a Nextcloud user myself, I would probably transfer the complete database from one server to the other. If you really only want your task and calendar data moved, you could export and import it. But that starts to become cumbersome with many entries or lists.
