### ISSUE TITLE
Nextcloud Tasks will not sync with 2Do application via CalDAV.

### ISSUE THREAD

**Issue by sunjam** [nextcloud/tasks#221]
[From this Sabre-dav issue](https://github.com/sabre-io/dav/issues/986).  2do will not accept Nextcloud caldav credentials, and I've been unable to get them to work together. :(  Very unfortunate.  Here is a direct quote from the 2Do team, as mentioned in the linked issue.

>  Sadly nextcloud is one of those CalDAV servers 2Do does not fully support (or rather, nextcloud has a half-hearted, obsolete implementation taken from an older version of Sabre). Given it's got a poorly implemented CalDAV server, we're currently not endorsing it nor able to provide any support as there are various known issues with nextcloud as we speak. I apologize for this unhelpful response, but we've in the past spent several man-hours trying to resolve this with little to no luck :) We're instead asking our users to provide us with any tips if they're able to get it to work

**Comment by raimund-schluessler** [comment]
The [issue](https://github.com/sabre-io/dav/issues/986) you linked was closed, saying this is the correct behaviour:
> From RFC5545 (https://tools.ietf.org/html/rfc5545#section-3.8.2.3)
>    ```
>    For cases where this property
>    is specified in a "VTODO" calendar component that also specifies a
>    "DTSTART" property, the value type of this property MUST be the
>    same as the "DTSTART" property, and the value of this property
> ```

 There was also an [issue](https://github.com/nextcloud/server/issues/7771) in Nextcloud server, leading to the same conclusion, that 2DO does not follow the CalDAV standard. I can't see what NC could do here.

Also, please report problems with the NC CalDAV server in the server repository.

**Comment by sunjam** [comment]
Thanks, report filed to 2Do team.
