### ISSUE TITLE
Errors in vue branch

### ISSUE THREAD

**Issue by nicolad** [nextcloud/tasks#222]
I wanted to start contributing to this project, but I cannot build the project.
These errors are left on purpose ?
I am using node v10.13.0
![image](https://user-images.githubusercontent.com/1477453/49701690-148c4b80-fbf8-11e8-91f2-a1f1d71428ce.png)

**Comment by raimund-schluessler** [comment]
Your repository does not seem to be clean. There is no such file `css/style.scss` in the vue branch.

**Comment by nicolad** [comment]
Thank you, I have made checkout from `master`, my bad.
