### ISSUE TITLE
[Feature Request] Option to import

### ISSUE THREAD

**Issue by hellmachine2000** [nextcloud/tasks#2247]
Hi, 
it is really nice that you can export the tasks as .ics file. But It would be really helpful if it is possible to also import the exported file.

Thanks,
Marc

**Comment by raimund-schluessler** [comment]
Duplicate of #122. You can use the function in the Calendar app for now.

**Comment by hellmachine2000** [comment]
Hi Raimund,I tried, but the Nextcloud 15 Calendar App drops an error when importing.Am 04.04.2023 um 00:56 schrieb Raimund Schlüßler ***@***.***>:﻿
Duplicate of #122. You can use the function in the Calendar app for now.
