### ISSUE TITLE
Unable to sync tasks if web app is not used once 

### ISSUE THREAD

**Issue by avinash-0007** [nextcloud/tasks#2268]
### Steps to reproduce
1.Create an account on nextcloud
2. Now use  task [mobile app](https://f-droid.org/en/packages/org.tasks/) on mobile device
3. default **Task calendar** is missing if you have-not used task app once on web.

### Expected behaviour
Default task Calendar should be present on Task Mobile app otherwise sync is broken. 
App link: https://play.google.com/store/apps/details?id=org.tasks&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1&pcampaignid=pcampaignidMKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1&pli=1
I see that this is handled for calendar app 

https://github.com/nextcloud/server/blob/v25.0.4/apps/dav/lib/HookManager.php#L177 but we need this to be handled for task calendar.

### Actual behaviour
No default Task Calendar Present

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud -25.0.6
**Tasks version:** (see Nextcloud apps page)
0.14.5

**Comment by raimund-schluessler** [comment]
Closing in favor of https://github.com/nextcloud/calendar/issues/4554.
