### ISSUE TITLE
Hide "Deck" entries

### ISSUE THREAD

**Issue by xstable** [nextcloud/tasks#2295]
### Steps to reproduce
1. Install DECK Plugin
2. Enter some Lists and cards
3. Open Tasks
4. You'll see all your DESK-Lists in Tasks

### Expected behaviour
I would like to have the option to show or hide the DECK-Lists in Tasks

### Actual behaviour
All DECK Lists are shown as TASK-Lists

**List of activated apps:**

Deck 1.9.2
Tasks 0.15.0

**Nextcloud configuration:** 26.0.2

![image](https://github.com/nextcloud/tasks/assets/1778068/ff834039-1df0-4125-aa6e-b0014ba0053f)

**Comment by raimund-schluessler** [comment]
You can disable this in the Deck app.

**Comment by xstable** [comment]
@raimund-schluessler ok, thanks. Where can I found this config-setting in GUI?
