### ISSUE TITLE
Combined task view - the ability to see all tasks at once

### ISSUE THREAD

**Issue by smokinjo** [nextcloud/tasks#2354]
Individual lists are great. But, needing to go inside each list to see the items makes it hard to see the global, overall list of things to do.

Adding the option  to see all task items in one single view, allowing to view and sort them all at once to see your entire list of tasks to do.

**Comment by raimund-schluessler** [comment]
We have the smart list "All". If you don't see it, it's probably disabled. Enable it in the settings on the left bottom.

**Comment by smokinjo** [comment]
OK, I did nto see th eall view.  I did not notice it.

But, this does not do what I was looking for(even though my description was not perfectly clear).

I want to be able to literally combine all the tasks in one list.   In order to clarify each item and where it comes from, a column would be created to identify the list that it is on.

How can this be achieved?
