### ISSUE TITLE
Feature Requests User Management / Permission and Time Statistics

### ISSUE THREAD

**Issue by GVLLIFESTYLE** [nextcloud/tasks#2387]
### Is your feature request related to a problem? Please describe.

nope

### Describe the solution you'd like

It would be cool if tasks could be assigned to users + only they can change settings on the tasks then.
Moreover it would be nice if a user can assign a non assigned tasks to himself and then he only has control over it, like if the manger assigns a tasks to him.

taks should also be able to be assigned to other users from the current user if approved by the admin or so.

second thing is, that it would be nice to get a statistic of how long each tasks took from assigning, till done + some overview who all worked on it + a sum of all working time group by user, task,...

**Comment by RokeJulianLockhart** [comment]
@MrLoverLoverMMMM, the issue title should reflect the specific suggestion, not its type.

**Comment by MrLoverLoverMMMM** [comment]
I renamed the title, if thats ok in this way

**Comment by raimund-schluessler** [comment]
Assigning users to tasks is tracked in #72.
Time tracking is tracked in #75.
