### ISSUE TITLE
Missing support of a task's privacy setting

### ISSUE THREAD

**Issue by JayEn84** [nextcloud/tasks#243]
### Steps to reproduce
1. Start a new task or open an existing task in order to see the task's individual settings.

### Expected behaviour
There should be an option to set the task as "public", "busy" or "private". (This option is supported within the calendar app.)

### Actual behaviour
There is no such option.
I am using Thunderbird with the Lightning plugin together with NextCloud. Setting tasks to private is possible in Thunderbird and it is supported by this app!!! The option is just not available within the NextCloud frontend.
(On a sidenote, I was actually looking for a way to mark new tasks private by default, which does not seem to be supported by Thunderbird, too.)

### Server configuration
LAMPP
NextCloud 15.0.2
Tasks App 0.9.8

**Operating system**:
Linux

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
15.0.2

**Tasks version:** (see Nextcloud apps page)
0.9.8

**Updated from an older Nextcloud or fresh install:**
Updated

**Signing status:**
Integrity checker has been disabled. Integrity cannot be verified.

**List of activated apps:**
Standard list plus "Deck" I guess.

**Nextcloud configuration:**
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'xxx',
  ),
  'datadirectory' => 'xxx',
  'overwrite.cli.url' => 'xxx',
  'overwriteprotocol' => 'https',
  'dbtype' => 'mysql',
  'version' => '15.0.2.0',
  'dbname' => 'xxx',
  'dbhost' => 'xxx',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'logtimezone' => 'Europe/Berlin',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'defaultapp' => 'calendar',
  'allow_user_to_change_display_name' => false,
  'remember_login_cookie_lifetime' => 2592000,
  'loglevel' => 0,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_from_address' => 'nextcloud',
  'mail_domain' => 'xxx',
  'mail_smtphost' => 'xxx',
  'mail_smtpport' => '25',
  'mail_smtpname' => 'xxx',
  'mail_smtppassword' => 'xxx',
  'maintenance' => false,
  'appstore.experimental.enabled' => true,
  'theme' => '',
  'updater.release.channel' => 'stable',
  'debug' => true,
  'integrity.check.disabled' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**
Thunderbird and its Lightning plugin in order to use the NextCloud calendar and tasks.

### Client configuration
**Browser:**
Firefox

**Operating system:**
Windows

**CalDAV-clients:**
Thunderbird

#### Web server error log
Debug entries only

#### Nextcloud log (data/nextcloud.log)
Debug entries only

#### Browser log
When adding a new task:

Put:
BEGIN:VCALENDAR
PRODID:-//Nextcloud Tasks vundefined
BEGIN:VTODO
CREATED:20190131T151854
DTSTAMP:20190131T151854
LAST-MODIFIED:20190131T151854
UID:ykrigl5lqg8
SUMMARY:asddd
PRIORITY:0
PERCENT-COMPLETE:0
X-OC-HIDESUBTASKS:0
END:VTODO
END:VCALENDAR

Get:
Status-Code:
200
Version:HTTP/1.1

Report:
Status-Code:
207
Version:HTTP/1.1

**Comment by raimund-schluessler** [comment]
We need to set the `CLASS` property with the values
PUBLIC
CONFIDENTIAL
PRIVATE
