### ISSUE TITLE
Datestrings from moment not correctly localized

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/tasks#2448]
The dates that moment.js parses are not correctly localized anymore. This happens since the migration to `vite` as a bundler in https://github.com/nextcloud/tasks/pull/2321.

`nextcloud/moment` should normally load the correct localization on its own, which it did when the app was still build with `webpack`.

Since we switched to `vite`, the bundled `moment` version always uses the english locale. Weirdly, when executing `moment` in the javascript console, the correct locale is used (but that might be the global moment from server).

@susnux Do you have any idea what could go wrong with `vite` that the locale does not work anymore?

Example image:
![image](https://github.com/nextcloud/tasks/assets/2496460/f5fa4eb5-3230-4fa6-9fa3-7bf92344c4cf)

**Comment by susnux** [comment]
This seems to be related to tree shaking because the locales are not imported for moment thus they are removed. Fixed this on the nextcloud-moment package. See https://github.com/nextcloud-libraries/nextcloud-moment/pull/781
