### ISSUE TITLE
[Feature Request] show/hide Decks in Tasks Settings

### ISSUE THREAD

**Issue by punkyard** [nextcloud/tasks#2456]
### Is your feature request related to a problem? Please describe.

too many desks in tasks
can't modify desks nor cards nor user details - makes it useless

### Describe the solution you'd like

show//hide desks in tasks settings

### Describe alternatives you've considered

hide desks - no option
find desks in Desk and tasks in Task

### Additional context

thank you for reading

**Comment by raimund-schluessler** [comment]
You are in the wrong repository, both problems belong to the Deck app.

- Disabling showing Deck entries in the Tasks app (or actually any CalDAV client) can be done in the Deck app's settings. Go to Deck app, `Deck settings` -> disable `Show Board in Calendar`.
- Missing editing functionality is a missing feature of the Deck app, which does expose all its entries as read-only. See https://github.com/nextcloud/deck/issues/2399.

**Comment by punkyard** [comment]
ok thanks for the answer
it's funny though, show or hide decks in tasks is an option in another app

if user of a group can use Tasks but can't use Deck, they won't be able to access the option show/hide in task/calendar ..
the decks and cards the rest of the team don't want to show, will show

I hope my english will make sens and will be understandable
thanks fo reading and your fast response

**Comment by raimund-schluessler** [comment]
The Deck app exposes its entries via Nextcloud CalDAV server. The Tasks app ist just a CalDAV client and shows everything that Nextcloud server provides. So the Tasks app has no influence on what is delivered by the server.

Also, if the Deck app is disabled, no entries will be exposed and/or show up in the Tasks app.

**Comment by punkyard** [comment]
thanks for your reply
