### ISSUE TITLE
(1/)2-way synchronize supported task defaults with clients.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [nextcloud/tasks#2469]
### Is your feature request related to a problem? Please describe.

When I set my task defaults via clients like https://github.com/tasks/tasks.git, the defined task defaults are not reflected in the NextCloud server I've added to it, meaning that tasks added via its GUI and this are different. Likewise, task defaults defined in NextCloud are not provided to clients. I believe that this should change, because creating consistent task lists across different software becomes incredibly difficult.

### Describe the solution you'd like

I want those defaults to be synchronized with the clients like the aforementioned, but I also want to provide clients the capability to define task defaults for attributes NCT supports which it can inherit from.

### Describe alternatives you've considered

The current fragmentation of defaults is the sole alternative.

### Additional context

https://github.com/tasks/tasks/issues/2738#issue-2098362663

**Comment by raimund-schluessler** [comment]
I have no idea what your feature request is, honestly. Could you please elaborate.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/nextcloud/tasks/issues/2469#issuecomment-1908220372

@raimund-schluessler, sorry! Added the wrong task description.

**Comment by raimund-schluessler** [comment]
You did not change anything. The description you linked to is just a copy of the issue here.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/nextcloud/tasks/issues/2469#issuecomment-1908225065

@raimund-schluessler, it's not. It uses a similar template, but there are important differences. However, I'll flesh it out if it's not yet enough. Please read the summary I've provided at https://github.com/nextcloud/tasks/issues/2469#issuecomment-1908221304 and give me 15 minutes.

**Comment by raimund-schluessler** [comment]
Which defaults do you talk about? I wouldn't know that we set any default for the tasks or lists we create.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/nextcloud/tasks/issues/2469#issuecomment-1908234363

@raimund-schluessler, when I create a new task at https://wim.nl.tab.digital/apps/tasks/#/calendars/3de72895-d345-4ac4-8eec-1418e857ba7e, the resultant task's attributes are entirely blank. However, this is not true for every other client I've tried, especially the aforementioned. Instead, they allow the user to define a default location, tags, and priorities, for instance. I believe that these defaults should be able to be synchronized between client and server so that there is not significant mismatch between tasks created in client GUIs and server GUIs (NextCloud Tasks).

**Comment by raimund-schluessler** [comment]
Tasks does not support default parameters for new tasks yet. The related issue is #1619.
Implementing a synchronization of said settings between different clients is out of the scope of this app here, since there is no common standard for this. If we implement #1619, the default settings will of course have to saved on the Nextcloud server. But whether another client reads and syncs the settings from there is out of our hand.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/nextcloud/tasks/issues/2469#issuecomment-1922300768

Then shouldn't you close this as "Not planned" rather than "Completed", @raimund-schluessler?

**Comment by raimund-schluessler** [comment]
> > https://github.com/nextcloud/tasks/issues/2469#issuecomment-1922300768
> 
> 
> 
> Then shouldn't you close this as "Not planned" rather than "Completed", @raimund-schluessler?

Is this tiny detail really so important to you that it's worth commenting on (rhetorical question, the answer is obvious)?

And no, the feature is not "Not planned", otherwise I would have to close #1619 as not planned as well. Please ask GitHub to implement a third option that allows me to close issues as "Duplicate".

**Comment by RokeJulianLockhart** [comment]
> https://github.com/nextcloud/tasks/issues/2469#issuecomment-1922402669

Thanks, @raimund-schluessler. That's a good suggestion.
