### ISSUE TITLE
add discussion on task

### ISSUE THREAD

**Issue by punkyard** [nextcloud/tasks#2492]
### Is your feature request related to a problem? Please describe.

discussion in tasks could be useful to teams
it could be useful to link people to a specific task as well

<img width="376" alt="share event by shared users" src="https://github.com/nextcloud/tasks/assets/59349105/93f38cfc-196b-4471-8863-8fb4bc8f9c0b">

### Describe the solution you'd like

add a conversation tab, as in Deck

<img width="340" alt="desk" src="https://github.com/nextcloud/tasks/assets/59349105/f2ea9895-13ab-44ca-84b7-b657a130f96e">

### Additional context

thanks for your concern for this topic

**Comment by raimund-schluessler** [comment]
There is an issue for comments #109 and assigning users #72 already. Closing.
