### ISSUE TITLE
Add the Tasks app to the Nextcloud App Store

### ISSUE THREAD

**Issue by schiessle** [nextcloud/tasks#25]
Would be great to have the Tasks app at the Nextcloud App Store.
=> https://apps.nextcloud.com/

Nextcloud 11 is almost released and it would be really sad if the users of the app would have to disable it because they don't get a new version via the app store.

**Comment by raimund-schluessler** [comment]
Requires https://github.com/nextcloud/app-certificate-requests/pull/34

**Comment by raimund-schluessler** [comment]
I can't upload the app archive from https://github.com/nextcloud/tasks/releases/download/v0.9.4/tasks.tar.gz to apps.nextcloud.com. The appstore gives the error
```
No possible app folder found. App folder must contain only lowercase ASCII characters or underscores
```
although there is only one toplevel folder named ```tasks```.
@LukasReschke or @BernhardPosselt Could you give me a hint what I do wrong?

**Comment by LukasReschke** [comment]
@raimund-schluessler Can you post the signature that you used for uploading?

**Comment by ChristophWurst** [comment]
> although there is only one toplevel folder named tasks.

Apparently it's './tasks' - there's a folder `.` in the archive root.

**Comment by ChristophWurst** [comment]
![bildschirmfoto von 2016-12-14 22-53-42](https://cloud.githubusercontent.com/assets/1374172/21202805/2d68257c-c250-11e6-996e-53d740b23dd0.png)

**Comment by raimund-schluessler** [comment]
Damn, my file manager didn't show me the ```.``` folder. It was created due to a problem with my make file. Thanks a lot for the help @ChristophWurst and @LukasReschke. Now the upload worked flawlessly.

**Comment by raimund-schluessler** [comment]
The Tasks app is in the Nextcloud appstore now. Installing the app via appstore worked without problems for me

**Comment by BernhardPosselt** [comment]
Validation saved the day :D imagine the fucked up bug reports from users xD

**Comment by nickvergessen** [comment]
Thanks, works like charm!
