### ISSUE TITLE
Three dots menu button on task details sidebar always looks selected

### ISSUE THREAD

**Issue by RayBB** [nextcloud/tasks#2506]
### Steps to reproduce

Could be a nice small CSS bug for someone to fix if it is confirmed to be a bug and not intended.

1. Click on any task
2. See the three dots on the right menu bar

https://github.com/nextcloud/tasks/assets/921217/f3e291bb-f706-41a8-b3ee-7cf47b37e820

### Expected behavior

Three dots are not highlighted unless you hover

### Actual behaviour

They are always highlight and the highlighting lessens when you over.

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by raimund-schluessler** [comment]
This style comes from the nextcloud components, and it is a design choice, not a bug. But I don't know whether this design could be reconsidered or not, so please report this in https://github.com/nextcloud-libraries/nextcloud-vue/ (I cannot transfer the issue there, since it is a different org).

**Comment by RayBB** [comment]
Thanks for the info. I created the issue there. https://github.com/nextcloud-libraries/nextcloud-vue/issues/5363
