### ISSUE TITLE
smart add

### ISSUE THREAD

**Issue by meonkeys** [nextcloud/tasks#2527]
### Is your feature request related to a problem? Please describe.

Entering tasks in the web UI takes many clicks.

### Describe the solution you'd like

Implement "smart add", borrowing UI/UX concepts from https://www.rememberthemilk.com/help/

**Comment by raimund-schluessler** [comment]
Please describe your feature requested in more detail. A generic help link to another todo app is not very helpful, especially since I couldn't find anything related to "smart add" there.

**Comment by meonkeys** [comment]
Sorry about that, I broke the link. Here's the correct link: https://www.rememberthemilk.com/help/?ctx=basics.smartadd.howdoiuse

I'm happy to draw up a more detailed plan as well. The basic idea is to enhance the "add a task" text input field so fewer subsequent actions are required to set due date, etc. after adding a task. For example: using special characters to trigger property entry or maybe detecting time/date words (`buy milk tomorrow` would add the task `buy milk`, due tomorrow).

Here's more detail on what I'm suggesting for the first iteration of smart add:

* detect certain characters, translate to task properties
    * `^` (caret): due date entry
    * `#` (octothorpe): list/tag entry

These characters trigger a dropdown, similar to Nextcloud's existing "smart picker".

That alone would save a bunch of clicks. What do you think?

Auto-detection of dates and times might also be nice, but it's a bit more "magic" (maybe too "magic", if you ask me):

* detect date/time strings and convert to a due date
    * `today` = due today
    * `tomorrow` = due tomorrow
    * `next friday`, `1pm`, `April 12`, etc.

So I'd lean toward just doing the special character detection for a first iteration.

**Comment by raimund-schluessler** [comment]
Thanks a lot for the detailed explanation. That clears things up.

Your feature request was already proposed and is tracked in https://github.com/nextcloud/tasks/issues/1958.
The feature to add tags with `#` was recently implemented in https://github.com/nextcloud/tasks/pull/2425 and will be release with version v0.16.0.
