### ISSUE TITLE
Support selecting multiple tasks simultaneously for bulk actions.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [nextcloud/tasks#2539]
### Is your feature request related to a problem? Please describe.

I'm unable to delete or apply tags to multiple tasks simultaneously at https://wim.nl.tab.digital/apps/tasks/#/collections/all/tasks/.

### Describe the solution you'd like

Implement checkboxes (and the `Control`+`PrimaryMouseButton` binding) to allow the user to select multiple tasks to perform bulk actions upon.

### Describe alternatives you've considered

The current implementation of solely individual actions.

**Comment by raimund-schluessler** [comment]
Duplicate of https://github.com/nextcloud/tasks/issues/875.
