### ISSUE TITLE
Show all subtasks at once

### ISSUE THREAD

**Issue by NextBlaubeere** [nextcloud/tasks#2548]
### Is your feature request related to a problem? Please describe.

It would often be great to view all tasks with their subtasks at once.

### Describe the solution you'd like

Support for more than one expanded task would be great.
A button or some sort of option to expand all tasks at once automatically would be even better.

**Comment by raimund-schluessler** [comment]
There is a button to expand them in the right action menu of the respective task.

**Comment by NextBlaubeere** [comment]
Oh wow, this has a different behaviour than clicking on the tasks. I am sorry!

**Comment by raimund-schluessler** [comment]
No worries.
