### ISSUE TITLE
Completed Tasks are not listed

### ISSUE THREAD

**Issue by egal88** [nextcloud/tasks#256]
### Steps to reproduce
1. Configure a new lightning calendar to synchronize with nextcloud using caldav
2. Create a new task for this calendar
3. mark this task as completed

### Expected behaviour
The completed task should be listed in your tasks app under completed tasks

![2019-02-06 13_35_17-tasks](https://user-images.githubusercontent.com/4114490/52341903-3184a580-2a14-11e9-8307-dbe9d3b749f2.png)

### Actual behaviour
This is not the case.
No Tasks that were manually marked as completed using Thunderbirds Addon Lightning will ever been listed in the tasks app.

### Server configuration

**Operating system**: Debian

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.1

**Nextcloud version: 15.0.2

**Tasks version:** 0.9.8

**Updated from an older Nextcloud or fresh install:** Updated from an older Nextcloud

**List of activated apps:**

```
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_retention: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 65.0 x64

**Operating system:** Windows 10 Pro 1809 x64

**CalDAV-clients:** Thunderbird Lightning 6.2.5 (Thunderbird 60.5.0)

**Comment by raimund-schluessler** [comment]
This is by design. We don’t load any completed task into the app by default, because loading all completed tasks slows down the app a lot if there are many completed tasks. You can load completed tasks by selecting the calendar the tasks belong to in the left sidebar and click on “Load completed tasks” in the main view.

We could add this button to the completed list though to make it more obvious. I will create a separate issue for that.

**Comment by egal88** [comment]
> This is by design. We don’t load any completed task into the app by default, because loading all completed tasks slows down the app a lot if there are many completed tasks. You can load completed tasks by selecting the calendar the tasks belong to in the left sidebar and click on “Load completed tasks” in the main view.

Thanks for letting me know.
I did not realize that I had to first klick on a specific calendar.
 
> We could add this button to the completed list though to make it more obvious. I will create a separate issue for that.

I think this would be helpful because it's quite irritating that you only get a blank window when klicking on "completed tasks"

**Comment by RokeJulianLockhart** [comment]
> https://github.com/nextcloud/tasks/issues/256#issuecomment-461180887

@raimund-schluessler, did you ever create the issue for that?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/nextcloud/tasks/issues/256#issuecomment-1879824721

https://github.com/nextcloud/tasks/issues/2173#issuecomment-1366004746
