### ISSUE TITLE
Task app shows only blank page starting from 14.0

### ISSUE THREAD

**Issue by SBGit-2019** [nextcloud/tasks#2571]
### Steps to reproduce

1. Upgrade task app from 13.x to anything 14-16 
2.
3.

### Expected behavior

Going to the "task" menu item just shows an empty page. Setup is a quite standard docker configuration. It works up to version 13.x. From 14.0 the page shows no content at all and no interaction with the task app is thus possible.

Calendar , contacts, files etc work.

I noticed the behaviour with an existing installation but then made a completely fresh v29 installation. It appears there just the same.

### Actual behaviour

Only an empty page is shown. No interaction possible

### Tasks app version

16

### CalDAV-clients used

nextclout web interface

### Browser

Firefox and Opera tested

### Client operating system

Windows 10

### Server operating system

Docker on ubuntu 24

### Web server

Nginx

### Database engine version

PostgreSQL

### PHP engine version

PHP 8.2

### Nextcloud version

29

### Updated from an older installed version or fresh install

Fresh install

### List of activated apps

```Text
- activity: 2.21.1
  - calendar: 4.7.3
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_downloadlimit: 2.0.0
  - files_external: 1.21.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - mail: 3.6.0
  - nextcloud_announcements: 1.18.0
  - notes: 4.10.0
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - support: 1.12.0
  - survey_client: 1.17.0
  - systemtags: 1.19.0
  - tasks: 0.16.0
  - text: 3.10.0
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - updatenotification: 1.19.1
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
Disabled:
  - admin_audit: 1.19.0
  - bruteforcesettings: 2.9.0
  - encryption: 2.17.0
  - forms: 4.2.3 (installed 4.2.3)
  - suspicious_login: 7.0.0
  - twofactor_totp: 11.0.0-dev
  - user_ldap: 1.20.0
```

### Nextcloud configuration

```Text
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "upgrade.disable-web": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.2.85:8080"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "29.0.0.19",
        "overwrite.cli.url": "http:\/\/192.168.2.85:8080",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "app_install_overwrite": [
            "tasks"
        ],
        "maintenance": false
    }
}
```

### Web server error log

```Text
app-1    | 172.29.0.6 -  12/May/2024:08:29:17 +0000 "GET /index.php" 200
web-1    | 192.168.2.50 - - [12/May/2024:08:29:17 +0000] "GET /apps/tasks/ HTTP/1.1" 200 11145 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0" "-"
app-1    | 172.29.0.6 -  12/May/2024:08:29:17 +0000 "GET /index.php" 404
web-1    | 192.168.2.50 - - [12/May/2024:08:29:18 +0000] "GET /apps/firstrunwizard/js/firstrunwizard-activate.mjs?v=db17208b-0 HTTP/1.1" 404 4999 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0" "-"
app-1    | 172.29.0.6 -  12/May/2024:08:29:17 +0000 "GET /index.php" 404
web-1    | 192.168.2.50 - - [12/May/2024:08:29:18 +0000] "GET /apps/firstrunwizard/js/firstrunwizard-about.mjs?v=db17208b-0 HTTP/1.1" 404 4999 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0" "-"
app-1    | 172.29.0.6 -  12/May/2024:08:29:17 +0000 "GET /index.php" 404
web-1    | 192.168.2.50 - - [12/May/2024:08:29:18 +0000] "GET /custom_apps/tasks/js/tasks-main.mjs?v=db17208b-0 HTTP/1.1" 404 5000 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0" "-"
app-1    | 172.29.0.6 -  12/May/2024:08:29:18 +0000 "GET /ocs/v2.php" 200
web-1    | 192.168.2.50 - - [12/May/2024:08:29:18 +0000] "GET /ocs/v2.php/search/providers?from=%2Fapps%2Ftasks%2F HTTP/1.1" 200 590 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0" "-"
app-1    | 172.29.0.6 -  12/May/2024:08:29:18 +0000 "POST /index.php" 200
web-1    | 192.168.2.50 - - [12/May/2024:08:29:18 +0000] "POST /contactsmenu/contacts HTTP/1.1" 200 53 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0" "-"
app-1    | 172.29.0.6 -  12/May/2024:08:29:18 +0000 "GET /ocs/v2.php" 200
web-1    | 192.168.2.50 - - [12/May/2024:08:29:18 +0000] "GET /ocs/v2.php/apps/user_status/api/v1/user_status HTTP/1.1" 200 149 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0" "-"
app-1    | 172.29.0.6 -  12/May/2024:08:29:18 +0000 "PUT /ocs/v2.php" 200
web-1    | 192.168.2.50 - - [12/May/2024:08:29:18 +0000] "PUT /ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json HTTP/1.1" 200 149 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0" "-"
app-1    | 172.29.0.6 -  12/May/2024:08:29:18 +0000 "GET /ocs/v2.php" 200
web-1    | 192.168.2.50 - - [12/May/2024:08:29:18 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 676 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0" "-"
```

**Comment by drulum** [comment]
Just adding that I'm experiencing the same problem. I've just updated to Nextcloud 29. Tasks is enabled, but blank page and a constant "loading" indication on the home page widget.

**Comment by raimund-schluessler** [comment]
Please try to clear the caches, especially of your browser. Or try it with incognito mode (where the cache is not used).

**Comment by raimund-schluessler** [comment]
@SBGit-2019 please provide the server logs.

**Comment by SBGit-2019** [comment]
Cache or incognito mode do not help. 

Which other logs do you need, that is how do I get them?

**Comment by timparker14** [comment]
I had this issue after upgrading to 28.0.5. Adding mjs to application/javascript in the nginx mime.types file resolved it for me. Still ok with 29.0.0.

**Comment by raimund-schluessler** [comment]
> I had this issue after upgrading to 28.0.5. Adding mjs to application/javascript in the nginx mime.types file resolved it for me. Still ok with 29.0.0.

That is very likely the issue and explains why the `*.mjs` files fail to load.

See the nextcloud documentation:

https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html#nextcloud-in-the-webroot-of-nginx

**Comment by SBGit-2019** [comment]
ok I found the issue with the nginx. conf. 

For reference to others with the same problem, you need the mime.types

```
    types {
        text/javascript js mjs;
	application/wasm wasm;
    }
```

and the correct location

```
    # Serve static files
    location ~ \.(?:css|js|mjs|svg|gif|png|jpg|ico|wasm|tflite|map|ogg|flac)$ {
        try_files $uri /index.php$request_uri;
        # HTTP response headers borrowed from Nextcloud `.htaccess`
        add_header Cache-Control                     "public, max-age=15778463$asset_immutable";
        add_header Referrer-Policy                   "no-referrer"       always;
        add_header X-Content-Type-Options            "nosniff"           always;
        add_header X-Frame-Options                   "SAMEORIGIN"        always;
        add_header X-Permitted-Cross-Domain-Policies "none"              always;
        add_header X-Robots-Tag                      "noindex, nofollow" always;
        add_header X-XSS-Protection                  "1; mode=block"     always;
        access_log off;     # Optional: Don't log access to assets
    }
```

I mistyped the latter.
   
Thank you all for pointing me in the end into the right direction.

**Comment by Oclair** [comment]
> ok I found the issue with the nginx. conf.
> 
> For reference to others with the same problem, you need the mime.types
> 
> ```
>     types {
>         text/javascript js mjs;
> 	application/wasm wasm;
>     }
> ```
> 
> and the correct location
> 
> ```
>     # Serve static files
>     location ~ \.(?:css|js|mjs|svg|gif|png|jpg|ico|wasm|tflite|map|ogg|flac)$ {
>         try_files $uri /index.php$request_uri;
>         # HTTP response headers borrowed from Nextcloud `.htaccess`
>         add_header Cache-Control                     "public, max-age=15778463$asset_immutable";
>         add_header Referrer-Policy                   "no-referrer"       always;
>         add_header X-Content-Type-Options            "nosniff"           always;
>         add_header X-Frame-Options                   "SAMEORIGIN"        always;
>         add_header X-Permitted-Cross-Domain-Policies "none"              always;
>         add_header X-Robots-Tag                      "noindex, nofollow" always;
>         add_header X-XSS-Protection                  "1; mode=block"     always;
>         access_log off;     # Optional: Don't log access to assets
>     }
> ```
> 
> I mistyped the latter.
> 
> Thank you all for pointing me in the end into the right direction.

Why is editing nginx.conf required? 
isn't this a workaround?
Seriously this is not how to go about updates Nextcloud devs....

**Comment by raimund-schluessler** [comment]
> > ok I found the issue with the nginx. conf.
> > 
> > For reference to others with the same problem, you need the mime.types
> > 
> > ```
> >     types {
> >         text/javascript js mjs;
> > 	application/wasm wasm;
> >     }
> > ```
> > 
> > and the correct location
> > 
> > ```
> >     # Serve static files
> >     location ~ \.(?:css|js|mjs|svg|gif|png|jpg|ico|wasm|tflite|map|ogg|flac)$ {
> >         try_files $uri /index.php$request_uri;
> >         # HTTP response headers borrowed from Nextcloud `.htaccess`
> >         add_header Cache-Control                     "public, max-age=15778463$asset_immutable";
> >         add_header Referrer-Policy                   "no-referrer"       always;
> >         add_header X-Content-Type-Options            "nosniff"           always;
> >         add_header X-Frame-Options                   "SAMEORIGIN"        always;
> >         add_header X-Permitted-Cross-Domain-Policies "none"              always;
> >         add_header X-Robots-Tag                      "noindex, nofollow" always;
> >         add_header X-XSS-Protection                  "1; mode=block"     always;
> >         access_log off;     # Optional: Don't log access to assets
> >     }
> > ```
> > 
> > I mistyped the latter.
> > 
> > Thank you all for pointing me in the end into the right direction.
> 
> Why is editing nginx.conf required? 
> isn't this a workaround?
> Seriously this is not how to go about updates Nextcloud devs....

Major updates can be breaking or need configuration changes to get new features working (as it was the case here). You need to check the release notes and migration guide when upgrading. This feature was introduced into server some versions ago already and is documented in the official documentation. The feature was only used now in the Tasks app to give people time to adapt. If this doesn't suite you, please speak up in the server repository. And if keeping up with server maintenance is too stressful, you might want to consider using the Docker version where this is handled, or even a managed instance.

**Comment by Oclair** [comment]
> > > ok I found the issue with the nginx. conf.
> > > For reference to others with the same problem, you need the mime.types
> > > ```
> > >     types {
> > >         text/javascript js mjs;
> > > 	application/wasm wasm;
> > >     }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and the correct location
> > > ```
> > >     # Serve static files
> > >     location ~ \.(?:css|js|mjs|svg|gif|png|jpg|ico|wasm|tflite|map|ogg|flac)$ {
> > >         try_files $uri /index.php$request_uri;
> > >         # HTTP response headers borrowed from Nextcloud `.htaccess`
> > >         add_header Cache-Control                     "public, max-age=15778463$asset_immutable";
> > >         add_header Referrer-Policy                   "no-referrer"       always;
> > >         add_header X-Content-Type-Options            "nosniff"           always;
> > >         add_header X-Frame-Options                   "SAMEORIGIN"        always;
> > >         add_header X-Permitted-Cross-Domain-Policies "none"              always;
> > >         add_header X-Robots-Tag                      "noindex, nofollow" always;
> > >         add_header X-XSS-Protection                  "1; mode=block"     always;
> > >         access_log off;     # Optional: Don't log access to assets
> > >     }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I mistyped the latter.
> > > Thank you all for pointing me in the end into the right direction.
> > 
> > 
> > Why is editing nginx.conf required?
> > isn't this a workaround?
> > Seriously this is not how to go about updates Nextcloud devs....
> 
> Major updates can be breaking or need configuration changes to get new features working (as it was the case here). You need to check the release notes and migration guide when upgrading. This feature was introduced into server some versions ago already and is documented in the official documentation. The feature was only used now in the Tasks app to give people time to adapt. If this doesn't suite you, please speak up in the server repository. And if keeping up with server maintenance is too stressful, you might want to consider using the Docker version where this is handled, or even a managed instance.

or just...
![Image](https://github.com/user-attachments/assets/45b5f4c2-2cba-4275-8d94-d4c1c0eebb17)

**Comment by Oclair** [comment]
The problem is that nginx is not the dominant http server, in many cases things are apache centric, the docs for nginx config changes often and many nix distros have their own way of setting up nginx such as moving mime types into an included file.  I am not really sure how to suggest things to work better except for creating something like a file located at an url such as https://github.com/nextcloud/UPDATING


`This file documents some of the problems you may encounter when upgrading
your ports.  We try our best to minimize these disruptions, but sometimes
they are unavoidable.

You should get into the habit of checking this file for changes each time
you update your nextcloud instance.

20241004:
  AFFECTS: users of 
  AUTHOR: 
 DESCRIPTION:  

 For installation instructions please refer :
  https://sourceforge.net/sdfsdf
  https://sourceforge.net/sdfsdf/wiki


`
