### ISSUE TITLE
Link in navbar doesn't lead to tasks

### ISSUE THREAD

**Issue by D3nnis3n** [nextcloud/tasks#2573]
### Steps to reproduce

Open Nextcloud Dashboard
Click Tasks menu button
See page just refreshes (link is always to the page you currently are at instead of /tasks)

### Expected behavior

Open Nextcloud Dashboard
Click Tasks menu button
Actually go to the Tasks page

### Actual behaviour

Open Nextcloud Dashboard
Click Tasks menu button
See page just refreshes (link is always to the page you currently are at instead of /tasks)

### Tasks app version

0.16.0

### Browser

Chrome

### Server operating system

Ubuntu 22.04

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

Other

### Nextcloud version

29

### Updated from an older installed version or fresh install

Updated from an older version

### Additional info

Same is the case for Passwords, Polls and Tasks app, see for example here: https://github.com/marius-wieschollek/passwords/issues/656

All other apps work correctly. (I reported the bug to each app)

**Comment by raimund-schluessler** [comment]
I cannot reproduce this issue.

if this only happens in the dashboard app, please report it to the server repository.

**Comment by D3nnis3n** [comment]
Thanks for letting me know - it for some reason only happens for the four apps I noted, but seemingly is not related to them. I do have multiple other (non-official) apps that work fine, though. So I have no idea what could be the problem. All apps do still work fully when just manually opening their link through the browser.

It does happen in every app, though. Instead of the link having the name of the app the link should lead to in it, it has the name of the current app in it. But only for the four apps mentioned.

**Comment by baltaner** [comment]
@raimund-schluessler
Hi,
I have the same problem with the link to tasks in navigation menu - but I think the problem is fulltextsearch (for me)
[https://github.com/nextcloud/fulltextsearch/issues/842](https://github.com/nextcloud/fulltextsearch/issues/842)
