### ISSUE TITLE
Entire list never loads

### ISSUE THREAD

**Issue by benmordecai** [nextcloud/tasks#2581]
### Steps to reproduce

1. Navigate to the tasks app from nextcloud dashboard from the web.

### Expected behavior

Load the task list

### Actual behaviour

Just a blue background. 

CalDAV syncing with tasks still works with 3rd party apps. Problem persists on both Brave and Firefox.
![image](https://github.com/nextcloud/tasks/assets/2068192/452a0b2d-0812-4482-a51c-c8727fe91523)

### Tasks app version

0.16.0

### CalDAV-clients used

Web

### Browser

Brave

### Client operating system

Arch Linux

### Server operating system

Debian 12

### Web server

Nginx

### Database engine version

MariaDB

### PHP engine version

None

### Nextcloud version

29.0

### Updated from an older installed version or fresh install

None

**Comment by raimund-schluessler** [comment]
That is probably a misconfiguration of your server, this #2571.

If this doesn't help, please provide logs.

**Comment by benmordecai** [comment]
This did help. I had to add `text/javascript js mjs;` to my `mime.types`. Thank you
