### ISSUE TITLE
Not possible to choose the time when the task to be competed after the last update

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/tasks#2585]
### Steps to reproduce

1. Create new task
2. Go to Details
3. Unselect whole day
4. Observe that it is not possible to choose the time when the task to be finalised
![image](https://github.com/nextcloud/tasks/assets/5199030/89541674-2fa7-4e49-9b8a-fd586cb370b8)

### Expected behavior

If the task covers not the whole day the time deadline to be shown. 

### Actual behaviour

After the last update the time is not shown.

### Tasks app version

0.16.0

### CalDAV-clients used

web

### Server operating system

Ubuntu 22.04

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.2

### Nextcloud version

28.0.5

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by raimund-schluessler** [comment]
Click on the date to see the time input. If this is not what you are looking for, please provide a screenshot in English, so I can read what the GUI says. Thanks.

**Comment by raimund-schluessler** [comment]
I can reproduce the issue. Will look into it.

**Comment by nmsw** [comment]
I can reproduce the issue as well. I can select a time if I have both a start and due date selected. If only the due date is selected I cannot set the time.

**Comment by moboter** [comment]
I habe the same problem
store-DE2z1cMA.mjs:2 TypeError: Cannot read properties of null (reading 'getAllSubcomponents')
    at Proxy._ensureCoverage (store-DE2z1cMA.mjs:2:1018968)
    at Proxy.utcOffset (store-DE2z1cMA.mjs:2:1017685)
    at Proxy.utcOffset (store-DE2z1cMA.mjs:2:1026985)
    at Proxy.toUnixTime (store-DE2z1cMA.mjs:2:1028847)
    at Proxy.toJSDate (store-DE2z1cMA.mjs:2:1027628)
    at set allDay (store-DE2z1cMA.mjs:2:1072444)
    at Reflect.set (<anonymous>)
    at VD.set (store-DE2z1cMA.mjs:2:8598)
    at lu.toggleAllDay (store-DE2z1cMA.mjs:2:1309816)
    at store-DE2z1cMA.mjs:2:690671

**Comment by moboter** [comment]
https://github.com/nextcloud/tasks/assets/87427090/7c8bf3b6-fce6-4c7d-bb68-28f069dafd10

For a better understanding how you possibly could bypass the problem when you create a new task

**Comment by ostasevych** [comment]
> https://github.com/nextcloud/tasks/assets/87427090/7c8bf3b6-fce6-4c7d-bb68-28f069dafd10
> 
> For a better understanding how you possibly could bypass the problem when you create a new task
> Please note that there is also a problem with the start and due time There are always 2 Hours deducted so it defaults to UTC

Or using mobile app, where it works as intended.

**Comment by melroy89** [comment]
Exactly my problem, once I clicked "All day", you can only select a date which is fine. However, when unselecting "All day" I expect to select a time again. But I can't....

**Comment by Herbert-Sg** [comment]
I have the same problem. When I add a time in the mobile app, it shows up in the desktop app. But I can't add a time on the desktop if it doesn't already have a time before
![Nextcloud Task 2](https://github.com/user-attachments/assets/37510602-afdd-48fe-a0d0-09a37098335f)
![Nextcloud Task 1](https://github.com/user-attachments/assets/a9b9bc5b-fdb6-4406-9df8-52a44866fe84)
.

**Comment by raimund-schluessler** [comment]
I packed a version which hopefully has this issue fixed: [tasks.tar.gz](https://github.com/user-attachments/files/16501909/tasks.tar.gz)

It would be very helpful if someone could test it to confirm the issue being fixed.

**Comment by ostasevych** [comment]
> I packed a version which hopefully has this issue fixed: [tasks.tar.gz](https://github.com/user-attachments/files/16501909/tasks.tar.gz)
> 
> It would be very helpful if someone could test it to confirm the issue being fixed.

Hi! It seems that picking a time works fine. Thanks!

![Знімок екрана з 2024-08-05 23-26-01](https://github.com/user-attachments/assets/2c37bddf-316f-420e-a50f-39a0c51e39f7)

**Comment by raimund-schluessler** [comment]
> UPD: However the time of the created task (20:25) is not relevant: it is shown in UTC, but not accorting to the local time zone EEST = +03:00 GMT.

Yes, I noticed this as well. Should be fixed by #2638. Will be included in v0.16.1. Thanks for testing!

**Comment by ostasevych** [comment]
> > UPD: However the time of the created task (20:25) is not relevant: it is shown in UTC, but not accorting to the local time zone EEST = +03:00 GMT.
> 
> Yes, I noticed this as well. Should be fixed by #2638. Will be included in v0.16.1. Thanks for testing!

meanwhile, trash bin still is not working...
