### ISSUE TITLE
Sharing tasks

### ISSUE THREAD

**Issue by romaadereyko** [nextcloud/tasks#2587]
### Is your feature request related to a problem? Please describe.

No, not a problem, but real feature

### Describe the solution you'd like

Sharing tasks in UI with other users/groups of Nextcloud Instance

### Describe alternatives you've considered

Haven't

### Additional context

No

**Comment by raimund-schluessler** [comment]
Sharing a single task is technical not possible, but you can share a complete list with other users.

**Comment by PeonyThePeon** [comment]
> Sharing a single task is technical not possible, but you can share a complete list with other users.

That is a true statement.

However, this is not necessarily ideal. What if the user wants to share a specific task, but not an entire list?
