### ISSUE TITLE
Add List does not show error

### ISSUE THREAD

**Issue by 0verEngineer** [nextcloud/tasks#2597]
### Steps to reproduce

1. Create a lot of new lists in a short time
2. For me the 11th one will not be created
3. check the network log of the browser

### Expected behavior

Creating lists should always work or the app should show an error

### Actual behaviour

It silently fails

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

### Web server error log

```Text
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:o="http://owncloud.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\TooManyRequests</s:exception>
  <s:message>Too many calendars created</s:message>
  <o:hint xmlns:o="o:">too many requests</o:hint>
</d:error>
```

**Comment by Ripsnapper** [comment]
This happens because of the rate limit of the dav backend.  In case you want to change the rate limits that is explained here: https://docs.nextcloud.com/server/latest/admin_manual/groupware/calendar.html#rate-limits

I added an error dialog in https://github.com/nextcloud/tasks/pull/2607
