### ISSUE TITLE
Sync very slow with a lot of Lists with a lot of Tasks

### ISSUE THREAD

**Issue by 0verEngineer** [nextcloud/tasks#2598]
### Steps to reproduce

1. Have a lot of lists with a lot of tasks

### Expected behavior

The sync should be fast

### Actual behaviour

The sync is slow and it causes the Task.org app synced via Davx5 to be very slow and buggy, here is the Issue i created on Tasks.org: https://github.com/tasks/tasks/issues/2856

### Tasks app version

0.16.0

### CalDAV-clients used

DAVx5

### Server operating system

Docker

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

28.0.5

### Updated from an older installed version or fresh install

None

### Additional info

I have 21 Lists with 547 open tasks (sum of all lists) and i don't know how much closed ones, i would say 3000+ because i use this app combo since a few years now. It was always fast and i don't know when it became slow but last summer (2023) it was still fast, so it should be sometime in fall - winter 2023.

I don't know if this app is the problem and i don't know how to find out where the problem is, so any ideas how to find out are highly appreciated.

**Comment by raimund-schluessler** [comment]
Please report this in the server repository. The Tasks app is just a client itself and not involved in the sync process between the CalDAV server built into Nextcloud server and the Tasks.org client you use.

**Comment by 0verEngineer** [comment]
@raimund-schluessler Oh sorry i did not know this, do you mean the nextcloud server?

**Comment by raimund-schluessler** [comment]
Yes, here please https://github.com/nextcloud/server
