### ISSUE TITLE
[Bug]: Notes won't open in tasks app

### ISSUE THREAD

**Issue by venator42** [nextcloud/tasks#2610]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After updating from 29.0.2 to 29.0.3 the tab 'notes' doesn't open anymore. The tab 'details' stays open.

Interestingly, the bug changes when I change the language from german to english (my guess is that the german words are longer)

In german the tab is not visible. In english the tab is almost 50/50 with the details tab. Generally, the tab becomes a bit visible if I resize the windows (make it wider)

I tested this with Firefox and Chromium and in both browsers the bug is the same.

### Steps to reproduce

1. Go to tasks app and click on a task
2. Click on 'notes'

### Expected behavior

The tab with notes should open.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by raimund-schluessler** [comment]
Which version of Tasks do you use?

**Comment by venator42** [comment]
The version of Tasks is 0.16.0

**Comment by raimund-schluessler** [comment]
I cannot reproduce this issue. Nextcloud server 29.0.3 and Tasks 0.16.0 shows the notes tab just fine. Could you try to clear the caches of your browser?
Please also post a screenshot of the issue.

**Comment by venator42** [comment]
![nextcloud_tasks_notes_bug](https://github.com/nextcloud/tasks/assets/126705427/11470b99-f50a-45b1-bc07-927fd8f7395c)

Clearing the browser cache does not fix the problem unfortunately. I can observe this behavior on different browser / devices /users. The problem is occuring in the two nextcloud instances I manage.

**Comment by raimund-schluessler** [comment]
That is basically impossible to debug for me. It most likely is some CSS rule interfering with the layout. It could be custom CSS you added, or any other (maybe uncommong) app. You will have to take a look yourself with the site inspector of your browser.

If it is an option for you, you could provide a test account on one of your servers showing the issue, so I can have a look. But that is up to you.

**Comment by venator42** [comment]
I did some quick testing with developer tools in firefox and found out the following:

If I uncheck `display: flex` from `.app-sidebar .app-sidebar-tab, .event-popover .event-popover__inner .app-sidebar-tab` the behavior is just as expected.

The above mentioned CSS classes are from `app-sidebar.scss:56` according to Firefox Devtools.

I will try to update some apps where an update is available.

**Comment by venator42** [comment]
Solved. After updating Deck, Calendar and Talk (doesnt know which one did the trick 😕) the CSS is fixed.
