### ISSUE TITLE
Web UI does not show

### ISSUE THREAD

**Issue by hegGK** [nextcloud/tasks#2622]
### Steps to reproduce

1. click on tasks icon
2.
3.

### Expected behavior

tasks ui displayed in browser

### Actual behaviour

nothing, i.e. redraw of current page

### Tasks app version

0.16.0

### Browser

Chrome  126.0.6478.128 

### Client operating system

W11

### Server operating system

Betriebssystem: Linux 4.18.0-477.21.1.el8_8.x86_64 x86_64  Prozessor: AMD EPYC 7302P 16-Core Processor (4 cores)  Speicher: 15.64 GB

### Web server

None

### Database engine version

MySQL

### PHP engine version

PHP 8.2

### Nextcloud version

Nextcloud Hub 8 (29.0.3)

### Updated from an older installed version or fresh install

Updated from an older version

### Browser log

```Text
bootstrap:19 Proxying an event bus of version 3.3.1 with 1.3.0
t @ index.es.js:2337
2089 @ index.es.js:3314
r @ bootstrap:19
1894 @ requesttoken.js:11
r @ bootstrap:19
2200 @ index.js:25
r @ bootstrap:19
4820 @ index.js:14
r @ bootstrap:19
(anonymous) @ filelist.js?v=b0ca0085-60:1
(anonymous) @ filelist.js?v=b0ca0085-60:1
(anonymous) @ filelist.js?v=b0ca0085-60:1
Show 5 more frames
Show less
session-heartbeat.js:103 session heartbeat polling started
```

### Additional info

Hosted Nextcloud, no access to command line.
Problems occured after last update of Nextcloud server core to 29.03.

PHP:
Version: 8.2.21
Speicherlimit: 2 GB
Maximale Ausführungszeit: 3600
Maximale Größe zum Hochladen: 2 GB
OPcache-Revalidierungshäufigkeit: 1
Erweiterungen: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, intl, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, xmlreader, zip, apcu, igbinary, imagick, msgpack, smbclient, mysql, redis, libsmbclient, Zend OPcache

MySQL:
Art: mysql
Version: 10.3.39
Größe: 1,2 GB

**Comment by Hullayo** [comment]
I also encountered the same problem. When I opened the task tag, nothing was displayed.
![Uploading 20240722103704.png…]()

**Comment by viaregio** [comment]
Me too. The log is showing many entries with the following content:

``` 
[no app in context] Information: Unable to generate a URL for the named route "tasks.page.index" as such route does not exist.
	GET /apps/logreader/api/poll?lastReqId=MlgWHfv9k8wigIpsaA3I
	von 192.168.2.11 von admin um 22.07.2024, 09:20:46

```

**Comment by hegGK** [comment]
Thats true for me also, but also for other apps (raw log entries):
`{"reqId":"Zp4MzQTO1l5sodriOGmqXQAAAJY","level":1,"time":"2024-07-22T07:39:57+00:00","remoteAddr":"89.104.17.157","user":"admin","app":"no app in context","method":"GET","url":"/index.php/apps/logreader/api/poll?lastReqId=Zp4Mw3bR9m6u8273%40F9goAAAAMs","message":"Unable to generate a URL for the named route \"tables.page.index\" as such route does not exist.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36","version":"29.0.3.4","exception":{"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"tables.page.index\" as such route does not exist.","Code":0,"Trace":[{"file":"/var/www/html/lib/private/Route/Router.php","line":410,"function":"generate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->","args":["tables.page.index",[],1]},{"file":"/var/www/html/lib/private/Route/CachingRouter.php","line":65,"function":"generate","class":"OC\\Route\\Router","type":"->","args":["tables.page.index",[],false]},{"file":"/var/www/html/lib/private/URLGenerator.php","line":103,"function":"generate","class":"OC\\Route\\CachingRouter","type":"->","args":["tables.page.index",[]]},{"file":"/var/www/html/lib/private/NavigationManager.php","line":371,"function":"linkToRoute","class":"OC\\URLGenerator","type":"->","args":["tables.page.index"]},{"file":"/var/www/html/lib/private/NavigationManager.php","line":97,"function":"init","class":"OC\\NavigationManager","type":"->","args":[]},{"file":"/var/www/html/apps/fulltextsearch/lib/AppInfo/Application.php","line":125,"function":"add","class":"OC\\NavigationManager","type":"->","args":[["fulltextsearch",5,"/index.php/apps/fulltextsearch/","/apps/fulltextsearch/img/fulltextsearch.svg","Search"]]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/FunctionInjector.php","line":45,"function":"registerNavigation","class":"OCA\\FullTextSearch\\AppInfo\\Application","type":"->","args":[["OC\\Server"]]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/BootContext.php","line":50,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\FunctionInjector","type":"->","args":[["Closure"]]},{"file":"/var/www/html/apps/fulltextsearch/lib/AppInfo/Application.php","line":88,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\BootContext","type":"->","args":[["Closure"]]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":200,"function":"boot","class":"OCA\\FullTextSearch\\AppInfo\\Application","type":"->","args":[["OC\\AppFramework\\Bootstrap\\BootContext"]]},{"file":"/var/www/html/lib/private/App/AppManager.php","line":437,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":["fulltextsearch"]},{"file":"/var/www/html/lib/private/App/AppManager.php","line":216,"function":"loadApp","class":"OC\\App\\AppManager","type":"->","args":["fulltextsearch"]},{"file":"/var/www/html/lib/private/legacy/OC_App.php","line":128,"function":"loadApps","class":"OC\\App\\AppManager","type":"->","args":[[]]},{"file":"/var/www/html/lib/base.php","line":1030,"function":"loadApps","class":"OC_App","type":"::","args":[]},{"file":"/var/www/html/index.php","line":49,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/3rdparty/symfony/routing/Generator/UrlGenerator.php","Line":144,"message":"Unable to generate a URL for the named route \"tables.page.index\" as such route does not exist.","exception":[],"CustomMessage":"Unable to generate a URL for the named route \"tables.page.index\" as such route does not exist."},"id":"669e0ccd78e42"}`



and:
`{"reqId":"Zp4NLgTO1l5sodriOGmqcgAAAJQ","level":1,"time":"2024-07-22T07:41:34+00:00","remoteAddr":"89.104.17.157","user":"admin","app":"no app in context","method":"GET","url":"/index.php/apps/logreader/api/poll?lastReqId=Zp4NJMv7ARNEiDTJDMoyQAAAAAQ","message":"Unable to generate a URL for the named route \"snappymail.page.index\" as such route does not exist.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36","version":"29.0.3.4","exception":{"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"snappymail.page.index\" as such route does not exist.","Code":0,"Trace":[{"file":"/var/www/html/lib/private/Route/Router.php","line":410,"function":"generate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->","args":["snappymail.page.index",[],1]},{"file":"/var/www/html/lib/private/Route/CachingRouter.php","line":65,"function":"generate","class":"OC\\Route\\Router","type":"->","args":["snappymail.page.index",[],false]},{"file":"/var/www/html/lib/private/URLGenerator.php","line":103,"function":"generate","class":"OC\\Route\\CachingRouter","type":"->","args":["snappymail.page.index",[]]},{"file":"/var/www/html/lib/private/NavigationManager.php","line":371,"function":"linkToRoute","class":"OC\\URLGenerator","type":"->","args":["snappymail.page.index"]},{"file":"/var/www/html/lib/private/NavigationManager.php","line":97,"function":"init","class":"OC\\NavigationManager","type":"->","args":[]},{"file":"/var/www/html/apps/fulltextsearch/lib/AppInfo/Application.php","line":125,"function":"add","class":"OC\\NavigationManager","type":"->","args":[["fulltextsearch",5,"/index.php/apps/fulltextsearch/","/apps/fulltextsearch/img/fulltextsearch.svg","Search"]]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/FunctionInjector.php","line":45,"function":"registerNavigation","class":"OCA\\FullTextSearch\\AppInfo\\Application","type":"->","args":[["OC\\Server"]]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/BootContext.php","line":50,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\FunctionInjector","type":"->","args":[["Closure"]]},{"file":"/var/www/html/apps/fulltextsearch/lib/AppInfo/Application.php","line":88,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\BootContext","type":"->","args":[["Closure"]]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":200,"function":"boot","class":"OCA\\FullTextSearch\\AppInfo\\Application","type":"->","args":[["OC\\AppFramework\\Bootstrap\\BootContext"]]},{"file":"/var/www/html/lib/private/App/AppManager.php","line":437,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":["fulltextsearch"]},{"file":"/var/www/html/lib/private/App/AppManager.php","line":216,"function":"loadApp","class":"OC\\App\\AppManager","type":"->","args":["fulltextsearch"]},{"file":"/var/www/html/lib/private/legacy/OC_App.php","line":128,"function":"loadApps","class":"OC\\App\\AppManager","type":"->","args":[[]]},{"file":"/var/www/html/lib/base.php","line":1030,"function":"loadApps","class":"OC_App","type":"::","args":[]},{"file":"/var/www/html/index.php","line":49,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/3rdparty/symfony/routing/Generator/UrlGenerator.php","Line":144,"message":"Unable to generate a URL for the named route \"snappymail.page.index\" as such route does not exist.","exception":[],"CustomMessage":"Unable to generate a URL for the named route \"snappymail.page.index\" as such route does not exist."},"id":"669e0d2ea4d87"}`

where the other app, in this case snappy mail, does work!

**Comment by raimund-schluessler** [comment]
This is almost certainly not a bug of the Tasks app, but a misconfiguration or installation problem. As such, it is best discussed in the nextcloud [forum](help.nextcloud.com).

However, although the report is unfortunately lacking crucial information such as the server error log or the web server version, my best guess is that your nginx configuration is outdated / broken and you need to adjust it for current Nextcloud versions. See this issue for example https://github.com/nextcloud/tasks/issues/2571.

Furthermore, since it is a hosted Nextcloud environment, please ask your hoster for support.

**Comment by Hullayo** [comment]
1. Find the nginx/conf/mime.types
application/javascript                           js;
add mjs before js;

**Comment by rackspeed** [comment]
No Nginx server is used. The setup corresponds to the recommended one with Apache 2.4 web server: https://docs.nextcloud.com/server/stable/admin_manual/installation/system_requirements.html
