### ISSUE TITLE
"When due" is missing in the Desktop app

### ISSUE THREAD

**Issue by Herbert-Sg** [nextcloud/tasks#2626]
### Is your feature request related to a problem? Please describe.

I can't choose "When due" in the desktop app, like I can do it in the mobile app. The same is with the "add reminder".

### Describe the solution you'd like

I would like to change this in the same way as it is possible in the mobile app.

**Comment by raimund-schluessler** [comment]
As you already found out in https://github.com/nextcloud/tasks/issues/2585, the time setting has a bug since 0.16.0.

Reminders are not implemented, see https://github.com/nextcloud/tasks/issues/154

**Comment by Herbert-Sg** [comment]
Will it be solved?
