### ISSUE TITLE
tasks-main.mjs Not Found

### ISSUE THREAD

**Issue by ultronstudio** [nextcloud/tasks#2649]
### Steps to reproduce

1. Simply go to {your cloud url}/apps/tasks

### Expected behavior

I was expecting to see a GUI with tasks

### Actual behaviour

a blank page appears, only with the nextcloud header

![image](https://github.com/user-attachments/assets/0472ac9c-8431-4c08-a1ee-9e30764b4734)

### Tasks app version

0.16.0

### CalDAV-clients used

nothing

### Browser

Chrome 127.0.6533.100

### Client operating system

Windows 11

### Server operating system

Ubuntu 22.04

### Web server

Nginx

### Database engine version

MariaDB

### PHP engine version

Other

### Nextcloud version

Nextcloud Hub 8 (29.0.4)

### Updated from an older installed version or fresh install

Fresh install

**Comment by ultronstudio** [comment]
Console and Network in my browser shows this

![image](https://github.com/user-attachments/assets/239e2d84-4f8f-4bfc-b6d9-aed1c07c143b)

![image](https://github.com/user-attachments/assets/3ca1a85f-430d-466e-b05b-94ca443e811a)

**Comment by raimund-schluessler** [comment]
Guys, keep your server config up to date! Or use a Docker container with a proper config. See #2571.
