### ISSUE TITLE
App not open

### ISSUE THREAD

**Issue by sergiupapuc** [nextcloud/tasks#2650]
### Steps to reproduce

1.Click on menu icon 
2.App not opening 
3.

### Expected behavior

Open app.

### Actual behaviour

screen refresh but remain on actual app, no error in system log

### Tasks app version

0.16.0

### Server operating system

UBUNTU 22.04

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.1

### Nextcloud version

29.0.4

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by raimund-schluessler** [comment]
Problem is the fulltextsearch app, see #2573 and https://github.com/nextcloud/fulltextsearch/issues/842. For the next report, please fill the issue template completely, including logs!
