### ISSUE TITLE
Accept german translation suggestion for "Set due date"

### ISSUE THREAD

**Issue by jaylinski** [nextcloud/tasks#2659]
### Is your feature request related to a problem? Please describe.

The german translation for "Set due date" is "Ablaufdatum setzen", but should be "Fälligkeitsdatum setzen".

### Describe the solution you'd like

Accept this translation suggestion (from 5 years ago):

![image](https://github.com/user-attachments/assets/61eea33d-264e-4e84-a6b3-5ca7ae2b8801)

https://app.transifex.com/nextcloud/nextcloud/translate/#de_DE/tasks/99690055?q=user_suggestions%3Ayes

### Describe alternatives you've considered

I'd accept the suggestion, but I don't have the rights in transifex.

### Additional context

This is relevant to me, because I'm currently adding the "Reminder" feature, and its reminder-suggestions are affected by the due-date. So this should be correctly translated.

**Comment by raimund-schluessler** [comment]
Unfortunately, I cannot accept the suggestion either (I was the one who proposed it :see_no_evil:). @jancborchardt Do you have the power to accept it, or know someone who could?

**Comment by jancborchardt** [comment]
Good point @raimund-schluessler @jaylinski – I asked about it in the "Translations l10n i18n" on our instance: https://cloud.nextcloud.com/call/xhz52vhg

**Comment by nickvergessen** [comment]
I just translated it to that and it seems to have worked
