### ISSUE TITLE
Remove old hack from App.vue

### ISSUE THREAD

**Issue by RayBB** [nextcloud/tasks#2660]
### Is your feature request related to a problem? Please describe.

I was looking through the code and noticed a section that was mentioned as a hack [here](https://github.com/nextcloud/tasks/blob/9d20686ebbe2dc0ef15021dfbcbb06300a2a9ec4/src/App.vue#L155-L161).

I was curious if it was still needed and the issue it mentions being a hack for [says](https://github.com/nextcloud-libraries/nextcloud-vue/issues/1384#issuecomment-1498686060) this is no longer needed.

First added [back in 2020](https://github.com/nextcloud/tasks/pull/1224/files), perhaps these few lines of code can be removed?

### Describe the solution you'd like

Remove the extra code

### Describe alternatives you've considered

It could be left there. That would probably be fine, but as I was digging around to look how I might implement some PWA improvements for #2516 I noticed this and thought I'd look into it.

### Additional context

I have not tested removing the "hack" myself.

**Comment by raimund-schluessler** [comment]
I think it still cannot go completely. While it seems to work ok, the sortorder dropdown would gain a unnecssary scrollbar without these CSS lines.

**Comment by RayBB** [comment]
Drats, thanks for checking.
