### ISSUE TITLE
[Feature request] Add an option to separate the tasks between Deck and Tasks

### ISSUE THREAD

**Issue by mariohevia** [nextcloud/tasks#2670]
### Is your feature request related to a problem? Please describe.

Every time I create a Deck, it is also shown in the Tasks app as a list, which is undesirable for my use case.

### Describe the solution you'd like

I would like an option to separate the Deck app and the Tasks app. This could be done per user or for all the users. Any of the two options would work for me, but I think it would be better to be done per user.

### Describe alternatives you've considered

I considered using a tag for all decks and filtering them, but this is cumbersome and prone to errors.

**Comment by raimund-schluessler** [comment]
The Deck app has an option to disable exposing Deck boards over the CalDAV backend. Disabling this will hide the Deck entries from the Tasks app.
