### ISSUE TITLE
Tasks/Decks can't be set to write

### ISSUE THREAD

**Issue by I-I-IT** [nextcloud/tasks#2671]
### Steps to reproduce

1.Share Cal with CalDav or other
2.See app settings and notice is "read-only"
3.Open Cal, Tasks, and Deck settings to see if you change it
![screenshot](https://github.com/user-attachments/assets/0dafb6ce-fb23-432b-8c32-3f73cf58154a)

### Expected behavior

User can change it to allow write from third-party client

### Actual behaviour

No settings to allow the write permission. Makes the sync broken.

### Tasks app version

I use https://mia.nl.tab.digital/, ask them

### CalDAV-clients used

DAVX5 

### Browser

Davx5

### Client operating system

Android

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

### Additional info
User faced similar issue : https://help.nextcloud.com/t/nexcloud-creates-read-only-user-deck/188391

**Comment by abdulrehman-code** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by I-I-IT** [comment]
Hey, what's this file ?

**Comment by raimund-schluessler** [comment]
This is a limitation of the Deck app. Tasks cannot do anything about it. The Deck app exposes its entries via CalDAV (if enabled in the Deck app), but did not implement write access (yet). See here for details https://github.com/nextcloud/deck/issues/2399
