### ISSUE TITLE
Task/Calendar web interface does not include tasks while exported

### ISSUE THREAD

**Issue by wuesti** [nextcloud/tasks#2699]
### Steps to reproduce

1. Create calendar with tasks list
2. Export calendar 
3. Open downloaded .ics in Text editor
 => no task is in

### Expected behavior

Tasks should be exported.

### Actual behaviour

No tasks are in .ics

### Tasks app version

0.16.01

### CalDAV-clients used

Web interface

### Browser

firefox

### Client operating system

arch linux

### Server operating system

Ubuntu 24.04 lts 

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

snap 29.0.7

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by raimund-schluessler** [comment]
I cannot confirm this behaviour. Downloading an `ICS` file correctly includes `VTODOs` i.e. tasks. However, the Tasks app is anyway not responsible for creating said `ICS` file, it just accesses the endpoint provided by Nextcloud server. If this issue persists for you, please report it in https://github.com/nextcloud/server
