### ISSUE TITLE
Word wrap task titles in right pane

### ISSUE THREAD

**Issue by Victor239** [nextcloud/tasks#2705]
### Steps to reproduce

1. Click on task to open it in the right preview pane

### Expected behavior

Task titles should be word wrapped so they're entirely readable, or at least have the default option for it to be this way. 

### Actual behaviour

Task titles don't have word wrap:

![Image](https://github.com/user-attachments/assets/16d3d869-5048-496a-8422-2299fd0ff92d)

### Tasks app version

0.16.1

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by sketchee** [comment]
There seems to be no way to read a title that is longer than a certain length.
