### ISSUE TITLE
API access to tasks event

### ISSUE THREAD

**Issue by theRAGEhero** [nextcloud/tasks#2706]
### Is your feature request related to a problem? Please describe.

Hello,
I cannot find a way to access to Tasks with API.
Is it possible? If not, it would be nice to add it.
Thanks!

**Comment by raimund-schluessler** [comment]
The Tasks app itself is just a client and uses the API of Nextcloud server to read and write tasks. The API used is the CalDAV interface. Depending on how you want to interact with tasks or events, you can access it directly, see https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/groupware/index.html or via HTTP, see https://github.com/nextcloud/cdav-library
