### ISSUE TITLE
Move task to different list

### ISSUE THREAD

**Issue by cptMikky** [nextcloud/tasks#272]
There is currently no way of moving a task to a different list.

Ideally, a drag'n'drop feature should be available to move a task (including its subtasks) to a different task list. At minimum, an option to change task's list should be available in task edit window. This should also affect all subtasks.

Nextcloud version 15.0.4, Tasks app version 0.9.8.

**Comment by raimund-schluessler** [comment]
In Tasks v0.9.8 you can in principle drag and drop a task to a different list, but it is broken atm in Chrome (see #78). It should work in Firefox, though.

In the rewritten version that you find in the master branch (which will be Tasks v0.10.0) drag and drop is not implemented yet, but it will come before the next release, see #236. In v0.10.0 you will also find a drop-down-list in the details view where you can select the list/calendar a task belongs to. If you want to try it out, please see #270.
