### ISSUE TITLE
Task links from calendar do not open

### ISSUE THREAD

**Issue by manfredu** [nextcloud/tasks#2733]
### Steps to reproduce

1. Click on a task display on a calendar
2. The task app opens, but does not open the selected task

The not working link called from calender has the following format:
`https://mynextcloud.tld/apps/tasks/calendars/myuser#/calendars/myuser/tasks/task-id.ics`

When I change this to the following the task opens
`https://mynextcloud.tld/apps/tasks/calendars/myuser/tasks/task-id.ics`

### Expected behavior

When I click on a task show in calendar, the task should be opened in the task app.

### Actual behaviour

The tasks app is opend without any task selected

### Tasks app version

0.16.1

### CalDAV-clients used

DAVx5

### Browser

all

### Client operating system

all

### Server operating system

TrueNAS Core / FreeBSD 13.3

### Web server

Other

### Database engine version

MariaDB

### PHP engine version

PHP 8.2

### Nextcloud version

30.0.2

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text

```

### Nextcloud configuration

```Text

```

### Web server error log

```Text

```

### Log file

```Text

```

### Browser log

```Text

```

### Additional info

Since I'm not sure if this is caused by the calendar or the tasks app, I have also opened
[issue 6533](https://github.com/nextcloud/calendar/issues/6533) for the calendar app.

**Comment by raimund-schluessler** [comment]
Issue of the Calendar app, closing here.
