### ISSUE TITLE
[Feature Request] Sort tasks

### ISSUE THREAD

**Issue by enboig** [nextcloud/tasks#28]
### Steps to reproduce
1. Create a list
2. Add tasks
3. Try to sort task using drag and drop

### Expected behavior
I would like to be able to sort tasks, now I can only star them and this is quite limited

### Actual behavior
Now I only can star them, and they are alphabetically sorted.

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
11
**Tasks version:** (see Nextcloud apps page)
0.9.4
**Updated from an older Nextcloud or fresh install:**
Updated since owncloud 7

**Comment by raimund-schluessler** [comment]
You can already sort the tasks by other properties as start and end date, priority, alphabetically and the standard order (due date -> priority -> alphabetically). With https://github.com/nextcloud/tasks/pull/4 it will come the option to sort them manually.

**Comment by enboig** [comment]
I didn't think about setting their time. I was just trying to sort them by drag&drop.

Thanks

**Comment by enboig** [comment]
Despite an option to easily sort task without inserting them a date, I will close the issue because I could work adding a date/time

**Comment by raimund-schluessler** [comment]
We can keep this issue open as long as #4 is not merged. So others see the answer to this question faster. :smile:

**Comment by kramer65** [comment]
This is the one feature I'm waiting for. Without it, tasks is useless to me.

**Comment by nathan2423** [comment]
Another option might be to allow priorities to be double-digit  (ie, 1.1, 1.2, 1.3 etc) and that might give us enough fine-grain control to effectively sort manually.  But I agree I very much want manual sorting!  

Of course once you have manual sorting you essentially have a basic "outlining" app, and THAT is what I would really like to see.  Perhaps as a fork from this app?  Basic outlining is tremendously useful and any steps in that direction would be very much appreciated!

**Comment by aiomaster** [comment]
Just to make it more clear for people like me, who searched a while where the progress of this feature is tracked now, after the vue.js refactoring.
It is this PR: #237

**Comment by bronson** [comment]
Just installed this app. It's odd to see manual sorting work... until I release the mouse button and everything snaps back to its original place.

Looking forward to seeing manual sorting work one day.

**Comment by raimund-schluessler** [comment]
Please have a look at https://github.com/nextcloud/tasks/pull/237#issue-247935356. The PR is ready to be reviewed. I build and uploaded a version of the Tasks app including manual sorting, so you can test the feature easily.
