### ISSUE TITLE
Rearrange Lists

### ISSUE THREAD

**Issue by adamlove86** [nextcloud/tasks#30]
### Expected behaviour
Tell us what should happen
Hi there, I'd love to be able to rearrange lists - for example my "today" list first, my "shopping list" second, "this week" list third, etc.

Also, not particularly important as it all seems to still be functional on my phone, but when you open the web page via mobile, there is some overlap with the buttons at the top of the page. 

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
11 Snap

**Tasks version:** (see Nextcloud apps page)
0.9.4

**Updated from an older Nextcloud or fresh install:**
Updated

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/nextcloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by roadfox** [comment]
The possibility to sort Lists would be higly apperciated also from me. I tried with numbering my Lists like:
1. FirstList
2. SecondList
and so on, but they are even not human sorted, so atm i don't see any way to sort them somehow

**Comment by raimund-schluessler** [comment]
Please see https://github.com/nextcloud/tasks/issues/15
