### ISSUE TITLE
Is there any Api available

### ISSUE THREAD

**Issue by developerfromjokela** [nextcloud/tasks#304]
Hello!

I want to create an Android app to use tasks on my mobile device,

So, is there any JSON API for Tasks app?

Regards,
@developerfromjokela

**Comment by raimund-schluessler** [comment]
No, there is no such API available. And I think it doesn't really make sense to create one either. Tasks is a CalDAV client for the Nextcloud server and there are various todo apps with CalDAV support available for Android as well.

If you really want to create your own app, you will have to directly communicate with the CalDAV server in Nextcloud.

**Comment by developerfromjokela** [comment]
Hello!

Thanks for fast response!
I will look into it later today.

Regards,
@developerfromjokela

**Comment by Shahin-rmz** [comment]
Hello, 
thanks for nice app.
I have synched tasks with Gnome todo and also Tasks on Android and I am very satisfied.
I want to synch my tasks from selfhosted [Kanboard](https://kanboard.org/) with tasks.
How is it possible?
Thanks
PS. I code as hobby and just with Python.
