### ISSUE TITLE
Sync check list items

### ISSUE THREAD

**Issue by achimwagenknecht** [nextcloud/tasks#307]
When syncing a shared check list, items will be lost.

### Steps to reproduce
1. Create task with OpenTasks on Android
2. Add check list items a, b and c
3. share with other user
4. other user adds check list items d, e, f
5. sync

### Expected behaviour
After sync, list should contain items a, b, c, d, e, f.

### Actual behaviour
check list contains items a, b, and c. Items d, e and f are lost.

### Server configuration
nextcloud 12

**Operating system**:
Linux, Android

**Updated from an older Nextcloud or fresh install:**
Updated

**Comment by raimund-schluessler** [comment]
Please report this in the server repository. Tasks is just a client as well and is not involved in the sync process between Android OpenTasks and the Nextcloud CalDAV server.
