### ISSUE TITLE
[Feature Request] Add Actual Completetion date

### ISSUE THREAD

**Issue by TruputiGalvotas** [nextcloud/tasks#312]
### Steps to reproduce
1. Press check mark that Task is done

### Expected behaviour
Date when task is set as done is record on task and it is displayed on the completed task instead of due date
Tasks could be filtered by done date

### Actual behaviour
Date of completion is not recorded and is not shown to the user

### Mockup
Red color chosen just for the changes to be noticed, otherwise the actual color should follow the default color space.
![Done_Task_Mockup](https://user-images.githubusercontent.com/19952587/54073913-3e0b5080-4295-11e9-9595-01aa4d63c4ef.png)

I would be willing to implement this myself with some guidance/mentoring from the nextcloud team if this featured request would be accepted.

**Comment by raimund-schluessler** [comment]
I like the idea and implemented it in #313. The only thing I changed is that the completed date is shown in the task details footer tooltip. Because it is a date that cannot be edited directly, it doesn't make sense to show it next to the start and due date in my opinion. See the screenshot for how I did it:

<img width="491" alt="completed-date" src="https://user-images.githubusercontent.com/2496460/54082770-0810af80-431b-11e9-9a63-48a5164b14dc.png">

**Comment by raimund-schluessler** [comment]
Closed with #313

**Comment by TruputiGalvotas** [comment]
thank you @raimund-schluessler that is fantastic! Will be waiting for 0.10.0 :)

**Comment by freayd** [comment]
@raimund-schluessler, may I ask why completed dates can't be edited? I sometimes mark tasks completed a few days after it was actually done and would like to be able to edit the completed date to reflect the reality. Other CalDAV apps allow this field to be edited, it'll be nice to be able to do it directly into Nextcloud. One possibility would be to show the completed date picker only if the task is completed.

**Comment by raimund-schluessler** [comment]
> @raimund-schluessler, may I ask why completed dates can't be edited?

Because I never thought of this use case and also never noticed this feature in another CalDAV app. Please open a separate ticket for this feature request.

**Comment by freayd** [comment]
Fair enough. Thanks!
