### ISSUE TITLE
Tasks doesn´t show on calendar and are not save properly

### ISSUE THREAD

**Issue by danicotillas** [nextcloud/tasks#335]
### Steps to reproduce
1. I create a task
2. I set up beginning time and end time
3. Task doesn´t appear on calendar
4. When I come back to task there is not all the information saved.

### Expected behaviour
When you create the task the information is properly saved and appears on the calendar.

### Actual behaviour
It looks like the system is not working properly.

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Tasks version:** (see Nextcloud apps page)

**Updated from an older Nextcloud or fresh install:**

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/nextcloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by raimund-schluessler** [comment]
> Tasks doesn´t show on calendar

This is an issue with the Calendar app, see https://github.com/nextcloud/calendar/issues/28

**Comment by danicotillas** [comment]
> > Tasks doesn´t show on calendar
> 
> This is an issue with the Calendar app, see [nextcloud/calendar#28](https://github.com/nextcloud/calendar/issues/28)

I thought it was yours because on the app description of tasks it says that it´s link to a calendar.
Sorry because my github experience is not so high... is there no solution yet? Thanks

**Comment by raimund-schluessler** [comment]
>  it says that it´s link to a calendar.

This might be a bit misleading. It just means that tasks a stored in the calendar, so it is easy to sync them to other CalDAV clients, e.g. Thunderbird.

As you can see in the issue I linked, this feature is not yet implemented in the Calendar app.
