### ISSUE TITLE
[Feature Request] "Step-by-step" task

### ISSUE THREAD

**Issue by RavengamerSpace** [nextcloud/tasks#341]
### This idea comes from Google Task

What I mean it's to have the ability to have a task which a children task

Look at the join video for more explanation
![2019_03_27_19_58_40_trim (2)](https://user-images.githubusercontent.com/28545669/55105483-ee1ded80-50cc-11e9-92fa-53570f145712.gif)

**Comment by raimund-schluessler** [comment]
The Tasks app already supports subtasks or "children tasks". Just click on the plus icon on the left side of a task, type the title of the subtask and press enter, voilà a subtask 😉
