### ISSUE TITLE
Request for supporting Nextcloud 16

### ISSUE THREAD

**Issue by smirkybg** [nextcloud/tasks#375]
Nextcloud 16 was released a while ago and I'm planning to upgrade, but the Tasks app still needs to catch up.

**Comment by raimund-schluessler** [comment]
Sorry, the next version v0.10.0 is not quite ready for a final release yet. At the moment it still lacks the drag and drop support for moving subtasks. It will take at least two weeks from now on.

In the mean time you can test the alpha versions in #270. They should work well, besides the dnd support.

**Comment by j-ed** [comment]
@smirkybg As workaround you can use the new "Activate unstable app" function to get it activated again. On a first glance everything seems to work as expected.

**Comment by ShapeShifter499** [comment]
@j-ed your solution worked for me after an upgrade of NC 15 to NC 16 on a Arch Linux system. Thanks.

**Comment by lemmy04** [comment]
I can't find "Activate unstable app", all I see is to REMOVE it...

**Comment by rm76** [comment]
I'll hold off upgrading to Nextcloud 16 until the Tasks app is updated too!

**Comment by raimund-schluessler** [comment]
Tasks [v0.10.0](https://github.com/nextcloud/tasks/releases/tag/v0.10.0) is in the appstore now.
