### ISSUE TITLE
Request: Folders

### ISSUE THREAD

**Issue by benyanke** [nextcloud/tasks#39]
I see this being an excellent replacement for Wunderlist, except that it doesn't have folders for lists.

I would really love to see folders so I can do nested lists. For example:

school
-- class1todolist
-- class2todolist
-- class3todolist
personal
-- HomeLab
-- HouseChores
work
--ClientA
--ClientB

I do recognize that this is related, but somewhat different than https://github.com/nextcloud/tasks/issues/23

**Comment by raimund-schluessler** [comment]
If we implement this, it will either be folders OR nested lists. I will close this issue here in favor of #23, but I need to check what is possible.
