### ISSUE TITLE
Task should be open after it was created

### ISSUE THREAD

**Issue by mpodshivalin** [nextcloud/tasks#397]
Before version 0.10.0 a task was automatically opened immediately after it was created.
Now it is only being added to the task list and a user must find a newly created task in a task list manually to open it and add some additional information.

It is a problem if you actively use due dates and have a lot of tasks:
Before 0.10.0 - create a task, set due date - done
After 0.10.0 - create a task, look manually for a newly created task (I have ~200 tasks, and newly created task is not at the top and not at the bottom of the list, so I need to scroll though entire list to find it), and then set due date.

### Steps to reproduce
1. Create task
2. Newly created task is not active/open

### Expected behaviour
A newly created task should be open as in version 0.9.8 for example

### Actual behaviour
A newly created task is not open, a user must manually find it in the task list to add any additional information (due date, comments, priority, etc)

By the way 0.10.0 is very smooth and fast, great job on porting the app to Vue!

**Comment by raimund-schluessler** [comment]
Indeed, that's a regression and should not be like this. I will fix this and prepare a bugfix release.

> By the way 0.10.0 is very smooth and fast, great job on porting the app to Vue!

Thanks for the positive feedback!
