### ISSUE TITLE
Pale moon browser not supported

### ISSUE THREAD

**Issue by nathan2423** [nextcloud/tasks#398]
I am running Nextcloud 15.0.7 and today I upgraded to Tasks 0.10.1.
The result is that the blue bar along the top of my desktop browser looks exactly the same, but underneath that the screen is entirely WHITE -- no hint of data or application at all. All the rest of my Nextcloud seems to be working normally, and it appears that my thunderbird calendar is still syncing tasks, and that I can also view tasks on the browser of my telephone -- seems to be something with the desktop (linux) but I get the same result on every browser and machine I try.  <<<WRONG - just Palemoon so far.  Chromium works.

Can you suggest a way to start troubleshooting?  I have disabled and reenabled the app with no visible result.  Thanks very much.

**Comment by raimund-schluessler** [comment]
Did you install it from the appstore or manually?

Do you see something in the browser log?

**Comment by nathan2423** [comment]
I installed through the appstore (It showed a blue oval to update, and I hit it.)

In my list of apps it shows as a normal entry now, but I note that it does not have the "official" badge that most of the other apps have.

As to the browser log, if you mean under settings, overview "... check for any errors or warnings in the log. "  I clicked on that and there are no entries for today at all (and I did the upgrade about two hours ago 11 AM my time.

**Comment by nathan2423** [comment]
I have just learned that the issue is user-related -- my group partner opened up her task tab with no issue and sees her normal screen.

**Comment by nathan2423** [comment]
Now I see it must be browser-based -- Palemoon seems to be where my issue lies.  Sorry to have opened a general post for this.

**Comment by raimund-schluessler** [comment]
Hm, Pale moon is a rather exotic browser which we don't officially support. I might have a look once time allows, but I need to setup a pale moon instance first.

But just to double check, it works normally with other browsers?

**Comment by nathan2423** [comment]
So far I just tested on Chromium and and old version of Qupzilla (2.12)  On both, all the rest (calendar, files, bookmarks, contacts) of Nextcloud is working appropriately, except the task app.  And I am pretty sure that the task app worked on Qupzilla prior to the .10.1 upgrade too.  Unfortunately I am not sure what version I was on before this morning, but apparently something changed.

Anyway no big deal for me!  Thanks for a great program!

**Comment by nathan2423** [comment]
Just checked same setup as before, this time using Waterfox.  Task app works fine.  Must be something with Palemoon.

**Comment by raimund-schluessler** [comment]
> So far I just tested on Chromium and and old version of Qupzilla (2.12) On both, all the rest (calendar, files, bookmarks, contacts) of Nextcloud is working appropriately, except the task app.

So the app does not work on Qupzilla (never heard of it btw) and pale moon, right?

> And I am pretty sure that the task app worked on Qupzilla prior to the .10.1 upgrade too.  Unfortunately I am not sure what version I was on before this morning, but apparently something changed.

The app was completely rewritten using vue.js and modern web techniques. Probably, these browsers do not support some JavaScript features necessary for the app to work. That’s why I am also not sure if we can get it working (easily).

**Comment by raimund-schluessler** [comment]
Which version of contacts do you use? Contacts 3.0 and higher uses vue.js and a lot of code similar to Tasks. If Contacts works, we might be able to adjust Tasks too.

**Comment by raimund-schluessler** [comment]
@nathan2423 I had a look now and downloaded Pale Moon Portable for Windows. With https://github.com/nextcloud/tasks/tree/compatibility the app seems to work normally on the first sight. But basically none of the click actions (like starring or completing a task etc.) works. This seems to be because the event bubbling of Pale Moon is really weird. It basically does not bubble upwards, so the click handlers are never called.

I guess it would be possible to fix this by moving the click handlers to the innermost element, but this would be quite some effort.

However, we can merge https://github.com/nextcloud/tasks/tree/compatibility anyway, because it does not change the behaviour for other browsers and bundle size stays the same.

**Comment by nathan2423** [comment]
Thank you for taking a look at this!  I am only running Palemoon on Linux, so I was not able to test on anything else.  Sounds like it is somewhat different on Windows, since all I get on Linux (debian stretch) is a white screen.   Anyway thank you for looking at this!

**Comment by raimund-schluessler** [comment]
Well without the change in #401 I also only get a white screen with Pale Moon on windows.

**Comment by raimund-schluessler** [comment]
Following the discussion at nextcloud/contacts#414 we officially only support the same browsers as server, except IE11. Hence, I am going to close this issue here. With the upcoming v0.10.2 you should be able to load the app again, but most actions will probably not work since the click events are not recognized.

**Comment by raimund-schluessler** [comment]
PRs are welcome though.
