### ISSUE TITLE
[regression] ability to drag tasks to a new calendar on the left sidebar

### ISSUE THREAD

**Issue by nachoparker** [nextcloud/tasks#399]
We used to be able to do this.

- Create a new task, gets placed in the default calendar
- Drag it to a new calendar on the sidebar

If we have many calendars and many tasks it is hard to drag it down to a new calendar without using the left sidebar.

Thanks!

**Comment by raimund-schluessler** [comment]
Yes, that’s true. But I am not sure if this is possible with the drag and drop library we use now. I will look into this.

For now, you might use the ability to change the calendar in the details view of a task.
