### ISSUE TITLE
[Feature Request] - Allow to deactivate Calendars for using in Tasks

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/tasks#40]
Allow to deactivate Calendars for using in Tasks. Beacause I Manage a Club with that I have many calendars for many reasons.

In the best case I'm able to allow set-up the using of Tasks per calendar in the sharing access dialog. --> "Tasks edit", "Tasks read"

**Comment by raimund-schluessler** [comment]
The CalDAV-Standard forbids to change the allowed components of a calendar after its creation. This means we could only hide the calendar in the Tasks app, but other clients would still be able to insert tasks into the calendar.

**Comment by Mannshoch** [comment]
Maybe you could Prompt in Nextcloud the exist of tasks in other calendar then allowed and ask for moving to a defined calendar.

That creates a new Idea. 
This settings could allow me to setup an input calendar where other people could send me new tasks to evaluation and I or an other Observer could move it to the correct calendar if accepted.

**Comment by raimund-schluessler** [comment]
> Maybe you could Prompt in Nextcloud the exist of tasks in other calendar then allowed and ask for moving to a defined calendar or do it automatic.

Sorry, I don't get what you mean.

**Comment by Mannshoch** [comment]
If a Task arrive by CalDAV Client in an other Calendar then preferred. Nextcloud should Prompt it to a given User if he open the Task APP in Nextcloud.

![daily task](https://cloud.githubusercontent.com/assets/7795891/22074578/1caaf2d6-dda9-11e6-83db-76b1af8c73e2.png)

**Comment by raimund-schluessler** [comment]
We could hide calendars in the Tasks app, see https://github.com/nextcloud/tasks/issues/84
