### ISSUE TITLE
[Feature Request] - add an user Managemant and link to calendar entry.

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/tasks#41]
I'm Member of a Little club which has to plan little events. At moment we us a classic Paper Task Schedule to work with. If something like the following Mockup is available, we could do further planing on tablet and phone.

See Mokup
![aufgabenplanung-own](https://cloud.githubusercontent.com/assets/7795891/22074006/2fd7ad1a-dda7-11e6-881e-26f19ec724e9.png)

**Comment by raimund-schluessler** [comment]
For user management, please see https://github.com/nextcloud/tasks/issues/14 and https://github.com/nextcloud/tasks/issues/72.

Regarding calendar entry, see https://github.com/nextcloud/calendar/issues/28
