### ISSUE TITLE
Percentage complete value not visible at current width

### ISSUE THREAD

**Issue by mcocolla** [nextcloud/tasks#411]
https://github.com/nextcloud/tasks/blob/5648b2fd7fc87a07680a05b19f1706702f73b8af/css/src/style.scss#L937-L942

Please consider increasing the width of the percentage input to 44px to allot for the up/down arrows overlapping the text value of the percentage input element. Double digit percentages are not visible at the current 35px.

![nextcloud-tasks-input-percentage](https://user-images.githubusercontent.com/374625/57872118-f6df9580-77d8-11e9-825c-6d5d5673820b.png)

**Comment by raimund-schluessler** [comment]
Thanks for the report. The arrows are not meant to be visbile, but the CSS rule from Server did not work correctly with Chrome. I hid the arrows now, but adjusted the width anyway, since 44 px should be the default on any interactive element, see #392 .

**Comment by zjacreman** [comment]
I am seeing this issue still / again in v0.15.0 
![image](https://github.com/nextcloud/tasks/assets/1148990/59eb5ffa-83b7-4496-8f3b-fa3e3743f9b2)
