### ISSUE TITLE
[Feature Request] Hashtag tagging of new entries

### ISSUE THREAD

**Issue by benyanke** [nextcloud/tasks#42]
For easier tagging, I'd propose the extraction of tags from hashtags.

For example, I could enter:

> Fix SSL Error on example.com #work 
> Change Email Password #personal

And those two entries would be tagged with _work_ and _personal_, respectively.

**Comment by raimund-schluessler** [comment]
Please see https://github.com/nextcloud/tasks/issues/89

**Comment by raimund-schluessler** [comment]
This was implemented in #2425 now.
