### ISSUE TITLE
Scrolling Screen Moves Task Item on Smartphone

### ISSUE THREAD

**Issue by brianWreaves** [nextcloud/tasks#421]
### Steps to reproduce
View the _Tasks_ screen on a smartphone.

### Expected behaviour
The screen scrolls instead of the task(s).

### Actual behaviour
While viewing tasks, attempts to scroll the screen grabs the task, and it's sub-task, instead of moving the screen.
 
I noticed this after the latest update.
 
Work around is to use the far right edge and this typically works. 

Nextcloud version:  **15.0.7**
Tasks version:  **0.10.1**
Are you using encryption:  **no**
Are you using an external user-backend, if yes which one:  **No** 

### Client configuration
Browser:  **FF 66+**

Operating system:  **Android 9**

**Comment by raimund-schluessler** [comment]
Thanks for the report, fix is in #424.
