### ISSUE TITLE
Inconsistency when manually inserting due date

### ISSUE THREAD

**Issue by elpraga** [nextcloud/tasks#43]
### Steps to reproduce
1. start a new task on a mobile device
2. try to insert due date manually (the pop u calendar does not appear on mobile phone) in suggested format __dd.mm.yyyy__ 
3. this date will be converted to today

### Expected behaviour
When popup calendar does not appear, input date manually as __dd.mm.yyyy__ and it will be accepted as __dd.mm.yyyy__

### Actual behaviour
When date in inserted manually on a mobile phone in suggested format __dd.mm.yyyy__ it is converted to __today__

It is possible to manually insert due date, but it must be inserted as __mm/dd/yyyy__ followed by pressing __Enter__. It then gets converted automatically to __dd.mm.yyyy__ and after pressing :ballot_box_with_check: it is set. (I know, it sounds weird and it is weird)

### Server configuration
**Operating system**
Lubuntu 16.04.

**Web server:**
Apache2
**Database:**
SQLite3
**PHP version:**
7.0.
**Nextcloud version:** (see Nextcloud admin page)
11.0.1
**Tasks version:** (see Nextcloud apps page)
0.9.4

Tested on Google Chrome for Android 55 Huawei Y6II

**Comment by elpraga** [comment]
I'll add a screenshot..
![screenshot_2017-01-18-15-59-23](https://cloud.githubusercontent.com/assets/13814570/22120737/4698e6c4-de81-11e6-90f3-54afdb8fce32.png)

**Comment by raimund-schluessler** [comment]
Please see https://github.com/nextcloud/tasks/issues/45
