### ISSUE TITLE
[Style Request] User defined background, margins for task-list...

### ISSUE THREAD

**Issue by feluxe** [nextcloud/tasks#435]
Hi there,

I love `nextcloud/tasks`, but I find the task-list somewhat dense and unpleasant to read. I would like to suggest 3 things to improve the looks and readability of the task-list:

1) Add `~1px` margins for each task. This makes the task-list become less dense and more pleasant to read.  (IMHO).
2) Allow the user to upload a custom background-image for the task list or let him/her choose a color. This plays nicely with the margins from `1)`.
3) Change the color of the `Add new task` input filed to something else than white, to separate it from the task-list.

**The view before:**
(open in new tab to see on full-screen)
![tasks_style_1_before](https://user-images.githubusercontent.com/6545589/58752860-38995d00-84b6-11e9-9c80-b900365ef639.png)

**The view after (with user defined background image):**
(open in new tab to see on full-screen)
![tasks_style_1](https://user-images.githubusercontent.com/6545589/58752864-4949d300-84b6-11e9-895f-d9e84acc9cdc.png)

**The view after (with another user defined background image and a darker app-navigation):**
(open in new tab to see on full-screen)
![tasks_style_2](https://user-images.githubusercontent.com/6545589/58753576-7ea7ee00-84c1-11e9-838c-f9ad820f148e.png)

Any love for this?

**Comment by raimund-schluessler** [comment]
@nextcloud/designers What do you think?

Points 1 and 3 might be worth considering, but uploading a custom background is not a feature worth implementing I think. This is nowhere found in Nextcloud and everyone who wants this can just add a bit of custom CSS to achieve it (although I tend to agree it doesn’t look bad).

**Comment by feluxe** [comment]
Thanks for your reply!

> This is nowhere found in Nextcloud and everyone who wants this can just add a bit of custom CSS to achieve it (although I tend to agree it doesn’t look bad).

I think there are several nextcloud apps which could make use of a `custom background` feature. It would look great for the `bookmarks` app as well.

**Comment by skjnldsv** [comment]
I'm not really fan of the gradient itself :)
But overall, I agree that we could use a bit more readability.
Though having a gray background or whatever colour behind, is gonna make the design looks a bit old-ish :)

I would be more in favour of increasing the size like #392 suggest and use determined actions to ensure a visually cleaner look
![mio-design_assets_1VGUbTqihAbKetX6-HEXNsJOUqVqk_b8J_usage-types](https://user-images.githubusercontent.com/14975046/58757519-e8e68000-850d-11e9-89b3-7e0079084cac.png)
![mio-design_assets_1hc2ctdeE65wiDJNpup4pb1Agvug7P94A_lists-elements](https://user-images.githubusercontent.com/14975046/58757520-e97f1680-850d-11e9-808a-0bea2e125d28.png)

Dividers are not always needed.
If the whole ui make sense, we'll see the differences automatically ;)
![mio-design_assets_1TaxymtZ-I0U8XTqPmxIrlXN990WwuTEP_single-line-desktop](https://user-images.githubusercontent.com/14975046/58757539-10d5e380-850e-11e9-856b-1da51b02cb3e.png)

**Comment by raimund-schluessler** [comment]
The apps should have a `div #content .app-<appname>` element, see https://github.com/nextcloud/tasks/blob/master/src/app.vue#L23, with which you can distinguish between different apps.

**Comment by raimund-schluessler** [comment]
For the background idea, I would propose to discuss this in the server repo.

**Comment by jancborchardt** [comment]
Custom background is something that could be implemented through an app – just like [Unsplash](https://apps.nextcloud.com/apps/unsplash) does it for the header. But it’s not something which warrants the work to do it in core.

The "Add task" input field being grey looks as if it’s disabled, so that’s a bit confusing. Whitespace seems enough to separate it from the actual tasks.

Regarding spacing between entries:
- The margin is 0 so that there are fewer lines between the entries (1 instead of 2) which simplifies it.
- We could increase margins, but then the subentries for example should ideally still stick together.
- Generally agree with what @skjnldsv mentions quoting the Material Design guidelines.
- We should most likely work on a standard for these list elements, based on the Files and Tasks app to align their look and interaction.

**Comment by feluxe** [comment]
> I'm not really fan of the gradient itself :)

It was just an example. Every one cloud use his/her own image. :)

> Custom background is something that could be implemented through an app – just like Unsplash does it for the header.

Looking at `Unsplash` I realized, the lock-in screen would be another great place to show the user defined background. There are many apps that I can think off where app-desingers could use the `user-background` to improve the overall UX. Of cause this could be implemented via an extra app, but then it will never feel like a native feature, because the apps won't be designed with it in mind. Just my 2 cent :-)

**Comment by jancborchardt** [comment]
> Of cause this could be implemented via an extra app, but then it will never feel like a native feature, because the apps won't be designed with it in mind.

A lot of features which are now in the main release started as an app, because it’s easy to trial them without risk of putting bulk into the core which might not be used by anyone. :) Some examples are the app menu in the header by @juliushaertl and the right-click menu by @NastuzziSamy.

**Comment by raimund-schluessler** [comment]
So in conclusion what is left to do is:

- Implement #392 and work on standardizing list elements
- Merge PR for custom background element once there is a custom background app 😉 

Changing the margin around the task entries and gray color for input element will not be introduced.

I will close this issue then, since it is tracked in #392. Speak up if you disagree.

**Comment by jancborchardt** [comment]
> Merge PR for custom background element once there is a custom background app

If there would be a custom background app, it should use the standardized elements like `#app-content`, no additional modification should be needed in any app. :)
