### ISSUE TITLE
Add a gantt chart view

### ISSUE THREAD

**Issue by tterranigma** [nextcloud/tasks#44]
This is a great way to visualize the timeline for your tasks and to better organize them. Right now there is no way to tell what tasks overlap, which are the shortest to do, etc.

**Comment by copynpaste** [comment]
ref: owncloud/tasks#219

**Comment by hitam4450** [comment]
I certainly support the idea of implementing a gnatt chart view!

**Comment by raimund-schluessler** [comment]
I would like to keep the Tasks app simple and I rather think this should be implemented as a separate app. Feel free to send a PR, but I will not work on this, since I think there are more important things to improve on.
