### ISSUE TITLE
Tasks App with Microsoft Edge white page

### ISSUE THREAD

**Issue by JB1985** [nextcloud/tasks#442]
Hi, 

the App tasks do not work with Microsoft Edge on Windows 10.

I get a white page. Same with the Private Mode without any Plugins/addons.

Is it a known issue?

![image](https://user-images.githubusercontent.com/9932751/59156415-26618500-8a9b-11e9-8466-09fca4dfe035.png)

**Comment by raimund-schluessler** [comment]
Please fill the issue template. Especially which Tasks app version, which version of Edge etc.

For me Tasks v0.10.1 works fine with Edge 42.17134.1.0, Microsoft EdgeHTML 17.17134. Please make sure you use the newest program versions.

**Comment by JB1985** [comment]
Tasks 0.10.1
Nextcloud 16.0.1 (fresh install)
Microsoft EdgeHTML 18.17763
Microsoft Edge 44.17763.1.0

**Comment by raimund-schluessler** [comment]
Sorry, my mistake. It was a slightly newer version I tested on my server which includes #401. Fix will come with v0.11.0.
