### ISSUE TITLE
Do not show read only calendars

### ISSUE THREAD

**Issue by rkaraba** [nextcloud/tasks#446]
Do not show read only calendars in left panel.
I mean calendars that others users share with you but you can't modify them.
You can't add tasks to them so it's pointles to show them

**Comment by raimund-schluessler** [comment]
Why wouldn’t you show them? How would you then open the calendar to see which tasks are there?

I think not showing them is not reasonable.

**Comment by rkaraba** [comment]
@raimund-schluessler you are right this possibility did not occur to me.
I have a lot readonly calendars without tasks.
Maybe there could be an option in settings to hide read only calendars if they have no tasks in it
Like you have for Smart collections

**Comment by raimund-schluessler** [comment]
@rkaraba I think such an option would be a bit to specific, having an option to hide a list should be the proper solution for this: https://github.com/nextcloud/tasks/issues/84

**Comment by rkaraba** [comment]
Yes, option to hide a list will be perfect solution
