### ISSUE TITLE
Adding additional categories to tasks not possible

### ISSUE THREAD

**Issue by avanc** [nextcloud/tasks#46]
### Steps to reproduce
1. Create a task
2. Add a category
3. Open this task again
4. Try to add additional categorie

### Expected behaviour
The prompt for adding an additional category should open.

### Actual behaviour
Nothing happens. It is not possible to ad an additional categorie.

### Server configuration
**Operating system**:
Arch Linux

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.x

**Nextcloud version:** (see Nextcloud admin page)
11.0.1

**Tasks version:** (see Nextcloud apps page)
0.9.4

**Updated from an older Nextcloud or fresh install:**
Updated

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no 

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/nextcloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Firefox 45.5.1

**Operating system:**
Windows 7

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by raimund-schluessler** [comment]
I cannot confirm this. Please also provide the Browser log during the attempt to create a new category.

**Comment by avanc** [comment]
I cannot create a new category, if the task already has a category.
![screenshot](https://cloud.githubusercontent.com/assets/2905029/22464992/cb40d864-e7b9-11e6-8e45-2ab3efbf197f.png)
The icon left to "Testcategory" seems to be clickable. However, nothing happens.

I get the following error:

    Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src 'nonce-ai8raU81TDZrOUlLeUZ6OFFrK1lMZi9OMEdJcUxBSGxzbTV0bURsdXNiYz06MjR2M1ZQNnEwckZJajI2TEdpaWdaTW44NHhoVEcxWFUveDRmKzFnSjh1RT0=' 'unsafe-eval'").

**Comment by raimund-schluessler** [comment]
The icon to the left is for deleting the category, the problem of it not showing was fixed with https://github.com/nextcloud/tasks/commit/74e0b3406a31eb78482d32e6330642ea76f790ba but not published to the appstore yet.

You should be able to add further categories by clicking in the area to the right and type.

Your reported error is unrelated to the Tasks app.

**Comment by avanc** [comment]
Ah, thanks for the hint. Adding additional categories is working.
