### ISSUE TITLE
Changelog outdated

### ISSUE THREAD

**Issue by myxor** [nextcloud/tasks#465]
### Steps to reproduce
1. Open https://github.com/nextcloud/tasks/blob/master/CHANGELOG.md
2. See that it is outdated
3. Open https://github.com/nextcloud/tasks/releases
4. See that the changelog is there

### Expected behaviour
Put changelog into https://github.com/nextcloud/tasks/blob/master/CHANGELOG.md or at least link to the release page so everyone knows that the changes can be found there.

### Actual behaviour
Changelog is outdated since two years

This is not a huge thing but little things can help as well :)

**Comment by raimund-schluessler** [comment]
Thanks for the report, PR is in #466
