### ISSUE TITLE
Editing 'Show only busy' task always changes summary to 'busy'

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/tasks#467]
I am actually not sure, whether this is a server issue, if we should handle this in the CalDAV apps or if this is a non-issue. Originally reported in https://github.com/nextcloud/tasks/pull/412#issuecomment-506845619. Input is very welcome.

### Steps to reproduce
1. Share a calendar with write privileges to user B.
2. Create a task in said calendar and set the privacy setting to `show only busy`.
3. User B edits the task.

### Actual behaviour
The edits are saved (as one would expect?), but the title is set to `Busy` if nothing else is put there.

### Expected behaviour
Actually not really sure, what should happen. User B has write privileges to the calendar, so I guess it is ok, that he can change tasks. But for a `show only busy` task he doesnt get any more information than the title `Busy`, so changing any property potentially overwrites values without him knowing, as it happens for the title for example.

**Tasks version:**
v0.11.0 (as this supports sharing only), but happens before if you share via Calendar app.

Since the same thing happens in the Calendar app, I would like to hear what @nextcloud/calendar thinks about this. Potentially also @nextcloud/designers has an opinion.

**Comment by rkaraba** [comment]
Maybe show only busy should work only for read only Task lists(calendars) and it should be ignored in editable Task lists(calendars).
If shared Task list (calendar) is editable then act like show only busy = show full event

**Comment by raimund-schluessler** [comment]
So, this is a server issue https://github.com/nextcloud/server/issues/5551 in the first place, but we should forbid editing `Show only busy` tasks that are shared with you from the client side as well.

**Comment by raimund-schluessler** [comment]
We also have to prevent setting the access class to something else than `PUBLIC` if you are not owner of the calendar, is this correct @georgehrke ?

**Comment by georgehrke** [comment]
@raimund-schluessler Yes, ref https://github.com/nextcloud/calendar/issues/657
