### ISSUE TITLE
Missing functionality for categories

### ISSUE THREAD

**Issue by avanc** [nextcloud/tasks#47]
### Steps to reproduce
1. Adding categories to tasks

### Expected behaviour
I would expect to filter for categories.
Get a list of all task within a category.

### Actual behaviour
I don't the any functionality which uses the categories.

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
11.0.1
**Tasks version:** (see Nextcloud apps page)
0.9.4

**Comment by raimund-schluessler** [comment]
Please see https://github.com/nextcloud/tasks/issues/89
