### ISSUE TITLE
Tasks with date shown in calendar as event

### ISSUE THREAD

**Issue by vabatta** [nextcloud/tasks#50]
Hi,

is there a way to a tasks created with dates to be shown in calendar as an event?

Example:
Create `task A` on a tasks list `X` with start date `today` with end date `tomorrow` to be shown in calendar view as an event titled `task A` from `today` to `tomorrow`?

**Comment by raimund-schluessler** [comment]
This is currently not possible and needs to be implemented in the Calendar app. See https://github.com/nextcloud/calendar/issues/28.
