### ISSUE TITLE
Task deleting (with all subtasks)

### ISSUE THREAD

**Issue by ratermir** [nextcloud/tasks#521]
Sometimes it happens that I need to delete task with all subtasks (if any) without storing them among "Finished" tasks. This option I didn't find there. So it kould be really useful tu add this option.

**Comment by raimund-schluessler** [comment]
If you delete a task, all subtasks will be deleted as well. I guess, this is what you want already?

**Comment by ratermir** [comment]
Yes, and I didn't find something like "Delete tak" button on the screen at all.

**Comment by raimund-schluessler** [comment]
Open the details view of a task (click on it) and find the trashbin icon on the lower left of the details view (will delete without confirmation).

**Comment by ratermir** [comment]
Sorry for misunderstanding the concept - I considered the items on the left as "Groups" and the items on the right as "tasks" with subtasks. 
So what I wanted is to be able to delete items on the right - as shows the picture attached.

![2019-07-19 14_52_47-Úkoly - Nextcloud - Iron](https://user-images.githubusercontent.com/52619304/61536705-8a318300-aa35-11e9-884d-2c204845442e.png)

**Comment by raimund-schluessler** [comment]
You have to open the details view, by clicking on the task (one of the "items on the right"):
![Screenshot-2019-7-19 Aufgaben - Nextcloud(1)](https://user-images.githubusercontent.com/2496460/61537535-b0582280-aa37-11e9-9ed5-3b065f1d5fd0.png)

**Comment by ratermir** [comment]
Thak you a lot. Yah this button is really well hidden :) So I would recommend to move it closer to the rest of controls. Good way could be (by my opinion) to create "right-side" pull-down menu (and maybe also right-click menu) to be consistent with the rest on Nextcloud. 
But this app is really well usable, thank you for your work.

**Comment by ChameleonScales** [comment]
@raimund-schluessler 
Hi, thanks a lot for this app!
I think this button should be either next to the + and ★ buttons or on the side pane but right under the other items instead of the very bottom of the page. Personally I looked for it for a while and didn't find it. Only your answer here helped me.
