### ISSUE TITLE
[Feature Request] Store task Descriptions in Nextcloud Notes

### ISSUE THREAD

**Issue by sunjam** [nextcloud/tasks#533]
Different from #91, but would be amazing to access and edit task descriptions (already supporting markdown) from within Nextcloud Notes.

**Comment by raimund-schluessler** [comment]
This feature would have to be added in the Nextcloud Notes app, please request it in the Notes repository.

Although I don't really see, why this would be useful. Why wouldn't you just edit the task description in the Tasks app? What is your usecase here?

**Comment by sunjam** [comment]
It would be extremely useful, because it would make it easier to connect notes with text due dates (aka tasks).  This is a default behavior in both Evernote Reminders and Google Drive Tasks, both of which will show up in Google Calendars and be accessible directly from the specific files.
