### ISSUE TITLE
[Feature Request] Link Tasks with a Project

### ISSUE THREAD

**Issue by sunjam** [nextcloud/tasks#534]
[Projects are a recent addition to Nextcloud 16, as mentioned in this announcement](https://help.nextcloud.com/t/nextcloud-16-allows-you-to-link-resources-to-keep-track-of-your-projects/52172).
![project](https://user-images.githubusercontent.com/1787238/62507498-7f0e7f00-b7b9-11e9-966b-e0c6b4b44cff.png)

Projects currently support linking:
* Deck app boards
* Files
* Talk conversations

It would awesome to add Tasks as well!

**Comment by jakobroehrl** [comment]
Does it make sense to link a complete task list to a Project also?

**Comment by SystemKeeper** [comment]
Anyone knows if this feature is in development?!

**Comment by marc-romu** [comment]
> 
> 
> Does it make sense to link a complete task list to a Project also?

Yes, please! It would be really useful for teams organization.

**Comment by sunjam** [comment]
Projects functionality deprecated in nc25.

- https://github.com/nextcloud/server/issues/28320
