### ISSUE TITLE
No coordination betwen nexcloud app and mobile app about subtask

### ISSUE THREAD

**Issue by julbroa** [nextcloud/tasks#541]
If i create a subtask in nextcloud app on the mobile app appear like new task and if i create a subtask in mobile app on the nextcloud app appear like note of task, no like subtask.

**Comment by raimund-schluessler** [comment]
Please read #116 and #159. This is because of your “mobile app”. It doesn’t really support subtasks. You can edit and create “mobile subtasks” by writing in the notes field.
