### ISSUE TITLE
Tag List ( category) not working

### ISSUE THREAD

**Issue by ghosttable** [nextcloud/tasks#544]
HI,
tasks doesnt use the Nextcloud Tags as it seems.
But it doesnt even use its own Tags (category).. 
if i create a Tag for a Task this one is only for the task i created it, 
i cant use it for any other task...

Tells me the "List is empty"

Can anyone check this pls

**Comment by raimund-schluessler** [comment]
Nextcloud tags are not yet supported in Tasks, issue is #89.
