### ISSUE TITLE
Try to load task from server if not found locally

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/tasks#606]
When a task is not found on the client side, it should be queried from the server. At the moment a task is shown as `Not found` when it is opened, but not loaded from the server (this can happen e.g. for completed tasks, since they are not loaded by default from the server).

**Comment by georgehrke** [comment]
we need some special `getEntityAtUrl` method. Let me look into that today.

**Comment by georgehrke** [comment]
If you already have the cdav-calendar object, you can just use the find method btw.
https://github.com/nextcloud/cdav-library/blob/master/src/models/davCollection.js#L111

**Comment by raimund-schluessler** [comment]
> If you already have the cdav-calendar object, you can just use the find method btw.
> https://github.com/nextcloud/cdav-library/blob/master/src/models/davCollection.js#L111

Thanks, I must have overlooked this method. It should work fine.

**Comment by raimund-schluessler** [comment]
PR is in #608.

**Comment by raimund-schluessler** [comment]
Closed with #608.
