### ISSUE TITLE
[Feature Request] Remember setting of all-day toggle for creation of new tasks

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/tasks#615]
I would love to have the all day option set by default.

**Comment by raimund-schluessler** [comment]
Not sure about this one. This is a quite personal opinion and depends on ones habits. I often select a time for my tasks as well, so I chose to not set this option by default. In case the majority of users prefers to set it, we can do so. But I would like to have multiple opinions on that one. Maybe @jancborchardt has an opinion here.

**Comment by jancborchardt** [comment]
I would also tend towards all-day. But yes, this is likely a personal habit.

Luckily there’s a way we can fix it. :) We just remember what was used last. Ta-da! ;)

**Comment by raimund-schluessler** [comment]
> Luckily there’s a way we can fix it. :) We just remember what was used last. Ta-da! ;)

So whenever I toggle it for any task, this decision is remembered for the next task I create? We could do so (it will just send an additional request on every all-day toggle, but I guess this is ok). I changed the title to reflect this idea.

**Comment by jancborchardt** [comment]
Yup! This also then works when you normally create time-specific tasks, but then need to set a bunch of all-day tasks, but afterwards want to go back to time-specific tasks. :)

**Comment by rkaraba** [comment]
Or you can add it to settings with 3 posibilities:
something like
1 remember what was used last
2 create new tasks as all day
3 create new tasks a time specific

and remember what was used last can be set as default
