### ISSUE TITLE
[Feature Request] Checklists with automatic completion level update

### ISSUE THREAD

**Issue by simonspa** [nextcloud/tasks#623]
The OpenTasks Android app automatically renders the (markdown) content of a task as check list - and automatically updates the completion level of the task when checking or adding an item to the checklist:

![image](https://user-images.githubusercontent.com/1677436/65154241-76050480-da2b-11e9-9ea0-4ced399a79a9.png)

In Nextcloud Tasks, this however looks like this:

![image](https://user-images.githubusercontent.com/1677436/65156089-ba45d400-da2e-11e9-96a1-8502b20f9ccd.png)

Would it be possible to also render the task content similarly? I find myself always grabbing my phone if I want to check something off the list...

**Comment by raimund-schluessler** [comment]
The app already renders markdown in the notes field, but OpenTasks doesn't seem to use the common way of storing task lists in markdown; it misses the hyphen at the beginning. So it should be `- [ ] Item 1`, which would be rendered correctly, but it stores `[ ] Item 1`, which is not recognized as task list.

I will see, if we can somehow render both. Also, the checkboxes are disabled at the momen, so you would not be able to click them anyway. I will also check whether we can enable them to be clickable.

**Comment by simonspa** [comment]
I tested this a bit further and it seems that OpenTask

* uses all text *above* a list of `[ ]` as description of the task
* wrongly interprets all text *below* the list of `[ ]` as checklist items as well
* does not render `- [ ]` as checklist item

![image](https://user-images.githubusercontent.com/1677436/65232802-0c8c0100-dad2-11e9-98ea-b0df7d2f178b.png)

![image](https://user-images.githubusercontent.com/1677436/65232822-16adff80-dad2-11e9-8f94-b858cfd52995.png)

**Comment by tbm** [comment]
> So it should be - [ ] Item 1, which would be rendered correctly, but it stores [ ] Item 1, which is not recognized as task list

It seems this issue has been fixed in OpenTasks (will be in the next release).  See https://github.com/dmfs/opentasks/issues/875

**Comment by raimund-schluessler** [comment]
Seems so.
