### ISSUE TITLE
Broken link in apps.nextcloud.com page

### ISSUE THREAD

**Issue by mabkenar** [nextcloud/tasks#64]
The green button at the bottom of the [Task app page](https://apps.nextcloud.com/apps/tasks) for **Ask questions or discuss** is broken. It lands on [this page](https://help.nextcloud.com/c/apps/tasks), which doesn't exist.

### Expected behaviour
The link should bring up a page in help.nextcloud.com that points to the category for the tasks app, like [this page](https://help.nextcloud.com/c/apps/calendar) does for the [calendar app](https://apps.nextcloud.com/apps/calendar).

**Comment by raimund-schluessler** [comment]
Could you please also report this in the repo of the appstore: https://github.com/nextcloud/appstore.
Because i can't change this link, it is automatically generated when uploading an app.

**Comment by mabkenar** [comment]
I see. I thought the link is defined here. Sure, I'll also report it there. But first, what is the solution? Is there a correct link that this button should point to?

**Comment by raimund-schluessler** [comment]
I don't know, I have nothing to do with this link :wink:

**Comment by raimund-schluessler** [comment]
The link seems to work now, although I don't know why. Probably the topic was created in the forum!?
