### ISSUE TITLE
Tasks cannot be filtered on mobile devices, no response to taps

### ISSUE THREAD

**Issue by redshiftltd** [nextcloud/tasks#648]
### Steps to reproduce
1.  Access a Nextcloud instance via a mobile device (iOS [Safari or Chrome] or Android [Firefox])
2.  Tap the hamburger icon to expand task groups
3.  Tap a task group (i.e. Project X)

### Expected behaviour
Task groups should appear and be editable just like on a PC.

### Actual behaviour
Nothing happens, no share icons appear, list doesn't filter. "Request Desktop Site" setting doesn't help either. 

### Server configuration
Operating system: Linux 3.10.0-957.21.2.el7.x86_64 #1 SMP Wed Jun 5 14:26:44 UTC 2019 x86_64

Webserver: nginx/1.12.2 (fpm-fcgi)

Database: mysql 5.5.60

PHP version:

7.1.29 Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, igbinary, imagick, smbclient, memcached, redis, libsmbclient, Zend OPcache

Nextcloud version: 16.0.5 - 16.0.5.1

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: Mainline installer
Signing status
List of activated apps
``` Enabled: - accessibility: 1.2.0 - activity: 2.9.1 - admin_audit: 1.6.0 - bruteforcesettings: 1.4.0 - cloud_federation_api: 0.2.0 - comments: 1.6.0 - dav: 1.9.2 - federatedfilesharing: 1.6.0 - federation: 1.6.0 - files: 1.11.0 - files_accesscontrol: 1.6.0 - files_automatedtagging: 1.6.0 - files_pdfviewer: 1.5.0 - files_retention: 1.5.1 - files_rightclick: 0.15.1 - files_sharing: 1.8.0 - files_texteditor: 2.8.0 - files_trashbin: 1.6.0 - files_versions: 1.9.0 - files_videoplayer: 1.5.0 - firstrunwizard: 2.5.0 - gallery: 18.3.0 - groupfolders: 4.1.3 - issuetemplate: 0.5.0 - logreader: 2.1.0 - lookup_server_connector: 1.4.0 - nextcloud_announcements: 1.5.0 - notifications: 2.4.1 - oauth2: 1.4.2 - ownbackup: 19.9.0 - password_policy: 1.6.0 - privacy: 1.0.0 - provisioning_api: 1.6.0 - ransomware_protection: 1.4.0 - recommendations: 0.4.0 - serverinfo: 1.6.0 - sharebymail: 1.6.0 - support: 1.0.0 - survey_client: 1.4.0 - systemtags: 1.6.0 - tasks: 0.11.3 - theming: 1.7.0 - twofactor_backupcodes: 1.5.0 - twofactor_totp: 3.0.1 - updatenotification: 1.6.0 - user_ldap: 1.6.0 - user_usage_report: 1.1.2 - viewer: 1.1.0 - workflowengine: 1.6.0 Disabled: - encryption - files_external - fulltextsearch ```
Configuration (config/config.php)
``` { "instanceid": "***REMOVED SENSITIVE VALUE***", "passwordsalt": "***REMOVED SENSITIVE VALUE***", "secret": "***REMOVED SENSITIVE VALUE***", "trusted_domains": [ "nextcloud.website.local", "datatransfer.website.com" ], "datadirectory": "***REMOVED SENSITIVE VALUE***", "dbtype": "mysql", "version": "16.0.5.1", "overwrite.cli.url": "https:\/\/nextcloud.website.local", "dbname": "***REMOVED SENSITIVE VALUE***", "dbhost": "***REMOVED SENSITIVE VALUE***", "dbport": "", "dbtableprefix": "oc_", "mysql.utf8mb4": true, "dbuser": "***REMOVED SENSITIVE VALUE***", "dbpassword": "***REMOVED SENSITIVE VALUE***", "installed": true, "maintenance": false, "app_install_overwrite": [ "spgverein" ], "theme": "", "loglevel": 2 } ```

Are you using external storage, if yes which one: No

Are you using encryption:

Are you using an external user-backend, if yes which one: LDAP
LDAP configuration (delete this par if not used)

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Tasks version:** (see Nextcloud apps page)

**Updated from an older Nextcloud or fresh install:**

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/nextcloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0 + iOS Chrome/Safari + Android Firefox

**Operating system:**
Operating system: iOS, Android, Windows10

**CalDAV-clients:**

#### Web server error log
Insert your webserver log here
``` Blank, no errors ``` 

#### Nextcloud log (data/nextcloud.log)
```No errors generated in log ``` 
Insert your Nextcloud log here
```

#### Browser log
Insert your browser log here, this could for example include:
```10.0.0.1 - - [03/Oct/2019:13:58:17 -0400] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 74 "https://datatransfer.website.com/apps/tasks/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36" "-" 10.0.0.1 - - [03/Oct/2019:13:58:25 -0400] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 711 "https://datatransfer.website.com/settings/admin/issuetemplate" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0" "-" 10.0.0.1 - - [03/Oct/2019:13:58:29 -0400] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 74 "https://datatransfer.website.com/apps/tasks/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36" "-" 
```

**Comment by raimund-schluessler** [comment]
I cannot reproduce this. Afer opening the Tasks app, I can click the hamburger icon to show the Task lists, select one, see the contained tasks and share the list with others. Tested on iOS 13.1.

**Comment by raimund-schluessler** [comment]
You could try if it works for you on https://try.nextcloud.com/ to check whether it is a problem with your instance.

**Comment by redshiftltd** [comment]
Hello Raimund, 

I'm trying on iOS v 12.1 and the user is having trouble using v12 as
well. I'll update my phone and see if that helps. 

Android shows the exact same behavior on my server. 

Everything else seems to be working fine though, is there anything that
could affect this from a settings perspective?

---
Brandon 

On 2019-10-03 14:30, Raimund Schlüßler wrote:

> You could try if it works for you on https://try.nextcloud.com/ to check whether it is a problem with your instance. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/nextcloud/tasks/issues/648?email_source=notifications&amp;email_token=AA7BPKM3R3VRHW544Q67S5TQMY26FA5CNFSM4I5GM4K2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAJEUVQ#issuecomment-538069590
[2]

**Comment by raimund-schluessler** [comment]
> I'm trying on iOS v 12.1 and the user is having trouble using v12 as well.

I used iOS 12 before with Tasks and it worked fine as well. I don't think it is the iOS version.

>  is there anything that could affect this from a settings perspective?

I am not aware of any setting that could affect this, sorry.

**Comment by redshiftltd** [comment]
I just updated to iOS 13.x and through Safari the share button appears and is responsive.
I can have the user update their iPhone to resolve the issue. Thank you for the quick response and I'll close the ticket!
