### ISSUE TITLE
Crash - Where do I Find Tasks in Database

### ISSUE THREAD

**Issue by benyanke** [nextcloud/tasks#65]
My NC server recently crashed, and I've been trying to manually recover my tasklist. I have a tar and sql backup from the day before the crash, but due to extenuating circumstances, reloading to the server isn't an option.

A search of the database isn't coming up with much of anything.

Where can I find the items of my task list stored?

**Comment by raimund-schluessler** [comment]
The Tasks app is only a client to the CalDAV server built into NC server. It does not write to the database directly. However, the CalDAV entries should be stored in a table called ```oc_calendarobjects```, the respective calendars in ```oc_calendars```. If you need further detail, please ask in https://github.com/nextcloud/server.

**Comment by benyanke** [comment]
Thank you.
