### ISSUE TITLE
Usability problem with deleting a task

### ISSUE THREAD

**Issue by alajovic** [nextcloud/tasks#651]
I am a fresh user of the Tasks application, and I just spent several minutes struggling to find a way to delete a task. Finally giving up, I googled for the answer, and issue #521 popped right up, providing me with the instructions. Since it seems that I am not the first one to have had trouble with such an essential action, I would like to offer insight into why I struggled with finding the "delete" button, and why I think its placement should be reconsidered.

The main reason for my confusion is that I am used to the "Files" view on NextCloud, and I naturally expected the Tasks application to have a similar layout regarding basic actions. To delete a file, I click on the "..." button in the file view. A drop-down menu with actions such as "rename", "move", and "delete" appears, and I simply choose "delete". In Tasks, I noticed that each task has a "+" button, which somehow implies _adding_ something, and since in my mind, _adding_ and _removing_ are complementary operations, I expected the "trash" button to be somewhere near. But it wasn't.

What added to my confusion is that I did not have a good idea where else to look for it. I knew that clicking a task opens up a pane with task properties – name, starting time, due time etc. – but the concept of "deleting" does not fit with the concept of "properties" for me. Deleting is an action, not a property, so I did not expect to see it there.

The final problem was that the "trash" icon was right at the bottom of the "properties" pane, below a large span of vertical blank space that somehow implied that there is nothing worth seeing there. With the browser window maximized, the icon was well outside my "focus spot" – I was mostly looking at the task list, and the top of the properties pane.

Thanks for considering this report. I hope it provides a small, but valuable input for your UI design process.

**Comment by raimund-schluessler** [comment]
We will rework the sidebar of the Tasks app #664 and probably make the delete action a bit more prominent, similar as in the reworked Calendar app (to be released).

Adding a delete button to each task is not a good solution, I think. The task view is already filled with quite some actions / items and deleting a task is not so common. You normally complete them, but not delete them.
