### ISSUE TITLE
Tasks app doesn't honor the user enumeration prevention settings

### ISSUE THREAD

**Issue by doobry-systemli** [nextcloud/tasks#660]
Apparently, the tasks app doesn't respect the "allow user autocompletion in share dialog" setting. Despite user autocompletion being turned off, user autocompletion still works in the tasks share dialog.

### Steps to reproduce
1. Go to Settings -> Administration -> Sharing and disable "Allow user autocompletion in share dialog. If this is disabled the full username or e-mail address needs to be entered."
2. Go to the tasks app and try to share a task
3. Start typing the username and watch the matching user enumeration

### Expected behaviour
When user autocompletion is turned off, the tasks app should honor this.

### Actual behaviour
It enumerates all matching users and that way leaks all user accounts on this Nextcloud instance.

### Server configuration

**Server version:** 15.0.12
**Tasks version:** 0.11.3

**Comment by raimund-schluessler** [comment]
This is a server issue, the Tasks app does not cause nor can it prevent this behaviour. Please have a look at https://github.com/nextcloud/server/issues/11087.
