### ISSUE TITLE
[Feature Request] Firefox add-on 

### ISSUE THREAD

**Issue by TobiasDev** [nextcloud/tasks#669]
I'm not sure if this is possible but figured I  would ask.

I would love to see a Firefox plugin (think in the terms of Todoist). So you can quick add tasks directly from Firefox.

If you have something selected on the website it would use that as title + add a link to the website. Preferbly I would see that these are added to a chosen list I pick. The biggest reason for me wanting this is to add articles, movies, etc. to read them later. I've tried using pocket, wallabag, etc. but the one thing I noticed is that when I place something in my todo list I watch it or read it.

**Comment by raimund-schluessler** [comment]
Sounds like a nice idea, but is a bit out-of-scope for this repository here. Maybe you can post the idea in the forum https://help.nextcloud.com/c/feature/app-ideas, in case someone with experience in add-on development for Firefox has a bit of leisure time 😉 

Such an add-on would need to provide support for the CalDAV protocol, so it could in principle be used with every such server, not only Nextcloud.
