### ISSUE TITLE
Usability:  New check box issue with update

### ISSUE THREAD

**Issue by brianWreaves** [nextcloud/tasks#674]
### Steps to reproduce
1.  Click on check box to mark item as _Done_
2.  Side-panel opens for item as if selecting item row
3.  User is required to close after each check box tick

### Expected behaviour
The check box click area is now opening the side-panel when in previous versions it only marked item as _Done_
 
This is particularly onerous on mobile as closing the side-panel is required to see other tasks

### Actual behaviour
**As above, opens side-panel**

Nextcloud version:
**16.0.3**
 
Tasks version:
**0.11.3**
 
Are you using encryption:
**No**
  
### Client configuration
Browser:
**FF69+ on MAC, 68+ on Android**

Operating system:
**Mojave _and_ A8+**

**Comment by raimund-schluessler** [comment]
I can confirm the issue, this was caused by https://github.com/nextcloud/tasks/pull/572. Will prepare a fix.
