### ISSUE TITLE
Usability:  Hiding Tasks' interaction icons

### ISSUE THREAD

**Issue by brianWreaves** [nextcloud/tasks#675]
### Suggested Enhancement
Consider rendering each task's interaction icons without the requirement to select line item e.g.  Hide/view eye, sub-item bars
 
These hidden interaction icons amounts to mystery navigation requiring an extra click to view. That is counterproductive as it adds interaction cost for each task one wants to open
 
Thanks for considering!

Nextcloud version:
**16.0.3**
 
Tasks version:
**0.11.3**
 
Are you using encryption:
**No**
 
Browser:
**FF69+ on MAC, 68+ on Android**

Operating system:
**Mojave _and_ A8+**

**Comment by raimund-schluessler** [comment]
> Consider rendering each task's interaction icons without the requirement to select line item e.g. Hide/view eye, sub-item bars
> 
> These hidden interaction icons amounts to mystery navigation requiring an extra click to view. That is counterproductive as it adds interaction cost for each task one wants to open


Sorry, I don't understand what you mean. The "interaction items" (e.g. hiding/viewing the sub-tasks) are not hidden. They are always there whenever there is something to interact with.

The only case when the subtasks related icons are not shown is when completed subtasks are not loaded yet. We don't load completed subtasks by default, as this would slow down the app when you load thousands of subtasks. They are only loaded for a specific task when you open its details. Hence, the icons for hiding completed and not completed subtasks only appear after completed subtasks are loaded (given that the task has no uncompleted subtasks).

**Comment by raimund-schluessler** [comment]
Since this is only concerning completed tasks and loading all completed tasks on app load is no option, I am going to close this as won't fix. In case I got it wrong, please report.

**Comment by brianWreaves** [comment]
> We don't load completed subtasks by default, as this would slow down the app...
 
Fair point!  However, rendering the icons regardless of the existence of or the loading of sub-task would reduce required interaction.  Perhaps greying-out when none exist, then when they do exist, clicking the icon loads them from the server. 
 
Admittedly, not a high ROI for the work required.
