### ISSUE TITLE
Strike-through using Markdown does not work in task description

### ISSUE THREAD

**Issue by timholl** [nextcloud/tasks#678]
### Steps to reproduce
1. Write a task description containing Markdown `~~Foo~~` .
2. Click somewhere outside of the textarea, so it gets rendered by markdown-it.

### Expected behaviour
The description should be displayed as "~~Foo~~".

### Actual behaviour
The description is displayed as "Foo".

### Server configuration

**Operating system**: Ubuntu Server

**Web server:** Apache

**Database:** Sqlite

**PHP version:** 7.2

**Nextcloud version:** 17.0.0

**Tasks version:** 0.11.3

**Updated from an older Nextcloud or fresh install:** Fresh install

**Comment by timholl** [comment]
Turns out that the [global `text-decoration:none` CSS rule](https://github.com/nextcloud/tasks/blob/413c624ce791d332916f3a27ad45a298d263af5a/css/src/style.scss#L336) prevents the default style of `<s>` (as correctly created by markdown-it) inside the `#markdown`-container.

So a simple additional rule like
```
        s {
		text-decoration: line-through;
	}
```
in `css/src/markdown.scss`should do the trick.

**Comment by raimund-schluessler** [comment]
Fine with me, fix is in #682
