### ISSUE TITLE
Functions re not visible on page

### ISSUE THREAD

**Issue by lepidas** [nextcloud/tasks#70]
Yesterday I installed Tasks for NC but as show in the screenshot there is a problem with the functionality,
http://storage2.static.itmages.com/i/17/0427/h_1493264686_6213971_8425060031.png

Apache2
PHP7
Mysql5.7
Ubuntu 16.04

**Comment by raimund-schluessler** [comment]
Please describe your problem a bit more precise. The screenshot looks fine, besides you don't have any calendars / lists.

**Comment by lepidas** [comment]
I close this, it was my fault. Just didn't know how to work with it.
