### ISSUE TITLE
Italic text does not work in markdown

### ISSUE THREAD

**Issue by timholl** [nextcloud/tasks#701]
Similar to #678 , just for italic text.

![before1](https://user-images.githubusercontent.com/12062142/68010790-d66f9e80-fc85-11e9-8efc-af562f656dd5.png)
displayed as
![before2](https://user-images.githubusercontent.com/12062142/68010805-dbcce900-fc85-11e9-95e6-c0d969e41491.png)
but should
![after](https://user-images.githubusercontent.com/12062142/68010828-ea1b0500-fc85-11e9-83a8-aa81aa235609.png)

**Comment by timholl** [comment]
Why [does `server.css` even even change the default `font-style` of `em` tags](https://github.com/nextcloud/server/blob/468c61653fc968a837f0c4145af287784c038cbc/core/css/apps.scss#L41) ...

**Comment by raimund-schluessler** [comment]
> Why [does `server.css` even change the default `font-style` of `em` tags](https://github.com/nextcloud/server/blob/468c61653fc968a837f0c4145af287784c038cbc/core/css/apps.scss#L41) ...

No idea...

**Comment by timholl** [comment]
I also tested other common Markdown stuff, that works.

Conceptual one could make a clean-start inside the markdown container with
```css
#markdown {
   all: initial;
   * {
      all: unset;
   }
}
```
to reset every style to its default, since that rendered markdown will neither make use of nextcloud-specific styles nor should apply to that (like in this case) anyway.

**Comment by raimund-schluessler** [comment]
> I also tested other common Markdown stuff, that works.
> 
> Conceptual one could make a clean-start inside the markdown container with
> 
> ```css
> #markdown {
>    all: initial;
>    * {
>       all: unset;
>    }
> }
> ```
> 
> to reset every style to its default, since that rendered markdown will neither make use of nextcloud-specific styles nor should apply to that (like in this case) anyway.
> 
> But that would be kind of brute-force.

Hm, I think this would be to much. E.g. the font-color should align with the general nextcloud style and we would need to set it again then.

**Comment by timholl** [comment]
> . E.g. the font-color should align with the general nextcloud style and we would need to set it again then.

Yes, but it would make us immune against upstream style changes in core instead of manually reverting them afterwards. ^^

Just an idea, though. Will implement a prototype when the next issue occurs at that point :)
