### ISSUE TITLE
Enhancements to the Design

### ISSUE THREAD

**Issue by szaimen** [nextcloud/tasks#703]
Hello, 
at first thank you for this really nice working app.
I have seen the latest pre-release from Nextcloud Calendar and now I think this tasks app looks a little bit outdated. Maybe you could get some inspiration from Microsoft ToDo. I really love their Design:
![image](https://user-images.githubusercontent.com/42591237/68091121-257f2480-fe7c-11e9-97b0-e997846c80c5.png)
In comparison Nextcloud Tasks:
![tasks-1](https://user-images.githubusercontent.com/42591237/68423771-faaa0e80-01a2-11ea-839b-0b8726441f72.png)

**Comment by jakobroehrl** [comment]
@szaimen: Have a look at: #664

**Comment by raimund-schluessler** [comment]
Yes, let's track our progress regarding the design in #664.
