### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by brOOper** [nextcloud/tasks#715]
### Steps to reproduce
Open the Tasks app in a browser tab

### Expected behaviour
A favicon should appear left to the tab title

### Actual behaviour
There is none (each app seems to have its own favicon now)
![image](https://user-images.githubusercontent.com/7403075/68939283-7bb76600-07a0-11ea-9d62-c6c7392edb37.png)
Example from Notes app:
![image](https://user-images.githubusercontent.com/7403075/68939640-6abb2480-07a1-11ea-852e-7988264675fa.png)

**Web server:**
Apache 2.4

**PHP version:**
7.3

**Nextcloud version:**
16.0.6

**Tasks version:**
0.11.3

**Comment by raimund-schluessler** [comment]
I cannot reproduce this. The app does have a favicon https://github.com/nextcloud/tasks/blob/master/img/favicon.ico and it appears correctly on my setup. Could you please check that the access rights are correct and whether any request to the favicon fails for your setup?

**Comment by raimund-schluessler** [comment]
I assume this is a caching or access rights issue of your instance. The favicons are in the img folder and are loaded by the server.

**Comment by brOOper** [comment]
I'm running Nextcloud in a subfolder. That might lead to this behaviour.

I noticed this request: `/myncfolder/apps/theming/favicon/tasks?v=0` where no content is returned (Content-Length: 0, but still HTTP status code 200).

For example, the notes app delivers an icon for this request: `/myncfolder/apps/theming/favicon/notes?v=0`

**Comment by raimund-schluessler** [comment]
Hm, I am not aware of any differences between Notes and Tasks regarding the favicon. Both apps simply have the favicon files in `/img` and nothing more. I have no idea why this request returns no content. But since you seem to have the theming app enabled, this might also contribute to the problem. Have you tried to disable theming?

**Comment by brOOper** [comment]
With theming app disabled the default nextcloud favicon is displayed for tasks. Notes app still shows its custom favicon.
I'll try to reproduce this behaviour with a fresh installation...

**Comment by raimund-schluessler** [comment]
You could try what happens when you copy the notes favicon to the location of the tasks favicon (to rule out, that the favicon is somehow broken or not compatible with your browser). And did you check the access rights of your server to the favicon?

**Comment by brOOper** [comment]
This is weird. After disabling the theming app on friday i did several hard refresh in the browser. Also, i checked the _disable cache_ checkbox in Chrome dev tools and tried incognito window - still no icon!
Visiting the app today it's there! I enabled theming again and it's still there. Very confusing behavior. Probably disabling theming had some effect on my setup.
Anyway, thank you for your help!
