### ISSUE TITLE
[Feature Request] Adding tags during task creation

### ISSUE THREAD

**Issue by sschuhmann** [nextcloud/tasks#752]
It would be nice to have the ability to add specific tags or other information during the task creation, e.g. input of the tasks name. This could be accompilshed by adding specific special characters, which whill be parsed by the application. So it could be like some of the todo txt applications

```TAKS1 +TAG1 +TAG2 @HIGH```

**Comment by raimund-schluessler** [comment]
I guess we could do this, but I think it would be more common to use the hashtag `#` as token for tags/categories.

**Comment by raimund-schluessler** [comment]
This is tracked in https://github.com/nextcloud/tasks/issues/89#issuecomment-317190169 already 😉
