### ISSUE TITLE
Smart Collection Settings menus are non-functional in Chrome 58 on Win10

### ISSUE THREAD

**Issue by phetish** [nextcloud/tasks#77]
### Steps to reproduce
1. Using Chrome open the Tasks App in Nextcloud
2. Click the Settings Gear
3. Notice that the Smart Collections option dropdowns are offset by 1 row and do not work.

### Expected behaviour
Firefox and MS Edge work correctly - the dropdown options are correctly aligned and react when clicked.

### Actual behaviour
Nothing - except for the bottom 2 options - they work but they are misaligned.

**Comment by tschiu** [comment]
Confirm this behavior under Chrome 58 on Windows 10

**Comment by pistriger** [comment]
#app-settings-content li .label-container elements need be floating to left
This need add 
  float: left; 
to string 276 of file css/src/style.scss

**Comment by raimund-schluessler** [comment]
Fixed with 9ee6d23acad71251811a6b4e0e6656849829935d.
