### ISSUE TITLE
Tasks on Nextcloud Mobile App

### ISSUE THREAD

**Issue by fermulator** [nextcloud/tasks#791]
### Steps to reproduce
1. Add tasks app on server
2. Works in web UI
3. Unable to find in mobile app

### Expected behaviour
How do we use this task app in Nextcloud mobile app? IOS

### Actual behaviour
I may be thick but I can’t find any “apps list” or “tasks” icon in the app

### Server configuration

**Operating system**: iOS 13

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** v17 latest

**Tasks version:** 0.11.3

**Updated from an older Nextcloud or fresh install:**

**Signing status:**

**List of activated apps:**

**Nextcloud configuration

N/A

**Comment by MarinMikael** [comment]
Hello,

Read [README.md](https://github.com/nextcloud/tasks/blob/master/README.md) for a non exhaustive list of CalDAV applications.

**Comment by raimund-schluessler** [comment]
The iOS app doesn't contain a calendar or task app by itself, because iOS includes a good calendar and task app already and there are lots of alternatives for iOS calendars. You have to configure the CalDAV interface, so the calendars and task lists show up in the integrated apps. Please see here: https://docs.nextcloud.com/server/16/user_manual/pim/sync_ios.html

In the future, the iOS app will hopefully allow to automatically set up the calendars: https://github.com/nextcloud/ios/issues/70

**Comment by fermulator** [comment]
OK so this is where I was left with a gap in knowledge.

I understand how contacts = CardDAV, and calendar = CalDAV.
But how do "tasks" make sense for a CalDAV?

https://docs.nextcloud.com/server/16/user_manual/pim/sync_ios.html
Doesn't mention tasks at all.

**Comment by fermulator** [comment]
I also became wary of https://github.com/nextcloud/server/issues/17190, but maybe it was only an interim issue and is resolved now. After reading that I see that caldav tasks is a thing https://en.wikipedia.org/wiki/CalDAV#Specification.

**Comment by raimund-schluessler** [comment]
Calendars (synced by CalDAV) store different types of entries. An event (shown in Calendar) is of type VEVENT, a task (shown in Tasks) is of type VTODO and a journal entry would be VJOURNAL. All of them are stored in a calendar synced by CalDAV, see https://en.wikipedia.org/wiki/ICalendar#Core_object.

Please be aware that the calendars and task lists shown in the Calendar app and in the Tasks app are the same objects (depending a bit on how you created them: task lists created with the Task app only allow to contain VTODO entries and they won't show up in the Calendar app, calendars created with the Calendar app until 1.7.1 allow to contain both VEVENT and VTODO and show up in both apps, Calendar app 2.0 will allow to chose what to store).
