### ISSUE TITLE
Category list is empty when creating new task

### ISSUE THREAD

**Issue by philipreimer** [nextcloud/tasks#792]
### Steps to reproduce
1. Create a task
2. Add one or more categories to the task
3. Create another task
4. Open category list for 2. task

### Expected behaviour
The category list should display the categories added to 1. task

I know there is already #89 and using the system wide labels/tags might be a first solution for this issue.
However, I think that often you might want to have separate lists of categories for different task lists, i.e. when you have different task lists for different projects or work packages or something. In that case one global giant list of categories is not very useful, as you cannot easily see, which categories are applicable to the current task list.

### Actual behaviour
The category list is empty

### Server configuration

**Operating system**: don't know, it's a hosted instance

**Web server:** don't know, it's a hosted instance

**Database:** don't know, it's a hosted instance

**PHP version:** don't know, it's a hosted instance

**Nextcloud version:** 17.0.2

**Tasks version:**  0.11.3

**Updated from an older Nextcloud or fresh install:** don't know, it's a hosted instance

**Signing status:**

Integrity checker has been disabled. Integrity cannot be verified.

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 72.0.1

**Operating system:** Manjaro Linux

**CalDAV-clients:** none

**Comment by raimund-schluessler** [comment]
> However, I think that often you might want to have separate lists of categories for different task lists, i.e. when you have different task lists for different projects or work packages or something.

So you propose to store categories on a per-task-list basis?

**Comment by philipreimer** [comment]
> So you propose to store categories on a per-task-list basis?

I think that would make sense for a lot of use cases.
I can also see that for other use cases, having a global list of categories (i.e. the nextcloud-wide tags) could be useful as well, because you can use the same in other apps as well.

Maybe one could have both? Creating a new category in tasks app adds it to the current task list's categories but also to the nextcloud-wide tags list?

And the categories dropdown list in tasks app could be split in two section, showing the task list categories on top and the global tags beneath it?

**Comment by raimund-schluessler** [comment]
> So you propose to store categories on a per-task-list basis?

This would be quite some effort and require storing categories in a separate database table to keep track of which category belongs to which task-list. We won't go for this as a first implementation. What would be possible is to extract the categories from the tasks in a list on the client side, but the drawback would be that categories of completed tasks (which are not loaded by default) would not show up.

Anyway, let's track this issue in #89.

**Comment by cl4x** [comment]
in fact as it is now I do not understand the meaning of the categories. they even have to be rewritten every time, there is not even a list or an autocompletion. it is an apparently useless field.

**Comment by raimund-schluessler** [comment]
I agree, the usability is quite limited at the moment.

**Comment by philipreimer** [comment]
> but the drawback would be that categories of completed tasks (which are not loaded by default) would not show up.

I think that having inconsistent category lists does not add additional value and would almost be as "useless" (to quote @cl4x) as the empty list.
It would only add confusion for the user.

**Comment by philipreimer** [comment]
Also, #89 is about integrating categories with the global tags system, as far as I understand.

That is not what I would like to have. Should I create a separate "feature request" for this?

**Comment by raimund-schluessler** [comment]
> That is not what I would like to have. Should I create a separate "feature request" for this?

Well, I as far as I understood it, your request is to have a separate category list for every task list (and see both separate and global list in the category suggestions). But as I said above having a separate list would mean a lot of effort. You would need to maintain a separate database table just for this (Tasks does not directly interact with the database at all yet), and you would need to hook into the CalDAV code of the server in order to e.g. track when a list was deleted and delete the corresponding categories as well then. This really requires a lot of coding for an in my opinion rather limited use-case.

While I see that it could make sense for some users, we won't implement this given that integrating into the global tags system would already guarantee consistent categories (or category suggestions) for every task with a lot less effort. Pull-Requests are always welcome,though 😉 If you want this request to be tracked, feel free to create a feature request, or just edit this issue here (and I will reopen it).

**Comment by Tailored-Landon** [comment]
Is there any updates on incorporating system/global tags, or even just reusable tags within the tasks app? I apologize if I'm missing a separate PR thread, but I've gone through all relevant ones it seems and can't find anything on this. Any feedback/updates would be super helpful :)
