### ISSUE TITLE
Remember last view

### ISSUE THREAD

**Issue by borghal** [nextcloud/tasks#80]
I'd like to be able to define the default view when tasks is opened. 

Right now when you open tasks it shows a list of all tasks which is not very practical in my opinion. I'd love to open tasks and see the "today" list first, for example.

Cheers!

**Comment by jakobroehrl** [comment]
Hello @raimund-schluessler 
I would like to do this for the next version. Could you give me the steps for realizing this?

**Comment by raimund-schluessler** [comment]
@jakobroehrl @jancborchardt I don't think we will introduce a setting for this, will we? We could save the last selected view though, similar how we do it for the all-day setting. Although this wouldn't *really* be a default view then.

**Comment by jancborchardt** [comment]
>  We could save the last selected view though

Yes, always remembering the last used view is the proper way to do this. :)
