### ISSUE TITLE
Add link to calendar for tasks with due date

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/tasks#803]
We should provide a button / link for tasks with a due date to switch to the calendar app once https://github.com/nextcloud/calendar/pull/1798 is merged.

@georgehrke @bfritscher Could you tell me how the URL to navigate to an entry in the calendar looks like?

**Comment by raimund-schluessler** [comment]
@georgehrke Could you tell me how the link has to look like in order to navigate to a task?

**Comment by georgehrke** [comment]
@raimund-schluessler The calendar does not allow editing a task. It only displays them in the calendar-grid. (And takes you to the tasks app if it is enabled.)

So you can't directly link to a task. The only thing you can do is open the calendar in the view that contains the due-date.

**Comment by raimund-schluessler** [comment]
> @raimund-schluessler The calendar does not allow editing a task. It only displays them in the calendar-grid. (And takes you to the tasks app if it is enabled.)
> 
> So you can't directly link to a task. The only thing you can do is open the calendar in the view that contains the due-date.

Yes, I know. That's alright. But I wanted to show a link to view a task with duedate in the calendar grid.
I will link to `/index.php/apps/calendar/timeGridWeek/<duedate>` then, in case the Calendar app and show tasks in Calendar is enabled.
