### ISSUE TITLE
Hiding subtasks broken

### ISSUE THREAD

**Issue by ionl** [nextcloud/tasks#82]
### Steps to reproduce
1. If (important word) only parent task appeared, then click on a one (not on the icon)
2. Subtasks are developed (and right menu appeared), but icon with 3 horizontals bars doesn't change (first bug)
3. When you click again on a parent subtask, but on the icon this time, subtasks are always apparent (so no change) but icon changed.

### Expected behaviour
1. Icon develop subtask must represent reality
2. Action on parent task must be done

### System Information
* Tasks app version: 0.9.5
* Nextcloud version: 11.0.3
* PHP version: 7.0.19-1
* Database and version: MariaDB 10.0.30 
* Browser and version: Firefox 54
* Server Distribution and version: debian 9 kernel 3.14.32
* Client Distribution and version: ubuntu 17.10 and windows 10

**Comment by raimund-schluessler** [comment]
I am sorry, I really don't get what you want to say. Could you please give a better description of your issue, maybe with images? I will reopen the issue once more details are provided.

**Comment by ionl** [comment]
You have right, I should put image, it's easier to understand :)
When we click on icon (surrounded by images), it does nothing. What is it used for ?
![selection_001](https://user-images.githubusercontent.com/3930248/28492436-3acf89ce-6f04-11e7-883b-4cab0a94e59f.png)
![selection_002](https://user-images.githubusercontent.com/3930248/28492437-3ccde428-6f04-11e7-9725-3019a05d7b91.png)

**Comment by raimund-schluessler** [comment]
This icon should hide or show the subtasks. In the upper image, the subtasks should be hidden, and visible in the lower image. This seems to be a bug.

Could you give more details what browser and app you are using, please?

**Comment by ionl** [comment]
For details, I updated my first post (browser and php version have changed ;)

**Comment by raimund-schluessler** [comment]
Wait a second, subtasks should be shown when the parent task is opened, independent from the state of the hiding icon. This is by design, so you see the subtasks when you opened the parent task.

When you close the parent task (right sidebar hidden), then also the subtasks should be hidden.

**Comment by ionl** [comment]
So I had to resume situation, because it's not clear yet.
All screenshot is result of action.
1) I click on all task. It's ok 
![selection_001](https://user-images.githubusercontent.com/3930248/28497498-fcc05430-6f88-11e7-9fff-70c2810586bf.png)
2) I click on "apartment" task. You can see icon is not good :)
![selection_002](https://user-images.githubusercontent.com/3930248/28497500-1714427e-6f89-11e7-9e54-bd55a804e190.png)
3) I can click a lot of time on the icon, it changed only its status. So why there is an icon ? why it's not grey icon (or not visible to avoid action)
![selection_003](https://user-images.githubusercontent.com/3930248/28497512-90d286de-6f89-11e7-925b-af2ea57dc581.png)

I hope it's clear. It's subtle bug :-D

**Comment by raimund-schluessler** [comment]
That is how it is supposed to be. The icon represents the state of visibility when the task is not opened. You can see that in your first image:

![](https://user-images.githubusercontent.com/3930248/28497498-fcc05430-6f88-11e7-9fff-70c2810586bf.png)

The icon shows that the subtasks for the task "Appartment" are hidden --> subtasks are not visible.
For the other tasks "Kitchen" and "Repair" the icon shows that the tasks are visible --> subtasks are visible.

In the second image, you opened the task, hence you see the subtasks independent of the visibilty state.

So: Subtasks are *always* visible when you open the parent task. The icon does not change, because it is not supposed to show if the subtasks are visible (you see that they are visible, there is no icon necessary for that), but it shows if the subtasks would be visible, when the task is not opened. I think everything else does not make sense.

**Comment by ionl** [comment]
Like I said, the first image is ok.
I understand logical.
But you can see on the 2nd image that icon red surrounded is not like the others (for "Repair" and "Kithen" parent tasks)
If it's ok for you, no problem, I know how it works now, but there are 2 different information for the same state.

**Comment by raimund-schluessler** [comment]
The icon shows if the subtasks are shown when the parent task is closed, not if they are actually shown at the moment.

**Comment by ionl** [comment]
Ok and the icons are differents
What is the goal to put contradictories informations ? (ok I know it's only when the the parent task is closed, but I repeat, why show on the visual interface that ?)
If designers said before develop that : we had to put 2 differents icons when we click parent task. OK
But can you say me what is the purpose to help users ?

**Comment by raimund-schluessler** [comment]
Sorry, I don't get what is your problem. Do you want a further icon that show if the subtasks are visible? What would that be good for? You either see the subtasks or you don't see them. No need for a further icon to show that.

**Comment by ionl** [comment]
> What would that be good for ? : 

When we clicked parent task to edit it (subtasks appear), its icon must be 
![selection_003](https://user-images.githubusercontent.com/3930248/28500242-0b3d2e0c-6fc5-11e7-8ddc-d35d4d11341e.png) and not 
![selection_001](https://user-images.githubusercontent.com/3930248/28500243-1046519e-6fc5-11e7-8515-32e7c08a19b5.png).
We should not be able to click on it because action does nothing :)

I hope, I'm clear with my poor english words :-/

**Comment by raimund-schluessler** [comment]
Don't worry, you are clear. But I disagree with you. 😉 

When you click on the icon, it actually does something. Just close the parent task after clicking and you will see, that the visibility of the subtasks is toggled. This icon is not an indicator if the tasks are shown *at the moment* but if they are shown when *the parent task is closed*.

**Comment by ionl** [comment]
Yes, I understand your logical :-D 

So you said, when update parent task

> you click on the icon, it actually does something

I'm agree with your sentence \o/

So why is it possible to do an action that result is nothing ?
For me, an action possible but useless must be remove :-) (to avoid confusion)

Furthermore, when update parent task, for other parent task (not the current update one), icons works well. It's strange and not homogeneous :-). Why the current one doesn't work if the others work :-D ? (so, you don't have to remove action on it, only fix that :-p )
