### ISSUE TITLE
Long task name

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/tasks#834]
### Steps to reproduce
1. Add a new task.
2. Write a very long task name.
3. Save the task.
4. Click a task to set the details.
5. **It is not possible to edit the task and delete it.**

![obraz](https://user-images.githubusercontent.com/47037905/73141581-f694db00-4085-11ea-9100-4bf18ddb5067.png)

![obraz](https://user-images.githubusercontent.com/47037905/73141591-0e6c5f00-4086-11ea-8ab3-73fdb354c242.png)
But it came out :wink:.

**Nextcloud version:** (see Nextcloud admin page)
18.0.0

**Tasks version:** (see Nextcloud apps page)
0.11.3

**Comment by raimund-schluessler** [comment]
I can confirm the issue, though I have to say it is a quite constructed one 😉 We maybe should limit the title to 3 or 4 lines and ellipsize the rest.

As a workaround you can just edit the title to a shorter one by clicking on it in the details view.

**Comment by Valdnet** [comment]
> As a workaround you can just edit the title to a shorter one by clicking on it in the details view, then you can edit/delete the task again.

@raimund-schluessler It's hard to come to that :grimacing:.
I suggest that by hovering over the task title the task title color change and the cursor should change to hand :wink:. For the user, this is more intuitive.
