### ISSUE TITLE
Alignment of the column

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/tasks#854]
I suggest aligning task columns. Currently, if the task does not have a description, the task end date is shifted to the right in the list. This causes an unsightly appearance. In place of the details icon, you can leave the field blank or the icon inactive.

![obraz](https://user-images.githubusercontent.com/47037905/73738155-36258c00-4744-11ea-862c-bde383d736de.png)

**Comment by raimund-schluessler** [comment]
I would vote against that, because it would waste space and at least to me it would look weird if there is an empty space. But I am open to other opinions, so let's hear @nextcloud/designers.

**Comment by stefan-niedermann** [comment]
I think this allows a quicker "scanning" of the content, because one does not have to jump left/right when looking for one information, therefore: 👍

**Comment by raimund-schluessler** [comment]
While I understand why you want this, I still think it is problematic. There are up to four icons which are only shown when they are applicable:
<img width="1023" alt="Screenshot_2020-02-09 Tasks - Nextcloud" src="https://user-images.githubusercontent.com/2496460/74109300-61640d00-4b82-11ea-941d-1ccc8839bcfd.png">


Keeping this space free all the time wastes a lot of space, showing them greyed-out for all tasks out would look very busy.

**Comment by stefan-niedermann** [comment]
maybe switching the (temporarily) icons with the (permanent?) date?

So position the items which are always there o  the right side and the ones which only appear if applicable on the left side next to the others?

Might this be a solution?

**Comment by raimund-schluessler** [comment]
> maybe switching the (temporarily) icons with the (permanent?) date?

Hm, the date is also only there if you set a due date, so not really permanent either.

How about we move the active icons / actions (besides the star icon) into a drop-down menu and move the date to the right of the icons without an action?
![Screenshot_2020-02-10 Aufgaben - Nextcloud](https://user-images.githubusercontent.com/2496460/74130652-d5ce9880-4be2-11ea-9d9e-a6ef69315807.png)

We could then also add a delete action without further bloating the task list.

**Comment by raimund-schluessler** [comment]
Have a look at #866

**Comment by raimund-schluessler** [comment]
PR #866 is ready to be reviewed.
