### ISSUE TITLE
[Feature] Link task list to calendar of the same name after the calendar has already been created

### ISSUE THREAD

**Issue by PopeRigby** [nextcloud/tasks#869]

**Comment by raimund-schluessler** [comment]
This is not really possible. One would need to load all events or tasks from the other calendar as well when requesting data from the first calendar. This would need to be done on the server side, so if at all this is an issue for the server repository.

But it seems to me this is a lot of (unnecessary) code and effort if you could just create a calendar which can store both tasks and events (and maybe move your tasks and events to the new calendar).
