### ISSUE TITLE
Not available for translation in Transifex

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/tasks#876]
The following words are missing to be translated in Transifex:

- Successfully created the task.
- Successfully updated the task.
- Task successfully moved to new calendar.

Occurring in the file: src/store/tasks.js
https://github.com/nextcloud/tasks/blob/bc123919f1556a8673a0f417bc4d71e960cd1832/src/store/tasks.js#L638
https://github.com/nextcloud/tasks/blob/bc123919f1556a8673a0f417bc4d71e960cd1832/src/store/tasks.js#L1135
https://github.com/nextcloud/tasks/blob/bc123919f1556a8673a0f417bc4d71e960cd1832/src/store/tasks.js#L1204

One example:

![obraz](https://user-images.githubusercontent.com/47037905/74737553-57fb3480-5255-11ea-8854-5929ae37f07f.png)

App:
Nextcloud 18.0.1
Tasks 0.12.0

**Comment by raimund-schluessler** [comment]
Thanks for the hint, fix is in #877. Should be available on Transifex in the next days.
