### ISSUE TITLE
Disable 'Contacts Birthdays' task list

### ISSUE THREAD

**Issue by andreasjacobsen93** [nextcloud/tasks#88]
When using the calendar and contacts, a calendar is created with contacts birthdays.
This calendar is shown as task list in the tasks app, even though no tasks can be added to it.

Another problem is that it is shown as the default task list, so in order to add tasks one has to always click on the next list, which allow tasks.

Can we prevent 'Contacts Birthdays' to show up as a task list?

**Comment by raimund-schluessler** [comment]
This should not be the case. The birthday calendar should only contain VEVENT, see https://github.com/owncloud/core/pull/25636, hence, it should not show up in the Tasks app. If this is not the case and it is created as containing VTODO as well, please report that in the server repository.

**Comment by raimund-schluessler** [comment]
This was also already merged into Nextcloud, see https://github.com/nextcloud/server/commit/6eb1bc55ab24cf1cfae5995d5fbb976120df32d5. 

Maybe updating your Nextcloud instance will already solve this.

**Comment by andreasjacobsen93** [comment]
I'm running a fresh installation of NC 12.0.0.29 and still have this problem.

**Comment by raimund-schluessler** [comment]
Then please report this in the server repository.

**Comment by andreasjacobsen93** [comment]
https://github.com/nextcloud/server/issues/5504

nextcloud/server says that it belongs here.

**Comment by raimund-schluessler** [comment]
See my answer to https://github.com/nextcloud/server/issues/5504. I still think it is a server issue.
