### ISSUE TITLE
Checkbox checked color too dark on dark nextcloud theme

### ISSUE THREAD

**Issue by Baton34** [nextcloud/tasks#881]
### Steps to reproduce
1. Select list in Tasks
2. Press Share button
3. Check "Enable edit" checkbox for some user

### Expected behaviour
Checked checkbox background color must be blue as other checkboxes in other server pages
![okColor](https://user-images.githubusercontent.com/10797316/75088213-b41acd00-5563-11ea-8d68-5b04985aacba.jpg)
### Actual behaviour
Checked checkbox background color too dark and its checked state not recognized.
![wrongColor](https://user-images.githubusercontent.com/10797316/75088215-b4b36380-5563-11ea-82da-4a7b895edda7.jpg)
### Server configuration
**Operating system**:
Linux 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64
**Web server:**
nginx/1.14.0 (fpm-fcgi)
**Database:**
mysql 5.7.29
**PHP version:**
7.2.24-0ubuntu0.18.04.3
**Nextcloud version:** (see Nextcloud admin page)
17.0.3 - 17.0.3.1
**Tasks version:** (see Nextcloud apps page)
0.11.3
**Updated from an older Nextcloud or fresh install:**
updated from older version

**Comment by raimund-schluessler** [comment]
Should be fixed in master, will be released with 0.12.0:
![Screenshot_2020-02-23 Tasks - Nextcloud](https://user-images.githubusercontent.com/2496460/75119859-043e8000-5687-11ea-8b35-c649b25a8b36.png)
