### ISSUE TITLE
caldav documentation

### ISSUE THREAD

**Issue by guitar9** [nextcloud/tasks#888]
I want to build a own task manager with sync to nextcloud tasks.
I wasted many houres to search about documenation about caldav on internet but I dont find usefull resources. 
Is there a webclient which supports caldav with nextcloud where I can just capture network traffic and look for requests and responses?

**Comment by raimund-schluessler** [comment]
The CalDAV implementation of Nextcloud is nothing special. So any CalDAV client / library out there should work with the CalDAV server of Nextcloud. In fact, the Tasks app itself is only a CalDAV client (which happens to request data from the Nextcloud instance only).

We use ical.js (https://github.com/nextcloud/tasks/blob/master/package.json#L32) for handling the iCal data and the Nextcloud cdav library (https://github.com/nextcloud/tasks/blob/master/package.json#L31) to interact with the Nextcloud CalDAV server. I am not sure how much effort it is to use these libraries as a standalone app, but I am pretty sure it is possible.
