### ISSUE TITLE
Improvements for categories

### ISSUE THREAD

**Issue by spoorun** [nextcloud/tasks#89]
Nextcloud has a tagging system.
'Categories' are tags, and should sync with that system.

The benefits would be: 
1) Users managing different types of data (such as tasks, contacts, messages, files) would use the same sets of tags (including shared tags) to organise that data, 
2) and in future be able to find that data by global searches. 
3) It would make shared data management more consistent too.
4) The UI for tags would be consistent across apps (and that could be improved), and it would be more efficient - Users shouldn't need to learn endless different UIs and modes of operation to carry out the same task (using tags) within a single system (Nextcloud).

**Comment by raimund-schluessler** [comment]
I will use this issue to collect all the improvements requested for categories:

- [ ] Integrate into Nextcloud tagging system
- [ ] Allow adding categories / tags by hashtagging in the title (https://github.com/nextcloud/tasks/issues/42)
- [ ] Integrate into search, clicking a tag should start a search (https://github.com/nextcloud/tasks/issues/47)

**Comment by websafe** [comment]
@raimund-schluessler  any update on this enhancement?

**Comment by udolee** [comment]
Tasks is so good! One question, is there a way to sort by categories? Thanks!

**Comment by GambaJo** [comment]
Yap, this is very pitty. I miss this feature too.

**Comment by klawdhfzasjhaa** [comment]
> Tasks is so good! One question, is there a way to sort by categories? Thanks!

Additionally, it would be great to filter by category.

**Comment by javisomoza** [comment]
Yeah, i miss also the feature of filtering by category. And the category tags being also links to that filtering.

**Comment by duesseldorferjung** [comment]
+1

**Comment by GambaJo** [comment]
> 
> 
> > Tasks is so good! One question, is there a way to sort by categories? Thanks!
> 
> Additionally, it would be great to filter by category.

+1

**Comment by abers** [comment]
> Yeah, i miss also the feature of filtering by category. And the category tags being also links to that filtering.

I came to the git repo to see if anyone had requested this feature already. Do you know why it was removed? It'd be great if could view list of categories in left-hand panel, filter by category, and view all tasks tagged with a category. Would replicate the main features from Tasks.org (mobile app I sync tasks with) that are currently missing from Tasks.

**Comment by raimund-schluessler** [comment]
> > Yeah, i miss also the feature of filtering by category. And the category tags being also links to that filtering.
> 
> I came to the git repo to see if anyone had requested this feature already. Do you know why it was removed?

It was not removed. It was never available in the first place.

**Comment by jay3-3** [comment]
> And you can filter by category. Just type the category name in the search box at the top right.

That is not filtering per category, if you search for example with "category" on the search box you will see everything containing "category" on title, description... Not only in the category field.

IMHO a nice improvement would be the possibility to filter with categories (more than one). This is already working with tags in **files**.

**Comment by klawdhfzasjhaa** [comment]
Perhaps, this helps: https://github.com/nextcloud/cookbook/pull/375/

**Comment by MaggiWuerze** [comment]
Please also have a look at  #1453, maybe it can be added to this list

**Comment by caemor** [comment]
>     * [ ]  Allow adding categories / tags by hashtagging in the title ([[Feature Request] Hashtag tagging of new entries #42](https://github.com/nextcloud/tasks/issues/42))

Was there any work done into this direction already? And if not is there an easy way to add this and someone could point me into the right direction to start this? 
If possible I would like to look into an option to set some easy dates at the same time, e.g. today, tomorrow, monday-sunday,... will add the corresponding day as due day

**Comment by raimund-schluessler** [comment]
New tasks are created here:
https://github.com/nextcloud/tasks/blob/4346ae41d63bbcc34b4c0c729dced30fb43363a4/src/store/tasks.js#L708-L783

You can parse the summary and set categories and dates in this function.

**Comment by hoshi411** [comment]
> > > Yeah, i miss also the feature of filtering by category. And the category tags being also links to that filtering.
> > 
> > 
> > I came to the git repo to see if anyone had requested this feature already. Do you know why it was removed?
> 
> It was not removed. It was never available in the first place.
> 
> And you can filter by category. Just type the category name in the search box at the top right.

that requires you to know / remember what tags you have made.  It is especially tricky if you use emoji for your tags.  Best practice UX is to provide a list of tags somewhere (as every other GTD / TASK app does by default) .

Basic operation is the ability to filter by clicking on tags and even multiple tags.  These are common fundamentals.

**Comment by hoshi411** [comment]
> > And you can filter by category. Just type the category name in the search box at the top right.
> 
> That is not filtering per category, if you search for example with "category" on the search box you will see everything containing "category" on title, description... Not only in the category field.
> 
> IMHO a nice improvement would be the possibility to filter with categories (more than one). This is already working with tags in **files**.

This comment needs to be bumped up to the top priority.

**Comment by raimund-schluessler** [comment]
Extracting tags from the summary was just added in #2425.

**Comment by raimund-schluessler** [comment]
Filtering by tags was implemented in #2427 and will be released with v0.16.0.

I will close this issue, since the main features discussed here were implemented and the remaining requests have their own tickets. Please speak up for open a new issue if you think that a feature request got lost.
