### ISSUE TITLE
Linebreak issue in the settings

### ISSUE THREAD

**Issue by szaimen** [nextcloud/tasks#896]
Hi, I am currently running NC 18.0.1 and Tasks 0.11.3 and this looks like a bug:

![image](https://user-images.githubusercontent.com/42591237/75917681-a6662100-5e5a-11ea-985c-6d9226429a05.png)

The client is a chromium 80 based browser (but it also happens on Firefox 73). 
There is no (red) error in the console.

**Comment by raimund-schluessler** [comment]
It’s already fixed in master and will be released with 0.12.0. Sorry I don’t find the corresponding commit right now.

**Comment by szaimen** [comment]
No problem! Thanks for letting me know!
