### ISSUE TITLE
Reoccurring Tasks incl. Variable Planning

### ISSUE THREAD

**Issue by joekob** [nextcloud/tasks#90]
I am currently using "tasks" for onetime issues which really works very nice - including the integration with mobile devices.

What I would like to do in addition is managing reoccurring tasks like "Inspect the roof for leakage", "Change the oil of my old tractor" or "Check water pressure of the heating". These are reoccurring tasks, which have a recommended frequency. The time interval starts to count when the task was created or was done for the last time, i.e. closing the task starts the new period and creates the successor to be due after the defined period from when the previous task was closed.

I am used to this from maintenance management systems used on vessels but this would be also extremely useful for managing for example the family's household... :)

### Server configuration

**Operating system**: FreeBSD
**Web server:** Apache24
**Database:** mySQL
**Nextcloud version:** 11.0.3

**Comment by raimund-schluessler** [comment]
Please see https://github.com/nextcloud/tasks/issues/34
