### ISSUE TITLE
After update to 0.12.0 the tasks app is empty

### ISSUE THREAD

**Issue by szaimen** [nextcloud/tasks#908]
## Steps to reproduce
1. Update to 0.12.0
2. Open the tasks app
3. See the screenshot:
![20200308_140636](https://user-images.githubusercontent.com/42591237/76163432-50d59100-6146-11ea-8cbd-f78aea8ed98c.png)

### Expected behaviour
It should show all my tasks

### Actual behaviour
It doesn't show any tasks

### Server configuration

**Operating system**:
Ubuntu 18.04 LTS
**Web server:**
Apache2
**Database:**
Postgresql
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
18.0.1
**Tasks version:** (see Nextcloud apps page)
0.12.0
**Updated from an older Nextcloud or fresh install:**
Updated

This problem happens on all OS and Browsers.

This is in the console log:
![20200308_140553](https://user-images.githubusercontent.com/42591237/76163481-b9bd0900-6146-11ea-8c65-38d3721e70c2.png)

**Comment by raimund-schluessler** [comment]
Does it also happen for all users? On my instances it works just fine.

**Comment by raimund-schluessler** [comment]
Can you also please check the requests, especially the ones to the calendars?

**Comment by szaimen** [comment]
> Does it also happen for all users? On my instances it works just fine.

No, strangely just for one useraccount. The other work fine.

**Comment by szaimen** [comment]
> Can you also please check the requests, especially the ones to the calendars?

How do I do that?

**Comment by totoli78** [comment]
I have the same symptoms as the author. After upgrading tasks 0.12.0, all existing tasks do not appear. What should I do?

**Comment by raimund-schluessler** [comment]
>  How do I do that?

Also in the developer tools. In the console you should see a lot of requests to the server when you load the app. There should be one to `<ServerAdress>/remote.php/dav/calendars/<user>/` which should return the calendars (as array).

Weirdly, the code https://github.com/nextcloud/tasks/blob/master/src/store/calendars.js#L434-L439 which gives the error hasn't been touched since 0.11.3

**Comment by szaimen** [comment]
I am actually not quite sure what I am exactly looking for.
This is a request for the not working user:
![image](https://user-images.githubusercontent.com/42591237/76164450-49ff4c00-614f-11ea-9eda-f266ca931d1f.png)
**and it seems that the browser doesn't make a request to the "aufgaben" calendar, which is the case for another user, that also has the "aufgaben" calendar and sees the tasks calendar...**

**Comment by raimund-schluessler** [comment]
I might have an idea. Could you please try this build:
[tasks.tar.gz](https://github.com/nextcloud/tasks/files/4303308/tasks.tar.gz)

**Comment by groxxorg** [comment]
I noticed the same bug. The version of the calendar app is Ver. 2.0.2., Tasks Ver. 0.12.0
In the error log of my browser the following error is displayed:

```
TypeError: "e.shares is undefined"
    Fri uidToColor.js:101
    t calendars.js:274
    t calendars.js:263
vue.runtime.esm.js:1888:12
    VueJS 4
```

**Comment by totoli78** [comment]
Downgrade to 0.11.3 version, the existing tasks will be displayed normally.

**Comment by szaimen** [comment]
> I might have an idea. Could you please try this build:
> [tasks.tar.gz](https://github.com/nextcloud/tasks/files/4303308/tasks.tar.gz)

I've tried that but it still doesn't work...

**Comment by raimund-schluessler** [comment]
Still the same error? Did you clear the browser cache?

**Comment by szaimen** [comment]
Thanks! after clearing the browser cache it works but now it also shows a subscribed ical calendar, which shouldn't be the case since it is not writeable, imho.

**Comment by szaimen** [comment]
And btw: the console is now full of these messages. Wasn't there before:
![image](https://user-images.githubusercontent.com/42591237/76165081-75386a00-6154-11ea-8342-39e54adafbe4.png)

**Comment by raimund-schluessler** [comment]
> Thanks! after clearing the browser cache it works but now it also shows a subscribed ical calendar, which shouldn't be the case imho, since it is not writeable (and also wasn't shown on 0.11.3)...

Ok, then I will release v0.12.1 with the fix and we can discuss whether we should show subscribed calendars in a separate issue. Could you please open one @szaimen

These warnings are not critical and we already ship our own version with the app.

**Comment by raimund-schluessler** [comment]
The fix is in the appstore, should be visible soon. Let me know if there are still problems, besides #910.
