### ISSUE TITLE
[Feature Request] Show whole due (date and time) in the list

### ISSUE THREAD

**Issue by GambaJo** [nextcloud/tasks#914]
When a due is set the list shows only the date but not the time.
It would be useful if I can see date and time when I plan my day, now I have to open every appointment an keep in mind, what due time it has.

**Comment by zeroepix** [comment]
This would be a useful addition to the today view. For the week view it might get too crowded.

**Comment by GambaJo** [comment]
I don't really see the problem. There is enough space.
![19-03-_2020_15-01-16](https://user-images.githubusercontent.com/1378907/77075693-04fed380-69f3-11ea-888b-d5d04578d306.jpg)

**Comment by zeroepix** [comment]
It depends on how much screen-space you give the app I guess.
![ice_screenshot_20200320-100323](https://user-images.githubusercontent.com/1424840/77122993-13043100-6a93-11ea-9ebf-2d012130d60b.png)

**Comment by GambaJo** [comment]
It's possible to show or hide html elements depending on the screen size. Like in responsive design.
