### ISSUE TITLE
Enable manually ordering lists

### ISSUE THREAD

**Issue by alve89** [nextcloud/tasks#918]
Is there a possibility to order the lists (or at least change the "default" list at the top of the page, marked yellow)?
I'm on NC 18.0.1, tasks 0.12.1.

![image](https://user-images.githubusercontent.com/11487054/76418762-7e694700-639f-11ea-9117-03294e2fda19.png)

**Comment by raimund-schluessler** [comment]
The order of lists in the left sidebar cannot be changed yet, the corresponding issue is #15 (at least not in the GUI, you could do it by hand in the database at your own risk).

The default list can be changed in the settings (bottom left).
