### ISSUE TITLE
IE11 : nothing appears

### ISSUE THREAD

**Issue by jacestk** [nextcloud/tasks#92]
### Steps to reproduce
1. just launch the app

### Expected behaviour
Tasks should appears on screen

### Actual behaviour
white screene (except top NextCloud menu bar)

### Server configuration

**Operating system**:
Centos 7

**Web server:**
Virtual

**Database:**
Mysql 5.6

**PHP version:**
7

**Nextcloud version:** (see Nextcloud admin page)
NextCloud 12.0.0

**Tasks version:** (see Nextcloud apps page)
0.9.6

**Updated from an older Nextcloud or fresh install:**
fresh install

**List of activated apps:**
Circles, deck, calendar, impersonate, groups folder

{
    "system": {
        "instanceid": "ocrquov2xtht",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "domain.name",
            "xxxxxxxxx"
        ],
        "datadirectory": "\/app\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/domain.name",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "logtimezone": "Indian\/Reunion",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "xxxxxxx",
        "mail_domain": "xxxxxxxx",
        "mail_smtphost": "xxxxxxxxx",
        "mail_smtpport": "25",
        "has_internet_connection": false,
        "appstoreenabled": false,
        "appstore.experimental.enabled": false,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc"
        ],
        "loglevel": 2,
        "maintenance": false,
        "theme": "",
        "skeletondirectory": "\/app\/nextcloud\/data\/skeleton"
    }
}

### Client configuration
**Browser:** IE11

**Operating system:** Win7Pro

********** ERROR ************
SCRIPT1003: ':' attendu
Fichier : app.js, ligne : 4412, colonne : 22
SCRIPT5022: [$injector:modulerr] http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=Tasks&p1=Error%3A%20%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.5.5%2F%24injector%2Fnomod%3Fp0%3DTasks%0A%20%20%20at%20Anonymous%20function%20......
Fichier : angular.min.js, ligne : 40, colonne : 25

**Comment by jacestk** [comment]
Okay I have made some investigations. 

In the file js/public/app.js, line 4412 :

`updateLastModified : function() { ` instread of `updateLastModified { `

Now got an new error: _« XPathResult » is undefined_. 

Just because of IE11 not supporting « XPathResult » method... got some fix for this?

**Comment by raimund-schluessler** [comment]
Yes, this is the reason. Calendar guys tackled this by using a polyfill and compiling a separate javascript file just for IE. I guess you could do the same, see https://github.com/nextcloud/calendar/pull/329.

Mind sending a PR?

**Comment by jacestk** [comment]
thanx! Will try to patch it first :P

**Comment by jacestk** [comment]
No solutions for making this working?

![task](https://user-images.githubusercontent.com/1270552/36406154-359b1b38-160e-11e8-9154-f1163b1fec10.PNG)

**Comment by raimund-schluessler** [comment]
Similar to https://github.com/nextcloud/contacts/issues/414 we will not support IE11. Edge should work though once v0.10.2 is out.
