### ISSUE TITLE
Datepicker does not display sunday column

### ISSUE THREAD

**Issue by gjgd** [nextcloud/tasks#935]
### Steps to reproduce
1. Go to the Task app
2. Click on a task
3. Click on "Set start date" or "Set end date"

### Expected behaviour
Datepicker should appear and display all the dates

### Actual behaviour
Datepicker does not display the sunday column (see screenshot)

The sunday column is there, but is hidden by the section that lists the tasks

<img width="436" alt="Screenshot 2020-03-23 at 17 40 39" src="https://user-images.githubusercontent.com/7913565/77298104-b1132800-6d2d-11ea-9e48-edbf0c0e6cb2.png">

### Server configuration

**Operating system**: Ubuntu 18.04.2 LTS

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** 

**Nextcloud version:** (see Nextcloud admin page) 16.0.8

**Tasks version:** (see Nextcloud apps page) 0.12.1

**Updated from an older Nextcloud or fresh install:** I updated the Task app from the store, before I didn't have this problem, but I'm not sure which version I had before 0.12.1

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

**Nextcloud configuration:**

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 74.0

**Operating system:** MacOS Catalina 10.15

**Comment by raimund-schluessler** [comment]
I can reproduce the issue on certain zoom levels. As a workaround it might help to reduce the zoom level to values below 100% (zoom-out).

**Comment by gjgd** [comment]
@raimund-schluessler thanks! A zoom level of 80% works for me to display the full datepicker

**Comment by gjgd** [comment]
After a quick investigation, it is due to bumping the https://github.com/nextcloud/nextcloud-vue dependency from v1.3.1 to v1.4.0

**Comment by raimund-schluessler** [comment]
Reported it upstream in https://github.com/nextcloud/nextcloud-vue/issues/998.

**Comment by th23x** [comment]
Maybe to provide an interim solution for all people passing by here, while waiting for the upstream fix.

I simply installed [Customer CSS Theming](https://apps.nextcloud.com/apps/theming_customcss) app on Nextcloud and added the following CSS, which always should keep the full datepicker in view / accessible:

`.app-tasks #app-sidebar .mx-datepicker-main.mx-datepicker-popup { left: auto; }`

**Comment by gjgd** [comment]
Great fix!

In my case I had to add `!important` for this CSS directive to override the inline style:
`.app-tasks #app-sidebar .mx-datepicker-main.mx-datepicker-popup { left: auto !important; }`
