### ISSUE TITLE
Sync to openTask is broken

### ISSUE THREAD

**Issue by iteco** [nextcloud/tasks#936]
Can you help with https://github.com/dmfs/opentasks/issues/926 ?

Nextcloud task app lists that OpenTask app as [compatible](https://github.com/nextcloud/tasks/#apps-which-sync-with-nextcloud-tasks-using-caldav), but it seems to be a bit broken.

That OpenTasks app is the only free open source app that syncs with Nextcloud as far as I know.

**Comment by raimund-schluessler** [comment]
Please have a look at https://github.com/nextcloud/tasks/issues/116 and https://github.com/nextcloud/tasks/issues/159.

The sync is not broken, dmfs just chose to implement subtasks as checkboxes in the description field. Nothing we can do from our side.
