### ISSUE TITLE
When editing a tasks categories, make all tasks categories available to select

### ISSUE THREAD

**Issue by Bugsbane** [nextcloud/tasks#959]
### Steps to reproduce
1. Click on or create a task
2. Click on the categories area

### Expected behaviour
A list of all categories used by *any* task comes up. The categories used by the current task are ticked.

### Actual behaviour
Only categories already assigned to that task are shown. This is effective for removing categories, but not for adding categories used in other tasks, so they match.

**Nextcloud version:** (see Nextcloud admin page)
18.0.2

**Tasks version:** (see Nextcloud apps page)
0.12.1

**Comment by raimund-schluessler** [comment]
As a relatively quick improvement, we could show all categories from the tasks that are loaded from the server (which still might not be ALL categories, since completed tasks are not loaded by default).

Everything else should be tracked in #89.

**Comment by Bugsbane** [comment]
Yes, that's the best behaviour in my opinion. Otherwise it could end up pulling in 100 categories that haven't been used in years.
