### ISSUE TITLE
Dutch translation incomplete

### ISSUE THREAD

**Issue by Johnzooi** [nextcloud/tasks#964]
### Steps to reproduce
1. click on task, is displays add subtask, delete task, not the Dutch translation.

### Expected behaviour
Tell us what should happen
Display the text in the Dutch language.

### Actual behaviour
Tell us what happens instead
commands are displayed in English
### Server configuration
Nextcloud 18.0.3
Tasks: 0.12.1
The reason is quite simple, these translations are missing in nl.js en nl.json.
I would be happy to make all the translations to dutch, if just somebody could tell me how to find all translatable words, and how to submit them.

**Comment by raimund-schluessler** [comment]
Translations are handle via transifex, https://www.transifex.com/nextcloud/nextcloud/translate/#de/tasks/99690026. You have to create an account there and join the Nextcloud organization. Then you can start translating all strings (they are uploaded automatically every night).

You can read more about that here: https://help.nextcloud.com/t/translation-knowledge-valid-for-the-entire-nextcloud-project-wiki/51550
